Repository mattermost/docs, pull requests merged in 2018-12, with the labels that each got.

#2393 Newer SSL Configuration for nginx
  source/install/config-ssl-http2-nginx.rst
Labels: Review Complete - Ready to Merge

#2405 Update platform feature comparison chart
  source/overview/faq.rst
Labels: Review Complete - Ready to Merge

#2413 Add additional hardware requirements for EE deployments
  source/install/requirements.rst
Labels: Review Complete - Ready to Merge

#2404 Admin doc reorganization + FAQs
  source/administration/user-provisioning.rst
  source/guides/administrator.rst
Labels: Review Complete - Ready to Merge

#2415 Add hosting recommendation matrix between on-prem, AWS and Azure
  source/deployment/scaling.rst
  source/guides/administrator.rst
Labels: Review Complete - Ready to Merge

#2417 v5.5.1 changelog
  source/administration/changelog.md
Labels: Review Complete - Ready to Merge

#2418 Update version-archive.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2396 Terms of service changes for v5.6
  source/administration/config-settings.rst
  source/administration/custom-terms-of-service.rst
Labels: Review Complete - Ready to Merge

#2406 Update bulk-loading-data-format.rst
  source/deployment/bulk-loading-data-format.rst
Labels: Review Complete - Ready to Merge

#2419 Add Twitter response guidelines
  source/process/community-guidelines.rst
Labels: Review Complete - Ready to Merge

#2421 Miscellaneous v5.6 Docs
  source/administration/config-settings.rst
  source/developer/localization.rst
  source/guides/branding.rst
  source/help/settings/account-settings.rst
  source/install/requirements.rst
  source/overview/faq.rst
  source/overview/product.rst
  source/process/handbook.rst
Labels: Review Complete - Ready to Merge

#2426 Added a note to ensure the plugin is enabled
  source/integrations/jira.rst
Labels: Review Complete - Ready to Merge

#2422 Add Webhook delete command
  source/administration/command-line-tools.rst
Labels: Review Complete - Ready to Merge

#2427 Misc 5.6 docs
  source/administration/config-settings.rst
  source/help/settings/account-settings.rst
Labels: Needs PM Review, Review Complete - Ready to Merge

#2407 LDAP Group Sync Doc
  source/deployment/ldap-group-sync.rst
  source/guides/administrator.rst
  source/images/Add_Team_Or_Channel.png
  source/images/Group_Group_Member_Sync.png
  source/images/Group_Members.png
  source/images/Group_filter.png
  source/images/Groups_listing.png
  source/images/LinkFailed.png
  source/images/Team_Channel_Membership_Sync.png
  source/images/open_team.png
  source/images/private_channel.png
  source/images/private_team.png
  source/images/public_channel.png
Labels: Review Complete - Ready to Merge

#2395 Interactive Message Dialogs
  source/developer/interactive-dialogs.rst
  source/developer/interactive-messages.rst
  source/guides/integration.rst
  source/images/interactive-dialog-complete-example.png
  source/images/interactive-dialog-error.png
  source/images/interactive-dialog-example.png
  source/images/interactive-dialog-select-menu.png
  source/images/interactive-dialog-select.png
  source/images/interactive-dialog-text.png
Labels: Needs PM Review, Review Complete - Ready to Merge

#2382 v5.6 Changelog
  source/administration/changelog.md
Labels: Review Complete - Ready to Merge

#2346 MM-12505: remove all things WebRTC
  source/administration/config-settings.rst
  source/administration/telemetry.rst
  source/deployment/webrtc.rst
  source/guides/administrator.rst
  source/overview/faq.rst
Labels: Review Complete - Ready to Merge

#2431 Update ldap-group-sync.rst
  source/deployment/ldap-group-sync.rst
  source/images/Group_filter.png
Labels: Needs Editor Review

#2433 Update changelog.md
  source/administration/changelog.md
  source/administration/custom-terms-of-service.rst
Labels: Review Complete - Ready to Merge

#2436 Update version-archive.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2397 Add doc in how to install mm-te chart in gitlab chart
  source/guides/administrator.rst
  source/install/install-mmte-helm-gitlab-helm.rst
Labels: Needs PM Review

#2446 Formatting update
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2444 5.6.1 changelog + version archive
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2447 Update plugins.rst
  source/administration/plugins.rst
Labels: Review Complete - Ready to Merge

#2450 5.6.2 changelog + version archive
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2451 add troubleshooting info for broken server session data on desktop app
  source/install/desktop.rst
Labels: Review Complete - Ready to Merge
