Repository mattermost/docs, pull requests merged in 2018-07, with the labels that each got.

#2087 Added troubleshooting for mismatched server versions in HA
  source/deployment/cluster.rst
Labels: Awaiting Submitter Action

#2124 Upgrade instructions: Fix stray command from merge + reference previous binary name
  source/administration/upgrade.rst
Labels: Needs Dev Review

#2138 Telemetry docs for v5.1
  source/administration/telemetry.rst
Labels: Review Complete - Ready to Merge

#2120 Update important-upgrade-notes
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge

#2137 Update developer.rst
  source/process/developer.rst
Labels: Review Complete - Ready to Merge

#2140 Update Instruction Guidelines
  source/developer/fx-guidelines.rst
Labels: Review Complete - Ready to Merge

#2141 Missing Sample Response
  source/process/community-guidelines.rst
Labels: Review Complete - Ready to Merge

#2142 v5.0.1 docs
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2131 Update config-settings.rst for v5.1
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2145 Update Instructions for links
  source/developer/fx-guidelines.rst
Labels: Review Complete - Ready to Merge

#2143 small fix mattermost user migrate_auth command
  source/administration/command-line-tools.rst
Labels: Review Complete - Ready to Merge

#2147 ES 5.1 docs
  source/administration/config-settings.rst
  source/deployment/elasticsearch.rst
  source/deployment/permissions-backend.rst
  source/help/getting-started/organizing-conversations.rst
Labels: Review Complete - Ready to Merge

#2146 5.1 config setting for enabling email invitations
  source/administration/config-settings.rst
  source/help/getting-started/managing-members.rst
  source/install/prod-windows-2012.rst
  source/install/smtp-email-setup.rst
Labels: Review Complete - Ready to Merge

#2112 Adding CSV support to the documentation
  source/administration/command-line-tools.rst
  source/administration/compliance-export.rst
  source/administration/compliance.rst
  source/administration/config-settings.rst
Labels: Merge On Hold, Review Complete - Ready to Merge

#2144 Updated docker preview image documentation
  source/install/docker-local-machine.rst
Labels: Needs Dev Review

#2150 Adding QA items for final RC approval
  source/process/release-process.md
Labels: Review Complete - Ready to Merge

#2100 5.1 Changelog
  source/administration/changelog.md
Labels: Review Complete - Ready to Merge

#1962 Certificate-based authentication docs
  source/administration/config-settings.rst
  source/deployment/certificate-based-authentication.rst
  source/guides/administrator.rst
Labels: Review Complete - Ready to Merge

#2151 V5.1 documentation
  source/administration/changelog.md
  source/administration/compliance-export.rst
  source/administration/config-settings.rst
  source/administration/important-upgrade-notes.rst
  source/administration/telemetry.rst
  source/conf.py
  source/deployment/elasticsearch.rst
  source/deployment/permissions-backend.rst
  source/help/getting-started/managing-members.rst
  source/help/getting-started/organizing-conversations.rst
  source/install/config-cloudfront.rst
  source/install/prod-windows-2012.rst
  source/install/smtp-email-setup.rst
Labels: Review Complete - Ready to Merge

#2154 Update version-archive.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2155 Update conf.py
  source/conf.py
Labels: Review Complete - Ready to Merge

#2157 Fix broken zapier.rst logo URL
  source/integrations/zapier.rst
Labels: Review Complete - Ready to Merge

#2152 Grammar, structure, and readability edits
  source/help/getting-started/organizing.rst
Labels: Review Complete - Ready to Merge

#2057 Architecture Overview
  source/images/architecture_basics.png
  source/images/architecture_high_availability.png
  source/images/architecture_with_protocol.png
  source/images/architecture_with_proxy.png
  source/overview/architecture.rst
  source/overview/index.rst
Labels: Review Complete - Ready to Merge

#2161 Update sso-ldap.md
  source/deployment/sso-ldap.md
Labels: Review Complete - Ready to Merge

#2163 Update release-process.md
  source/process/release-process.md
Labels: Review Complete - Ready to Merge

#2160 Update the rm -r to rm -rf details bellow
  source/administration/upgrade.rst
Labels: Review Complete - Ready to Merge

#2165 9006 added the attachments to bulk import docs
  source/deployment/bulk-loading-data-format.rst
Labels: Review Complete - Ready to Merge

#2167 Update developer.rst with a link to developers.mattermost.com
  source/developer/api.rst
  source/developer/dev-setup.rst
  source/developer/mobile-developer-setup.rst
  source/guides/developer.rst
Labels: Review Complete - Ready to Merge

#2166 Update zoom.rst
  source/images/zoom_system_console.png
  source/integrations/zoom.rst
Labels: Review Complete - Ready to Merge

#2168 Update sso-ldap.md
  source/deployment/sso-ldap.md
Labels: Review Complete - Ready to Merge

#2169 Fix search metric names for perf monitoring
  source/deployment/metrics.rst
Labels: Review Complete - Ready to Merge

#2176 Gfycat API Key
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2178 Contributor steps updated
  README.md
Labels: Review Complete - Ready to Merge

#2182 copy security.md from developer docs, with tweaks
  source/administration/plugins.rst
Labels: Review Complete - Ready to Merge

#2183 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge

#2171 Patch 1 / Scaling doc
  source/deployment/scaling.rst
  source/images/scaling-1.png
  source/images/scaling-2.PNG
Labels: Review Complete - Ready to Merge

#1112 Changing "remote" to "distributed"
  source/process/working-at-mattermost.rst
Labels: Review Complete - Ready to Merge

#2184 Patch 2
  scaling-3.PNG
  source/deployment/scaling.rst
  source/images/scaling-3.PNG
Labels: Review Complete - Ready to Merge

#2186 Update telemetry.rst for v5.2
  source/administration/telemetry.rst
Labels: Review Complete - Ready to Merge
