Repository mattermost/docs, pull requests merged in 2018-06, with the labels that each got.

#2069 Add permissions and long posts upgrade notes
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge

#2061 [MM-10718] Move custom branding from enterprise to team edition
  source/administration/branding.rst
  source/administration/config-settings.rst
  source/deployment/customize-mattermost.rst
  source/overview/faq.rst
  source/overview/product.rst
Labels: Review Complete - Ready to Merge

#2075 4.10.1 docs
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: Needs PM Review, Review Complete - Ready to Merge

#2071 MM-9547 Added CustomUrlSchemes setting
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2077 Add daily/monthly active user count to telemetry docs.
  source/administration/telemetry.rst
Labels: Review Complete - Ready to Merge

#2076 Updates to dot release process
  source/process/release-process.md
Labels: Needs PM Review

#2080 System notice
  source/developer/fx-guidelines.rst
  source/images/systemnotice1.png
  source/images/systemnotice2.png
Labels: Review Complete - Ready to Merge

#1413 Documenting network access options
  source/deployment/deployment.md
Labels: Review Complete - Ready to Merge

#2084 Update mobile overview
  source/mobile/mobile-overview.rst
  source/overview/faq.rst
Labels: Review Complete - Ready to Merge

#2008 Add GitLab TE --> EE migration guide
  source/install/ee-install.rst
Labels: Review Complete - Ready to Merge

#2082 Added section on reporting issues about the desktop applications
  source/install/desktop.rst
Labels: Review Complete - Ready to Merge

#2086 Update working-at-mattermost.rst
  source/process/working-at-mattermost.rst
Labels: Review Complete - Ready to Merge

#2081 5.0 Docs part 1
  source/administration/config-settings.rst
  source/developer/slash-commands.rst
  source/developer/webhooks-incoming.rst
  source/developer/webhooks-outgoing.rst
  source/help/getting-started/configuring-notifications.rst
  source/help/settings/account-settings.rst
  source/overview/security.rst
Labels: Review Complete - Ready to Merge

#2091 Highlight need for PNS proxy server
  source/mobile/mobile-hpns.rst
Labels: Review Complete - Ready to Merge

#2094 Removing upcoming GitLab work from docs
  source/process/gitlab-process.rst
Labels: Review Complete - Ready to Merge

#2093 Update training.rst
  source/process/training.rst
Labels: Review Complete - Ready to Merge

#2090 Adds delete warning.
  source/administration/command-line-tools.rst
Labels: Review Complete - Ready to Merge

#2083 v5.0 docs Part 3
  source/administration/command-line-tools.rst
  source/administration/config-settings.rst
  source/administration/plugins.rst
  source/deployment/sso-ldap.md
  source/deployment/sso-saml-ldapsync.rst
Labels: Needs PM Review, Review Complete - Ready to Merge

#2019 v5.0 Changelog
  source/administration/changelog.md
Labels: Needs Dev Review, Review Complete - Ready to Merge

#2095 WIP: Advanced permissions docs
  source/administration/announcement-banner.rst
  source/administration/config-settings.rst
  source/deployment/advanced-permissions.rst
  source/deployment/permissions-backend.rst
  source/guides/administrator.rst
  source/images/system-scheme.png
  source/images/team-scheme-list.png
  source/images/team-scheme.png
Labels: Needs Dev Review, Needs PM Review, Review Complete - Ready to Merge

#2068 Documentation for ExperimentalEnableHardenedMode
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2092 Update telemetry.rst for v5.0
  source/administration/telemetry.rst
Labels: Review Complete - Ready to Merge

#2097 V5.0 documentation
  source/administration/announcement-banner.rst
  source/administration/branding.rst
  source/administration/changelog.md
  source/administration/command-line-tools.rst
  source/administration/config-settings.rst
  source/administration/important-upgrade-notes.rst
  source/administration/migrating.rst
  source/administration/plugins.rst
  source/administration/upgrade.rst
  source/conf.py
  source/deployment/advanced-permissions.rst
  source/deployment/bulk-loading-data.rst
  source/deployment/customize-mattermost.rst
  source/deployment/on-boarding.rst
  source/deployment/permissions-backend.rst
  source/deployment/sso-ldap.md
  source/deployment/sso-saml-ldapsync.rst
  source/developer/dev-setup-troubleshooting.rst
  source/developer/developer-flow.md
  source/developer/integration-faq.md
  source/developer/slash-commands.rst
  source/developer/webhooks-incoming.rst
  source/developer/webhooks-outgoing.rst
  source/guides/administrator.rst
  source/help/getting-started/configuring-notifications.rst
  source/help/settings/account-settings.rst
  source/images/system-scheme.png
  source/images/team-scheme-list.png
  source/images/team-scheme.png
  source/install/config-tls-mattermost.rst
  source/install/ee-install.rst
  source/install/install-debian-88-mattermost.rst
  source/install/install-rhel-66-mattermost.rst
  source/install/install-rhel-71-mattermost.rst
  source/install/install-ubuntu-1404-mattermost.rst
  source/install/install-ubuntu-1604-mattermost.rst
  source/install/prod-windows-2012.rst
  source/install/smtp-email-setup.rst
  source/install/troubleshooting.rst
  source/overview/auth.rst
  source/overview/faq.rst
  source/overview/product.rst
  source/overview/security.rst
  source/process/mobile-release-process.md
Labels: Review Complete - Ready to Merge

#2099 Update version-archive.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2102 5.0 docs corrections
  source/administration/changelog.md
  source/administration/command-line-tools.rst
  source/administration/config-settings.rst
  source/deployment/advanced-permissions.rst
  source/deployment/sso-ldap.md
  source/process/release-process.md
Labels: Review Complete - Ready to Merge

#2104 Short note about updating your service file to point to the mattermost binary
  source/administration/changelog.md
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge

#2103 Minor update to Global Relay docs for v5.1
  source/administration/compliance-export.rst
Labels: Review Complete - Ready to Merge

#2105 Update metrics.rst
  source/deployment/metrics.rst
Labels: Work in Progress

#2107 Add a known issue about configuring image proxy
  source/administration/changelog.md
Labels: Review Complete - Ready to Merge

#2108 Update training.rst adding ESR
  source/process/training.rst
Labels: Needs PM Review, Review Complete - Ready to Merge

#2110 Update QA checklist items
  source/process/release-process.md
Labels: Needs PM Review, Review Complete - Ready to Merge

#2111 Update mobile-troubleshoot.rst
  source/mobile/mobile-troubleshoot.rst
Labels: Review Complete - Ready to Merge

#2113 Changing platform to mattermost in permisssions export command documentation
  source/administration/command-line-tools.rst
Labels: Review Complete - Ready to Merge

#2114 Update intro to product overview
  source/overview/product.rst
Labels: Review Complete - Ready to Merge

#2088 MM-9929 Technical description of SAML sync with AD/LDAP
  source/deployment/sso-saml-ldapsync.rst
Labels: Review Complete - Ready to Merge

#2115 Update desktop-guide.rst
  source/help/apps/desktop-guide.rst
Labels: Review Complete - Ready to Merge

#2116 Correct an outdated doc for link previews.
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2037 Redirect dev docs to developers.mattermost.com
  source/developer/contribution-guide.md
  source/developer/core-developer-handbook.md
  source/developer/dev-setup-archlinux.rst
  source/developer/dev-setup-centos-7.rst
  source/developer/dev-setup-compiling.rst
  source/developer/dev-setup-osx.rst
  source/developer/dev-setup-ubuntu-1604.rst
  source/developer/dev-setup-windows.rst
  source/developer/dev-setup.rst
  source/developer/developer-flow.md
  source/developer/mobile-developer-setup.rst
  source/developer/redux-to-flow.rst
  source/developer/redux.rst
  source/developer/webapp-component.rst
  source/developer/webapp-end-to-end-testing.rst
  source/developer/webapp-to-redux.rst
Labels: Review Complete - Ready to Merge

#2117 document subpath support
  source/administration/config-settings.rst
  source/install/config-cloudfront.rst
Labels: Review Complete - Ready to Merge

#2119 v5.1 important upgrade notes
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge
