Repository mattermost/docs, pull requests merged in 2018-10, with the labels that each got.

#2306 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge

#2311 Update telemetry for v5.4
  source/administration/telemetry.rst
Labels: Review Complete - Ready to Merge

#2304 Clarified 'Allow untrusted network connections to' section
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2312 Add docs for EnablePublicChannelsMaterialization
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2314 Remove all users from channel
  source/administration/command-line-tools.rst
Labels: Review Complete - Ready to Merge

#2316 Restrict Team by Email
  source/help/settings/team-settings.rst
Labels: Review Complete - Ready to Merge

#2313 Update metrics.rst
  source/deployment/metrics.rst
Labels: Needs Dev Review

#2307 Add a troubleshooting section for resolving sticky statuses
  source/install/troubleshooting.rst
Labels: Review Complete - Ready to Merge

#2318 Edit Others Posts Permission
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2319 In: DMs and GMs
  source/help/getting-started/searching.rst
Labels: Review Complete - Ready to Merge

#2317 Add account setting option to hide channel switcher button in the sidebar
  source/help/settings/account-settings.rst
Labels: Review Complete - Ready to Merge

#2322 MM-10578 Update HA guide for plugins
  source/administration/plugins.rst
Labels: Needs PM Review

#2323 Webhook Description Limit
  source/developer/webhooks-incoming.rst
  source/developer/webhooks-outgoing.rst
Labels: Review Complete - Ready to Merge

#2309 Reduce size of search filter calendar image
  source/help/getting-started/searching.rst
Labels: Review Complete - Ready to Merge

#2320 Docs for E20 custom terms of service
  source/administration/config-settings.rst
  source/administration/custom-terms-of-service.rst
Labels: Review Complete - Ready to Merge

#2330 Writing optimization
  source/help/messaging/formatting-text.rst
Labels: Review Complete - Ready to Merge

#2324 Themes Across Teams
  source/deployment/bulk-loading-data-format.rst
Labels: Review Complete - Ready to Merge

#2282 v5.4 Changelog
  source/administration/changelog.md
Labels: Review Complete - Ready to Merge

#2334 Update compliance-export.rst
  source/administration/compliance-export.rst
Labels: Review Complete - Ready to Merge

#2335 Clarify not all user accounts need to use paid Zoom plan
  source/integrations/zoom.rst
Labels: Review Complete - Ready to Merge

#2329 Bulk-Export
  source/administration/bulk-export-data.rst
  source/administration/bulk-export.rst
  source/administration/command-line-tools.rst
  source/guides/administrator.rst
Labels: Review Complete - Ready to Merge

#2325 v5.4 - update account settings
  source/help/settings/account-settings.rst
Labels: Merge On Hold, Review Complete - Ready to Merge

#2337 V5.4 documentation
  source/administration/bulk-export-data.rst
  source/administration/bulk-export.rst
  source/administration/changelog.md
  source/administration/command-line-tools.rst
  source/administration/config-settings.rst
  source/administration/custom-terms-of-service.rst
  source/administration/important-upgrade-notes.rst
  source/administration/telemetry.rst
  source/conf.py
  source/deployment/bulk-loading-data-format.rst
  source/developer/interactive-message-buttons.rst
  source/developer/interactive-messages.rst
  source/developer/message-attachments.rst
  source/developer/slash-commands.rst
  source/developer/webhooks-incoming.rst
  source/developer/webhooks-outgoing.rst
  source/guides/administrator.rst
  source/help/getting-started/searching.rst
  source/help/settings/account-settings.rst
  source/help/settings/team-settings.rst
  source/images/message-menus.png
  source/integrations/webhook.rst
Labels: Review Complete - Ready to Merge

#2343 Update bug-fix-release.md
  source/process/bug-fix-release.md
Labels: Work in Progress

#2344 MM-11623: Add GPG signatures to version archive (v4.10+)
  source/administration/version-archive.rst
  source/process/feature-release.md
Labels: Review Complete - Ready to Merge

#2348 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge

#2347 Update compliance-export.rst
  source/administration/compliance-export.rst
Labels: Review Complete - Ready to Merge

#2349 fix changelog db changes
  source/administration/changelog.md
Labels: Review Complete - Ready to Merge

#2310 PLT-8347: Docs needed for CLI commands in Docker preview image
  source/administration/command-line-tools.rst
Labels: Hacktoberfest, Review Complete - Ready to Merge

#2342 fixed indentation issue
  source/install/config-tls-mattermost.rst
Labels: Awaiting Submitter Action

#2350 Added feature comparison table
  source/overview/faq.rst
Labels: Review Complete - Ready to Merge

#2355 Update QA steps for adding new teammates to testing
  source/process/bug-fix-release.md
  source/process/feature-release.md
Labels: Review Complete - Ready to Merge

#2354 Update doc for MaxNotificationsPerChannel
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2362 removing Pulling additional user attributes
  source/deployment/sso-ldap.md
Labels: Needs Dev Review

#2363 Update feature-release.md
  source/process/bug-fix-release.md
  source/process/feature-release.md
  source/process/security-release.md
Labels: Work in Progress
