Repository mattermost/docs, pull requests merged in 2018-02, with the labels that each got.

#1777 Add AD/LDAP setting updates
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#1778 Updated AD/LDAP FAQ
  source/deployment/sso-ldap.md
Labels: Review Complete - Ready to Merge

#1781 PLT-8726 - update cd path instruction in step 11 of upgrade
  source/administration/upgrade.rst
Labels: Review Complete - Ready to Merge

#1786 Update guest-article.rst
  source/process/guest-article.rst
Labels: Review Complete - Ready to Merge

#1789 Update asset-guidelines.rst
  source/process/asset-guidelines.rst
Labels: Review Complete - Ready to Merge

#1787 Update release-process.md
  source/process/release-process.md
Labels: Review Complete - Ready to Merge

#1790 Telemetry doc update for v4.7
  source/administration/telemetry.rst
Labels: Review Complete - Ready to Merge

#1794 Add minimum required version for software requirements
  source/developer/mobile-developer-setup.rst
Labels: Review Complete - Ready to Merge

#1743 v4.7 changelog
  source/administration/changelog.md
Labels: Needs Dev Review, Needs PM Review

#1775 4.7 Docs
  source/administration/config-settings.rst
  source/administration/image-proxy.rst
  source/developer/webhooks-outgoing.rst
  source/guides/administrator.rst
  source/help/settings/account-settings.rst
  source/images/image-proxy.png
  source/integrations/zoom.rst
Labels: Needs Dev Review

#1797 Update version-archive.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#1798 V4.7 documentation
  source/administration/changelog.md
  source/administration/telemetry.rst
  source/conf.py
Labels: Review Complete - Ready to Merge

#1791 Document custom post types for integrations and remove usage of 'payload' in outgoing webhooks and slash commands docs
  source/developer/slash-commands.rst
  source/developer/webhooks-incoming.rst
  source/developer/webhooks-outgoing.rst
Labels: Review Complete - Ready to Merge

#1809 Note for 4.7.1 release note
  source/administration/changelog.md
Labels: Review Complete - Ready to Merge

#1808 Update messaging-basics.rst
  source/help/getting-started/messaging-basics.rst
  source/images/messagesTable1.png
Labels: Review Complete - Ready to Merge

#1810 Update image path
  source/help/getting-started/messaging-basics.rst
  source/images/messagesTable1.PNG
Labels: Review Complete - Ready to Merge

#1803 Update conf.py
  source/conf.py
Labels: Needs PM Review

#1807 Update image-proxy.rst
  source/administration/image-proxy.rst
  source/images/image-proxy.png
Labels: Needs PM Review

#1788 Update database software requirement
  source/install/requirements.rst
Labels: Review Complete - Ready to Merge

#1795 Added asterisks around a word makes it italic too
  source/help/getting-started/messaging-basics.rst
Labels: Needs PM Review

#1817 v4.7.1 docs
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#1814 Update release-process.md
  source/process/release-process.md
Labels: Review Complete - Ready to Merge

#1792 MM-8368, nginx proxy faq
  source/install/config-proxy-nginx.rst
Labels: Review Complete - Ready to Merge

#1823 Update changelog.md
  source/administration/changelog.md
Labels: Review Complete - Ready to Merge

#1822 Additional 4.7 Docs corrections
  source/administration/changelog.md
  source/help/settings/account-settings.rst
Labels: Needs PM Review

#1825 Move image proxy doc above EE features in TOC
  source/guides/administrator.rst
Labels: Review Complete - Ready to Merge

#1801 4.7 Docs corrections - config-settings.rst
  source/administration/changelog.md
  source/administration/config-settings.rst
Labels: Needs PM Review

#1821 Update release-process.md
  source/process/release-process.md
Labels: Review Complete - Ready to Merge

#1812 Updated Ubuntu 16.04 unit file so service (re-)starts after automatic database updates
  source/install/install-ubuntu-1604-mattermost.rst
Labels: Review Complete - Ready to Merge

#1826 Update config-settings.rst
  source/administration/config-settings.rst
Labels: Needs Editor Review, Needs PM Review

#1815 Update asset-guidelines.rst
  source/process/asset-guidelines.rst
Labels: Review Complete - Ready to Merge

#1785 webhook.rst
  source/integrations/webhook.rst
Labels: Needs Dev Review, Needs PM Review

#1827 Update sso-ldap.md
  source/deployment/sso-ldap.md
Labels: Review Complete - Ready to Merge

#1820 Changelog and docs for 4.7.2
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#1793 4.6.2/4.5.2 Docs
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#1834 Make a note that output logs are not rotated at 10K lines
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#1832 Update release-process.md
  source/process/release-process.md
Labels: Review Complete - Ready to Merge

#1836 Update mobile-developer-setup.rst
  source/developer/mobile-developer-setup.rst
Labels: Review Complete - Ready to Merge

#1837 Fix config settings for ExperimentalGroupUnreadChannels
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#1838 Fix developer setup links in remaining two places
  source/developer/api-development-version4.rst
  source/developer/localization.rst
Labels: Review Complete - Ready to Merge
