Repository mattermost/docs, pull requests merged in 2019-03, with the labels that each got.

#2569 Add Tomasz Gruca as Polish reviewer, update localization maintainer info
  source/developer/localization.rst
Labels: Review Complete - Ready to Merge

#2507 RHEL version update
  source/install/config-mattermost-server.rst
  source/install/config-proxy-nginx.rst
  source/install/config-ssl-http2-nginx.rst
  source/install/ee-install.rst
  source/install/install-rhel-6-mattermost.rst
  source/install/install-rhel-6-mysql.rst
  source/install/install-rhel-6-postgresql.rst
  source/install/install-rhel-6-server.rst
  source/install/install-rhel-6.rst
  source/install/install-rhel-66-server.rst
  source/install/install-rhel-7-mattermost.rst
  source/install/install-rhel-7-mysql.rst
  source/install/install-rhel-7-postgresql.rst
  source/install/install-rhel-7-server.rst
  source/install/install-rhel-7.rst
  source/install/install-rhel-71-server.rst
  source/install/install-rhel-nginx.rst
  source/install/prod-rhel-6.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2574 Upgrade: correct path step 14
  source/administration/upgrade.rst
Labels: Review Complete - Ready to Merge

#2575 Update compliance.rst
  source/overview/compliance.rst
Labels: Review Complete - Ready to Merge

#2576 Bulk loading - Fix field name of user object
  source/deployment/bulk-loading-data-format.rst
Labels: Review Complete - Ready to Merge

#2580 Bulk loading - Fix scheme of emoji
  source/deployment/bulk-loading-data-format.rst
Labels: Review Complete - Ready to Merge

#2582 Fix appdata path
  source/install/desktop.rst
Labels: Review Complete - Ready to Merge

#2560 Added account settings section where a user can swap the send/new lin…
  source/help/getting-started/messaging-basics.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2584 Add to FAQ on Elasticsearch doc
  source/deployment/elasticsearch.rst
Labels: Review Complete - Ready to Merge

#2577 Add a note about pinned/flagged messages
  source/help/messaging/flagging-messages.rst
  source/help/messaging/pinning-messages.rst
Labels: Review Complete - Ready to Merge

#2585 Update training.rst
  source/process/training.rst
Labels: Review Complete - Ready to Merge

#2588 Fix outdated link in manifesto
  source/developer/manifesto.rst
Labels: Review Complete - Ready to Merge

#2589 Update ldap-group-sync.rst
  source/deployment/ldap-group-sync.rst
Labels: Review Complete - Ready to Merge

#2567 Restore text about invitations expire time to 48h, and removed relation with the InviteId.
  source/administration/config-settings.rst
  source/help/getting-started/managing-members.rst
Labels: Review Complete - Ready to Merge

#2591 Additional notice for Gmail SMTP users on required back-end changes
  source/install/smtp-email-setup.rst
Labels: Review Complete - Ready to Merge

#2561 WIP: Docs for customer obsession meeting
  source/process/training.rst
Labels: Review Complete - Ready to Merge

#2593 Update config-settings.rst
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2572 Add steps for how to upload plugins in HA
  source/administration/plugins.rst
Labels: Needs Dev Review, Review Complete - Ready to Merge

#2583 Added missing plugins and client-plugins folders in prod docker
  source/install/prod-docker.rst
Labels: Needs Dev Review

#2587 Add documentation about AllowedUntrustedInternalConnections changes in 5.9
  source/administration/config-settings.rst
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge

#2571 v5.9 Docs - documenting breaking change
  source/administration/config-settings.rst
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge

#2532 v5.9 Changelog
  source/administration/changelog.md
Labels: Needs PM Review, Review Complete - Ready to Merge

#2590 MM-14478 Update documentation on local image proxy and AllowUntrustedInternalConnections
  source/administration/changelog.md
  source/administration/config-settings.rst
  source/administration/image-proxy.rst
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge

#2598 5.9 version archive
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2596 Dot release docs
  source/administration/changelog.md
  source/administration/extended-support-release.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2578 Add AppConfig values for VPN connections
  source/mobile/mobile-appconfig.rst
Labels: Review Complete - Ready to Merge

#2601 Use OPTION in place of ALT for mac shortcuts
  source/help/messaging/keyboard-shortcuts.rst
Labels: Review Complete - Ready to Merge

#2599 Update install guides - listening on all IP addresses should be an optional step
  source/install/install-debian-postgresql.rst
  source/install/install-rhel-7-postgresql.rst
  source/install/install-ubuntu-1604-postgresql.rst
  source/install/install-ubuntu-1804-postgresql.rst
Labels: Review Complete - Ready to Merge

#2602 Stop deletion of client/plugins directory
  source/administration/upgrade.rst
Labels: Review Complete - Ready to Merge

#2586 fix: Interactive Dialogs field type
  source/developer/interactive-dialogs.rst
Labels: Review Complete - Ready to Merge

#2605 Desktop dot release docs
  source/help/apps/desktop-changelog.rst
  source/install/desktop.rst
Labels: Review Complete - Ready to Merge

#2606 Update prod-docker.rst to add Git installation step.
  source/install/prod-docker.rst
Labels: Review Complete - Ready to Merge

#2568 Pen test policy
  source/overview/security.rst
  source/process/security.md
Labels: Review Complete - Ready to Merge

#2600 Update community design meeting notes
  source/process/community-guidelines.rst
Labels: Needs PM Review, Review Complete - Ready to Merge
