Repository mattermost/docs, pull requests merged in 2019-11, with the labels that each got.

#3123 Update time and link info of the developers meeting
  source/process/training.rst
Labels: 3: Reviews Complete

#3109 Update install-mmte-helm-gitlab-helm.rst
  source/install/install-mmte-helm-gitlab-helm.rst
Labels: 3: Reviews Complete

#3034 Update permalink for help wanted issues
  source/process/community-guidelines.rst
  source/process/developer.rst
  source/process/help-wanted.rst
  source/process/overview.rst
Labels: 3: Reviews Complete

#3133 v5.16.3 / v5.15.3 dot release docs
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3136 Update open-source-components.rst
  source/administration/open-source-components.rst
Labels: 3: Reviews Complete

#3139 Equalsigns had been replaced with hyphen
  source/install/trouble_mysql.rst
Labels: 3: Reviews Complete

#3087 Update requirements.rst
  source/install/requirements.rst
  source/process/bug-fix-release.md
  source/process/feature-release.md
  source/process/software-requirements.rst
Labels: 3: Reviews Complete

#3126 New IR app screenshots
  source/images/incident-response-app-intro-image-fullpage.png
  source/images/incident-response-app-intro-image.png
  source/images/incident-response-app-post-action.png
Labels: 3: Reviews Complete

#3146 Add image text below images in intro section
  source/administration/incident-response-application.rst
Labels: 3: Reviews Complete

#3132 Change recommendation around jobserver and schedulers.
  source/deployment/cluster.rst
Labels: 3: Reviews Complete

#3122 Update README.md
  README.md
Labels: 1: PM Review

#3143 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 1: PM Review, 3: Reviews Complete

#3121 Update elasticsearch.rst
  source/deployment/elasticsearch.rst
Labels: 3: Reviews Complete

#3115 Draft 1: Kubernetes documentation
  source/install/faq_kubernetes.rst
  source/install/install-kubernetes-cluster.rst
  source/install/install-kubernetes-mattermost.rst
  source/install/install-kubernetes-operator.rst
  source/install/install-kubernetes.rst
  source/install/manage_kubernetes.rst
  source/install/use-kubernetes-mattermost.rst
Labels: 3: Reviews Complete

#3142 Update guest-accounts.rst
  source/deployment/guest-accounts.rst
Labels: 3: Reviews Complete

#3138 Update training.rst
  source/process/training.rst
Labels: 3: Reviews Complete

#3153 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3154 Kubernetes docs fixes
  source/install/install-kubernetes-cluster.rst
  source/install/install-kubernetes-mattermost.rst
  source/install/manage_kubernetes.rst
Labels: 3: Reviews Complete

#3155 Update docker-local-machine.rst
  source/install/docker-local-machine.rst
Labels: 3: Reviews Complete

#3078 v5.17 Changelog
  source/administration/changelog.md
Labels: 1: PM Review, 3: Reviews Complete

#3172 Update desktop-att-deployment.rst
  source/deployment/desktop-app-deployment.rst
Labels: 2: Dev Review

#3137 Update data-retention.rst
  source/administration/data-retention.rst
Labels: 3: Reviews Complete

#3128 Update extended-support-release.rst
  source/administration/changelog.md
  source/administration/extended-support-release.rst
  source/administration/release-lifecycle.rst
  source/administration/version-archive.rst
  source/images/ESR_graph.png
Labels: 1: PM Review, 3: Reviews Complete

#3188 5.17.1 docs
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3096 MM-18659 Improve documentation for outgoing proxy and link previews
  source/administration/config-settings.rst
  source/install/outbound-proxy.rst
Labels: 3: Reviews Complete

#3168 Update product.rst
  source/overview/product.rst
Labels: 3: Reviews Complete

#3192 Encourage devs to create blog posts for campaigns
  source/process/community-guidelines.rst
Labels: 3: Reviews Complete

#3160 Is this a correct update?
  source/deployment/ldap-group-sync.rst
Labels: 1: PM Review

#3199 Move future improvements to tips under community design meetings
  source/process/community-guidelines.rst
Labels: 3: Reviews Complete

#3195 Desktop 4.3.2 docs
  source/help/apps/desktop-changelog.rst
  source/install/desktop.rst
Labels: 1: PM Review, 3: Reviews Complete
