Repository mattermost/docs, pull requests merged in 2019-04, with the labels that each got.

#2531 Added join/list public/private teams permissions
  source/deployment/permissions-backend.rst
Labels: Review Complete - Ready to Merge

#2610 Adding "production quality" to our home
  source/process/handbook.rst
Labels: Review Complete - Ready to Merge

#2612 Update config-settings.rst
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2614 Clarify timeoutVPN only applies when the initial VPN connection is established
  source/mobile/mobile-appconfig.rst
Labels: Review Complete - Ready to Merge

#2607 Release schedule changes
  source/process/bug-fix-release.md
  source/process/feature-release.md
Labels: Review Complete - Ready to Merge

#2616 Add meeting etiquette to handbook
  source/process/training.rst
Labels: Review Complete - Ready to Merge

#2619 5.10 telemetry doc updates
  source/administration/telemetry.rst
Labels: Needs Editor Review

#2621 Toggle DisableLegacyMFA to true by default
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2613 Update bulk-export-data.rst
  source/administration/bulk-export-data.rst
  source/deployment/bulk-loading-data-format.rst
Labels: Review Complete - Ready to Merge

#2622 Google SSO updates
  source/deployment/sso-google.md
  source/images/google_authorised_domains.png
  source/images/google_enable_api.png
Labels: Review Complete - Ready to Merge

#2611 Update command-line-tools.rst
  source/administration/command-line-tools.rst
Labels: Review Complete - Ready to Merge

#2624 Rewrite audio/video call documentation
  source/deployment/video-and-audio-calling.rst
  source/guides/administrator.rst
Labels: Review Complete - Ready to Merge

#2625 Add a new screenshot for interactive messages docs
  source/developer/interactive-messages.rst
  source/images/interactive-messages.png
Labels: Review Complete - Ready to Merge

#2627 Remove expectancy for multi server support
  source/mobile/mobile-faq.rst
Labels: Review Complete - Ready to Merge

#2618 Update config-settings.rst
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2628 Update CO meeting doc
  source/process/training.rst
Labels: Needs Editor Review

#2634 Update permissions-backend.rst
  source/deployment/permissions-backend.rst
Labels: Review Complete - Ready to Merge

#2631 Update config-settings.rst
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2632 Update command-line-tools.rst
  source/administration/command-line-tools.rst
Labels: Review Complete - Ready to Merge

#2633 Update bulk-export-data.rst
  source/administration/bulk-export-data.rst
Labels: Review Complete - Ready to Merge

#2499 Added details for setting up channel-based deep linking
  source/mobile/mobile-faq.rst
Labels: Merge On Hold, Review Complete - Ready to Merge

#2620 Support for interactive ephemeral messages
  source/developer/interactive-messages.rst
Labels: Needs PM Review, Review Complete - Ready to Merge

#2630 Update managing-members.rst
  source/help/getting-started/managing-members.rst
Labels: Needs PM Review, Review Complete - Ready to Merge

#2604 v5.10 Changelog
  source/administration/changelog.md
Labels: Review Complete - Ready to Merge

#2636 Update version-archive.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2638 Tweak plugins section of 5.10 changelog
  source/administration/changelog.md
Labels: Needs Editor Review

#2629 Update prod-docker.rst
  source/install/prod-docker.rst
Labels: Review Complete - Ready to Merge

#2644 Document for engineer onboarding timeline & expectations
  source/guides/core.rst
  source/process/engineer-expectations.md
Labels: Review Complete - Ready to Merge

#2643 add info for mobile image preview troubleshooting
  source/mobile/mobile-troubleshoot.rst
Labels: Review Complete - Ready to Merge

#2641 Add FAQ for Customer Obs Meeting
  source/process/training.rst
Labels: Review Complete - Ready to Merge

#2642 Updated Login with ADFS/Office365 is not working
  source/mobile/mobile-troubleshoot.rst
Labels: Review Complete - Ready to Merge

#2648 Add chair and vice chair to COM doc
  source/process/training.rst
Labels: Review Complete - Ready to Merge

#2651 Update requirements.rst
  source/install/requirements.rst
Labels: Review Complete - Ready to Merge

#2649 Update desktop troubleshooting section
  source/install/desktop.rst
Labels: Review Complete - Ready to Merge

#2650 Updated IWA references in doc to be standard
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2652 Updated IWA guidance
  source/install/requirements.rst
Labels: Review Complete - Ready to Merge

#2637 Dot release docs
  source/administration/changelog.md
  source/administration/extended-support-release.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2654 BindPassword is not required
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2655 Updating release checklists
  source/process/bug-fix-release.md
  source/process/feature-release.md
Labels: Review Complete - Ready to Merge

#2656 v5.11 Upgrade note
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge

#2657 Update statistics.rst
  source/administration/statistics.rst
Labels: Review Complete - Ready to Merge

#2659 Add a note about log rotation
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2663 Update benefits-us.rst
  source/process/benefits-us.rst
Labels: Review Complete - Ready to Merge

#2664 Remove reference to matterbot in internal process doc
  source/process/training.rst
Labels: Review Complete - Ready to Merge

#2667 Added new ESR release to extended-support-release.rst
  source/administration/extended-support-release.rst
Labels: Review Complete - Ready to Merge

#2623 Add high trust FAQ
  source/overview/faq.rst
Labels: Review Complete - Ready to Merge

#2666 Update ESR info in version-archive.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge
