Repository mattermost/docs, pull requests merged in 2019-10, with the labels that each got.

#3021 Update doc to Buster
  source/guides/administrator.rst
  source/install/install-debian-mattermost.rst
  source/install/install-debian-mysql.rst
  source/install/install-debian-postgresql.rst
  source/install/install-debian-server.rst
  source/install/install-debian.rst
Labels: 3: Reviews Complete, Hacktoberfest

#3029 Add license step to k8s install instructions
  source/install/install-kubernetes-mattermost.rst
Labels: 1: Editor Review

#2987 MM-15220 Document Interactive Dialog submission error field
  source/developer/interactive-dialogs.rst
Labels: 3: Reviews Complete

#3033 Update config-in-database.rst
  source/administration/config-in-database.rst
Labels: 3: Reviews Complete

#3026 Update on-boarding.rst
  source/deployment/on-boarding.rst
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#3028 Update open-source-components.rst
  source/administration/open-source-components.rst
Labels: 3: Reviews Complete

#3037 Update advanced-permissions.rst
  source/deployment/advanced-permissions.rst
Labels: 3: Reviews Complete

#3046 Update branding.rst
  source/administration/branding.rst
Labels: 3: Reviews Complete

#3048 Update searching.rst
  source/help/getting-started/searching.rst
Labels: 3: Reviews Complete

#3036 Update bulk-export-data.rst
  source/administration/bulk-export-data.rst
Labels: 3: Reviews Complete

#3052 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3054 Add telemetry docs for 5.16
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#3058 Update changelog.md
  source/administration/changelog.md
  source/administration/extended-support-release.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3051 Fix user password after executing sampledata
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete, Hacktoberfest

#3060 Update managing-members.rst
  source/help/getting-started/managing-members.rst
Labels: 3: Reviews Complete

#3061 Update organizing-conversations.rst
  source/help/getting-started/organizing-conversations.rst
Labels: 3: Reviews Complete

#3027 Update Notification Docs and Add Flow Charts
  source/help/getting-started/configuring-notifications.rst
  source/images/browser_notification.png
  source/images/desktop_notification.png
  source/images/desktop_notification_chart.png
  source/images/email_notification.png
  source/images/email_notification_chart.png
  source/images/push_notification.png
  source/images/push_notification_chart.png
  source/overview/faq.rst
Labels: 3: Reviews Complete

#3019 Rename Architect to Principal SDE.
  source/process/developer.rst
Labels: 3: Reviews Complete

#3050 Create guest-accounts.rst
  source/deployment/guest-accounts.rst
  source/guides/administrator.rst
  source/help/getting-started/managing-members.rst
  source/images/Guest_Badges.png
  source/images/Guest_Invite_Screen.png
Labels: 1: PM Review, 3: Reviews Complete

#3055 Add two new perf monitoring metrics (for 5.16)
  source/deployment/metrics.rst
Labels: 1: PM Review, 3: Reviews Complete

#2968 update migrating.rst
  source/administration/migrating.rst
Labels: 1: Editor Review, 2: Dev Review

#3063 Update command-line-tools.rst
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#2992 v5.16 Changelog
  source/administration/changelog.md
Labels: 3: Reviews Complete

#3067 v5.16 docs
  source/help/getting-started/configuring-notifications.rst
  source/help/getting-started/signing-in.rst
  source/help/messaging/formatting-text.rst
  source/help/settings/account-settings.rst
  source/install/desktop-msi-gpo.rst
  source/install/desktop.rst
  source/install/prod-windows-2012.rst
  source/install/requirements.rst
  source/process/software-requirements.rst
Labels: 3: Reviews Complete

#2960 Remove color and footer known issues
  source/developer/message-attachments.rst
  source/images/attachments-footer.png
Labels: 3: Reviews Complete

#3041 AppConfig copyPasteProtection for Android since v1.24
  source/mobile/mobile-appconfig.rst
Labels: 3: Reviews Complete

#3080 Fixing a few broken v5.16 docs
  source/administration/branding.rst
  source/administration/changelog.md
  source/administration/config-settings.rst
  source/help/getting-started/managing-members.rst
Labels: 3: Reviews Complete

#3082 Update configuring-notifications.rst
  source/help/getting-started/configuring-notifications.rst
Labels: 3: Reviews Complete

#3083 Update changelog.md
  source/administration/changelog.md
Labels: 1: PM Review, 2: Dev Review

#3049 Update desktop-changelog.rst
  source/guides/administrator.rst
  source/help/apps/desktop-changelog.rst
  source/install/desktop.rst
Labels: 3: Reviews Complete

#3094 MM-18870 Workflow examples.
  source/samples/workflow.json
  source/samples/workflow_multiple.json
Labels: 3: Reviews Complete

#3095 Update desktop-changelog.rst
  source/help/apps/desktop-changelog.rst
  source/install/desktop.rst
Labels: 1: PM Review, 2: Dev Review

#3103 Update elasticsearch.rst
  source/deployment/elasticsearch.rst
Labels: 3: Reviews Complete

#3105 Update feature-release.md
  source/process/feature-release.md
Labels: 3: Reviews Complete

#3107 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#3112 Updated mattermost username in ()
  source/developer/localization.rst
Labels: Hacktoberfest

#3069 Moved Zoom docs to Zoom repo
  source/integrations/zoom.rst
Labels: 3: Reviews Complete, Lifecycle/1:stale

#3047 Add docs for incident response app (EE, Closed Alpha)
  source/administration/incident-response-application.rst
  source/guides/administrator.rst
  source/images/incident-response-app-fields.png
  source/images/incident-response-app-intro-image-fullpage.png
  source/images/incident-response-app-intro-image.png
  source/images/incident-response-app-post-action.png
  source/images/incident-response-app-statistics.png
  source/images/incident-response-app-transitions.png
Labels: 3: Reviews Complete
