Repository mattermost/docs, pull requests merged in 2019-02, with the labels that each got.

#2495 Dot release docs
  source/administration/changelog.md
  source/administration/extended-support-release.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2463 Update feature screenshot guidelines
  source/process/asset-guidelines.rst
Labels: Review Complete - Ready to Merge

#2497 Update client-side-data.rst
  source/deployment/client-side-data.rst
Labels: Review Complete - Ready to Merge

#2498 Update telemetry doc for 5.8
  source/administration/telemetry.rst
Labels: Review Complete - Ready to Merge

#2493 Clarify that "Restrict account creation to specified email domains" setting only applies to email login
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2501 Change heading for "0/5" subsection to properly link by autolink plugin
  source/process/training.rst
Labels: Review Complete - Ready to Merge

#2503 Documenting community moderators
  source/process/community-overview.rst
Labels: Review Complete - Ready to Merge

#2496 Upgrade - simpler way for copy paste
  source/administration/upgrade.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2500 Add sphinx-sitemap extension
  Pipfile
  Pipfile.lock
  source/conf.py
Labels: Hackfest, Review Complete - Ready to Merge

#2506 Update Global Relay config setting docs
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2505 add note about wrong default value for Allow Team Administrators to edit others posts
  source/administration/important-upgrade-notes.rst
Labels: Review Complete - Ready to Merge

#2508 MFA Doc for 5.8
  source/administration/config-settings.rst
  source/deployment/auth.rst
Labels: Review Complete - Ready to Merge

#2509 Add Webhook Modify-outgoing
  source/administration/command-line-tools.rst
Labels: Review Complete - Ready to Merge

#2510 Filter Users by User Role
  source/help/getting-started/managing-members.rst
Labels: Review Complete - Ready to Merge

#2511 5.8 LDAP Group Sync
  source/administration/config-settings.rst
  source/deployment/ldap-group-sync.rst
Labels: Review Complete - Ready to Merge

#2512 Add FAQ on how to add a message attachment via the API
  source/developer/message-attachments.rst
Labels: Review Complete - Ready to Merge

#2516 ES 5.8 docs
  source/administration/config-settings.rst
  source/help/messaging/mentioning-teammates.rst
  source/help/settings/channel-settings.rst
Labels: Review Complete - Ready to Merge

#2476 Hot Seat
  source/process/working-at-mattermost.rst
Labels: Review Complete - Ready to Merge

#2513 Add mattermost logs to command-line-tools.rst
  source/administration/command-line-tools.rst
Labels: Review Complete - Ready to Merge

#2519 Update a note on search replicas
  source/deployment/cluster.rst
Labels: Review Complete - Ready to Merge

#2514 Update image proxy documentation
  source/administration/config-settings.rst
  source/administration/image-proxy.rst
  source/images/image-proxy.png
Labels: Review Complete - Ready to Merge

#2520 Add section breaks for desktop app troubleshooting
  source/install/desktop.rst
Labels: Review Complete - Ready to Merge

#2522 Remove known issue from ToS
  source/administration/custom-terms-of-service.rst
Labels: Review Complete - Ready to Merge

#2479 v5.8 Changelog
  source/administration/changelog.md
Labels: Needs PM Review, Review Complete - Ready to Merge

#2504 Remove Ubuntu 14.04
  source/guides/administrator.rst
  source/install/ee-install.rst
  source/install/install-ubuntu-1404-mattermost.rst
  source/install/install-ubuntu-1404-mysql.rst
  source/install/install-ubuntu-1404-postgresql.rst
  source/install/install-ubuntu-1404-server.rst
  source/install/install-ubuntu-1404.rst
  source/install/prod-ubuntu-1404.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2487 [WIP] Add Group Policy documentation
  source/install/desktop.rst
Labels: Hackfest, Work in Progress

#2528 Update version-archive.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2518 Dot release docs
  source/administration/changelog.md
  source/administration/extended-support-release.rst
  source/administration/version-archive.rst
Labels: Review Complete - Ready to Merge

#2525 adds additional info for desktop app troubleshooting
  source/install/desktop.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2527 binding to low ports must be reenabled before restart
  source/administration/upgrade.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2530 Update feature-release.md
  source/process/bug-fix-release.md
  source/process/feature-release.md
Labels: Review Complete - Ready to Merge

#2534 Update clustering doc based on customer question
  source/administration/command-line-tools.rst
  source/deployment/cluster.rst
Labels: Needs Dev Review

#2537 Add QA step to merge Se test updates on Release Day
  source/process/bug-fix-release.md
  source/process/feature-release.md
Labels: Review Complete - Ready to Merge

#2529 Update poll example in interactive message doc
  source/developer/interactive-messages.rst
  source/images/poll.png
Labels: Review Complete - Ready to Merge

#2540 Fix contributors guidelines link
  CONTRIBUTING.md
Labels: Hackfest, Review Complete - Ready to Merge

#2524 Update plugin instruction during update
  source/administration/upgrade.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2541 Update compliance.rst
  source/overview/compliance.rst
Labels: Review Complete - Ready to Merge

#2542 Update managing-members.rst
  source/help/getting-started/managing-members.rst
Labels: Review Complete - Ready to Merge

#2543 Update requirements.rst
  source/install/requirements.rst
Labels: Review Complete - Ready to Merge

#2549 Adding Herzum
  source/administration/hipchat-migration-guidelines.rst
Labels: Review Complete - Ready to Merge

#2552 Corrected Custom Emoji config for sys admins
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2554 link to curl-for-windows
  source/developer/webhooks-incoming.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2533 Differentiate /join from /open
  source/developer/slash-commands.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2551 fixed typo in windows examples
  source/developer/webhooks-incoming.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2555 s/:doc:/:ref:/ to fix cross document link
  source/deployment/cluster.rst
Labels: Review Complete - Ready to Merge

#2556 Added detail on where the Support Email appears
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2559 Document customer obsession meeting
  source/process/training.rst
Labels: Needs Editor Review

#2558 Updated spelling under Common Issues section
  source/install/troubleshooting.rst
Labels: Hackfest

#2557 Updated the "MySql 8 Support" section
  source/install/requirements.rst
Labels: Hackfest

#2564 Update people-ops.rst
  source/process/people-ops.rst
Labels: Review Complete - Ready to Merge

#2546 How to run a community design meeting?
  source/process/community-guidelines.rst
Labels: Review Complete - Ready to Merge

#2553 Update ExperimentalHideTownSquareinLHS doc entry
  source/administration/config-settings.rst
Labels: Review Complete - Ready to Merge

#2563 Replace an awkward turn-of-phrase
  source/deployment/deployment.md
Labels: Hackfest

#2566 Update official reviewer of Polish translations
  source/developer/localization.rst
Labels: Review Complete - Ready to Merge

#2521 Debian Stretch and normalize path
  source/guides/administrator.rst
  source/install/ee-prod-debian-88.rst
  source/install/ee-prod-debian.rst
  source/install/install-debian-88-mattermost.rst
  source/install/install-debian-88-mysql.rst
  source/install/install-debian-88-postgresql.rst
  source/install/install-debian-88-server.rst
  source/install/install-debian-88.rst
  source/install/install-debian-mattermost.rst
  source/install/install-debian-mysql.rst
  source/install/install-debian-postgresql.rst
  source/install/install-debian-server.rst
  source/install/install-debian.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2539 bring zoom plugin docs up to date with zoom v2 api
  source/images/zoom_api_key.png
  source/integrations/zoom.rst
Labels: Hackfest, Review Complete - Ready to Merge

#2550 Adding import-bulk command to the documentation
  source/administration/command-line-tools.rst
Labels: Review Complete - Ready to Merge
