Repository mattermost/docs, pull requests merged in 2019-12, with the labels that each got.

#3203 Very minor formatting change
  source/developer/bot-accounts.rst
Labels: 1: PM Review

#3181 Clarify read and search replicas are in E10 and higher
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3178 Minor review of FAQ
  source/overview/faq.rst
Labels: 3: Reviews Complete

#3201 Include year factor in example storage calculation
  source/install/requirements.rst
Labels: 3: Reviews Complete

#3194 Updated note
  source/install/install-common-intro.rst
Labels: 3: Reviews Complete

#3193 Updated link in Note
  source/install/docker-local-machine.rst
Labels: 3: Reviews Complete

#3175 Edit: Formatting and updated FAQs
  source/administration/compliance-export.rst
Labels: 3: Reviews Complete

#3204 Update organizing-conversations.rst
  source/help/getting-started/organizing-conversations.rst
Labels: 3: Reviews Complete

#3202 Add documentation on how to run a Hackathon
  source/process/community-guidelines.rst
  source/process/how-to-run-a-hackathon.rst
Labels: 3: Reviews Complete

#3031 Cluster Transport Encryption Documentation
  source/guides/administrator.rst
  source/images/transport-encryption.png
  source/install/transport-encryption/config-cluster.rst
  source/install/transport-encryption/config-database.rst
  source/install/transport-encryption/config-mattermost.rst
  source/install/transport-encryption/config.rst
Labels: 3: Reviews Complete

#3207 Update guest-accounts.rst
  source/deployment/guest-accounts.rst
Labels: 3: Reviews Complete

#3209 Update command-line-tools.rst
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#3212 Moved Synchronized Groups into the general AD/LDAP content
  source/deployment/ldap-group-constrained-team-channel.rst
  source/deployment/ldap-group-sync.rst
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#3216 FAQ: How do I receive mobile push notification if my IT policy requires the use of a corporate proxy server?
  source/images/mobile-post-proxy-relay.png
  source/images/mobile-pre-proxy-relay.png
  source/mobile/mobile-faq.rst
  source/overview/faq.rst
Labels: 1: Editor Review, 1: PM Review, 2: Dev Review

#3210 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3223 Define "MLT"
  source/process/training.rst
Labels: 3: Reviews Complete

#3222 Update note about Mattermost supporting mobile wrapping
  source/mobile/mobile-faq.rst
Labels: 3: Reviews Complete

#3228 Update data-retention.rst
  source/administration/config-settings.rst
  source/administration/data-retention.rst
Labels: 3: Reviews Complete

#3232 Update telemetry for 5.18
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#3231 Update release checklists
  source/process/bug-fix-release.md
  source/process/feature-release.md
Labels: 3: Reviews Complete

#3233 Moving materials to Handbook > Messaging and Math
  source/process/asset-guidelines.rst
  source/process/casestudy.rst
  source/process/guest-article.rst
Labels: 3: Reviews Complete

#3226 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3241 Update data-retention.rst
  source/administration/data-retention.rst
Labels: 3: Reviews Complete

#3238 v5.18 docs (ES)
  source/administration/config-settings.rst
  source/help/getting-started/signing-in.rst
  source/help/messaging/sending-messages.rst
  source/images/email_notification_chart.png
  source/images/mobile_push_contents.png
  source/mobile/mobile-appstore-install.rst
  source/mobile/mobile-compile-yourself.rst
  source/mobile/mobile-faq.rst
Labels: 3: Reviews Complete

#3197 Add plugin marketplace telemetry
  source/administration/telemetry.rst
Labels: 1: PM Review, 3: Reviews Complete

#3242 Change three dots > hamburger menu (Part 2)
  source/help/settings/custom-emoji.rst
Labels: 3: Reviews Complete

#3240 Update data-retention.rst
  source/administration/data-retention.rst
Labels: 3: Reviews Complete

#3243 Add "How to run a Hackathon" to the TOC
  source/guides/core.rst
Labels: 3: Reviews Complete

#3164 v5.18 Changelog
  source/administration/changelog.md
Labels: 1: PM Review, 2: Dev Review, 3: Reviews Complete

#3177 Update docs for archived channels
  source/administration/config-settings.rst
  source/help/getting-started/organizing-conversations.rst
Labels: 1: PM Review, 3: Reviews Complete

#3180 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 1: PM Review, 3: Reviews Complete

#3239 Update compliance.rst
  source/administration/compliance.rst
Labels: 1: PM Review, 3: Reviews Complete

#3020 MM-18463/MM-19503 Add update_badge notifications to push proxy metrics dashboard
  source/samples/grafana-dashboards/mobile-push-notifications-monitoring.json
Labels: 3: Reviews Complete

#3056 Document API perf monitoring metrics (for 5.18)
  source/deployment/metrics.rst
Labels: 3: Reviews Complete

#3200 Update managing-members.rst
  source/help/getting-started/managing-members.rst
Labels: 3: Reviews Complete

#3221 Update compliance-export.rst
  source/administration/compliance-export.rst
Labels: 3: Reviews Complete

#3218 Added signing plugins section to plugins topic
  source/administration/plugins.rst
Labels: 3: Reviews Complete

#3213 AD/LDAP and SAML updates.
  source/administration/config-settings.rst
  source/deployment/guest-accounts.rst
  source/deployment/ldap-group-sync.rst
Labels: 3: Reviews Complete

#3249 Update version-archive.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3246 Update install-mmte-helm-gitlab-helm.rst
  source/install/install-mmte-helm-gitlab-helm.rst
Labels: 3: Reviews Complete

#3252 Update changelog.md
  source/administration/changelog.md
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#3255 Small tweaks to config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3245 Add Webex and WebRTC to list of available audio/video integration solutions
  source/deployment/video-and-audio-calling.rst
Labels: 3: Reviews Complete

#3257 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#2949 [GSoD'19] in-product text guidelines
  source/guides/core.rst
  source/process/documentation-UItext-guidelines.rst
  source/process/images/action.png
  source/process/images/cheatsheet.png
  source/process/images/field.png
  source/process/images/help.png
  source/process/images/label_after.png
  source/process/images/label_before.png
  source/process/images/menu.png
  source/process/images/title.png
  source/process/images/tooltip.png
Labels: 3: Reviews Complete

#3261 Backport docs
  source/administration/changelog.md
  source/administration/extended-support-release.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3264 Update prod-docker.rst
  source/install/prod-docker.rst
Labels: 3: Reviews Complete

#3266 Update training.rst
  source/process/training.rst
Labels: 3: Reviews Complete

#3267 Update ldap-group-constrained-team-channel.rst
  source/deployment/ldap-group-constrained-team-channel.rst
Labels: 3: Reviews Complete

#3276 Update release-faq.rst
  source/process/release-faq.rst
Labels: 1: PM Review

#3262 Update Plugin Doc for 5.18 Marketplace
  source/administration/plugins.rst
Labels: 3: Reviews Complete

#3270 Update feature-release.md
  source/process/feature-release.md
Labels: 3: Reviews Complete

#3141 GH-2615 and GH-2997- Added an updated guide for Windows Server 2016
  source/deployment/sso-saml-adfs-msws2016.rst
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_000.png
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_001.png
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_002.png
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_003.png
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_004.png
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_005.png
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_006.png
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_007.png
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_008.png
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_009.png
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_010.png
  source/images/SSO-SAML-ADFS_add-new-relying-party-trust_011.png
  source/images/SSO-SAML-ADFS_configure-saml_001.png
  source/images/SSO-SAML-ADFS_configure-saml_002.png
  source/images/SSO-SAML-ADFS_configure-saml_003.png
  source/images/SSO-SAML-ADFS_configure-saml_004.png
  source/images/SSO-SAML-ADFS_create-claim-rules_001.png
  source/images/SSO-SAML-ADFS_create-claim-rules_002.png
  source/images/SSO-SAML-ADFS_create-claim-rules_003.png
  source/images/SSO-SAML-ADFS_create-claim-rules_004.png
  source/images/SSO-SAML-ADFS_create-claim-rules_005.png
  source/images/SSO-SAML-ADFS_create-claim-rules_006.png
  source/images/SSO-SAML-ADFS_export-id-provider-cert_001.png
  source/images/SSO-SAML-ADFS_export-id-provider-cert_002.png
  source/images/SSO-SAML-ADFS_export-id-provider-cert_003.png
  source/images/SSO-SAML-ADFS_export-id-provider-cert_004.png
  source/images/SSO-SAML-ADFS_export-id-provider-cert_005.png
  source/images/SSO-SAML-ADFS_export-id-provider-cert_006.png
  source/images/SSO-SAML-ADFS_export-id-provider-cert_007.png
Labels: 2: Dev Review, Lifecycle/1:stale

#3277 Added ADFS SAML Config for Windows server 2016 to TOC.
  source/deployment/sso-saml.rst
Labels: 3: Reviews Complete

#3273 Update mobile-release-process.md
  source/process/mobile-release-process.md
Labels: 3: Reviews Complete

#3272 Update security-release.md
  source/process/security-release.md
Labels: 3: Reviews Complete
