Repository mattermost/docs, pull requests merged in 2020-10, with the labels that each got.

#3951 [MM-29144] Modify Omnibus curl command to use https
  source/help/getting-started/light-install.rst
  source/install/mattermost-omnibus.rst
Labels: 3: Reviews Complete

#3932 Clarify step 12 of server upgrade
  source/administration/upgrade.rst
Labels: 3: Reviews Complete

#3891 added gossip and fixed link to AD/LDAP
  source/administration/encryption.rst
Labels: 3: Reviews Complete

#3952 Formatting updates to docs based on local build errors
  source/administration/audit-log.rst
  source/administration/backup.rst
  source/administration/command-line-tools.rst
  source/administration/config-settings.rst
  source/administration/mmctl-cli-tool.rst
  source/administration/plugins.rst
  source/administration/prev-config-settings.rst
Labels: 3: Reviews Complete

#3956 Update README.md
  README.md
Labels: 3: Reviews Complete, Hacktoberfest

#3958 Update open-source-components.rst
  source/administration/open-source-components.rst
Labels: 3: Reviews Complete

#3953 Update cluster.rst
  source/administration/upgrade.rst
  source/deployment/cluster.rst
Labels: 3: Reviews Complete

#3931 Update guest-accounts.rst
  source/deployment/guest-accounts.rst
Labels: 3: Reviews Complete

#3954 Add note to install mailcap package for app functionality
  source/install/install-rhel-7-server.rst
Labels: 3: Reviews Complete

#3961 Update slash-commands.rst
  source/developer/slash-commands.rst
Labels: 3: Reviews Complete

#3985 Update searching.rst
  source/help/getting-started/searching.rst
Labels: 3: Reviews Complete

#3973 Update ldap-group-constrained-team-channel.rst
  source/deployment/ldap-group-constrained-team-channel.rst
Labels: 3: Reviews Complete

#3959 Update telemetry.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#3976 Add guide for RHEL 8 #3800
  source/guides/administrator.rst
  source/install/config-proxy-nginx.rst
  source/install/config-ssl-http2-nginx.rst
  source/install/ee-install.rst
  source/install/ee-prod-rhel-8.rst
  source/install/install-centos-oracle-scientific.rst
  source/install/install-rhel-8-mattermost.rst
  source/install/install-rhel-8-mysql.rst
  source/install/install-rhel-8-postgresql.rst
  source/install/install-rhel-8-server.rst
  source/install/install-rhel-8.rst
  source/install/install-rhel-nginx.rst
  source/install/prod-rhel-8.rst
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#3975 Update bleve.rst
  source/deployment/bleve.rst
Labels: 3: Reviews Complete

#3981 Update bulk-export.rst
  source/administration/bulk-export-data.rst
Labels: 3: Reviews Complete

#3971 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3968 ES v5.28 docs
  source/administration/config-settings.rst
  source/administration/notices.rst
  source/guides/administrator.rst
  source/help/getting-started/configuring-notifications.rst
  source/help/messaging/formatting-text.rst
  source/images/notices.png
Labels: 3: Reviews Complete

#3982 Update advanced-permissions.rst
  source/deployment/advanced-permissions.rst
Labels: 3: Reviews Complete

#3991 Update telemetry.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#3969 Update mmctl-cli-tool.rst
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#3978 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3995 Added Alt text to image
  source/404.html
Labels: Hacktoberfest, hacktoberfest-accepted

#3972 Create admin-roles.rst
  source/deployment/admin-roles.rst
  source/guides/administrator.rst
Labels: 1: Dev Review, 3: Reviews Complete

#3906 v5.28 Changelog
  source/administration/changelog.md
Labels: 3: Reviews Complete

#3986 added examples for editing privileges
  source/deployment/admin-roles.rst
Labels: 1: Dev Review, 3: Reviews Complete

#3967 Mattermost Cloud Billing
  source/overview/index.rst
  source/overview/mattermost-cloud-overview.rst
Labels: 1: PM Review

#3987 added telemetry for New Admin Roles (coming 5.28)
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#3989 added advanced logging config for audit
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3988 added logging metrics
  source/deployment/metrics.rst
Labels: 3: Reviews Complete

#3864 [MM-25659] document config settings for permanent delete of channel
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3824 [MM-25647] document config settings for permanent delete of user
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3934 v1.36 Mobile Changelog
  source/administration/mobile-changelog.md
Labels: 3: Reviews Complete

#3998 Update version-archive.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3997 Update desktop.rst
  source/install/desktop-msi-gpo.rst
  source/install/desktop.rst
Labels: 3: Reviews Complete

#3947 v4.6 Desktop Changelog
  source/help/apps/desktop-changelog.rst
Labels: 3: Reviews Complete

#4003 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4005 Adding Table of Content to Readme.md
  README.md
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4002 Adding FAQ on illicit use
  source/overview/faq.rst
Labels: 1: Dev Review

#4006 Updated sso-office.md
  source/deployment/sso-office.md
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4008 Update mattermost-cloud-overview.rst
  source/overview/mattermost-cloud-overview.rst
Labels: 1: PM Review

#3945 AAv2-doc-updates
  source/deployment/advanced-permissions.rst
  source/deployment/auth.rst
  source/deployment/sso-ldap.md
  source/deployment/sso-saml.rst
Labels: 3: Reviews Complete

#4011 docs: Updated elasticsearch documentation
  source/deployment/elasticsearch.rst
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4014 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#3970 docs: Nginx with SSL and HTTP/2 is now default
  source/install/config-proxy-nginx.rst
  source/install/config-ssl-http2-nginx.rst
  source/install/install-post-deployment-solution.rst
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4013 clarify requirements for custom sounds
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4023 Update theme-colors.rst
  source/help/settings/theme-colors.rst
Labels: 2: Editor Review

#4025 Update mattermost-cloud-overview.rst
  source/overview/mattermost-cloud-overview.rst
Labels: 1: PM Review

#4027 docs : Added note about DB performance to LDAP
  source/administration/config-settings.rst
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4026 Update upgrade notes
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4028 Clarifying what is not supported for PostgreSQL
  source/administration/changelog.md
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#3980 [GH-3979] fix(upgrade-script): script filename changed accross document for consistency
  source/administration/upgrade-script.rst
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4024 Update cluster.rst
  source/deployment/cluster.rst
Labels: 3: Reviews Complete

#4035 Desktop v4.6.1 docs
  source/help/apps/desktop-changelog.rst
  source/install/desktop-msi-gpo.rst
  source/install/desktop.rst
Labels: 3: Reviews Complete

#4019 Updating License Information Documentation
  source/install/ee-install.rst
Labels: 3: Reviews Complete

#4021 Updated Docs for`ElasticsearchSettings.IndexPrefix` setting
  source/administration/config-settings.rst
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#3963 Update plugins.rst
  source/administration/plugins.rst
Labels: 1: PM Review

#4041 Adds print media to resolve truncated printed pages
  source/theme.css
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4040 Fixed some typos
  source/administration/bulk-export-data.rst
Labels: 2: Editor Review, Hacktoberfest, hacktoberfest-accepted

#4046 Update ldap-group-sync.rst
  source/deployment/ldap-group-sync.rst
Labels: 3: Reviews Complete

#4039 Update devops-command-center.rst
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete
