Repository mattermost/docs, pull requests merged in 2020-05, with the labels that each got.

#3583 Move how-to-run-a-hackathon.rst to new handbook
  source/process/how-to-run-a-hackathon.rst
Labels: 3: Reviews Complete

#3577 Development process overview migrated to handbook
  source/process/overview.rst
Labels: 3: Reviews Complete

#3573 Move PM FAQ to the new handbook
  source/process/pm-faq.rst
Labels: 3: Reviews Complete

#3584 Migrate remaining marketing-related items from legacy handbook
  source/process/asset-guidelines.rst
  source/process/marketing-guidelines.rst
Labels: 3: Reviews Complete

#3526 Proposal: Add new section for training & education, move legacy handbook to handbook.mattermost.com
  source/guides/administrator.rst
  source/guides/education.rst
  source/index.rst
  source/templates/header.html
Labels: 1: PM Review, Do Not Merge

#3588 Education content fixes
  source/guides/core.rst
  source/guides/education.rst
  source/templates/index.html
Labels: 3: Reviews Complete

#3587 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#3590 Add documentation links for webapp message syntax
  source/developer/localization.rst
Labels: 3: Reviews Complete

#3576 Move feature quality levels section to product FAQ
  source/overview/faq.rst
  source/process/definitions.rst
Labels: 3: Reviews Complete

#3580 Update performance-alerting-guide.rst
  source/administration/performance-alerting-guide.rst
Labels: 3: Reviews Complete

#3591 Update versions from 4.3.0 to 4.4.1 in MSI installer guide
  source/install/desktop-msi-gpo.rst
Labels: 3: Reviews Complete

#3594 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#3585 Migrate engineer onboarding doc to handbook
  source/process/engineer-expectations.md
Labels: 3: Reviews Complete

#3597 Update administrator.rst
  source/guides/administrator.rst
Labels: 1: PM Review

#3604 Desktop 4.4.2 docs
  source/help/apps/desktop-changelog.rst
  source/install/desktop-msi-gpo.rst
  source/install/desktop.rst
Labels: 1: PM Review

#3582 Complete "community overview" page migration to handboock
  source/process/community-overview.rst
Labels: 3: Reviews Complete

#3579 Update backup.rst
  source/administration/backup.rst
Labels: 1: Dev Review, 1: PM Review

#3610 Update Download Link 4.4.1 --> 4.4.2
  source/help/apps/desktop-changelog.rst
Labels: 3: Reviews Complete

#3602 Updating docs to reference NAS #3486
  source/deployment/cluster.rst
Labels: 3: Reviews Complete

#3605 Update custom-emoji.rst
  source/help/settings/custom-emoji.rst
  source/images/add_custom_emoji.png
  source/images/delete_custom_emoji.png
Labels: 3: Reviews Complete

#3565 Update telemetry.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#3522 New documentation: Account management
  source/deployment/deployment.md
  source/images/Customer_Portal_Subscriptions.png
  source/images/mattermost_enterprise_license.png
  source/overview/architecture.rst
  source/overview/compliance.rst
  source/overview/faq.rst
  source/overview/index.rst
  source/overview/integrations.rst
  source/overview/license-and-subscription.rst
  source/overview/product.rst
  source/overview/security.rst
Labels: 2: Editor Review

#3596 MM-24808: Add "?src= arc" querysting tag to download source for the version archive
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3613 Update ldap-group-sync.rst
  source/deployment/ldap-group-sync.rst
Labels: 2: Editor Review

#3538 v5.23 Changelog
  source/administration/changelog.md
Labels: 1: PM Review, 3: Reviews Complete

#3575 Update integrations-directory.rst
  source/process/integrations-directory.rst
Labels: 3: Reviews Complete

#3618 Fix typo in mattermost license file in K8s install guide
  source/install/install-kubernetes-mattermost.rst
Labels: 3: Reviews Complete

#3539 Rework Logging in General Troubleshooting section
  source/install/troubleshooting.rst
Labels: 3: Reviews Complete

#3614 Add 50k AWS architecture.
  source/images/MattermostDeployment50kaws.png
  source/overview/architecture.rst
Labels: 3: Reviews Complete

#3534 MM-24094 EnableOpenTracing config setting missing from telemetry
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#3620 Update version-archive.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3611 Update GitLab Omnibus "mattermost" command
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#3603 Add (optional) pgpass steps to postgres installation in docs #3483
  source/install/install-ubuntu-1604-postgresql.rst
Labels: 3: Reviews Complete

#3619 [WIP] Broken images in inline section #3615
  source/help/messaging/formatting-text.rst
Labels: 2: Editor Review

#3581 Update sysctl settings
  source/deployment/cluster.rst
Labels: 3: Reviews Complete

#3624 Update team-settings.rst
  source/help/settings/team-settings.rst
Labels: 3: Reviews Complete

#3629 Javascript -> JavaScript
  source/deployment/bots.rst
Labels: 2: Editor Review

#3631 Update formatting-text.rst
  source/help/messaging/formatting-text.rst
Labels: 3: Reviews Complete

#3638 Update mobile-app-deployment.rst
  source/deployment/mobile-app-deployment.rst
Labels: 3: Reviews Complete

#3641 Add team settings to mobile feature parity faq.rst
  source/overview/faq.rst
Labels: 3: Reviews Complete

#3636 fixed typos in backup.rst file
  source/administration/backup.rst
Labels: 3: Reviews Complete

#3637 Update mobile-faq.rst
  source/mobile/mobile-faq.rst
Labels: 3: Reviews Complete

#3635 Including documentation for radio element in interactive dialog
  source/developer/interactive-dialogs.rst
  source/images/interactive-dialog-radio.png
Labels: 3: Reviews Complete

#3632 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3645 Revert querystring from URL link in version archive but keep for download link
  source/administration/version-archive.rst
Labels: 2: Editor Review

#3640 Add note about unsupported versions
  source/administration/extended-support-release.rst
  source/administration/important-upgrade-notes.rst
  source/administration/release-lifecycle.rst
  source/administration/upgrade.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3453 Clarifying TE & E10 scope
  source/overview/product.rst
Labels: 1: PM Review

#3189 Update configuring-notifications.rst
  source/help/getting-started/configuring-notifications.rst
Labels: 3: Reviews Complete
