Repository mattermost/docs, pull requests merged in 2020-03, with the labels that each got.

#3345 Add PR review guidelines
  source/process/sg_general-guidelines.rst
Labels: 3: Reviews Complete

#3425 Updates to Docker documentation
  source/install/prod-docker.rst
  source/process/bug-fix-release.md
  source/process/feature-release.md
Labels: 3: Reviews Complete

#3426 Update community-guidelines.rst
  source/process/community-guidelines.rst
Labels: 3: Reviews Complete

#3407 Update prod-docker to use sudo for chown
  source/install/prod-docker.rst
Labels: 3: Reviews Complete

#3424 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#3409 Update Troubleshooting for Citrix Virtual Apps and Desktop
  source/install/desktop.rst
Labels: 3: Reviews Complete

#3388 Create enterprise-roll-out-checklist.rst
  source/getting-started/enterprise-roll-out-checklist.rst
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#3392 Update install-mmte-helm-gitlab-helm.rst
  source/install/install-mmte-helm-gitlab-helm.rst
Labels: 2: Dev Review

#3429 Update command-line-tools.rst
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#3405 Update the deployment documentation
  source/deployment/desktop-app-deployment.rst
Labels: 3: Reviews Complete

#3428 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3440 Update on-boarding.rst
  source/deployment/on-boarding.rst
Labels: 3: Reviews Complete

#3430 Update telemetry.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#3436 Update image proxy documentation
  source/administration/image-proxy.rst
Labels: 1: Editor Review

#3444 fix typo in video-and-audio-calling.rst
  source/deployment/video-and-audio-calling.rst
Labels: 1: Editor Review

#3398 v5.21 Changelog
  source/administration/changelog.md
Labels: 1: PM Review, 2: Dev Review, 3: Reviews Complete

#3445 Add Tom De Moor as Dutch official reviewer
  source/developer/localization.rst
Labels: 3: Reviews Complete

#3449 Update version-archive.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3437 mmctl command update
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#3415 Bug severity guidelines docs
  source/guides/core.rst
  source/process/bug-fix-release.md
  source/process/bug-severity-guidelines.rst
  source/process/feature-release.md
Labels: 1: PM Review, 3: Reviews Complete

#3369 Update release checklists
  source/process/bug-fix-release.md
  source/process/feature-release.md
Labels: 3: Reviews Complete

#3183 Updating Jira Fix Version details
  source/process/community-systems.md
  source/process/overview.rst
  source/process/training.rst
Labels: 3: Reviews Complete

#3455 Fix broken links
  source/overview/faq.rst
  source/process/bug-fix-release.md
  source/process/bug-severity-guidelines.rst
  source/process/feature-release.md
Labels: 3: Reviews Complete

#3458 Improve troubleshooting/docs for gfycat integration
  source/install/troubleshooting.rst
Labels: 3: Reviews Complete

#3463 Add a new official reviewer for Russian, removing one for Ukrainian.
  source/developer/localization.rst
Labels: 3: Reviews Complete

#3465 Update organizing-conversations.rst
  source/help/getting-started/organizing-conversations.rst
Labels: 3: Reviews Complete

#3448 Moving Push Proxy related entry to developer documentation
  source/mobile/mobile-faq.rst
  source/overview/faq.rst
Labels: 3: Reviews Complete

#3467 Update bug-severity-guidelines.rst
  source/process/bug-severity-guidelines.rst
Labels: 3: Reviews Complete

#3427 Hint to `"skip_slack_parsing"` to ignore Slack-compatibility logic
  source/developer/interactive-messages.rst
Labels: 3: Reviews Complete

#3450 Added Video to AD/LDAP Group Sync
  source/deployment/ldap-group-sync.rst
Labels: 3: Reviews Complete

#3471 Update desktop-changelog.rst
  source/help/apps/desktop-changelog.rst
Labels: 3: Reviews Complete

#3473 Update desktop-changelog.rst
  source/help/apps/desktop-changelog.rst
Labels: 3: Reviews Complete

#3476 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#3470 FAQ on Archived Channels and data retention
  source/administration/data-retention.rst
Labels: 3: Reviews Complete

#3477 Correct Code Block Formatting for Transport Encryption (closes #3456)
  source/install/transport-encryption/config-mattermost.rst
Labels: 3: Reviews Complete

#3482 Fixes GH-542-Moved : Request for Documentation: Add to interactive-messages documentation
  source/developer/interactive-messages.rst
Labels: 3: Reviews Complete

#3480 Documenting how to change the default docker-compose network
  source/install/prod-docker.rst
Labels: 3: Reviews Complete

#3484 Update release-faq.rst
  source/process/release-faq.rst
Labels: 3: Reviews Complete

#3462 Update sg_grammar-spelling-mechanics.rst
  source/process/sg_grammar-spelling-mechanics.rst
Labels: 3: Reviews Complete

#3434 Update security.rst
  source/overview/security.rst
Labels: 3: Reviews Complete
