Repository mattermost/docs, pull requests merged in 2020-06, with the labels that each got.

#3654 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#3653 Update to "Plugin Configuration Information" telemetry
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#3655 5.23.1 docs
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3658 Update documentation-guidelines.rst
  source/process/documentation-guidelines.rst
Labels: 1: PM Review

#3662 Update open-source-components.rst
  source/administration/open-source-components.rst
Labels: 3: Reviews Complete

#3665 Create an integrations overview page for MS tools
  source/deployment/microsoft-integrations.rst
Labels: 3: Reviews Complete

#3668 ES v5.24 Docs
  source/administration/config-settings.rst
  source/help/apps/desktop-guide.rst
  source/help/getting-started/configuring-notifications.rst
  source/help/getting-started/searching.rst
  source/help/messaging/formatting-text.rst
  source/images/search-pop.png
Labels: 3: Reviews Complete

#3633 Update changelog.md
  source/administration/changelog.md
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#3669 Update elasticsearch.rst
  source/deployment/elasticsearch.rst
Labels: 3: Reviews Complete

#3644 DOCC Admin and User Guides
  source/administration/devops-command-center.rst
  source/administration/incident-response-application.rst
  source/guides/administrator.rst
Labels: Area/Feature Documentation

#3673 Add MS integrations overview to TOC
  source/deployment/microsoft-integrations.rst
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#3628 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#3670 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3679 Compliance: Create audit-log.rst
  source/administration/audit-log.rst
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#3683 Create bleve.rst
  source/deployment/bleve.rst
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#3684 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3682 Create team-channel-management.rst
  source/deployment/advanced-permissions.rst
  source/deployment/team-channel-management.rst
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#3675 Update channel-settings.rst
  source/help/settings/account-settings.rst
  source/help/settings/channel-settings.rst
  source/help/settings/team-settings.rst
Labels: 3: Reviews Complete

#3678 Update mmctl-cli-tool.rst
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#3672 Update license-and-subscription.rst
  source/overview/license-and-subscription.rst
Labels: 3: Reviews Complete

#3685 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3680 Update telemetry.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#3646 Remove unnecessary plugin directory rename step
  source/administration/upgrade.rst
Labels: 3: Reviews Complete

#3622 v5.24 Changelog
  source/administration/changelog.md
Labels: 1: PM Review, 3: Reviews Complete

#3556 v4.5 Desktop Changelog
  source/help/apps/desktop-changelog.rst
Labels: 3: Reviews Complete

#3694 Update download links for desktop 4.5
  source/install/desktop-msi-gpo.rst
  source/install/desktop.rst
Labels: 3: Reviews Complete

#3650 Adding Group Mentions
  source/help/messaging/mentioning-teammates.rst
Labels: 3: Reviews Complete

#3651 LDAP Profile Picture Sync attribute
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3652 clarification of profile picture sync
  source/deployment/sso-ldap.md
Labels: 3: Reviews Complete

#3696 Update version-archive.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3697 Fixing broken docs
  source/administration/telemetry.rst
  source/deployment/advanced-permissions.rst
  source/help/messaging/mentioning-teammates.rst
Labels: 3: Reviews Complete

#3693 Update devops-command-center.rst
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#3649 Added docs on how away status triggered
  source/help/getting-started/signing-in.rst
Labels: 3: Reviews Complete

#3690 Updated Skype for Business information
  source/deployment/video-and-audio-calling.rst
Labels: 3: Reviews Complete

#3701 update troubleshooting on mac
  source/install/desktop.rst
Labels: 2: Editor Review

#3687 Grammatical adjustment to general Mattermost description
  source/guides/branding.rst
Labels: 3: Reviews Complete

#3700 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#3704 Update desktop.rst
  source/install/desktop.rst
Labels: 3: Reviews Complete

#3703 Add release definitions
  source/administration/release-definitions.rst
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#3708 Change mscalendar docs link to be gitbooks link
  source/deployment/microsoft-integrations.rst
Labels: 3: Reviews Complete

#3663 Update feature quality level descriptions
  source/overview/faq.rst
Labels: 3: Reviews Complete

#3709 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#3686 Mobile App Deployment Guide Iteration - Voice and Tone
  source/deployment/mobile-app-deployment.rst
Labels: 3: Reviews Complete

#3710 Update interactive-dialogs.rst
  source/developer/interactive-dialogs.rst
Labels: 1: PM Review

#3715 Update open-source-components.rst
  source/administration/open-source-components.rst
Labels: 3: Reviews Complete

#3551 New CE Enterprise Deployment Guide
  source/deployment/enterprise-deployment-guide.rst
  source/guides/education.rst
Labels: 1: PM Review, Area/Core

#3713 Add troubleshooting doc when attempting to run the CLI or bulk loading tool with Bleve enabled
  source/administration/command-line-tools.rst
  source/deployment/bulk-loading-troubleshooting.rst
  source/deployment/bulk-loading.rst
Labels: 3: Reviews Complete

#3718 Update README.md
  README.md
Labels: 3: Reviews Complete

#3724 UI text guidelines moved from docs to handbook
  source/process/documentation-UItext-guidelines.rst
Labels: 2: Editor Review

#3719 Remove reference to the emoji cheat-sheet
  source/help/messaging/formatting-text.rst
Labels: 3: Reviews Complete

#3723 Update faq.rst
  source/overview/faq.rst
Labels: 3: Reviews Complete

#3714 Documentation: Data Retention FAQ
  source/administration/data-retention.rst
Labels: 3: Reviews Complete
