Repository mattermost/docs, pull requests merged in 2020-04, with the labels that each got.

#3464 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#3488 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#3493 Fix broken link in Bot Account Creation > Plugin
  source/developer/bot-accounts.rst
Labels: 3: Reviews Complete

#3469 Adding NPS rating for docs pages
  source/myscript.js
  source/templates/layout.html
  source/theme.css
Labels: 3: Reviews Complete

#3395 Add Plugin Labels and Prepackaged Plugin Info
  source/administration/plugins.rst
Labels: 3: Reviews Complete

#3495 Revert "Adding NPS rating for docs pages"
  source/myscript.js
  source/templates/layout.html
  source/theme.css
Labels: 3: Reviews Complete

#3491 Remove Oracle from Bitnami packages
  source/install/deploy-bitnami.rst
Labels: 3: Reviews Complete

#3466 Update FAQ on video, audio and screenshare
  source/overview/faq.rst
Labels: 1: PM Review

#3014 Added --remove-deactivated-users flag to channel move
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#3499 Add link to mattermost.com/contribute in community overview page
  source/process/community-overview.rst
Labels: 3: Reviews Complete

#3503 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#3512 Update telemetry docs for 5.22
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#3506 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3498 Update integrations.rst
  source/install/troubleshooting.rst
  source/overview/integrations.rst
Labels: 3: Reviews Complete

#3497 Update video-and-audio-calling.rst
  source/deployment/video-and-audio-calling.rst
Labels: 1: PM Review

#3513 Update mmctl-cli-tool.rst
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#3507 Update config-settings.rst (office365 update)
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3501 ES v5.22 docs
  source/help/getting-started/creating-teams.rst
  source/help/getting-started/organizing-conversations.rst
  source/images/sidebar-phase-1.gif
  source/images/team-sidebar.gif
Labels: 3: Reviews Complete

#3519 sidebar config
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3505 Update config-ssl-http2-apache2.rst
  source/install/config-ssl-http2-apache2.rst
Labels: 3: Reviews Complete

#3511 Add docs to unarchive channels (resubmit)
  source/help/getting-started/organizing-conversations.rst
  source/images/unarchive-channel.png
Labels: 3: Reviews Complete

#3517 Update config-settings.rst
  source/administration/config-settings.rst
Labels: 2: Dev Review

#3508 Update config-settings.rst (experimental audit settings)
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#3521 Update bulk-export.rst
  source/administration/bulk-export.rst
Labels: 3: Reviews Complete

#3443 Password Reset Section
  source/install/troubleshooting.rst
Labels: 3: Reviews Complete

#3496 Update advanced-permissions.rst
  source/deployment/advanced-permissions.rst
Labels: 3: Reviews Complete

#3451 v5.22 Changelog
  source/administration/changelog.md
Labels: 1: PM Review, 3: Reviews Complete

#3515 Update config-settings.rst (SMTP timeout)
  source/administration/config-settings.rst
Labels: 1: PM Review, 3: Reviews Complete

#3509 Update feature parity table in product FAQ
  source/overview/faq.rst
Labels: 3: Reviews Complete

#3518 Updated to include Account and team setup events, system console events
  source/administration/telemetry.rst
Labels: 2: Dev Review, 3: Reviews Complete

#3520 Update bulk-export-data.rst with post prop information
  source/administration/bulk-export-data.rst
  source/deployment/bulk-loading-data-format.rst
Labels: 3: Reviews Complete

#3533 Update version-archive.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3525 About Mattermost page moved to handbook
  source/process/handbook.rst
Labels: 3: Reviews Complete

#3502 Update desktop-changelog.rst
  source/help/apps/desktop-changelog.rst
Labels: 2: Dev Review

#3514 Update mmctl-cli-tool.rst
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#3489 Update feature-release.md
  source/process/feature-release.md
Labels: 3: Reviews Complete

#3540 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#3494 Edited NPS rating options from 4 to 3. (for docs.mattermost.com)
  source/myscript.js
  source/theme.css
Labels: 3: Reviews Complete

#3543 Move PM hiring process to the handbook
  source/process/product-manager-hiring.rst
Labels: 3: Reviews Complete

#3547 Update desktop-changelog.rst
  source/help/apps/desktop-changelog.rst
  source/install/desktop.rst
Labels: 1: PM Review, 3: Reviews Complete

#3553 v5.22.1 docs
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#3554 Update GA tag for docs page ratings
  source/myscript.js
Labels: 1: Editor Review, 2: Dev Review

#3549 Added pre-requisite
  source/deployment/auth.rst
Labels: 3: Reviews Complete

#3557 Update extended-support-release.rst
  source/administration/extended-support-release.rst
Labels: 3: Reviews Complete

#3542 Move release process docs to handbook
  source/guides/core.rst
  source/process/bug-fix-release.md
  source/process/bug-fix-release.rst
  source/process/dot-release.md
  source/process/dot-release.rst
  source/process/feature-release.md
  source/process/feature-release.rst
  source/process/mobile-release-process.md
  source/process/mobile-release-process.rst
  source/process/release-faq.rst
  source/process/release-scorecard-definitions.rst
  source/process/release-tips.md
  source/process/release-tips.rst
  source/process/security-release.md
  source/process/security-release.rst
Labels: 3: Reviews Complete

#3555 Update compliance.rst
  source/administration/compliance.rst
Labels: 3: Reviews Complete

#3546 Add reply arrow example
  source/help/messaging/sending-messages.rst
Labels: 1: Editor Review

#3561 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#3564 Update custom-emoji.rst
  source/help/settings/custom-emoji.rst
Labels: 3: Reviews Complete

#3566 Update myscript.js
  source/myscript.js
Labels: 3: Reviews Complete

#3559 Update migrating.rst
  source/administration/migrating.rst
Labels: 3: Reviews Complete

#3570 Fix link to Cloudron demo
  source/install/deploy-cloudron.rst
Labels: 3: Reviews Complete

#3567 Introduce Discord Dark themed Mattermost
  source/help/settings/theme-colors.rst
  source/images/discordDarkTheme.png
Labels: 3: Reviews Complete

#3574 Migrate development process to new handbook
  source/process/bug-severity-guidelines.rst
  source/process/deprecated-features.rst
  source/process/new-bug-tickets.rst
  source/process/software-requirements.rst
Labels: 3: Reviews Complete

#3578 Delete style-guide.md
  source/developer/style-guide.md
Labels: 3: Reviews Complete
