Repository mattermost/docs, pull requests merged in 2020-12, with the labels that each got.

#3811 Add Microsoft Teams Meetings to documentation
  source/deployment/video-and-audio-calling.rst
Labels: 2: Editor Review

#4140 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4128 Update notices.rst
  source/administration/notices.rst
  source/images/mattermost_admin_advisor_banner.png
  source/images/mattermost_admin_advisor_bot.png
  source/images/notices_admin.png
Labels: 3: Reviews Complete

#4142 Minor typo that did not render the markdown correctly
  source/developer/interactive-dialogs.rst
Labels: 2: Editor Review

#3977 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4150 MM-28882 Add Ignore Guests config to Server Config > SAMLSettings
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4151 SAML UI clarification
  source/deployment/sso-saml.rst
Labels: 3: Reviews Complete

#4152 SAML UI clarification
  source/cloud/cloud-administration/sso-saml.rst
Labels: 3: Reviews Complete

#4145 Update interactive-dialogs.rst
  source/developer/interactive-dialogs.rst
Labels: 3: Reviews Complete

#4134 `config migrate` and EnvVars warnings
  source/administration/config-in-database.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4154 Numbered step formatting updates
  source/cloud/cloud-administration/sso-ldap.md
Labels: 3: Reviews Complete

#4148 New config: Ignore Guest Users on AD/LDAP sync
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4149 MM-28882 Add config to Ignore Guests on AD/LDAP Sync
  source/deployment/sso-saml-ldapsync.rst
Labels: 3: Reviews Complete

#4166 Update faq.rst
  source/overview/faq.rst
Labels: 1: PM Review

#4161 MM-28630 - Add ping endpoint to local mode
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4156 MM-30436 Initialize server configuration with custom defaults
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4157 MM-28803 - Update Maximum Users Per Team
  source/cloud/cloud-administration/site-configuration.rst
Labels: 3: Reviews Complete

#4162 MM-28227 - Add mmctl role reset command
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4171 MM-31203 UX Optimizations to make end users happier
  source/deployment/on-boarding.rst
Labels: 3: Reviews Complete

#4177 Update training.rst
  source/process/training.rst
Labels: 3: Reviews Complete

#4155 Heading format corrections
  source/administration/config-settings.rst
Labels: 1: PM Review, 3: Reviews Complete

#4179 Removed `mmctl permissions reset` documentation
  source/administration/mmctl-cli-tool.rst
Labels: 1: PM Review, 3: Reviews Complete

#4175 MM-28717 Modify get and search user api endpoints to allow for new roles
  source/deployment/permissions-backend.rst
Labels: 1: PM Review, 3: Reviews Complete

#4160 MM-11399-Manage Admin Roles Using System Console
  source/deployment/admin-roles.rst
Labels: 1: PM Review, 3: Reviews Complete

#4167 MM-31032 Docs on rolling out new HA server versions to prod
  source/deployment/cluster.rst
Labels: 1: Dev Review, 3: Reviews Complete

#4172 MM 29223 Retrieve Compliance files from System Console
  source/administration/compliance-export.rst
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#4174 MM-28551 mmctl local mode API migration (phase 4)
  source/administration/mmctl-cli-tool.rst
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#4114 v5.30 changelog
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4178 Update training.rst
  source/process/training.rst
Labels: 3: Reviews Complete

#4163 Added Night Owl Theme
  source/help/settings/theme-colors.rst
  source/images/nightOwlDark.PNG
Labels: 3: Reviews Complete

#4137 Replace embedded scripts with google tag manager
  source/404.html
  source/templates/layout-notoc.html
  source/templates/layout.html
Labels: 3: Reviews Complete

#3946 [MM-28630] Fixes mattermost version note and adds mmctl system version and status docs
  source/administration/command-line-tools.rst
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4182 Update command-line-tools.rst
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#4115 v1.38 mobile changelog
  source/administration/mobile-changelog.md
Labels: 3: Reviews Complete

#4183 Update command-line-tools.rst
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#4181 Add recommended postgres config
  source/deployment/cluster.rst
Labels: 1: Dev Review

#4169 Update devops-command-center.rst
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#4187 Update version-archive.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#4189 Fixing broken docs
  source/deployment/permissions-backend.rst
  source/deployment/sso-saml-ldapsync.rst
Labels: 3: Reviews Complete

#4188 Update devops-command-center.rst
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#4159 Create cloud-changelog
  source/cloud/cloud-administration/cloud-changelog.md
  source/guides/cloud-admin-guide.rst
Labels: 3: Reviews Complete

#4191 Mobile v1.38.1 changelog
  source/administration/mobile-changelog.md
Labels: 3: Reviews Complete

#4186 [MM-30269] Add MySQL collation note
  source/install/requirements.rst
Labels: 3: Reviews Complete

#4080 Update troubleshooting-mobile.rst
  source/cloud/cloud-mobile/troubleshooting-mobile.rst
Labels: 3: Reviews Complete

#4190 Update devops-command-center.rst
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#4195 Read-Only admin role name changed to Viewer
  source/deployment/admin-roles.rst
Labels: 3: Reviews Complete
