Repository mattermost/docs, pull requests merged in 2020-11, with the labels that each got.

#4047 added -y to install command
  source/install/mattermost-omnibus.rst
Labels: 3: Reviews Complete

#4051 Fix FAQ section header levels
  source/overview/license-and-subscription.rst
Labels: 3: Reviews Complete

#4050 Image name removed
  source/deployment/sso-google.md
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4029 Ensure DB encoding is UTF-8
  source/install/install-rhel-7-postgresql.rst
  source/install/install-rhel-8-postgresql.rst
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4054 Update mattermost-cloud-overview.rst
  source/overview/mattermost-cloud-overview.rst
Labels: 1: PM Review

#4060 Update open-source-components.rst
  source/administration/open-source-components.rst
Labels: 3: Reviews Complete

#4059 removed "beta"
  source/install/mattermost-omnibus.rst
Labels: 3: Reviews Complete

#4061 Channel moderation out of beta
  source/deployment/advanced-permissions.rst
  source/deployment/team-channel-management.rst
Labels: 3: Reviews Complete

#4058 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4036 Cloud documentation reorganization
  source/administration/devops-command-center.rst
  source/cloud/cloud-administration/authentication.rst
  source/cloud/cloud-administration/cloud-compliance.rst
  source/cloud/cloud-administration/compliance-export.rst
  source/cloud/cloud-administration/custom-terms-of-service.rst
  source/cloud/cloud-administration/data-retention-policy.rst
  source/cloud/cloud-administration/site-configuration.rst
  source/cloud/cloud-administration/sso-gitlab.rst
  source/cloud/cloud-administration/sso-google.md
  source/cloud/cloud-administration/sso-ldap.md
  source/cloud/cloud-administration/sso-office.md
  source/cloud/cloud-administration/sso-saml.rst
  source/cloud/cloud-administration/system-administration.rst
  source/cloud/cloud-billing/cloud-billing.rst
  source/cloud/cloud-guest-accounts.rst
  source/cloud/cloud-incoming-webhooks.rst
  source/cloud/cloud-integrations.rst
  source/cloud/cloud-integrations/cloud-bot-accounts.rst
  source/cloud/cloud-integrations/cloud-incoming-webhooks.rst
  source/cloud/cloud-integrations/cloud-outgoing-webhooks.rst
  source/cloud/cloud-integrations/cloud-personal-access-tokens.rst
  source/cloud/cloud-integrations/cloud-slash-commands.rst
  source/cloud/cloud-integrations/embedding.rst
  source/cloud/cloud-integrations/integrations-faq.md
  source/cloud/cloud-integrations/oauth-2-0-applications.rst
  source/cloud/cloud-integrations/webhook.rst
  source/cloud/cloud-mobile/cloud-app-config.rst
  source/cloud/cloud-mobile/cloud-mobile-apps.rst
  source/cloud/cloud-mobile/mobile-apps-faq.rst
  source/cloud/cloud-mobile/troubleshooting-mobile.rst
  source/cloud/cloud-plugins.rst
  source/cloud/cloud-reporting.rst
  source/cloud/cloud-user-management/advanced-permissions.rst
  source/cloud/cloud-user-management/cloud-groups.rst
  source/cloud/cloud-user-management/cloud-team-and-channel.rst
  source/cloud/cloud-user-management/user-management.rst
  source/cloud/cloud-user-management/user-satisfaction-surveys.rst
  source/cloud/mobile-apps-faq.rst
  source/guides/administrator.rst
  source/guides/cloud-admin-guide.rst
  source/guides/education.rst
  source/guides/mobile-apps-faq.rst
  source/index.rst
  source/overview/index.rst
  source/overview/mattermost-cloud-overview.rst
  source/templates/index.html
Labels: 1: PM Review, 2: Editor Review

#4062 Update cloud-reporting.rst
  source/cloud/cloud-reporting.rst
Labels: 2: Editor Review

#4063 Update user-management.rst
  source/cloud/cloud-user-management/user-management.rst
Labels: 2: Editor Review

#4064 Update advanced-permissions.rst
  source/cloud/cloud-user-management/advanced-permissions.rst
Labels: 3: Reviews Complete

#4065 Update authentication.rst
  source/cloud/cloud-administration/authentication.rst
Labels: 3: Reviews Complete

#4076 Update cloud-admin-guide.rst
  source/guides/cloud-admin-guide.rst
Labels: 3: Reviews Complete

#4075 Update troubleshooting-mobile.rst
  source/cloud/cloud-mobile/troubleshooting-mobile.rst
Labels: 2: Editor Review

#4073 Update cloud-compliance.rst
  source/cloud/cloud-administration/cloud-compliance.rst
Labels: 3: Reviews Complete

#4072 Update integrations-faq.md
  source/cloud/cloud-integrations/integrations-faq.md
Labels: 3: Reviews Complete

#4071 Update cloud-personal-access-tokens.rst
  source/cloud/cloud-integrations/cloud-personal-access-tokens.rst
Labels: 3: Reviews Complete

#4082 Delete cloud-incoming-webhooks.rst
  source/cloud/cloud-incoming-webhooks.rst
Labels: 3: Reviews Complete

#4070 Update cloud-bot-accounts.rst
  source/cloud/cloud-integrations/cloud-bot-accounts.rst
Labels: 2: Editor Review

#4081 Update cloud-compliance.rst
  source/cloud/cloud-administration/cloud-compliance.rst
Labels: 1: PM Review

#4079 Update cloud-guest-accounts.rst
  source/cloud/cloud-guest-accounts.rst
Labels: 3: Reviews Complete

#4077 Update cloud-compliance.rst
  source/cloud/cloud-administration/cloud-compliance.rst
Labels: 3: Reviews Complete

#4078 Update cloud-team-and-channel.rst
  source/cloud/cloud-user-management/cloud-team-and-channel.rst
Labels: 3: Reviews Complete

#4067 Update sso-ldap.md
  source/cloud/cloud-administration/sso-ldap.md
Labels: 3: Reviews Complete

#4066 Update sso-saml.rst
  source/cloud/cloud-administration/saml-technical.rst
  source/cloud/cloud-administration/sso-saml.rst
Labels: 2: Editor Review

#4068 Update cloud-outgoing-webhooks.rst
  source/cloud/cloud-integrations/cloud-outgoing-webhooks.rst
Labels: 2: Editor Review

#4087 Cloud doc fixes
  source/cloud/cloud-administration/sso-saml.rst
  source/cloud/cloud-integrations/cloud-outgoing-webhooks.rst
  source/guides/cloud-admin-guide.rst
Labels: 3: Reviews Complete

#4069 Update cloud-slash-commands.rst
  source/cloud/cloud-integrations/cloud-slash-commands.rst
Labels: 3: Reviews Complete

#4088 Update cloud-outgoing-webhooks.rst
  source/cloud/cloud-integrations/cloud-outgoing-webhooks.rst
  source/cloud/cloud-integrations/cloud-slash-commands.rst
Labels: 3: Reviews Complete

#4074 Update mobile-apps-faq.rst
  source/cloud/cloud-mobile/mobile-apps-faq.rst
Labels: 2: Editor Review

#3984 [GH-3983] upgrade_mattermost: fixing `find` failure to delete non-empty dir
  source/administration/upgrade-script.rst
  source/administration/upgrade_mattermost.sh
Labels: 3: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#4018 Create light-install-hindi.rst
  light-install-hindi.rst
Labels: 2: Editor Review, Hacktoberfest, hacktoberfest-accepted

#4090 Update administrator.rst
  source/guides/administrator.rst
Labels: 2: Editor Review

#4093 Update light-install-hindi.rst
  source/administration/light-install-hindi.rst
Labels: 3: Reviews Complete

#4043 Clarified retaining files between Mattermost upgrades.
  source/administration/upgrade.rst
Labels: 1: Dev Review

#4045 added list of roles and privileges
  source/deployment/admin-roles.rst
Labels: 3: Reviews Complete

#4044 Adds information related to the license and the cluster limitation
  source/install/mattermost-omnibus.rst
Labels: 3: Reviews Complete

#4096 Update telemetry.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4098 updated sso-office.md
  source/deployment/sso-office.md
Labels: 3: Reviews Complete

#4100 v5.25.6 docs
  source/administration/changelog.md
  source/administration/extended-support-release.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#4104 Update config-settings.rst for AutoFollowThreads
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4017 v5.29 changelog
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4015 v1.37 mobile changelog
  source/administration/mobile-changelog.md
Labels: 3: Reviews Complete

#4089 MM-30090 Add documentation for ManagedResourcePaths setting
  source/administration/config-settings.rst
  source/install/desktop-managed-resources.rst
Labels: 3: Reviews Complete

#4092 Update telemetry.rst for product notices
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4094 Update and rename devops-command-center.rst to devops-command-center.md
  source/administration/devops-command-center.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4097 added `EnableExperimentalGossipEncryption`
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4111 Update devops-command-center.rst
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#4117 Update requirements.rst
  source/install/requirements.rst
Labels: 3: Reviews Complete

#4113 MM-27120 - Document how to use external database and filestore with Mattermost Operator
  source/install/install-kubernetes-mattermost.rst
Labels: 3: Reviews Complete

#4122 Update keyboard-shortcuts.rst
  source/help/messaging/keyboard-shortcuts.rst
Labels: 3: Reviews Complete

#4118 Update license-and-subscription.rst
  source/overview/license-and-subscription.rst
Labels: 3: Reviews Complete

#4116 Correct pronoun usage in Omnibus install instructions
  source/install/mattermost-omnibus.rst
Labels: 3: Reviews Complete

#4105 Update release processes
  source/administration/extended-support-release.rst
  source/administration/release-definitions.rst
  source/administration/release-lifecycle.rst
  source/images/ESR20212.png
Labels: 3: Reviews Complete

#4126 Use same filename for the environment file throughout
  source/administration/config-in-database.rst
Labels: 2: Editor Review

#4099 Update notices.rst
  source/administration/notices.rst
Labels: 3: Reviews Complete

#4123 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4037 solving #2876
  source/install/config-tls-mattermost.rst
Labels: 1: Dev Review, Hacktoberfest, Lifecycle/1:stale, hacktoberfest-accepted

#4125 Added static robots.txt file, corrected https reference on 404 page
  source/404.html
  source/_static/robots.txt
  source/conf.py
Labels: 2: Editor Review

#4130 Update config-tls-mattermost.rst
  source/install/config-tls-mattermost.rst
Labels: 3: Reviews Complete

#4121 Update requirements.rst
  source/install/requirements.rst
Labels: 3: Reviews Complete

#4129 Update devops-command-center.rst
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#4136 Emoji Autocomplete image resized
  source/help/messaging/emoji.rst
Labels: 2: Editor Review
