Repository mattermost/docs, pull requests merged in 2021-05, with the labels that each got.

#4542 MM-9695 Added statuses to channel invite modal
  source/help/getting-started/setting-your-status-availability.rst
Labels: 3: Reviews Complete

#4544 MM-31339: Send one direct message reply a day
  source/help/settings/account-settings.rst
Labels: 3: Reviews Complete

#4541 MM-19327 Add keyboard shortcut to focus search bar
  source/help/messaging/keyboard-shortcuts.rst
Labels: 3: Reviews Complete

#4538 Outdated screenshots
  source/help/getting-started/accessibility.rst
  source/help/getting-started/welcome-to-mattermost.rst
  source/help/messaging/executing-commands.rst
  source/help/messaging/pinning-messages.rst
  source/images/channel-sidebar-navigation.gif
  source/images/focus.png
  source/images/message-navigation.gif
  source/images/navigation.gif
  source/images/pinned-example-channel.png
  source/images/pinned-example-rhs.png
  source/images/pinned-posts.png
  source/images/slash-commands.gif
  source/images/teams.gif
  source/images/ui2.png
  source/images/ui_channels5.png
  source/images/ui_messages.png
  source/images/ui_notifications.png
  source/images/ui_search.png
Labels: 2: Editor Review

#4548 Replaced Teams screenshot with animated GIF
  source/help/getting-started/welcome-to-mattermost.rst
Labels: 3: Reviews Complete

#4543 MM-33853 remove CSV row limit in compliance monitoring
  source/administration/compliance-export.rst
  source/cloud/cloud-administration/compliance-export.rst
Labels: 3: Reviews Complete

#4527 Cloud changelog - May 5
  source/cloud/cloud-administration/cloud-changelog.md
Labels: 3: Reviews Complete

#4558 Update cloud-billing.rst
  source/cloud/cloud-billing/cloud-billing.rst
Labels: 3: Reviews Complete

#4559 Add a note about scaling above 100,000 registered users, reference loadtest framework
  source/deployment/scaling.rst
Labels: 3: Reviews Complete

#4551 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4560 Fix broken link
  source/deployment/scaling.rst
Labels: 3: Reviews Complete

#4554 mmctl heading formatting fixes
  source/administration/mmctl-cli-tool.rst
Labels: 2: Editor Review

#4563 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4540 Update config-ssl-http2-nginx.rst
  source/install/config-ssl-http2-nginx.rst
Labels: 3: Reviews Complete, preview-environment

#4536 Light Performance Adjustments for Page Speed Opportunities
  source/_static/images/Mattermost-Logo-Blue.svg
  source/templates/header.html
  source/templates/layout-notoc.html
  source/templates/layout.html
  source/theme.css
Labels: 3: Reviews Complete

#4562 Revised user rating to use GTM dataLayer
  source/myscript.js
Labels: 3: Reviews Complete

#4516 v5.35 Changelog
  source/administration/changelog.md
Labels: 1: PM Review

#4515 v1.43 Mobile Changelog
  source/administration/mobile-changelog.md
Labels: 1: PM Review

#4549 #MM-34893 removed a section about Admin Advisor as the feature is now disabled
  source/overview/compliance.rst
Labels: 3: Reviews Complete

#4547 MM-34893 Completely disabled Admin Advisor
  source/administration/notices.rst
Labels: 3: Reviews Complete

#4573 Update version-archive.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#4574 Update changelog.md
  source/administration/changelog.md
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4571 MM-25651 add ldap idmigrate command
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4533 Updating partner program definition
  source/process/partner-programs.rst
Labels: 3: Reviews Complete, preview-environment

#4539 Update product-manager.rst
  source/conf.py
  source/process/product-manager.rst
Labels: 3: Reviews Complete

#4589 Update mattermost team modify examples.
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#4587 Update Windows Requirement
  source/install/desktop.rst
Labels: 2: Editor Review

#4583 Fix GitLab documentation link
  source/deployment/deployment.md
Labels: 3: Reviews Complete, preview-environment

#4601 Update index.rst
  source/index.rst
  source/templates/index.html
Labels: 3: Reviews Complete

#4602 Format Fix
  source/install/desktop.rst
Labels: 3: Reviews Complete

#4605 Clarified the postgress access documentation
  source/install/install-ubuntu-2004-postgresql.rst
Labels: 3: Reviews Complete

#4596 Update devops-command-center.rst
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#4586 Adding new language Hungarian beta
  source/administration/config-settings.rst
  source/cloud/cloud-administration/site-configuration.rst
  source/help/settings/account-settings.rst
  source/overview/product.rst
Labels: 3: Reviews Complete

#4570 MM-33908 Resync LDAP Groups to Teams and Channels
  source/cloud/cloud-user-management/cloud-groups.rst
  source/deployment/ldap-group-sync.rst
Labels: 3: Reviews Complete

#4567 MM-34674 Adding config telemetry for feature flags
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4608 Adding a known issue to mobile changelog
  source/administration/mobile-changelog.md
Labels: 3: Reviews Complete

#4581 Create incident-collaboration.rst
  source/guides/incident-collaboration.rst
  source/incident-collaboration/getting-started.rst
  source/incident-collaboration/launching-playbooks.rst
  source/incident-collaboration/overview.rst
  source/incident-collaboration/playbook-planning.rst
  source/incident-collaboration/review-and-refine.rst
  source/incident-collaboration/updating-playbook-run.rst
  source/index.rst
  source/templates/index.html
Labels: Staging

#4607 Update faq.rst
  source/overview/faq.rst
Labels: 3: Reviews Complete

#4610 Update review-and-refine.rst
  source/incident-collaboration/review-and-refine.rst
  source/index.rst
  source/templates/index.html
Labels: Staging
