Repository mattermost/docs, pull requests merged in 2021-12, with the labels that each got.

#5279 Cloud changelog - Dec 1
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#5292 Gitlab OpenID to select correct scopes
  source/onboard/sso-gitlab.rst
Labels: 3: Reviews Complete

#5260 Remove license key deletion instructions
  source/upgrade/installing-license-key.rst
Labels: 3: Reviews Complete

#5299 Typo in Administration guide
  source/guides/administration.rst
Labels: 3: Reviews Complete

#5298 Update advanced-permissions.rst
  source/onboard/advanced-permissions.rst
Labels: 3: Reviews Complete

#5274 Updated Terms of Service to Terms of Use
  source/about/faq-mattermost-source-available-license.rst
  source/about/frequently-asked-questions.rst
  source/conf.py
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5294 Removed outdated configuration settings
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5282 v6.2 Important upgrade notes
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#5304 Removed unfinished config settings
  source/configure/configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#5290 Cloud changelog - Dec 8
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#5271 Update work-with-cards.rst
  source/boards/work-with-cards.rst
Labels: 1: PM Review, 2: Editor Review

#5306 Added Click to open thread user preference
  source/messaging/manage-channels-settings.rst
Labels: 2: Editor Review

#5308 Updated US Department of State link
  source/about/vpat.rst
Labels: 3: Reviews Complete

#5305 Added Developerflags config setting
  source/configure/configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#5206 Migrate from cloud > self-hosted
  source/manage/cloud-data-export.rst
Labels: 1: Dev Review, 1: PM Review

#5313 Incorporated cipher updates from the Security Team
  source/install/config-proxy-nginx.rst
  source/install/config-ssl-http2-nginx.rst
Labels: 2: Editor Review

#5311 Tabbed content fix
  source/messaging/configuring-notifications.rst
Labels: 3: Reviews Complete

#5277 Updates to Docker Local Setup
  source/install/setting-up-local-machine-using-docker.rst
Labels: 3: Reviews Complete

#5319 Real-Time update removed
  source/messaging/mentioning-teammates.rst
  source/onboard/guest-accounts.rst
Labels: 3: Reviews Complete

#5316 Up/Down Arrows navigate reply threads
  source/messaging/keyboard-accessibility.rst
Labels: 3: Reviews Complete

#5315 Channel autocomplete supports private channels
  source/messaging/channels-basics.rst
Labels: 3: Reviews Complete

#5320 Capitalization fix
  source/messaging/channels-basics.rst
Labels: 3: Reviews Complete

#5322 Add link to content channel.
  source/guides/community-chat.rst
Labels: 3: Reviews Complete

#5321 Removed unnecessary heading
  source/install/setting-up-local-machine-using-docker.rst
Labels: 3: Reviews Complete

#5314 Update notifications-and-updates.rst
  source/playbooks/notifications-and-updates.rst
Labels: 3: Reviews Complete

#5280 v6.2 changelog
  source/install/self-managed-changelog.md
  source/upgrade/open-source-components.rst
Labels: 1: PM Review, 3: Reviews Complete

#5312 Notifications updates
  source/conf.py
  source/images/channel-header.png
  source/images/channel-preferences.png
  source/images/channel-purpose.png
  source/messaging/channel-preferences.rst
  source/messaging/configuring-notifications.rst
  source/messaging/manage-channels-settings.rst
Labels: 2: Editor Review

#5310 v1.48.1 Mobile Changelog
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#5325 Update working-with-boards.rst
  source/boards/working-with-boards.rst
Labels: 3: Reviews Complete

#5323 Added redirect
  source/conf.py
Labels: 3: Reviews Complete

#5324 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5318 Clarified that mmctl is bundled from v6.0
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#5333 Changelog patch release updates
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#5332 Dot release docs
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5328 CRT known issues (Changelog)
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#5326 CRT Perf tweaks #1 (config and CRT docs)
  source/configure/configuration-settings.rst
  source/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete

#5329 Migrations Numbering Issue
  source/onboard/migrating-to-mattermost.rst
Labels: 3: Reviews Complete

#5300 Keycloak docs
  source/images/keycloak_10_get_metadata.png
  source/images/keycloak_1_client_settings.png
  source/images/keycloak_2_saml_keys.png
  source/images/keycloak_3_add_builtins.png
  source/images/keycloak_4_create_username_attribute.png
  source/images/keycloak_5_mattermost_config.png
  source/images/keycloak_6_mattermost_encryption.png
  source/images/keycloak_7_mattermost_request_signing.png
  source/images/keycloak_8_mattermost_attributes.png
  source/images/keycloak_9_export_metadata.png
  source/onboard/sso-saml-keycloak.rst
  source/onboard/sso-saml.rst
Labels: 3: Reviews Complete
