Repository mattermost/docs, pull requests merged in 2021-10, with the labels that each got.

#5087 Update mobile-faq.rst
  source/deploy/mobile-faq.rst
Labels: 3: Reviews Complete

#5109 chown only the Mattermost directory not the parent
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5071 Update conf.py
  source/conf.py
Labels: 3: Reviews Complete

#5079 Added Telemetry for MaxImageResolution
  source/manage/telemetry.rst
Labels: 2: Editor Review

#5083 Update audit-log.rst
  source/comply/audit-log.rst
  source/configure/configuration-settings.rst
  source/samples/sample-logger-config.json
Labels: 3: Reviews Complete

#5080 Fixed formatting for Maximum Image Resolution
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5077 Punctuation Correction
  source/playbooks/running-playbooks.rst
Labels: 2: Editor Review, Contributor

#5112 Added mmctl equivalents
  source/conf.py
  source/configure/configuation-in-mattermost-database.rst
  source/getting-started/admin-onboarding-tasks.rst
Labels: 3: Reviews Complete

#5093 Updated Mattermost heading references to Channels
  source/guides/channels.rst
Labels: 3: Reviews Complete

#5110 Dropped Windows 7 support
  source/install/software-hardware-requirements.rst
Labels: 2: Editor Review

#5103 Added CRT notifications docs
  source/conf.py
  source/guides/channels.rst
  source/messaging/configuring-notifications.rst
  source/messaging/managing-account-settings.rst
  source/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete

#5117 mattermost import/export CLI commands available in v6.0
  source/manage/command-line-tools.rst
Labels: 3: Reviews Complete

#5067 Create self-hosted-subscriptions
  source/about/cloud-subscriptions.rst
  source/about/licensing-and-subscription.rst
  source/about/self-hosted-subscriptions.rst
  source/about/subscription.rst
  source/conf.py
  source/images/Site_Statistics.png
  source/overview/index.rst
Labels: 3: Reviews Complete

#5104 Fixed typos and punctuation
  source/about/vpat.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor
