Repository mattermost/docs, pull requests merged in 2021-08, with the labels that each got.

#4805 Add missing space between SSL and guide
  source/install/config-tls-mattermost.rst
Labels: 2: Editor Review, Docathon 2021

#4812 Fix "Inline emphasis start-string without end-string" warnings on build
  source/deploy/mobile-apps-faq.rst
  source/deploy/mobile-faq.rst
  source/developer/dev-setup-troubleshooting.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4813 updating supported languages and converting display to a table
  source/messaging/formatting-text.rst
  source/messaging/syntax-highlighting.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4820 Fix all block related indent problems
  source/about/frequently-asked-questions.rst
  source/about/licensing-and-subscription.rst
  source/conf.py
  source/deploy/client-side-data.rst
  source/deploy/mobile-apps-faq.rst
  source/deploy/mobile-faq.rst
  source/deploy/mobile-hpns.rst
  source/developer/fx-guidelines.rst
  source/developer/webhooks-incoming.rst
  source/getting-started/enterprise-roll-out-checklist.rst
  source/guides/install-deploy-upgrade-scale.rst
  source/incident-collaboration/running-playbooks.rst
  source/incident-collaboration/setting-up-playbooks.rst
  source/install/config-tls-mattermost.rst
  source/install/desktop-app-changelog.rst
  source/install/desktop-app-install.rst
  source/install/heroku.rst
  source/install/install-debian-mattermost.rst
  source/install/install-rhel-6-mattermost.rst
  source/install/install-rhel-7-mattermost.rst
  source/install/install-rhel-8-mattermost.rst
  source/install/install-rhel-nginx.rst
  source/install/install-ubuntu-1804-mattermost.rst
  source/install/install-ubuntu-2004-mattermost.rst
  source/integrations/cloud-embedding.rst
  source/integrations/cloud-incoming-webhooks.rst
  source/integrations/cloud-webhook.rst
  source/integrations/embedding.rst
  source/integrations/webhook.rst
  source/integrations/zapier.rst
  source/onboard/advanced-permissions.rst
  source/onboard/cloud-guest-accounts.rst
  source/onboard/sso-saml-adfs-msws2016.rst
  source/onboard/sso-saml-adfs.rst
  source/onboard/sso-saml-okta.rst
  source/onboard/sso-saml-onelogin.rst
  source/process/training.rst
  source/scale/elasticsearch.rst
  source/scale/high-availability-cluster.rst
  source/scale/performance-alerting.rst
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete, Docathon 2021

#4824 Updated links
  source/deploy/mobile-hpns.rst
Labels: 3: Reviews Complete, Docathon 2021

#4822 Fixed Commas, Links and Updated links
  source/onboard/common-sso-office365.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4841 Update links to the exact section and update 1 broken link
  source/messaging/signing-in.rst
Labels: 3: Reviews Complete, Area/Content, Docathon 2021

#4790 Desktop v4.7.1 changelog
  source/install/desktop-app-changelog.rst
  source/install/desktop-app-install.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#4771 document custom dictionaries
  source/guides/install-deploy-upgrade-scale.rst
  source/install/desktop-custom-dictionaries.rst
Labels: 3: Reviews Complete, Area/Content, Docathon 2021

#4860 Fix broken links
  source/install/desktop-custom-dictionaries.rst
Labels: 3: Reviews Complete

#4825 Fixed and Updated Links, grammatical errors
  source/integrations/cloud-bot-accounts.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4849 Updated deprecated link in configuration-settings.rst
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete, Docathon 2021

#4836 Fixed deprecated link in audit-log.rst
  source/comply/audit-log.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4832 Fixed minor Typo and Punctuation
  source/integrations/cloud-outgoing-webhooks.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4767 Default PUID and GUID to 2000
  source/install/prod-docker.rst
Labels: 3: Reviews Complete, Do Not Merge, Docathon 2021

#4759 Fix incorrect WebSocket configuration for Apache2
  source/configure/config-proxy-apache2.rst
  source/configure/config-ssl-http2-apache2.rst
Labels: 1: Dev Review, Docathon 2021

#4835 Updated Links
  source/messaging/keyboard-shortcuts.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4903 Updated deprecated links in deploying-team-edition-on-bitnami.rst
  source/install/deploying-team-edition-on-bitnami.rst
Labels: 3: Reviews Complete, Docathon 2021

#4848 Update product.rst
  source/about/product.rst
Labels: 3: Reviews Complete, Area/Content, Docathon 2021

#4904 Updated dead links: certificate-and-compliance.rst
  source/about/certifications-and-compliance.rst
Labels: 3: Reviews Complete, Docathon 2021

#4922 Update vpat.rst
  source/about/vpat.rst
Labels: 3: Reviews Complete

#4788 additional information for "Migrate LDAP IdAttribute"
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete, Area/Content, Docathon 2021

#4870 Add Get Help and Community Chat Pages
  source/guides/community-chat.rst
  source/guides/get-help.rst
  source/index.rst
  source/templates/index.html
Labels: 3: Reviews Complete, Docathon 2021

#4892 update docs to explain how to determine channel IDs
  source/manage/command-line-tools.rst
Labels: 3: Reviews Complete, Docathon 2021

#4837 created bulk loading common issues
  source/onboard/bulk-loading-common-issues.rst
  source/onboard/bulk-loading-data.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4874 Updated the depreacted link in deploy-mobile-apps-using-emm-provider.rst
  source/deploy/deploy-mobile-apps-using-emm-provider.rst
Labels: 2: Editor Review, Docathon 2021

#4931 Update conf.py (redirects)
  source/conf.py
Labels: 3: Reviews Complete

#4924 Bleve search doc updates
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#4919 update dead links in corporate-directory-integration.rst
  source/about/corporate-directory-integration.rst
Labels: 2: Editor Review, Docathon 2021

#4850 Update links to the exact section and 1 broken link
  source/configure/using-outbound-proxy.rst
Labels: 3: Reviews Complete, Docathon 2021

#4839 Updated deprecated links in telemetry.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4930 Troubleshooting for NGINX error log: Connection Refused
  source/install/config-proxy-nginx.rst
  source/install/config-ssl-http2-nginx.rst
Labels: 3: Reviews Complete

#4705 External emojis prevents mobile messages from being sent
  source/configure/configuration-settings.rst
  source/deploy/mobile-troubleshoot.rst
Labels: 3: Reviews Complete

#4831 Fixed Broken Links , Typo and Grammatical error
  source/integrations/cloud-bot-accounts.rst
Labels: 2: Editor Review, Area/Documentation Improvements, Docathon 2021

#4834 Fixed deprecated Links, typos and Grammatical errors
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4840 Updated deprecated link in user-satisfaction-surveys.rst
  source/manage/user-satisfaction-surveys.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4842 Updated all deprecated links in command-line-tools.rst
  source/manage/command-line-tools.rst
Labels: 3: Reviews Complete, 2: Editor Review, Docathon 2021

#4838 Updated deprecated links in statistics.rst
  source/manage/statistics.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4845 Updated deprecated links in bulk-export-tool.rst
  source/manage/bulk-export-tool.rst
Labels: 3: Reviews Complete, Area/Content, Docathon 2021

#4844 Updated deprecated links in cloud-reporting.rst
  source/manage/cloud-reporting.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements, Docathon 2021

#4846 Updated deprecated links in organizing-conversations.rst
  source/getting-started/organizing-conversations.rst
Labels: 3: Reviews Complete, 2: Editor Review, Area/Content, Docathon 2021

#4852 Updated Deprecated Links and Grammatical error
  source/configure/enabling-chinese-japanese-korean-search.rst
Labels: 3: Reviews Complete, 2: Editor Review, Docathon 2021

#4853 Spelling Mistakes and Incorrect use of Grammar
  source/configure/email-templates.rst
Labels: 3: Reviews Complete, Docathon 2021

#4908 Updated deprecated links in elasticsearch.rst
  source/scale/elasticsearch.rst
Labels: 3: Reviews Complete, Docathon 2021

#4909 Updated deprecated links in high-availability-cluster.rst
  source/scale/high-availability-cluster.rst
Labels: 3: Reviews Complete, Docathon 2021

#4912 Updated deprecated links in performance-alerting.rst
  source/scale/performance-alerting.rst
Labels: 3: Reviews Complete, Docathon 2021

#4913 Updated deprecated links in performance-monitoring.rst
  source/scale/performance-monitoring.rst
Labels: 3: Reviews Complete, Docathon 2021

#4910 updated dead links in frequently-asked-questions.rst
  source/about/frequently-asked-questions.rst
Labels: 3: Reviews Complete, Docathon 2021

#4863 Fixed deprecated Links, typos and Grammatical errors in corporate-dir…
  source/about/corporate-directory-integration.rst
Labels: 3: Reviews Complete, Docathon 2021

#4873 Updated the deprecated links in consider-mobile-vpn-options.rst
  source/deploy/consider-mobile-vpn-options.rst
Labels: 3: Reviews Complete, Docathon 2021

#4878 Updated deprecated links in encryption-options.rst
  source/deploy/encryption-options.rst
Labels: 3: Reviews Complete, Docathon 2021

#4879 Updated the deprecated link in image-proxy.rst
  source/deploy/image-proxy.rst
Labels: 3: Reviews Complete, Docathon 2021

#4877 Updated deprecated links in desktop-app.rst
  source/deploy/desktop-app.rst
Labels: 3: Reviews Complete, Docathon 2021

#4857 Updated dead links in configuation-in-mattermost-database.rst
  source/configure/configuation-in-mattermost-database.rst
Labels: 3: Reviews Complete, Docathon 2021

#4864 Remove deprecated darkmode information
  source/images/dark_theme.png
  source/messaging/managing-desktop-app-options.rst
Labels: 3: Reviews Complete, Docathon 2021

#4868 Updated deprecated links in build-custom-mobile-apps.rst
  source/deploy/build-custom-mobile-apps.rst
Labels: 3: Reviews Complete, Docathon 2021

#4861 Updated deprecated link in common-sso-google.rst
  source/onboard/common-sso-google.rst
Labels: 3: Reviews Complete, Docathon 2021

#4865 Updated deprecated links in backup-disaster-recovery.rst
  source/deploy/backup-disaster-recovery.rst
Labels: 3: Reviews Complete, Docathon 2021

#4862 Fixed deprecated link in certifications-and-compliance.rst
  source/about/certifications-and-compliance.rst
Labels: 3: Reviews Complete, Docathon 2021

#4920 Update dead links in licensing-and-subscription.rst
  source/about/licensing-and-subscription.rst
Labels: 2: Editor Review, Docathon 2021

#4881 Updated deprecated links in mobile-overview.rst
  source/deploy/mobile-overview.rst
Labels: 2: Editor Review, Docathon 2021

#4880 Updated deprecated links in mobile-app-changelog.md
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete, Docathon 2021

#4867 Updated Dead links in integrations.rst
  source/about/integrations.rst
Labels: 3: Reviews Complete, Docathon 2021

#4932 Updated inactive anchor links and changed old url paths in admin-onboarding-tasks.rst
  source/about/corporate-directory-integration.rst
  source/getting-started/admin-onboarding-tasks.rst
Labels: 3: Reviews Complete, 2: Editor Review, Docathon 2021

#4926 Update broken links in security.rst
  source/about/security.rst
Labels: 3: Reviews Complete, Docathon 2021

#4928 MM-36779 - Add ChimeraOAuthProxyURL config option
  source/configure/configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete, preview-environment

#4918 Reliable Websockets: default to true
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#4927 Added functionality to archive/unarchive teams from system console
  source/guides/setup-onboard-manage-comply.rst
  source/manage/cloud-team-and-channel.rst
  source/manage/team-channel-members.rst
Labels: 3: Reviews Complete

#4916 Updated deprecated links in scaling-for-enterprise.rst
  source/scale/scaling-for-enterprise.rst
Labels: 3: Reviews Complete, Docathon 2021

#4858 Updated deprecated link in index.rst
  source/index.rst
Labels: 3: Reviews Complete, Docathon 2021

#4936 Formatting fix to return content
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#4925 Add sudo restorecon -R /opt/mattermost/ command line to the documenta…
  source/install/install-rhel-8-mattermost.rst
Labels: 3: Reviews Complete, Docathon 2021

#4944 Update telemetry.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#4821 Remove version numbers from generated sitemap
  source/conf.py
Labels: 3: Reviews Complete

#4851 New links added for reference on SMTP connection
  source/configure/smtp-email.rst
Labels: 2: Editor Review, Docathon 2021

#4949 Update python to use 3.7
  .circleci/config.yml
  .github/workflows/preview-env-fork.yml
  .github/workflows/preview-env.yml
Labels: 3: Reviews Complete

#4942 MM-35722: CRT, post click open thread
  source/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete

#4814 Cloud changelog - Aug 11th
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#4843 Environment Cleanup (Docathon 2021)
  Makefile
  Pipfile
  Pipfile.lock
  extensions/README.md
  extensions/reredirects/__init__.py
  extensions/sitemap/__init__.py
  make.bat
  source/conf.py
  source/index.rst
  source/templates/404.html
Labels: 2: Editor Review, Tech/RST, Tech/Sphinx, Docathon 2021

#4951 MM-35470 Disable config watching logic
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#4952 Environment cleanup - conf.py changes for build speed
  .circleci/config.yml
  Makefile
  Pipfile
  Pipfile.lock
  extensions/README.md
  extensions/reredirects/__init__.py
  extensions/sitemap/__init__.py
  make.bat
  source/conf.py
  source/templates/404.html
Labels: 3: Reviews Complete, preview-environment

#4943 Fix Upgrade docs content issues
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#4810 v5.38.0 Changelog
  source/install/self-managed-changelog.md
Labels: 1: PM Review, 3: Reviews Complete

#4957 Incident collaboration > playbooks
  source/conf.py
  source/guides/incident-collaboration.rst
  source/guides/playbooks.rst
  source/incident-collaboration/getting-started.rst
  source/index.rst
  source/playbooks/TOC.rst
  source/playbooks/getting-started.rst
  source/playbooks/overview.rst
  source/playbooks/refining-and-improving.rst
  source/playbooks/running-playbooks.rst
  source/playbooks/setting-up-playbooks.rst
  source/playbooks/updating-playbook-run.rst
  source/templates/index.html
Labels: 3: Reviews Complete

#4953 Clarifying which command to use to convert bots
  source/developer/bot-accounts.rst
Labels: 3: Reviews Complete

#4960 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#4809 v1.46.0 Mobile App Changelog
  source/deploy/mobile-app-changelog.md
Labels: 1: Dev Review, 3: Reviews Complete

#4817 Add desktop app compatibility
  source/install/desktop-app-changelog.rst
  source/upgrade/release-lifecycle.rst
Labels: 3: Reviews Complete

#4962 Update bot-accounts.rst
  source/developer/bot-accounts.rst
Labels: 3: Reviews Complete

#4964 Update self-managed-changelog.md
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4965 Update corporate-directory-integration.rst
  source/about/corporate-directory-integration.rst
Labels: 3: Reviews Complete

#4970 Added 301 redirects for v6.0 blog links
  source/conf.py
Labels: 3: Reviews Complete

#4961 Added 301 redirects for legacy guides
  source/conf.py
Labels: 3: Reviews Complete

#4954 Update self-managed-changelog.md
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#4956 Update conf.py (added 301 redirects)
  source/conf.py
Labels: 3: Reviews Complete

#4946 Update setting-up-playbooks.rst
  source/playbooks/TOC.rst
  source/playbooks/getting-started.rst
  source/playbooks/setting-up-playbooks.rst
Labels: 3: Reviews Complete

#4978 Upgrade process corrections
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#4950 Update desktop-app-changelog.rst
  source/install/desktop-app-changelog.rst
Labels: 1: Dev Review

#4968 Clarified that read only channels are available via E20
  source/onboard/advanced-permissions.rst
Labels: 3: Reviews Complete

#4967 Clarified auto-follow threads functionality
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#4987 New Deployment Landing Page
  source/conf.py
  source/guides/deployment.rst
Labels: 2: Editor Review

#4989 Update important-upgrade-notes.rst
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4997 Formatting fix for bulleted sub-list
  source/deploy/mobile-hpns.rst
Labels: 2: Editor Review

#4998 Update extending-messaging-with-integrations.md
  source/messaging/extending-messaging-with-integrations.md
Labels: 3: Reviews Complete

#5001 Update extending-messaging-with-integrations.md
  source/messaging/extending-messaging-with-integrations.md
Labels: 3: Reviews Complete

#5010 Update self-managed-changelog.md
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#5011 Switching the setcap / chown
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#4990 Update integrations.rst
  source/about/integrations.rst
Labels: 3: Reviews Complete

#4994 MM-27312 Allow uploading 10 files per post
  source/messaging/sharing-files.rst
Labels: 3: Reviews Complete

#4982 CRT Known Issues > Removed Limitations
  source/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete

#4981 CRT Known Issues > Removed Mobile limitation
  source/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete

#5009 Restructure deploy toc
  source/conf.py
  source/guides/deployment.rst
  source/guides/install-deploy-upgrade-scale.rst
  source/index.rst
  source/scale/scaling-for-enterprise.rst
  source/templates/index.html
Labels: 2: Editor Review

#5012 Add FAQ for non-profit program
  source/about/frequently-asked-questions.rst
  source/about/licensing-and-subscription.rst
Labels: 3: Reviews Complete
