Repository mattermost/docs, pull requests merged in 2021-02, with the labels that each got.

#4278 Update Incident Management's telemetry data
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4273 MM-31716 Remove the word experimental from gossip setting
  source/administration/config-settings.rst
  source/administration/telemetry.rst
  source/deployment/cluster.rst
Labels: 3: Reviews Complete

#4139 [MM-19888]: Add documentation for silent installation of MSI
  source/install/desktop-msi-gpo.rst
Labels: 3: Reviews Complete

#4038 Detailed the description to enable easy setup
  README.md
Labels: 1: PM Review, 2: Editor Review, Hacktoberfest, hacktoberfest-accepted

#4282 Update open-source-components.rst
  source/administration/open-source-components.rst
Labels: 3: Reviews Complete

#4284 Fixing a few desktop release links
  source/help/apps/desktop-changelog.rst
  source/install/desktop-msi-gpo.rst
Labels: 3: Reviews Complete

#4279 Add Incident Management automation features
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#4281 MM-31749 - Adjust documentation of Mattermost Operator
  source/install/install-kubernetes-cluster.rst
  source/install/install-kubernetes-mattermost.rst
  source/install/install-kubernetes-operator.rst
  source/install/install-kubernetes.rst
  source/install/use-kubernetes-mattermost.rst
Labels: 3: Reviews Complete

#4272 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4276 MM-4644 Upgrade Rate Limiting help text
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4261 Update license-and-subscription.rst
  source/overview/license-and-subscription.rst
Labels: 3: Reviews Complete

#4291 Cloud - MaxFileSize changed from 50Mb to 100Mb
  source/administration/config-settings.rst
  source/help/messaging/attaching-files.rst
Labels: 3: Reviews Complete

#4223 MM-31085 Create db init CLI command
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#4206 MM-25657 Add 'config migrate'
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4283 Update devops-command-center.rst
  source/administration/devops-command-center.rst
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#4288 Update license-and-subscription.rst
  source/overview/license-and-subscription.rst
Labels: 2: Editor Review

#4274 Adding Swedish and Bulgarian translations #7289
  source/administration/config-settings.rst
  source/cloud/cloud-administration/site-configuration.rst
  source/help/apps/desktop-guide.rst
  source/help/settings/account-settings.rst
  source/overview/product.rst
Labels: 3: Reviews Complete

#4255 Mobile Changelog v1.40
  source/administration/mobile-changelog.md
Labels: 3: Reviews Complete

#4298 MM-32227 - Update docs for saved messages
  source/administration/data-retention.rst
  source/administration/telemetry.rst
  source/cloud/cloud-administration/data-retention-policy.rst
  source/help/getting-started/accessibility.rst
  source/help/getting-started/creating-teams.rst
  source/help/getting-started/messaging-basics.rst
  source/help/getting-started/welcome-to-mattermost.rst
  source/help/messaging/flagging-messages.rst
  source/images/remove-from-saved-posts.png
  source/images/reply-icon.png
  source/images/save-message.png
  source/images/saved-posts.png
  source/overview/faq.rst
Labels: 3: Reviews Complete

#4306 Redirect to App custom url scheme with token data as query params
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4256 v5.32 Changelog
  source/administration/changelog.md
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#4266 MM-30851 Replace ExperimentalChannelSidebarOrganization with EnableLegacySidebar
  source/administration/config-settings.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4307 V5.32 documentation
  source/administration/changelog.md
  source/administration/config-settings.rst
  source/administration/important-upgrade-notes.rst
  source/administration/open-source-components.rst
  source/cloud/cloud-administration/site-configuration.rst
  source/conf.py
  source/deployment/cluster.rst
  source/help/apps/desktop-guide.rst
  source/help/settings/account-settings.rst
  source/overview/product.rst
Labels: 3: Reviews Complete

#4132 Remove `ExperimentalDataPrefetch` from system console
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4310 Update version-archive.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#4305 Revert MM-27312
  source/help/messaging/attaching-files.rst
Labels: 3: Reviews Complete

#4221 MM-28549 Bump postgres version to 10
  source/administration/backup.rst
  source/administration/encryption.rst
  source/install/prod-windows-2012.rst
Labels: 3: Reviews Complete

#4295 [MM-32393] Add documentation for the custom nginx template
  source/install/mattermost-omnibus.rst
Labels: 3: Reviews Complete

#4289 Update mmctl-cli-tool.rst
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4204 MM-31575 ENV var license override
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4227 MM-31518 Cloud Docs Technical Review Updates
  source/cloud/cloud-integrations/cloud-incoming-webhooks.rst
  source/cloud/cloud-integrations/cloud-outgoing-webhooks.rst
  source/cloud/cloud-integrations/embedding.rst
  source/cloud/cloud-mobile/troubleshooting-mobile.rst
Labels: 3: Reviews Complete

#4312 Fix typo in config-settings
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4315 Update changelog.md
  source/administration/changelog.md
Labels: 1: PM Review

#4303 MM-27688 - Implement OpenId Connect in Cloud
  source/cloud/cloud-administration/converting-oauth-2.0-to-openid-connect.rst
  source/cloud/cloud-administration/sso-gitlab.rst
  source/cloud/cloud-administration/sso-google.md
  source/cloud/cloud-administration/sso-office.md
  source/cloud/cloud-administration/sso-openid-connect.rst
  source/guides/cloud-admin-guide.rst
  source/images/Convert-to-OpenID-Connect.png
  source/images/OAuth20Deprecated.png
  source/images/create-google-sso-credentials.png
  source/images/google-sso-credentials.png
  source/images/google-sso-redirect-uri.png
  source/images/google-sso-web-app-name.png
  source/images/select-google-sso-web-app.png
Labels: 3: Reviews Complete

#4296 Verify SAML setup documentation for NameID
  source/deployment/sso-saml-adfs-msws2016.rst
  source/deployment/sso-saml-adfs.rst
Labels: 3: Reviews Complete

#4275 mmctl roles missing from product docs
  source/administration/mmctl-cli-tool.rst
Labels: 2: Editor Review

#4247 MM-31513 Document how team admins can see their teams' statistics
  source/administration/statistics.rst
  source/cloud/cloud-reporting.rst
Labels: 3: Reviews Complete

#4320 Broken Link Fixes
  source/cloud/cloud-administration/sso-gitlab.rst
  source/cloud/cloud-administration/sso-google.md
  source/cloud/cloud-administration/sso-office.md
Labels: 2: Editor Review

#4286 Replaced inherited layout with full layout to add article markup
  source/templates/layout.html
Labels: 3: Reviews Complete

#4311 Update signing-in.rst
  source/help/getting-started/signing-in.rst
Labels: 3: Reviews Complete

#4339 Clarify who can remove members from a Private Channel
  source/help/getting-started/welcome-to-mattermost.rst
Labels: 3: Reviews Complete

#4336 Update cloud-admin-guide.rst
  source/guides/cloud-admin-guide.rst
Labels: 3: Reviews Complete

#4337 Updating Image max sizes
  source/help/messaging/attaching-files.rst
Labels: 3: Reviews Complete

#4347 UseGossip setting should be UseExperimentalGossip
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4316 Cloud changelog Feb 24th release
  source/cloud/cloud-administration/cloud-changelog.md
Labels: 3: Reviews Complete

#4314 Update important-upgrade-notes.rst
  source/administration/changelog.md
  source/administration/important-upgrade-notes.rst
Labels: 1: Dev Review, 3: Reviews Complete

#4334 MM-31148 Add Formatting Shortcut Keys to Shortcut modal
  source/help/messaging/keyboard-shortcuts.rst
Labels: 3: Reviews Complete

#4333 MM-31993: Add flag to disable gossip compression
  source/administration/config-settings.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4331 MM-32726 Generate Support Packet
  source/cloud/cloud-administration/downloading-support-packet.rst
  source/guides/cloud-admin-guide.rst
Labels: 3: Reviews Complete

#4329 MM-33014 Add 'files' as a reserved team
  source/help/getting-started/creating-teams.rst
Labels: 3: Reviews Complete

#4332 MM-31391: Add max connection idle timeout to config - Cloud
  source/administration/config-settings.rst
  source/administration/telemetry.rst
Labels: 1: PM Review, 3: Reviews Complete

#4300 v1.40 Mobile Changelog
  source/administration/mobile-changelog.md
Labels: 3: Reviews Complete
