Repository mattermost/docs, pull requests merged in 2021-09, with the labels that each got.

#4985 Updated H1 to match URL
  source/getting-started/admin-onboarding-tasks.rst
Labels: 3: Reviews Complete

#5014 Fixed slack advanced exporter link
  source/onboard/migrating-to-mattermost.rst
Labels: 3: Reviews Complete

#5015 Add table of contents for version archive
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#4995 MM-36085: Split out System/Team Schemes from license feature checks
  source/onboard/advanced-permissions.rst
Labels: 3: Reviews Complete

#5023 Update deployment.rst (other resources link)
  source/guides/deployment.rst
Labels: 3: Reviews Complete

#4980 Initial POC commit
  source/images/all-plans-badge.png
  source/images/cloud-badge.png
  source/images/enterprise-badge.png
  source/images/professional-badge.png
  source/images/self-hosted-badge.png
  source/images/self-managed-badge.png
  source/scale/elasticsearch.rst
Labels: 3: Reviews Complete

#5028 Removed duplicate note
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5029 Update conf.py
  source/conf.py
Labels: 3: Reviews Complete

#4993 MM-10166 Add MaxImageResolution config setting
  source/configure/configuration-settings.rst
  source/messaging/sharing-files.rst
Labels: 2: Editor Review

#5008 Updated "self-managed" to "self-hosted"
  source/about/frequently-asked-questions.rst
  source/about/licensing-and-subscription.rst
  source/about/product.rst
  source/configure/configuration-settings.rst
  source/deploy/deployment-overview.md
  source/deploy/mobile-hpns.rst
  source/guides/setup-onboard-manage-comply.rst
  source/install/enterprise-install-upgrade.rst
  source/install/troubleshooting.rst
  source/manage/mmctl-command-line-tool.rst
  source/messaging/managing-account-settings.rst
  source/playbooks/getting-started.rst
  source/upgrade/release-lifecycle.rst
Labels: 3: Reviews Complete

#5002 Update remaining instances of "Messaging" to "Channels"
  source/deploy/build-custom-mobile-apps.rst
  source/getting-started/implementation-plan.rst
  source/getting-started/light-install.rst
  source/getting-started/welcome-email-to-end-users.rst
  source/install/self-managed-changelog.md
  source/onboard/bulk-loading-data.rst
  source/onboard/migrating-from-hipchat-to-mattermost.rst
  source/onboard/migrating-to-mattermost.rst
  source/onboard/migration-announcement-email.rst
  source/scale/performance-monitoring.rst
Labels: 3: Reviews Complete

#4871 Added back absent mobile FAQ topics
  source/conf.py
  source/deploy/consider-mobile-vpn-options.rst
  source/deploy/mobile-faq.rst
Labels: 1: Dev Review

#4974 Link updates
  source/comply/data-retention-policy.rst
  source/conf.py
  source/getting-started/enterprise-roll-out-checklist.rst
  source/getting-started/implementation-plan.rst
Labels: 3: Reviews Complete

#4979 Create Boards doc set
  source/boards/accessing-boards.rst
  source/boards/focalboard/installing-boards.rst
  source/boards/getting-started.rst
  source/boards/overview.rst
  source/boards/sharing-boards.rst
  source/boards/templates.rst
  source/boards/working-with-boards.rst
  source/boards/working-with-views.rst
  source/guides/boards.rst
  source/index.rst
  source/templates/index.html
Labels: 3: Reviews Complete

#5030 Fix Form Link
  source/about/licensing-and-subscription.rst
Labels: 3: Reviews Complete

#5031 Update boards.rst
  source/guides/boards.rst
Labels: 3: Reviews Complete

#5025 Add telemetry related to Apps Framework
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#5022 Added link to example webhook payloads
  source/playbooks/setting-up-playbooks.rst
Labels: 3: Reviews Complete

#5032 Link updates for guide content
  source/getting-started/implementation-plan.rst
Labels: 3: Reviews Complete

#4692 Update AppConfig spec file
  source/deploy/mattermost-specfile.xml
Labels: 3: Reviews Complete

#5036 LHS formatting fix for Helm operators installation
  source/guides/deployment.rst
Labels: 2: Editor Review

#5019 Update telemetry.rst
  source/manage/telemetry.rst
Labels: 1: Dev Review

#5037 Update telemetry.rst
  source/manage/telemetry.rst
Labels: 2: Editor Review

#5033 Create new Admin Guide
  source/conf.py
  source/getting-started/implementation-plan.rst
  source/guides/administration.rst
  source/guides/setup-onboard-manage-comply.rst
  source/index.rst
  source/templates/index.html
Labels: 3: Reviews Complete

#5020 Desktop 4.7.2 docs
  source/install/desktop-app-changelog.rst
  source/install/desktop-app-install.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#5005 Incorporated mmctl new and changed videos from R&D
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#5035 v6.0 mmctl command & inherited option updates
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#5027 Update playbooks.rst
  source/guides/playbooks.rst
  source/playbooks/setting-up-playbooks.rst
Labels: 3: Reviews Complete

#5041 Remove references to product names.
  source/guides/deployment.rst
Labels: 3: Reviews Complete

#5043 Fixed formatting for 301 redirects causing build failures
  source/conf.py
Labels: 2: Editor Review

#5013 Update configuration-settings - MaxFileSize
  source/configure/configuration-settings.rst
Labels: 1: PM Review

#5016 v5.39 Changelog
  source/conf.py
  source/deploy/mobile-app-changelog.md
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5038 Fix environment pickling
  Makefile
  extensions/reredirects/__init__.py
  extensions/sitemap/__init__.py
  source/conf.py
Labels: 3: Reviews Complete

#5049 Added new redirect and a new bots file for integrations
  source/conf.py
  source/messaging/extending-messaging-with-integrations.md
Labels: 3: Reviews Complete

#5047 Added 301 redirects
  source/conf.py
Labels: 3: Reviews Complete

#5046 Added missing mobile topic to LHS
  source/guides/deployment.rst
Labels: 3: Reviews Complete

#5054 Update setting-up-playbooks.rst
  source/playbooks/setting-up-playbooks.rst
Labels: 3: Reviews Complete

#5044 New Channels, Playbooks, and Boards User Guide Landing pages
  source/boards/focalboard/installing-boards.rst
  source/conf.py
  source/getting-started/implementation-plan.rst
  source/guides/boards.rst
  source/guides/channels.rst
  source/guides/messaging.rst
  source/guides/playbooks.rst
  source/images/Boards_Hero.png
  source/images/Channels_Hero.png
  source/images/Playbooks_Hero.png
  source/index.rst
  source/messaging/accessing-your-workspace.rst
  source/messaging/welcome-to-mattermost-messaging.rst
  source/templates/index.html
Labels: 2: Editor Review

#5050 Sphinx Cleanup - Explicit references to static files in HTML templates
  source/_static/favicon.ico
  source/_static/myscript.js
  source/_static/mytheme.css
  source/conf.py
  source/templates/layout-notoc.html
  source/templates/layout.html
Labels: 3: Reviews Complete

#5060 Added sphinx-tabs extension
  Pipfile
  Pipfile.lock
  source/conf.py
Labels: 2: Editor Review

#4983 v6.0 Beta to GA Updates - Config Settings
  source/about/frequently-asked-questions.rst
  source/about/licensing-and-subscription.rst
  source/archive/cloud-compliance-export.rst
  source/archive/cloud-custom-terms-of-service.rst
  source/archive/cloud-guest-accounts.rst
  source/comply/cloud-compliance-and-oversight.rst
  source/comply/compliance-export.rst
  source/comply/custom-terms-of-service.rst
  source/conf.py
  source/configure/configuration-settings.rst
  source/deploy/bleve-search.rst
  source/guides/setup-onboard-manage-comply.rst
  source/install/enterprise-install-upgrade.rst
  source/manage/cloud-user-satisfaction-surveys.rst
  source/manage/command-line-tools.rst
  source/manage/mmctl-command-line-tool.rst
  source/manage/statistics.rst
  source/manage/user-satisfaction-surveys.rst
  source/messaging/managing-channels.rst
  source/onboard/ad-ldap-groups-synchronization.rst
  source/onboard/ad-ldap.md
  source/onboard/advanced-permissions-backend-infrastructure.rst
  source/onboard/advanced-permissions.rst
  source/onboard/guest-accounts.rst
  source/onboard/sso-saml-faq.rst
  source/onboard/system-admin-roles.rst
  source/onboard/user-provisioning-workflows.rst
  source/scale/elasticsearch.rst
Labels: 3: Reviews Complete

#5026 Update telemetry.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#5062 Update telemetry.rst: boards formatting
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#5065 Update playbooks.rst: Revised landing page links.
  source/guides/playbooks.rst
Labels: 1: PM Review

#5068 updating links mmctl
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#5063 Update admin-onboarding-tasks.rst
  source/getting-started/admin-onboarding-tasks.rst
Labels: 3: Reviews Complete

#5034 Update Boards content/v2
  source/boards/accessing-boards.rst
  source/boards/sharing-boards.rst
  source/boards/templates.rst
  source/boards/working-with-boards.rst
  source/boards/working-with-views.rst
Labels: 3: Reviews Complete

#5069 Update conf.py
  source/conf.py
Labels: 3: Reviews Complete

#5076 Add CTA for Hacktoberfest
  source/templates/header.html
Labels: 3: Reviews Complete

#5078 Remove invisible paragraph icon from docs html
  source/conf.py
Labels: 3: Reviews Complete, preview-environment

#5084 301 redirect corrections
  source/conf.py
Labels: 3: Reviews Complete

#5081 Updated links in Document
  source/onboard/cloud-sso-saml.rst
Labels: 3: Reviews Complete, Contributor

#5085 Updated the links
  source/deploy/mobile-faq.rst
Labels: 3: Reviews Complete, Contributor

#5075 Re-added missing upgrade command example
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#5051 Cloud changelog - Sept 29
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#5090 Update boards.rst
  source/guides/boards.rst
Labels: 3: Reviews Complete
