Repository mattermost/docs, pull requests merged in 2021-04, with the labels that each got.

#4441 Update notes on supported versions
  source/administration/extended-support-release.rst
  source/administration/important-upgrade-notes.rst
  source/administration/release-lifecycle.rst
  source/administration/upgrade.rst
  source/administration/version-archive.rst
  source/images/ESR20213.png
Labels: 3: Reviews Complete

#4440 Update open-source-components.rst
  source/administration/open-source-components.rst
  source/administration/release-lifecycle.rst
Labels: 3: Reviews Complete

#4438 Staging Test - Added formatting to first note
  source/help/messaging/mentioning-teammates.rst
Labels: 3: Reviews Complete

#4452 Update announcement-banner.rst
  source/administration/announcement-banner.rst
Labels: 3: Reviews Complete

#4453 Update ldap-group-sync.rst
  source/deployment/ldap-group-sync.rst
Labels: 3: Reviews Complete

#4456 Update on-boarding.rst
  source/deployment/on-boarding.rst
Labels: 3: Reviews Complete

#4455 Update announcement-banner.rst
  source/administration/announcement-banner.rst
Labels: 3: Reviews Complete

#4418 MM-31674 Cloud app/product notices for ext dependecies
  source/cloud/cloud-administration/site-configuration.rst
Labels: 3: Reviews Complete

#4446 Added inAppSessionAuth to mobile AppConfig
  source/mobile/mobile-appconfig.rst
Labels: 3: Reviews Complete

#4436 Update mobile-changelog.md
  source/administration/mobile-changelog.md
Labels: 1: Dev Review

#4458 MM-29607 allow user to deactivate MFA even when disabled
  source/cloud/cloud-administration/authentication.rst
  source/cloud/cloud-administration/common-disable-mfa.rst
  source/deployment/auth.rst
Labels: 3: Reviews Complete

#4457 MM-22840 DMs show recent 20 with relative timestamp
  source/help/getting-started/organizing-conversations.rst
  source/images/recent-direct-group-messages.png
Labels: 3: Reviews Complete

#4447 Update license-and-subscription.rst
  source/overview/license-and-subscription.rst
Labels: 2: Editor Review

#4465 Fixed missing page in Admin guide
  source/deployment/sso-ldap.md
  source/guides/administrator.rst
Labels: 2: Editor Review

#4468 Update compliance-export.rst
  source/administration/compliance-export.rst
Labels: 3: Reviews Complete

#4467 Update compliance.rst
  source/administration/compliance.rst
Labels: 3: Reviews Complete

#4473 Update troubleshooting.rst
  source/install/troubleshooting.rst
Labels: 3: Reviews Complete

#4471 Update statistics.rst
  source/administration/statistics.rst
Labels: 3: Reviews Complete

#4451 Update desktop-app-deployment.rst
  source/deployment/desktop-app-deployment.rst
Labels: 3: Reviews Complete

#4462 Clarify that System & Team admins can delete posts
  source/administration/config-settings.rst
Labels: 1: PM Review

#4470 Update migrating.rst
  source/administration/migrating.rst
Labels: 3: Reviews Complete

#4469 Update deployment.md
  source/deployment/deployment.md
Labels: 3: Reviews Complete

#4459 MM-32943 add promote/demote user to local router
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4374 Modified postgres folder path for clarity
  source/install/install-ubuntu-1804-postgresql.rst
  source/install/install-ubuntu-2004-postgresql.rst
Labels: 3: Reviews Complete

#4431 #MM-18818 Updated docs for change in default support email
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4424 Update compliance language
  source/overview/security.rst
Labels: 3: Reviews Complete

#4448 Create incoming and outgoing webhooks for a different user
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4449 MM-31132 app/server: add pprof endpoint
  source/deployment/metrics.rst
  source/overview/product.rst
Labels: 3: Reviews Complete

#4466 Update guest-accounts.rst
  source/deployment/guest-accounts.rst
Labels: 3: Reviews Complete

#4344 MM-30008 - Implement mmctl import command
  source/administration/config-settings.rst
  source/administration/mmctl-cli-tool.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4479 Update devops-command-center.rst
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#4433 OneLogin Setup Instructions Need Update
  source/deployment/sso-saml-onelogin.rst
Labels: 3: Reviews Complete

#4476 Terminology updates - "left-hand sidebar" > "channel sidebar"
  source/administration/devops-command-center.rst
  source/developer/message-attachments.rst
  source/help/getting-started/organizing-conversations.rst
  source/help/messaging/keyboard-shortcuts.rst
  source/help/settings/account-settings.rst
  source/help/settings/team-settings.rst
Labels: 3: Reviews Complete

#4429 Clarify HTTPS proxy server
  source/install/outbound-proxy.rst
Labels: 3: Reviews Complete

#4398 5.34 Changelog
  source/administration/changelog.md
Labels: 1: PM Review, 3: Reviews Complete

#4461 MM-29726 Allow disabling link previews from certain domains
  source/administration/config-settings.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4472 Update net-promoter-score.rst
  source/integrations/net-promoter-score.rst
Labels: 3: Reviews Complete

#4460 MM-33818: Add replica lag metric
  source/administration/config-settings.rst
  source/administration/telemetry.rst
  source/deployment/metrics.rst
Labels: 3: Reviews Complete

#4414 Update devops-command-center.rst
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#4360 MM-32162 Review and Update mmctl product docs
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4485 Formatting fix for mmctl user demote
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4483 V5.34 documentation
  source/administration/changelog.md
  source/administration/extended-support-release.rst
  source/administration/important-upgrade-notes.rst
  source/administration/mmctl-cli-tool.rst
  source/administration/notices.rst
  source/administration/open-source-components.rst
  source/administration/release-lifecycle.rst
  source/administration/upgrade.rst
  source/administration/version-archive.rst
  source/conf.py
  source/deployment/metrics.rst
  source/help/getting-started/organizing-conversations.rst
  source/help/messaging/sending-messages.rst
  source/help/settings/theme-colors.rst
  source/images/ESR20213.png
  source/overview/product.rst
Labels: 3: Reviews Complete

#4486 Update version-archive.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#4491 v5.34.1 dot release changelog note
  source/administration/changelog.md
Labels: 1: Dev Review

#4412 v1.42 Mobile Changelog
  source/administration/mobile-changelog.md
Labels: 3: Reviews Complete

#4496 Add backport note to changelog
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4502 Update changelog.md
  source/administration/changelog.md
Labels: 1: Dev Review

#4505 v1.42.1 changelog
  source/administration/mobile-changelog.md
Labels: 1: Dev Review

#4481 MM-34771: Docs Corrections
  source/deployment/deployment.md
  source/images/network.png
  source/install/install-rhel-8-mattermost.rst
Labels: 3: Reviews Complete

#4480 Fix Configure SSL/TLS docs error
  source/install/config-ssl-http2-nginx.rst
Labels: 3: Reviews Complete

#4478 Roles docs do not list built-in system roles
  source/deployment/permissions-backend.rst
Labels: 3: Reviews Complete

#4499 DOPS-380 Add 404.html that redirects to index.html
  source/404.html
  source/conf.py
  source/templates/404.html
Labels: 3: Reviews Complete

#4507 Update install-ubuntu-2004-postgresql.rst
  source/install/install-ubuntu-2004-postgresql.rst
Labels: 3: Reviews Complete

#4495 MM-12290 inline image collapse
  source/cloud/cloud-administration/site-configuration.rst
  source/cloud/cloud-integrations/cloud-slash-commands.rst
  source/help/messaging/executing-commands.rst
  source/help/messaging/formatting-text.rst
  source/help/settings/account-settings.rst
Labels: 3: Reviews Complete

#4506 Update install-ubuntu-1804-postgresql.rst
  source/install/install-ubuntu-1804-postgresql.rst
Labels: 3: Reviews Complete

#4498 Organizing Your Sidebar - add mid-page links
  source/help/getting-started/organizing-your-sidebar.rst
Labels: 3: Reviews Complete

#4428 Update i18n.rst
  source/install/i18n.rst
Labels: 3: Reviews Complete

#4474 MM-28090 User settings api when ldap sync
  source/cloud/cloud-administration/common-sso-google.rst
  source/cloud/cloud-administration/common-sso-office365.rst
  source/cloud/cloud-administration/common-sso-openidconnect.rst
  source/cloud/cloud-administration/saml-technical.rst
  source/cloud/cloud-administration/sso-gitlab.rst
  source/cloud/cloud-administration/sso-ldap.md
  source/deployment/sso-gitlab.rst
  source/deployment/sso-ldap.md
  source/deployment/sso-saml-technical.rst
Labels: 3: Reviews Complete

#4475 Cloud Enterprise FAQs
  source/overview/mattermost-cloud-overview.rst
Labels: 3: Reviews Complete

#4490 Update conf.py
  source/conf.py
Labels: 3: Reviews Complete

#4509 Update cloud-billing.rst
  source/cloud/cloud-billing/cloud-billing.rst
  source/overview/mattermost-cloud-overview.rst
Labels: 3: Reviews Complete

#4512 Update index.rst
  source/index.rst
  source/templates/index.html
Labels: 3: Reviews Complete

#4514 Update security overview page following customer questions
  source/overview/security.rst
Labels: 3: Reviews Complete

#4497 [MM-33853] mention BatchSize in Compliance Monitoring section
  source/administration/config-settings.rst
Labels: 1: Dev Review

#4510 Files search interface
  source/administration/command-line-tools.rst
  source/administration/config-settings.rst
  source/deployment/bleve.rst
  source/deployment/elasticsearch.rst
  source/help/getting-started/searching.rst
  source/images/calendar2.png
  source/images/channel-files-icon.png
  source/images/file-search-filter.png
  source/images/jump-to-message.png
  source/images/review-all-search-results.png
  source/images/search-files.png
  source/images/search-messages.png
  source/images/search-modifiers.png
Labels: 3: Reviews Complete

#4519 v5.31.4 docs
  source/administration/changelog.md
  source/administration/extended-support-release.rst
Labels: 1: Dev Review

#4518 All Sections to SubSections
  source/deployment/admin-roles.rst
Labels: 3: Reviews Complete

#4526 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4520 saml idp with okta updates
  source/deployment/sso-saml-ldapsync.rst
  source/deployment/sso-saml-okta.rst
  source/images/okta_13_mattermost_attributes.PNG
  source/images/okta_13_mattermost_attributes.png
  source/images/okta_6_attribute_statements.PNG
  source/images/okta_6_attribute_statements.png
Labels: 3: Reviews Complete

#4524 301 redirects from staging to prod
  Pipfile
  Pipfile.lock
  source/conf.py
  source/help/messaging/mentioning-teammates.rst
Labels: 3: Reviews Complete

#4521 MM-34820 Improve spell check's option help text
  source/help/apps/desktop-guide.rst
  source/images/desktop.png
Labels: 3: Reviews Complete

#4529 Update mobile-changelog.md
  source/administration/important-upgrade-notes.rst
  source/administration/mobile-changelog.md
Labels: 1: Dev Review

#4528 Update cloud-changelog.md
  source/cloud/cloud-administration/cloud-changelog.md
Labels: 3: Reviews Complete

#4517 Telemetry Updates for file content search
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4531 rename network.PNG to network.png
  source/deployment/deployment.md
  source/getting-started/implementation_plan.rst
  source/images/network.png
  source/install/requirements.rst
Labels: 3: Reviews Complete

#4530 Removed missing screenshot code
  source/deployment/sso-saml-okta.rst
Labels: 3: Reviews Complete

#4534 refactor to use s3 to host the environment preview
  .github/workflows/gh-pages-cleanup.yml
  .github/workflows/preview-env.yml
  source/index.rst
Labels: 3: Reviews Complete

#4535 Update open-source-components.rst
  source/administration/open-source-components.rst
  source/administration/release-lifecycle.rst
Labels: 3: Reviews Complete
