Repository mattermost/docs, pull requests merged in 2021-06, with the labels that each got.

#4537 Add native apps support of fixed inline image size
  source/help/messaging/formatting-text.rst
Labels: 3: Reviews Complete

#4613 Cloud changelog June 2nd
  source/administration/changelog.md
  source/cloud/cloud-administration/cloud-changelog.md
Labels: 3: Reviews Complete

#4631 Changelog - dot releases
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: 1: Dev Review

#4630 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4552 MM-31513 How team admins can see team statistics
  source/administration/statistics.rst
  source/images/assign-people-to-system-role.png
  source/images/edit-viewer-system-admin-role.png
  source/images/restrict-role-access.png
Labels: 3: Reviews Complete

#4635 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4633 MM-34389: Reliable websockets first commit
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4639 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4644 Fixed typo
  source/administration/ediscovery.rst
Labels: 3: Reviews Complete

#4640 MM-22818 - Removing status from post profile picture
  source/help/settings/account-settings.rst
Labels: 3: Reviews Complete

#4634 MM-35767 Ignore readTimeout param from MySQL datasource
  source/administration/config-in-database.rst
  source/install/install-debian-mattermost.rst
  source/install/install-rhel-7-mattermost.rst
  source/install/install-rhel-8-mattermost.rst
  source/install/install-ubuntu-1604-mattermost.rst
  source/install/transport-encryption/config-database.rst
  source/install/trouble_mysql.rst
Labels: 3: Reviews Complete

#4585 Document content of log.settings.options.txt
  source/administration/config-settings.rst
  source/samples/advanced-logging-options-sample-json.zip
Labels: 3: Reviews Complete

#4632 Config setting correction
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4646 Fix Table Formatting
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4638 Update devops-command-center.rst
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#4641 Document File Content Search Details
  source/administration/command-line-tools.rst
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4625 v5.36 Changelog
  source/administration/changelog.md
Labels: 1: PM Review

#4653 V5.36 documentation
  source/administration/changelog.md
  source/administration/config-settings.rst
  source/administration/important-upgrade-notes.rst
  source/administration/open-source-components.rst
  source/administration/release-lifecycle.rst
  source/cloud/cloud-administration/site-configuration.rst
  source/conf.py
  source/help/settings/account-settings.rst
  source/overview/product.rst
Labels: 3: Reviews Complete

#4654 Update version-archive.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#4545 MM-31717: Remove HTTP clustering
  source/administration/config-settings.rst
  source/deployment/cluster.rst
Labels: 3: Reviews Complete

#4612 Add Focalboard to client matrix
  source/overview/faq.rst
Labels: 3: Reviews Complete

#4626 v1.44 Mobile changelog
  source/administration/mobile-changelog.md
Labels: 3: Reviews Complete

#4659 Update conf.py
  source/conf.py
Labels: 3: Reviews Complete

#4609 Update command-line-tools.rst
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#4664 Update integration-settings.md
  source/help/settings/integration-settings.md
Labels: 3: Reviews Complete

#4647 Document EnableFileSearch Config Setting
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4660 Update i18n.rst
  source/install/i18n.rst
Labels: 3: Reviews Complete

#4648 Network map missing ports
  source/overview/architecture.rst
Labels: 3: Reviews Complete

#4606 Mobile deployment docs overhaul
  source/deployment/client-side-data.rst
  source/guides/administrator.rst
  source/guides/install-deploy-upgrade-scale.rst
  source/mobile/build-custom-mobile-apps.rst
  source/mobile/consider-mobile-vpn-options.rst
  source/mobile/deploy-mobile-apps-using-emm-provider.rst
  source/mobile/mobile-appconfig.rst
  source/mobile/mobile-faq.rst
  source/mobile/mobile-hpns.rst
  source/mobile/mobile-overview.rst
  source/mobile/mobile-troubleshoot.rst
  source/mobile/use-prebuilt-mobile-apps.rst
Labels: 3: Reviews Complete

#4402 v4.7.0 Desktop App changelog
  source/help/apps/desktop-changelog.rst
Labels: 3: Reviews Complete

#4671 Desktop download links
  source/install/desktop-msi-gpo.rst
  source/install/desktop.rst
Labels: 1: PM Review, 3: Reviews Complete

#4568 MM-32809 Remove Toggle Dark Mode for Windows enable on Linux
  source/help/apps/desktop-guide.rst
Labels: 3: Reviews Complete

#4569 MM-22013 - Allow users to specify default download locations
  source/help/apps/desktop-guide.rst
Labels: 3: Reviews Complete

#4658 Improve documentation for CanonicalAlgorithm
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4663 File Content Extraction clarifications
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#4680 Mobile v1.44.1 Changelog
  source/administration/mobile-changelog.md
Labels: 3: Reviews Complete

#4686 Update changelog.md
  source/administration/changelog.md
Labels: 2: Editor Review

#4689 Formatting fixes
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4679 clean up upgrade documentation and files created on upgrade
  source/administration/upgrade.rst
Labels: 3: Reviews Complete

#4688 Add bulk export options
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#4668 Cloud Changelog - June 30th
  source/cloud/cloud-administration/cloud-changelog.md
  source/help/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete
