Repository mattermost/docs, pull requests merged in 2021-03, with the labels that each got.

#4355 Update important-upgrade-notes.rst
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4361 Removed WIP text
  source/cloud/cloud-administration/sso-gitlab.rst
Labels: 3: Reviews Complete

#4345 Sign In Screenshots are outdated
  source/help/getting-started/signing-in.rst
  source/images/sign-in-gitlab.png
  source/images/sign-in-google-apps.png
  source/images/sign-in-office365.png
  source/images/sign-in_with_email.png
  source/images/sign-in_with_ldap.png
  source/images/sign-in_with_saml.png
  source/images/team-sidebar.png
Labels: 3: Reviews Complete

#4348 GDPR FAQ Update
  source/overview/compliance.rst
Labels: 3: Reviews Complete

#4290 MM-27377 api4/team_local: add updateChannelPrivacy and restoreTeam to…
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4343 Adding links to install guides from main overview page
  source/overview/index.rst
Labels: 3: Reviews Complete

#4354 MM-32047 - Added AppCustomURLSchemes settings to telemetry
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4327 MM-32232: Clarifications to Allow Untrusted Internal Connections config
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4338 MM-32423 - Elastic Search indexing progress bar gets stuck
  source/deployment/elasticsearch.rst
Labels: 3: Reviews Complete

#4326 MM-32230: Clarify mmctl vs cli usage in HA
  source/administration/command-line-tools.rst
  source/administration/mmctl-cli-tool.rst
  source/deployment/cluster.rst
Labels: 3: Reviews Complete

#4371 Fix broken image link
  source/help/getting-started/messaging-basics.rst
Labels: 3: Reviews Complete

#4328 MM-27254 Include the types of supported groups
  source/cloud/cloud-user-management/cloud-groups.rst
  source/deployment/ldap-group-sync.rst
Labels: 3: Reviews Complete

#4350 add mmctl user verify
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4308 Update oauth-2-0-applications.rst
  source/developer/oauth-2-0-applications.rst
Labels: 3: Reviews Complete

#4370 UG References to "sign-in" are inconsistent
  source/help/getting-started/signing-in.rst
  source/help/settings/account-settings.rst
  source/help/settings/team-settings.rst
Labels: 3: Reviews Complete

#4356 MM-33019 Job metrics & dynamic Grafana annotations
  source/deployment/metrics.rst
  source/images/mattermost_active_jobs_chart.png
  source/images/mattermost_dynamic_range_annotation.png
  source/images/mattermost_system_server_start_time.png
Labels: 3: Reviews Complete

#4230 MM-31518 Cloud Integrations updates
  source/cloud/cloud-administration/data-retention-policy.rst
  source/cloud/cloud-administration/sso-google.md
  source/cloud/cloud-integrations/cloud-bot-accounts.rst
  source/cloud/cloud-integrations/integrations-faq.md
  source/cloud/cloud-mobile/cloud-app-config.rst
  source/cloud/cloud-user-management/cloud-groups.rst
Labels: 3: Reviews Complete

#4231 MM-31518 Update Server References to Workspace, PII
  source/cloud/cloud-administration/cloud-compliance.rst
  source/cloud/cloud-administration/custom-terms-of-service.rst
  source/cloud/cloud-integrations/cloud-personal-access-tokens.rst
  source/cloud/cloud-integrations/cloud-slash-commands.rst
  source/cloud/cloud-user-management/user-satisfaction-surveys.rst
Labels: 3: Reviews Complete

#4322 Instructions to install mysql yum repo and disable mysql module
  source/install/install-rhel-8-mysql.rst
Labels: 3: Reviews Complete

#4365 MM- 18893: Change text User to Member - Self-Managed
  source/deployment/guest-accounts.rst
  source/images/Guest_Invite_Screen.png
Labels: 3: Reviews Complete

#4376 Cloud: Removed Server Restart step
  source/cloud/cloud-administration/sso-gitlab.rst
  source/cloud/cloud-administration/sso-office.md
Labels: 3: Reviews Complete

#4378 Quick improvment for config in db
  source/administration/config-in-database.rst
Labels: 3: Reviews Complete

#4323 [MM-33009] Set correct HTTP version for websocket upgrade on NGINX
  source/deployment/cluster.rst
  source/install/config-proxy-nginx.rst
  source/install/config-ssl-http2-nginx.rst
Labels: 3: Reviews Complete

#4357 Cloud changelog - March 10th
  source/cloud/cloud-administration/cloud-changelog.md
Labels: 3: Reviews Complete

#4252 Update troubleshooting.rst
  source/install/troubleshooting.rst
Labels: 3: Reviews Complete

#4383 Docs typo fix
  source/install/install-kubernetes-cluster.rst
Labels: 3: Reviews Complete

#4389 Clarified the Telemetry setting in 5.12+ versions
  source/administration/telemetry.rst
Labels: 3: Reviews Complete

#4391 Document commander automation in Incident Collaboration
  source/administration/devops-command-center.rst
Labels: 3: Reviews Complete

#4381 Adding note about restarting Mattermost
  source/deployment/elasticsearch.rst
Labels: 3: Reviews Complete

#4392 Update changelog.md
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4379 MM-32654 - OpenID Connect Self-Managed
  source/deployment/sso-gitlab.rst
  source/deployment/sso-google.md
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#4353 v1.41 Mobile Changelog
  source/administration/mobile-changelog.md
Labels: 3: Reviews Complete

#4340 v5.33 changelog
  source/administration/changelog.md
Labels: 3: Reviews Complete

#4368 MM-31993 Add flag to disable gossip compression Self-Managed
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4369 MM-31148 - Review formatting shortcut keys popup - Self-Managed
  source/help/messaging/keyboard-shortcuts.rst
Labels: 3: Reviews Complete

#4396 Create administrator.rst
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#4364 MM-33103 Generate Support Packet Self-Managed
  source/administration/generating-support-packet.rst
  source/cloud/cloud-administration/common-support-packet.rst
  source/cloud/cloud-administration/downloading-support-packet.rst
  source/guides/administrator.rst
Labels: 3: Reviews Complete

#4324 Update config.yml
  .circleci/config.yml
Labels: 3: Reviews Complete

#4387 MM-33629 - HPNS docs are outdated
  source/images/mobile_hpns.png
  source/mobile/mobile-hpns.rst
Labels: 3: Reviews Complete

#4399 Update conf.py
  source/conf.py
Labels: 3: Reviews Complete

#4400 Update scaling.rst
  source/deployment/scaling.rst
Labels: 3: Reviews Complete

#4401 Update oauth-2-0-applications.rst
  source/developer/oauth-2-0-applications.rst
Labels: 3: Reviews Complete

#4405 v5.33.1 docs
  source/administration/changelog.md
  source/administration/version-archive.rst
Labels: 1: Dev Review

#4388 Remove documentation for XMLSec1 installation
  source/administration/config-settings.rst
  source/deployment/sso-saml-adfs-msws2016.rst
  source/deployment/sso-saml-adfs.rst
  source/deployment/sso-saml-before-you-begin.rst
  source/deployment/sso-saml-okta.rst
  source/deployment/sso-saml-onelogin.rst
Labels: 3: Reviews Complete

#4408 Update webhooks-incoming.rst
  source/developer/webhooks-incoming.rst
Labels: 3: Reviews Complete

#4407 Backport notes to changelog
  source/administration/changelog.md
Labels: 1: Dev Review

#4373 Update Pipfile.lock
  Pipfile.lock
  source/conf.py
  source/deployment/sso-ldap.md
  source/templates/layout-notoc.html
  source/templates/layout.html
Labels: 1: Dev Review, 1: PM Review, 2: Editor Review, Staging

#4366 source/administration/mmctl: update local mode doc to include socketpath
  source/administration/mmctl-cli-tool.rst
Labels: 1: Dev Review, 2: Editor Review

#4386 MM-31250 Implement export command
  source/administration/config-settings.rst
  source/administration/mmctl-cli-tool.rst
  source/administration/telemetry.rst
Labels: 1: PM Review, 3: Reviews Complete

#4411 Update mmctl-cli-tool.rst
  source/administration/mmctl-cli-tool.rst
Labels: 3: Reviews Complete

#4410 Added plus signs to list docs
  source/help/messaging/formatting-text.rst
Labels: 3: Reviews Complete

#4419 Update options to reflect code changes
  source/help/apps/desktop-guide.rst
Labels: 2: Editor Review

#4409 Sphinx upgrade to prod
  Pipfile.lock
  source/conf.py
  source/deployment/sso-ldap.md
  source/templates/layout-notoc.html
  source/templates/layout.html
Labels: 3: Reviews Complete

#4404 update Korean translation in i18n.rst
  source/install/i18n.rst
Labels: 2: Editor Review

#4200 Update the certbot documentation to better utilize the updated certbot versions and information
  source/install/config-proxy-nginx.rst
  source/install/config-ssl-http2-nginx.rst
Labels: 3: Reviews Complete

#4420 Style Guide Consistency Updates
  source/cloud/cloud-integrations/cloud-personal-access-tokens.rst
  source/cloud/cloud-integrations/cloud-slash-commands.rst
Labels: 3: Reviews Complete

#4228 MM-31518 Update Server References to Workspace
  source/cloud/cloud-administration/site-configuration.rst
  source/cloud/cloud-administration/sso-ldap.md
  source/cloud/cloud-administration/sso-saml.rst
  source/cloud/cloud-billing/cloud-billing.rst
  source/cloud/cloud-guest-accounts.rst
  source/cloud/cloud-mobile/mobile-apps-faq.rst
  source/cloud/cloud-reporting.rst
  source/cloud/cloud-user-management/advanced-permissions.rst
  source/cloud/cloud-user-management/cloud-team-and-channel.rst
Labels: 3: Reviews Complete

#4426 Broken link fix from PR 4420
  source/cloud/cloud-integrations/cloud-slash-commands.rst
Labels: 3: Reviews Complete

#4423 Updates to self-managed docs for PR4420
  source/developer/personal-access-tokens.rst
  source/developer/slash-commands.rst
Labels: 3: Reviews Complete

#4432 5.31.2 docs
  source/administration/changelog.md
  source/administration/extended-support-release.rst
  source/administration/version-archive.rst
Labels: 1: Dev Review

#4417 MM-31674 app/product_notices implement notices for ext dependencies
  source/administration/notices.rst
Labels: 3: Reviews Complete

#4416 MM-30531: importing slack theme in new format
  source/help/settings/theme-colors.rst
Labels: 3: Reviews Complete

#4415 MM 25430 - Show online status in channel switcher
  source/help/getting-started/organizing-conversations.rst
Labels: 3: Reviews Complete

#4425 Overhaul on Compliance language
  source/overview/compliance.rst
Labels: 3: Reviews Complete

#4430 Update telemetry.rst
  source/administration/telemetry.rst
Labels: 3: Reviews Complete
