Repository mattermost/docs, pull requests merged in 2021-11, with the labels that each got.

#5228 Grammatical corrections
  source/onboard/cloud-groups.rst
Labels: Hacktoberfest, 2: Editor Review, Hacktoberfest-accepted, Contributor

#5230 Update version-archive.rst
  source/install/self-managed-changelog.md
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5238 Update open source components, release lifecycle, and ESR graphic
  source/images/esr-graphic.png
  source/upgrade/extended-support-release.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 3: Reviews Complete

#5202 Clarified file format support OOTB
  source/configure/configuration-settings.rst
  source/messaging/searching-in-mattermost.rst
Labels: 3: Reviews Complete

#5232 Split FAQ into sections
  source/about/faq-business.rst
  source/about/faq-community.rst
  source/about/faq-design-decisions.rst
  source/about/faq-enterprise.rst
  source/about/faq-general.rst
  source/about/faq-high-trust.rst
  source/about/faq-illicit-use.rst
  source/about/faq-integrations.rst
  source/about/faq-mattermost-source-available-license.rst
  source/about/faq-notifications.rst
  source/about/faq-product.rst
  source/about/faq-use-cases.rst
  source/about/faq-video-audio-screensharing.rst
  source/about/frequently-asked-questions.rst
Labels: 3: Reviews Complete

#5181 Added v6.0 workaround for upgrade error
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#5247 Fixed missing badge image
  source/messaging/mentioning-teammates.rst
Labels: 3: Reviews Complete

#5250 Channel category updates
  source/images/channel-heading-categories.png
  source/messaging/channel-settings.rst
  source/messaging/organizing-your-sidebar.rst
Labels: 3: Reviews Complete

#5222 Page clarifications based on visitor feedback
  source/upgrade/upgrading-to-v60.rst
Labels: 3: Reviews Complete

#5245 Added config setting JobSettings.CleanupJobsThresholdDays
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5248 Cross team mentions, saves, and searches return all teams
  source/messaging/mentioning-teammates.rst
  source/messaging/saving-messages.rst
  source/messaging/searching-in-mattermost.rst
Labels: 2: Editor Review

#5246 bleve-updates
  source/deploy/bleve-search.rst
Labels: 3: Reviews Complete

#5213 Terminology change from switch to navigate
  source/about/frequently-asked-questions.rst
  source/boards/getting-started.rst
  source/conf.py
  source/configure/cloud-site-configuration.rst
  source/configure/configuration-settings.rst
  source/guides/channels.rst
  source/install/desktop-app-install.rst
  source/messaging/about-teams-channels-messages.rst
  source/messaging/common-navigating-mattermost-products.rst
  source/messaging/creating-teams.rst
  source/messaging/customizing-theme-colors.rst
  source/messaging/keyboard-shortcuts.rst
  source/messaging/managing-channels.rst
  source/messaging/managing-members.rst
  source/messaging/navigating-between-teams.rst
  source/messaging/organizing-conversations.rst
  source/messaging/searching-in-mattermost.rst
  source/messaging/setting-your-status-availability.rst
  source/onboard/guest-accounts.rst
Labels: 3: Reviews Complete

#5254 Clarified config setting unit of measure
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5256 Show confirmation for @here
  source/configure/configuration-settings.rst
  source/messaging/mentioning-teammates.rst
Labels: 3: Reviews Complete

#5239 Updated Configuration Settings
  source/configure/configuration-settings.rst
Labels: 1: PM Review, 2: Editor Review

#5243 Added one-click reaction documentation
  source/images/attachment-icon.png
  source/images/gear-icon.png
  source/images/recent-emojis.png
  source/images/reply-arrow.png
  source/images/save-icon.png
  source/images/smile-icon.png
  source/messaging/channels-basics.rst
  source/messaging/managing-account-settings.rst
  source/messaging/using-emoji.rst
Labels: 3: Reviews Complete

#5237 Important upgrade notes - v6.1
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#5258 Update software-hardware-requirements.rst
  source/install/software-hardware-requirements.rst
Labels: 3: Reviews Complete

#5252 Updated Saved Messages
  source/messaging/saving-messages.rst
Labels: 3: Reviews Complete

#5257 Added Inline latex rendering documentation
  source/conf.py
  source/configure/cloud-site-configuration.rst
  source/configure/configuration-settings.rst
  source/images/latex-codeblock.png
  source/images/latex-inline.png
  source/manage/telemetry.rst
  source/messaging/formatting-text.rst
Labels: 3: Reviews Complete

#5223 Consolidated tabbed content
  source/messaging/setting-your-status-availability.rst
Labels: 3: Reviews Complete

#5227 Updates the AWS Beanstalk instructions
  source/install/install-ios-app.rst
  source/install/setting-up-aws-elastic-beanstalk-docker.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5259 Update playbooks for 6.1
  source/guides/playbooks.rst
  source/playbooks/getting-started.rst
  source/playbooks/notifications-and-updates.rst
Labels: 3: Reviews Complete

#5261 Update cloud-changelog.md
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#5234 v6.1 Changelog
  source/install/self-managed-changelog.md
Labels: 1: PM Review, 3: Reviews Complete

#5264 linkcheck_rate_limit_timeout must be a decimal value
  source/conf.py
Labels: 3: Reviews Complete

#5262 v5.0.2 Desktop app docs
  source/install/desktop-app-changelog.rst
  source/install/desktop-app-install.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#5263 Patch release docs
  source/install/self-managed-changelog.md
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5242 V6.1 documentation
  source/conf.py
  source/configure/cloud-site-configuration.rst
  source/configure/configuration-settings.rst
  source/deploy/bleve-search.rst
  source/guides/playbooks.rst
  source/images/attachment-icon.png
  source/images/channel-heading-categories.png
  source/images/esr-graphic.png
  source/images/gear-icon.png
  source/images/latex-codeblock.png
  source/images/latex-inline.png
  source/images/recent-emojis.png
  source/images/reply-arrow.png
  source/images/save-icon.png
  source/images/set-your-availability.png
  source/images/smile-icon.png
  source/install/self-managed-changelog.md
  source/install/software-hardware-requirements.rst
  source/manage/telemetry.rst
  source/messaging/channel-settings.rst
  source/messaging/channels-basics.rst
  source/messaging/formatting-text.rst
  source/messaging/managing-account-settings.rst
  source/messaging/mentioning-teammates.rst
  source/messaging/organizing-your-sidebar.rst
  source/messaging/saving-messages.rst
  source/messaging/searching-in-mattermost.rst
  source/messaging/setting-your-status-availability.rst
  source/messaging/using-emoji.rst
  source/playbooks/getting-started.rst
  source/playbooks/notifications-and-updates.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 3: Reviews Complete

#5269 Update nav and footer
  source/_static/images/nav/Integrate.svg
  source/_static/mytheme.css
  source/templates/header.html
  source/templates/index.html
Labels: 3: Reviews Complete, preview-environment

#5273 Moved log rotation note
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5272 Removed legacy link no longer adding value
  source/messaging/signing-in.rst
Labels: 3: Reviews Complete

#5270 Update configuration-settings.rst
  source/configure/configuration-settings.rst
  source/messaging/team-settings.rst
Labels: 3: Reviews Complete

#5266 Documented channel info character limitations
  source/images/channel-header.png
  source/images/channel-purpose.png
  source/images/globe-icon.png
  source/images/lock-icon.png
  source/messaging/about-teams-channels-messages.rst
  source/messaging/channel-settings.rst
  source/messaging/creating-teams.rst
Labels: 3: Reviews Complete

#5268 Cloud changelog - Nov 24
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#5275 Clarified scope of System Roles
  source/onboard/system-admin-roles.rst
Labels: 3: Reviews Complete

#5278 Navigation Update
  source/_static/mytheme.css
  source/templates/header.html
  source/templates/index.html
Labels: 3: Reviews Complete, preview-environment
