Repository mattermost/docs, pull requests merged in 2021-07, with the labels that each got.

#4695 Update cloud-changelog.md
  source/cloud/cloud-administration/cloud-changelog.md
Labels: 3: Reviews Complete

#4624 Clarify Wording in Security Page
  source/overview/security.rst
Labels: 3: Reviews Complete

#4706 5.37 upgrade notes
  source/administration/extended-support-release.rst
  source/administration/important-upgrade-notes.rst
  source/administration/open-source-components.rst
  source/administration/release-lifecycle.rst
  source/administration/upgrade.rst
  source/administration/version-archive.rst
Labels: 3: Reviews Complete

#4714 Update architecture.rst
  source/overview/architecture.rst
Labels: 3: Reviews Complete

#4685 Added mini-toc to changelogs
  source/administration/changelog.md
  source/administration/mobile-changelog.md
  source/cloud/cloud-administration/cloud-changelog.md
  source/help/apps/desktop-changelog.rst
Labels: 2: Editor Review

#4690 Docs issues on Production
  source/administration/compliance-export.rst
  source/administration/custom-terms-of-service.rst
  source/administration/image-proxy.rst
  source/administration/legacy-upgrade.md
  source/administration/upgrade.rst
  source/cloud/cloud-integrations.rst
  source/deployment/advanced-permissions.rst
  source/deployment/bulk-loading-data.rst
  source/deployment/certificate-based-authentication.rst
  source/deployment/elasticsearch.rst
  source/deployment/ssl-client-certificate.rst
  source/developer/webhooks-outgoing.rst
  source/help/messaging/executing-commands.rst
  source/install/ee-install.rst
Labels: 3: Reviews Complete

#4682 Add sendmail SMTP configuration option
  source/install/smtp-email-setup.rst
Labels: 3: Reviews Complete

#4715 Delete DisablePostMetadata config setting
  source/administration/config-settings.rst
Labels: 3: Reviews Complete

#4681 Add note about new mmctl CLI
  source/administration/command-line-tools.rst
Labels: 3: Reviews Complete

#4699 Adding English Australian to translated languages
  source/cloud/cloud-administration/site-configuration.rst
  source/help/settings/account-settings.rst
  source/overview/product.rst
Labels: 3: Reviews Complete

#4700 MM-34475 Emoji 13.0 with new library
  source/guides/messaging.rst
  source/help/messaging/emoji.rst
  source/images/add_custom_emoji.png
  source/images/emoji-skin-tone.png
  source/images/selectemoji.png
Labels: 3: Reviews Complete

#4701 Allow uploading .jpeg files on Linux
  source/help/settings/account-settings.rst
Labels: 3: Reviews Complete

#4704 Clarify Add Member to Channel limit
  source/help/getting-started/organizing-conversations.rst
Labels: 3: Reviews Complete

#4697 Custom status expiry
  source/help/getting-started/setting-your-status-availability.rst
  source/images/custom-status-expiry.png
Labels: 3: Reviews Complete

#4698 MM-24335 Show recently viewed channels when channel switcher opens
  source/help/getting-started/organizing-conversations.rst
  source/images/switch-channels.png
Labels: 3: Reviews Complete

#4670 Added shared channels docs draft for System Admins
  source/administration/config-settings.rst
  source/administration/telemetry.rst
  source/guides/setup-onboard-manage-comply.rst
  source/set-up/shared-channels.rst
Labels: 3: Reviews Complete

#4724 Update 5.35 upgrade notes
  source/administration/changelog.md
  source/administration/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#4727 Embedded CRT YouTube video on the page
  source/help/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete

#4728 Adding back CRT page
  source/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete

#4729 Adding back CRT page to LHS
  source/guides/messaging.rst
Labels: 3: Reviews Complete

#4730 Fixing relative image links
  source/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete

#4731 Added 301 redirects for CRT and CRT > Known Issues
  source/conf.py
Labels: 3: Reviews Complete

#4702 v5.37 Changelog
  source/install/self-managed-changelog.md
Labels: 1: PM Review, 3: Reviews Complete

#4726 Adding docs banner
  source/myscript.js
  source/templates/header.html
  source/theme.css
Labels: 3: Reviews Complete

#4703 Mobile 1.45 Changelog
  source/deploy/mobile-app-changelog.md
Labels: 1: Dev Review, 3: Reviews Complete

#4708 Cloud Changelog July 14th
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#4738 Update conf.py
  source/conf.py
Labels: 3: Reviews Complete

#4736 Docs notification banner
  source/myscript.js
  source/templates/header.html
  source/theme.css
Labels: 3: Reviews Complete

#4734 Update extended-support-release.rst
  source/images/ESR20214.png
  source/upgrade/extended-support-release.rst
Labels: 3: Reviews Complete

#4740 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#4743 Fixing a few broken docs
  source/comply/compliance-export.rst
  source/configure/smtp-email.rst
  source/install/self-managed-changelog.md
  source/messaging/managing-channels.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#4696 Updating thermometer feature
  source/myscript.js
  source/theme.css
Labels: 3: Reviews Complete

#4745 Update banner with CTA
  source/templates/header.html
Labels: 3: Reviews Complete

#4747 Update upgrading-mattermost-server.rst
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#4755 v1.45.1 changelog
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#4766 Update self-managed-changelog.md
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#4776 Create install-ubuntu-1804-mattermost.rst
  source/install/install-ubuntu-1804-mattermost.rst
  source/install/installing-ubuntu-1804-LTS.rst
Labels: 3: Reviews Complete

#4778 Create install-ubuntu-2004-mattermost.rst
  source/install/install-ubuntu-2004-mattermost.rst
  source/install/installing-ubuntu-2004-LTS.rst
Labels: 3: Reviews Complete

#4780 Add Shared Channels topic to LHS
  source/configure/configuration-settings.rst
  source/guides/setup-onboard-manage-comply.rst
  source/onboard/shared-channels.rst
Labels: 3: Reviews Complete

#4775 Added 301 redirect for legacy cloud page to latest documentation
  source/conf.py
Labels: 2: Editor Review

#4774 Correct CollapsedThreads listed option
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#4782 Make Banner text more generic
  source/templates/header.html
Labels: 3: Reviews Complete

#4783 Update CRT Known Issues
  source/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete

#4781 Formatting fix for Shared Channels config setting
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#4784 Update use-kubernetes-mattermost.rst
  source/install/use-kubernetes-mattermost.rst
Labels: 3: Reviews Complete, Docathon 2021

#4749 CRT: Add subheading for clarity
  source/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete

#4779 Update install-ubuntu-2004-mattermost.rst
  source/install/config-mattermost-server.rst
  source/install/install-ubuntu-2004-mattermost.rst
Labels: 3: Reviews Complete

#4785 Add cloud pages to LHS
  source/guides/install-deploy-upgrade-scale.rst
  source/guides/setup-onboard-manage-comply.rst
  source/install/trouble_mysql.rst
  source/install/troubleshooting.rst
  source/manage/cloud-team-and-channel.rst
  source/manage/cloud-user-satisfaction-surveys.rst
  source/onboard/cloud-groups.rst
  source/onboard/cloud-guest-accounts.rst
Labels: 3: Reviews Complete

#4773 Experimental Sidebar config setting correction
  source/configure/configuration-settings.rst
Labels: 2: Editor Review

#4786 Fixed broken links
  source/messaging/organizing-conversations.rst
Labels: 3: Reviews Complete

#4748 Update extended-support-release.rst
  source/upgrade/extended-support-release.rst
Labels: 3: Reviews Complete, Docathon 2021

#4792 Update links to the exact section and update broken links aswell
  source/about/security.rst
Labels: 3: Reviews Complete, Docathon 2021

#4791 Update formatting-text.rst
  source/messaging/formatting-text.rst
Labels: 3: Reviews Complete

#4770 Update shared-channels.rst
  source/onboard/shared-channels.rst
Labels: 3: Reviews Complete, Docathon 2021

#4757 Update deploy-mobile-apps-using-emm-provider.rst
  source/deploy/deploy-mobile-apps-using-emm-provider.rst
Labels: Docathon 2021

#4789 Update mis-worded RHEL7/8 install instructions - Issue4013
  source/install/install-rhel-7-mattermost.rst
  source/install/install-rhel-8-mattermost.rst
Labels: 2: Editor Review, Area/Content, Area/Documentation Improvements, Docathon 2021

#4796 Update enterprise-roll-out-checklist.rst
  source/getting-started/enterprise-roll-out-checklist.rst
Labels: 3: Reviews Complete, Area/Content, Docathon 2021

#4795 Update links and link to the exact section
  source/about/product.rst
Labels: 3: Reviews Complete, Area/Content, Docathon 2021

#4768 Update frequently-asked-questions.rst
  source/about/frequently-asked-questions.rst
Labels: 3: Reviews Complete, Docathon 2021

#4798 Updated and fixed the broken links
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete, Docathon 2021

#4797 Updated Links
  source/upgrade/release-lifecycle.rst
Labels: 2: Editor Review, Area/Content, Docathon 2021

#4764 Make format of action ID clear
  source/developer/interactive-messages.rst
Labels: 3: Reviews Complete, Docathon 2021

#4752 Update config-mattermost-server.rst
  source/install/config-mattermost-server.rst
Labels: Docathon 2021

#4751 Update ad-ldap-groups-synchronization.rst
  source/onboard/ad-ldap-groups-synchronization.rst
Labels: Docathon 2021

#4801 Fixed the commas
  source/manage/cloud-billing.rst
Labels: 3: Reviews Complete, Area/Content, Docathon 2021

#4725 Bleve index directory preservation on upgrade
  source/configure/configuration-settings.rst
  source/deploy/bleve-search.rst
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#4804 Update links and link to the exact section
  source/install/install-common-intro.rst
Labels: 3: Reviews Complete, Area/Content, Docathon 2021

#4800 Updated and fixed links
  source/developer/webhooks-incoming.rst
Labels: 3: Reviews Complete, Area/Content, Docathon 2021

#4802 Ewwollesen issue3857
  source/configure/configuation-in-mattermost-database.rst
  source/configure/using-outbound-proxy.rst
  source/install/install-debian-mattermost.rst
  source/install/install-rhel-7-mattermost.rst
  source/install/install-rhel-8-mattermost.rst
  source/install/install-ubuntu-1804-mattermost.rst
  source/install/install-ubuntu-2004-mattermost.rst
Labels: 3: Reviews Complete, Area/Content, Docathon 2021, preview-environment

#4807 Add to FAQ SAML config issue on Mattermost Operator installations
  source/install/faq_kubernetes.rst
Labels: 3: Reviews Complete, Docathon 2021, preview-environment

#4818 301 Redirect correction for Upgrade
  source/conf.py
Labels: 2: Editor Review

#4803 Updated links
  source/getting-started/light-install.rst
Labels: 3: Reviews Complete, Docathon 2021

#4758 Update elasticsearch.rst
  source/scale/elasticsearch.rst
Labels: 3: Reviews Complete, Docathon 2021

#4819 Update certifications-and-compliance.rst
  source/about/certifications-and-compliance.rst
Labels: 3: Reviews Complete
