Repository mattermost/docs, pull requests merged in 2022-12, with the labels that each got.

#6083 Favorite channels included in export
  source/manage/bulk-export-data.rst
  source/manage/bulk-export-tool.rst
Labels: 3: Reviews Complete

#6078 Added mov as supported media format
  source/channels/share-files-in-messages.rst
Labels: 1: Dev Review

#6064 Use go install instead of go get
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#6087 Admins can re-add users to default teams/channels
  source/conf.py
  source/images/Group_Configuration.png
  source/images/Group_Members.png
  source/images/Group_filter.png
  source/images/Groups_listing.png
  source/onboard/ad-ldap-groups-synchronization.rst
Labels: 2: Editor Review

#6098 Add missing "role" in examples
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#6103 Update work-with-boards.rst
  source/boards/work-with-boards.rst
Labels: 1: PM Review

#6093 Added related link
  source/install/trouble_mysql.rst
Labels: 3: Reviews Complete

#6094 Clarified group membership management options
  source/channels/create-channels.rst
Labels: 3: Reviews Complete

#6067 Desktop app v5.2.2 docs
  source/install/desktop-app-changelog.rst
  source/install/desktop-app-install.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#6096 Added new page on marking channels as unread
  source/channels/mark-channels-unread.rst
  source/channels/mark-messages-unread.rst
  source/guides/channels.rst
  source/images/channel-more.png
  source/install/desktop-custom-dictionaries.rst
Labels: 3: Reviews Complete

#6085 Added admin first steps
  source/install/common-local-deploy-docker.rst
Labels: 3: Reviews Complete

#6105 Cloud configuration defaults
  source/configure/authentication-configuration-settings.rst
  source/configure/compliance-configuration-settings.rst
  source/configure/configuration-settings.rst
  source/configure/database-configuration-settings.rst
  source/configure/environment-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/high-availability-configuration-settings.rst
  source/configure/integrations-configuration-settings.rst
  source/configure/plugins-configuration-settings.rst
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete

#6097 Documented Channel Info functionality
  source/channels/favorite-channels.rst
  source/channels/keyboard-shortcuts-for-channels.rst
  source/channels/manage-channel-members.rst
  source/channels/search-for-messages.rst
  source/channels/set-channel-preferences.rst
  source/channels/share-links.rst
  source/images/file-image-outline-large_E905.svg
  source/images/file-text-outline_F09EE.svg
  source/images/star-outline_F04D2.svg
Labels: 3: Reviews Complete

#6116 [MM-48659] Improve network requirements table for Calls
  source/configure/calls-deployment.rst
Labels: 3: Reviews Complete

#6102 [GH-5951] Updates Authentication > SAML 2.0 Settings to New Format
  source/configure/authentication-configuration-settings.rst
Labels: 3: Reviews Complete, Contributor

#6110 Removed SCIM roadmap language
  source/onboard/ad-ldap.rst
  source/onboard/sso-saml-faq.rst
  source/onboard/sso-saml.rst
Labels: 3: Reviews Complete

#6106 Boards: drag and drop
  source/boards/navigate-boards.rst
Labels: 1: PM Review

#6123 Mark channel as unread keyboard shortcut
  source/channels/keyboard-shortcuts-for-channels.rst
Labels: 2: Editor Review

#6095 [MM-47780] Update shortcut to start/join calls
  source/channels/keyboard-shortcuts-for-channels.rst
Labels: 3: Reviews Complete

#6092 Elasticsearch documentation updates
  source/configure/elasticsearch-configuration-settings.rst
  source/scale/elasticsearch.rst
Labels: 3: Reviews Complete

#6124 Added DB install links to Generic Linux deploy docs
  source/install/common-prod-deploy-tar.rst
Labels: 3: Reviews Complete

#6126 [GH-5951] Updates Authentication > OAuth 2.0 Google Settings
  source/configure/authentication-configuration-settings.rst
Labels: 3: Reviews Complete, preview-environment, Contributor

#6125 Docs listening: Added FAQ about LDAP groups and OpenID
  source/onboard/ad-ldap-groups-synchronization.rst
  source/onboard/common-sso-openidconnect.rst
  source/onboard/sso-gitlab.rst
  source/onboard/sso-google.rst
  source/onboard/sso-office.rst
Labels: 3: Reviews Complete

#6111 [GH-5951] Updates Authentication > OAuth 2.0 GitLab Settings
  source/conf.py
  source/configure/authentication-configuration-settings.rst
Labels: 3: Reviews Complete, preview-environment, Contributor

#6080 Added new docs contribution page
  source/conf.py
  source/guides/contribute-to-documentation.rst
  source/images/edit-on-github.png
  source/index.rst
Labels: 3: Reviews Complete, 2. SME Review

#6113 Message priority & acknowledgements
  source/channels/message-priority.rst
  source/channels/send-messages.rst
  source/configure/site-configuration-settings.rst
  source/guides/channels.rst
  source/images/Ack-Button-Active.svg
  source/images/Ack-Button-Default.svg
  source/images/Message-Priority-Animated-optimized.gif
  source/images/Priority-Message-Icon.svg
  source/images/send_F048A.svg
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#6100 Doc listening: Replaced circular link with content
  source/install/install-docker.rst
Labels: 1: PM Review

#6128 Add clarification on ICE host override setting for Calls
  source/configure/calls-deployment.rst
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#6133 Fix broken docs build due to pipenv update
  Makefile
  Pipfile
  Pipfile.lock
Labels: Contributor
