Repository mattermost/docs, pull requests merged in 2022-01, with the labels that each got.

#5342 Update command-line-tools.rst
  source/configure/configuration-settings.rst
  source/manage/command-line-tools.rst
Labels: 3: Reviews Complete, Contributor

#5341 Clarifying the functionality
  source/onboard/migrating-to-mattermost.rst
Labels: 3: Reviews Complete

#5330 Fix slack-advanced-exporter order of operations
  source/onboard/migrating-to-mattermost.rst
Labels: 3: Reviews Complete, Lifecycle/1:stale, Contributor

#5352 Update docs banner for Desktop App Event
  source/templates/header.html
Labels: 3: Reviews Complete

#5349 Update copyright year
  source/conf.py
  source/images/DiscordDarkTheme.png
  source/images/NightOwlDark.png
  source/templates/index.html
Labels: 3: Reviews Complete, preview-environment

#5350 Update desktop-app-install.rst
  source/install/desktop-app-install.rst
Labels: 3: Reviews Complete, Contributor

#5353 Move Enable Reliable Websockets config setting to GA
  source/configure/configuration-settings.rst
  source/configure/deprecated-configuration-settings.rst
Labels: 3: Reviews Complete

#5358 Fix links in changelog table of contents
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete, 2: Editor Review

#5347 Split changelog from latest ESR
  source/guides/deployment.rst
  source/install/legacy-self-hosted-changelog.md
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#5343 Update important-upgrade-notes.rst
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#5359 Update cloud-changelog.md
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#5346 Add example PNS payload for id-only notifications
  source/deploy/mobile-faq.rst
Labels: 3: Reviews Complete

#5366 Update download links to deploy
  source/archive/branding.rst
  source/archive/legacy-upgrade.md
  source/developer/slash-commands.rst
  source/install/install-rhel-6-mattermost.rst
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#5364 Boards: Follow cards/updates
  source/boards/work-with-cards.rst
Labels: 3: Reviews Complete

#5295 Create playbook-permissions.rst
  source/playbooks/playbook-permissions.rst
Labels: 3: Reviews Complete

#5368 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5378 replace circleci to use github actions and add internal job for deployment
  .circleci/config.yml
  .github/workflows/build.yml
  .gitlab-ci.yml
  Makefile
Labels: 3: Reviews Complete

#5382 Upgrade Mattermost Server updates
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#5389 v6.3.2 Docs
  source/install/self-managed-changelog.md
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5392 Add mattermost db migrate command documentation
  source/manage/command-line-tools.rst
Labels: 3: Reviews Complete

#5390 Update recommendations around disabling ThreadAutoFollow and update GA date to Q2
  source/configure/configuration-settings.rst
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete
