Repository mattermost/docs, pull requests merged in 2022-07, with the labels that each got.

#5760 Add section on processor architectures.
  source/install/software-hardware-requirements.rst
Labels: 3: Reviews Complete

#5762 Update index.rst
  source/index.rst
Labels: 3: Reviews Complete

#5764 Added MaxImageDecoderConcurrency config setting
  source/configure/configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#5754 Added documentation on how to join teams
  source/images/join-team.png
  source/welcome/about-teams.rst
Labels: 3: Reviews Complete

#5768 Updated Send messages docs based on user feedback
  source/channels/send-messages.rst
  source/images/more-actions.png
Labels: 3: Reviews Complete

#5743 Clarified how recent emoji are sorted re: quick reactions
  source/channels/react-to-messages.rst
Labels: 3: Reviews Complete

#5741 Insecure outgoing connections setting supports S3
  source/configure/web-server-configuration-settings.rst
Labels: 3: Reviews Complete

#5734 Sphinx search enhancements
  Makefile
  source/_static/searchtools.js
Labels: 1: PM Review, preview-environment, Contributor

#5756 Separate Configuration Settings per System Console section
  source/conf.py
  source/configure/configuration-settings.rst
  source/configure/database-configuration-settings.rst
  source/configure/deprecated-configuration-settings.rst
  source/configure/elasticsearch-configuration-settings.rst
  source/configure/file-storage-configuration-settings.rst
  source/configure/high-availability-configuration-settings.rst
  source/configure/image-proxy-configuration-settings.rst
  source/configure/push-notification-server-configuration-settings.rst
  source/configure/smtp-configuration-settings.rst
  source/configure/user-management-configuration-settings.rst
  source/configure/web-server-configuration-settings.rst
  source/guides/administration.rst
Labels: 3: Reviews Complete

#5769 Bringing back CRT known issues for v6.x customers
  source/channels/organize-conversations.rst
Labels: 3: Reviews Complete

#5742 Documented support for diacritics (accents) in autocomplete @mentions
  source/channels/mention-people.rst
Labels: 3: Reviews Complete

#5763 Insights end user documentation
  source/guides/welcome-to-mattermost.rst
  source/welcome/insights.rst
Labels: 3: Reviews Complete

#5765 Added mmctl options for bulk import/export tasks
  source/manage/bulk-export-data.rst
  source/manage/bulk-export-tool.rst
  source/onboard/run-bulk-loading-command.rst
Labels: 3: Reviews Complete

#5773 Upgrade to v7.1 database prep details
  source/conf.py
  source/guides/deployment.rst
  source/upgrade/prepare-to-upgrade-mattermost.rst
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#5746 v7.1 changelog + docs
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 3: Reviews Complete

#5777 Update SQL command to reflect #20643
  source/install/self-managed-changelog.md
Labels: Contributor

#5745 V7.1 Docs
  source/channels/mention-people.rst
  source/channels/react-to-messages.rst
  source/channels/search-for-messages.rst
  source/channels/send-messages.rst
  source/conf.py
  source/configure/configuation-in-mattermost-database.rst
  source/configure/configuration-settings.rst
  source/configure/database-configuration-settings.rst
  source/configure/deprecated-configuration-settings.rst
  source/configure/elasticsearch-configuration-settings.rst
  source/configure/file-storage-configuration-settings.rst
  source/configure/high-availability-configuration-settings.rst
  source/configure/image-proxy-configuration-settings.rst
  source/configure/push-notification-server-configuration-settings.rst
  source/configure/smtp-configuration-settings.rst
  source/configure/user-management-configuration-settings.rst
  source/configure/web-server-configuration-settings.rst
  source/guides/administration.rst
  source/guides/deployment.rst
  source/guides/welcome-to-mattermost.rst
  source/images/join-team.png
  source/images/more-actions.png
  source/install/self-managed-changelog.md
  source/manage/bulk-export-data.rst
  source/manage/bulk-export-tool.rst
  source/manage/mmctl-command-line-tool.rst
  source/manage/telemetry.rst
  source/onboard/bulk-loading-data-format.rst
  source/onboard/run-bulk-loading-command.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/prepare-to-upgrade-mattermost.rst
  source/upgrade/release-lifecycle.rst
  source/upgrade/upgrading-mattermost-server.rst
  source/welcome/about-teams.rst
  source/welcome/insights.rst
  source/welcome/manage-your-profile.rst
Labels: 3: Reviews Complete

#5775 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5774 v7.1 ESR docs
  source/images/esr.graphic.2.png
  source/upgrade/extended-support-release.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/prepare-to-upgrade-mattermost.rst
  source/upgrade/release-lifecycle.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5781 Remove legacy $149/yr Cloud Starter plan from overview page, link to workspace limits
  source/about/editions-and-offerings.rst
Labels: 3: Reviews Complete

#5783 Add contributors
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#5770 Enable Notice.txt generation
  .config/notice-file/Readme.md
  .config/notice-file/config.yaml
  LICENSE.txt
  NOTICE.txt
  Pipfile
Labels: 1: Dev Review

#5786 Scroll position preference for unread messages
  source/channels/channels-settings.rst
Labels: 3: Reviews Complete

#5791 Removed duplicate LHS entries in Administration
  source/guides/administration.rst
Labels: 3: Reviews Complete

#5793 BUG: Env variables don't overwrite config on save
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5795 Update `mmctl plugin marketplace install` command to reflect behavior of only installing latest plugin versions
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#5799 Export file names include Job ID
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#5798 [MM-45017] Add requirements section for calls
  source/channels/make-calls.rst
Labels: 3: Reviews Complete

#5808 Fixed `ServiceSettings.WriteTimeout` doc example snippet
  source/configure/web-server-configuration-settings.rst
Labels: 3: Reviews Complete

#5809 Update Calls limitations section
  source/channels/make-calls.rst
Labels: 3: Reviews Complete

#5810 Fix Calls FAQ section
  source/channels/make-calls.rst
Labels: 1: Dev Review

#5789 Update telemetry.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#5807 Added mmctl prefix to command examples
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#5812 [MM-45211] Update Calls configuration docs
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete
