Repository mattermost/docs, pull requests merged in 2022-05, with the labels that each got.

#5625 MM-43524 Add note about not unzipping Slack exports
  source/onboard/migrating-to-mattermost.rst
Labels: 3: Reviews Complete

#5637 Docs listening: incorporated feedback
  source/install/install-android-app.rst
  source/install/install-ios-app.rst
Labels: 3: Reviews Complete

#5623 Dark Mode extends beyond title bar
  source/welcome/customize-your-theme.rst
Labels: 3: Reviews Complete

#5635 Updating "Mattermost Free" plan references to "Mattermost Starter"
  source/about/editions-and-offerings.rst
Labels: 3: Reviews Complete

#5575 Added Cloud Connection URL
  source/welcome/sign-in.rst
Labels: 3: Reviews Complete

#5573 Added CleanupConfigThresholdDays setting
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5578 Removed content duplication
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#5607 Incorporated payload descriptions
  source/deploy/mobile-faq.rst
  source/deploy/mobile-hpns.rst
Labels: 3: Reviews Complete

#5638 Update common-sso-openidconnect.rst
  source/onboard/common-sso-openidconnect.rst
Labels: 3: Reviews Complete

#5641 Clarifying the Cloud VPC add-on refers to infrastructure, not to a dedicated AWS account
  source/about/cloud-subscriptions.rst
Labels: 1: Dev Review

#5608 Deprecated BulkIndexingTimeWindowSeconds
  source/configure/configuration-settings.rst
  source/configure/deprecated-configuration-settings.rst
  source/manage/telemetry.rst
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#5601 Global retention policy updates
  source/comply/data-retention-policy.rst
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5647 Clarifying the Cloud VPC add-on refers to infrastructure, not to a dedicated AWS account, part 2
  source/archive/mattermost-cloud-overview.rst
Labels: 2: Editor Review

#5644 Update playbook-permissions.rst
  source/playbooks/playbook-permissions.rst
Labels: 3: Reviews Complete

#5629 Simplify configuration settings
  source/conf.py
  source/configure/common-config-settings-notation.rst
  source/configure/configuration-settings.rst
  source/configure/database-configuration-settings.rst
  source/configure/reporting-configuration-settings.rst
  source/configure/user-management-configuration-settings.rst
  source/configure/web-server-configuration-settings.rst
Labels: 2: Editor Review

#5576 Added screenshots for clarity
  source/channels/channel-naming-conventions.rst
  source/channels/keyboard-shortcuts-for-channels.rst
  source/images/desktop-edit-server.png
  source/images/desktop-remove-server.png
  source/images/desktop-server-add.png
  source/images/desktop-server-add2.png
  source/welcome/keyboard-shortcuts.rst
  source/welcome/manage-desktop-app-server-connections.rst
  source/welcome/team-keyboard-shortcuts.rst
Labels: 2: Editor Review

#5622 Desktop App v5.1 updates
  source/images/desktop-app-settings.jpg
  source/images/dots-vertical_F01D9.svg
  source/images/mac-desktop-app-settings.png
  source/welcome/customize-desktop-app-experience.rst
Labels: 3: Reviews Complete

#5605 v6.7 Changelog and Important Upgrade Notes
  source/install/self-managed-changelog.md
  source/install/software-hardware-requirements.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
Labels: 3: Reviews Complete

#5640 Update statistics.rst
  source/manage/statistics.rst
Labels: 3: Reviews Complete

#5652 Add FAQs to cloud subscriptions page
  source/about/cloud-subscriptions.rst
Labels: 3: Reviews Complete

#5643 Playbooks: Due dates in runs
  source/playbooks/customize-a-playbook.rst
Labels: 1: Dev Review

#5653 Update cloud user limits
  source/about/cloud-subscriptions.rst
  source/manage/cloud-billing.rst
  source/manage/telemetry.rst
Labels: 1: Dev Review

#5577 Specify that telemetry applies to custom groups too
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#5556 self-hosted to cloud migration addition
  source/manage/cloud-data-export.rst
Labels: 1: Dev Review, 1: PM Review

#5654 Update announcement-banner.rst
  source/manage/announcement-banner.rst
Labels: 3: Reviews Complete

#5628 Desktop App Automatic & Manual Updates
  source/conf.py
  source/install/desktop-app-install.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
  source/welcome/sign-in.rst
Labels: 1: Dev Review

#5655 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5663 Add references to Mac app store for desktop
  source/install/desktop-app-changelog.rst
  source/install/desktop-app-install.rst
Labels: 3: Reviews Complete

#5670 Clarify wording of the dedicated Cloud environment add-on
  source/about/cloud-subscriptions.rst
Labels: 2: Editor Review

#5595 Added ALT Tag for guides/channels.rst
  source/guides/channels.rst
Labels: 3: Reviews Complete, Contributor

#5594 Added ALT Tag for guides/boards.rst
  source/guides/boards.rst
Labels: 3: Reviews Complete, Contributor

#5662 Formatting updates
  source/scale/performance-monitoring.rst
Labels: 3: Reviews Complete

#5661 Cloud changelog May 25
  source/install/cloud-changelog.md
Labels: 1: Dev Review

#5680 Fix Link
  source/guides/get-help.rst
Labels: 3: Reviews Complete, Contributor

#5681 Update editions-and-offerings.rst
  source/about/editions-and-offerings.rst
  source/guides/administration.rst
  source/onboard/mattermost-limits.rst
Labels: 1: PM Review
