Repository mattermost/docs, pull requests merged in 2022-10, with the labels that each got.

#5909 Add info to first clone the git repo
  source/boards/migrate-to-boards.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5921 Changed Team Override Scheme to Enterprise only
  source/onboard/advanced-permissions.rst
Labels: 3: Reviews Complete

#5936 Clarified that message formatting is available from Mattermost v7.2
  source/channels/forward-messages.rst
Labels: 3: Reviews Complete

#5934 Updated Mattermost Export CLI child commands with new batchSize option
  source/manage/command-line-tools.rst
Labels: 1: Dev Review, 2: Editor Review

#5902 v7.4 changelog
  source/install/self-managed-changelog.md
  source/install/software-hardware-requirements.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/prepare-to-upgrade-mattermost.rst
  source/upgrade/release-lifecycle.rst
  source/upgrade/version-archive.rst
Labels: 1: Dev Review, 1: PM Review

#5834 Audit logging beta documentation
  source/comply/audit-log.rst
  source/comply/embedded-json-audit-log-schema.rst
  source/guides/administration.rst
Labels: 3: Reviews Complete

#5942 Update version archive
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5938 Dot release docs
  source/install/self-managed-changelog.md
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5946 Minor updates and spelling fixes
  source/archive/cloud-advanced-permissions.rst
  source/boards/share-and-collaborate.rst
  source/channels/channels-settings.rst
  source/deploy/mobile-app-changelog.md
  source/guides/deployment.rst
  source/install/install-nginx.rst
  source/install/install-rhel-8-server.rst
  source/install/install-rhel-nginx.rst
  source/onboard/advanced-permissions.rst
  source/welcome/manage-your-profile.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5949 small typo 7.4 changelog
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5918 added alt text for embedded videos in the docs
  source/about/self-hosted-subscriptions.rst
  source/archive/organizing-conversations-copy2.rst
  source/manage/mmctl-command-line-tool.rst
  source/onboard/ad-ldap-groups-synchronization.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5940 Add some handy Sphinx/docutils scripts
  scripts/config-redirects.py
  scripts/dump-doctree.py
  scripts/validate-refuris.py
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5959 Document channel deletion with content (#5953)
  source/configure/user-management-configuration-settings.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5947 modified create-channel
  source/channels/create-channels.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, preview-environment, Contributor

#5937 Cloud changelog - Oct 20th
  source/install/cloud-changelog.md
  source/install/software-hardware-requirements.rst
Labels: 1: PM Review

#5978 Rectified the bug with the correct link
  source/install/self-managed-changelog.md
Labels: Hacktoberfest, 2: Editor Review, Hacktoberfest-accepted, Contributor

#5965 Clarifying active user count behaviour (#5955)
  source/configure/reporting-configuration-settings.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5975 [Bug] - Fixed Broken 404 Link at Cloud Subscriptions Page
  source/about/cloud-subscriptions.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5972 [GH-5952] - Updated Guest Abilities in Auth Section and Welcome Section
  source/onboard/guest-accounts.rst
  source/welcome/about-user-roles.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5967 Specify click path in system console
  source/manage/in-product-notices.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5986 GH-5985 - Fixed broken links in README
  README.md
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5963 Added desktop app onboarding updates
  source/install/desktop-app-install.rst
  source/welcome/manage-desktop-app-server-connections.rst
Labels: 2: Editor Review

#5979 Changed the broken link to a working link
  source/about/faq-license.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5964 Updated zoom shortcut key sequence
  source/welcome/keyboard-shortcuts.rst
Labels: 3: Reviews Complete

#5984 Update create-channels.rst
  source/channels/create-channels.rst
Labels: 3: Reviews Complete

#5983 Update rename-channels.rst
  source/channels/rename-channels.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, preview-environment, Contributor

#5930 Notify admin
  source/configure/configuration-settings.rst
  source/guides/administration.rst
  source/manage/telemetry.rst
  source/upgrade/notify-admin.rst
Labels: 3: Reviews Complete

#5988 fix: broken table in docs
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5973 [GH-5917] - Added Alt Text For Video About Organizing Convos
  source/archive/organizing-conversations.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5971 [GH-5954] - Updated Authentication Page
  source/configure/authentication-configuration-settings.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5987 [Bug] - Fixed Broken Links in Docs
  source/about/faq-license.rst
  source/about/faq-mattermost-source-available-license.rst
  source/archive/mobile-apps-faq.rst
  source/channels/reply-to-messages.rst
  source/deploy/deployment-overview.rst
  source/deploy/mobile-faq.rst
  source/install/installing-team-edition-helm-chart.rst
  source/install/legacy-self-hosted-changelog.md
  source/onboard/common-sso-openidconnect.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5981 Modified join and leave channels page with mobile content
  source/channels/join-leave-channels.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#5962 Elasticsearch/database search fallback behaviour (#5957)
  source/configure/database-configuration-settings.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, preview-environment, Contributor

#5901 Single-source RST substitutions + include Compass Icon assets
  Makefile
  extensions/compass-icons/__init__.py
  source/_static/css/compass-icons.css
  source/_static/font/compass-icons.eot
  source/_static/font/compass-icons.svg
  source/_static/font/compass-icons.ttf
  source/_static/font/compass-icons.woff
  source/_static/font/compass-icons.woff2
  source/conf.py
Labels: 3: Reviews Complete, Contributor

#6006 Update elasticsearch.rst linking out to ES 7.17 guides
  source/scale/elasticsearch.rst
Labels: 3: Reviews Complete

#5995 Documented that Playbooks is required for channel actions
  source/channels/create-channels.rst
Labels: 3: Reviews Complete

#6001 MM-46980: Add screensharing troubleshooting info; add links to sections
  source/channels/make-calls.rst
Labels: 3: Reviews Complete, preview-environment

#5999 Added note re: OAuth & plugin posts filtered out
  source/welcome/insights.rst
Labels: 2: Editor Review

#5998 Changed terminology: avatar to profile picture
  source/boards/boards-settings.rst
  source/boards/migrate-to-boards.rst
  source/boards/work-with-boards.rst
  source/channels/channels-settings.rst
  source/channels/save-pin-messages.rst
  source/deploy/client-side-data.rst
  source/manage/command-line-tools.rst
  source/onboard/bulk-loading-data-format.rst
  source/onboard/guest-accounts.rst
  source/onboard/multi-factor-authentication.rst
  source/onboard/sso-saml-adfs-msws2016.rst
  source/onboard/sso-saml-adfs.rst
  source/onboard/sso-saml-okta.rst
  source/onboard/sso-saml-onelogin.rst
  source/welcome/get-started-mattermost-channels.rst
  source/welcome/log-out.rst
  source/welcome/manage-your-profile.rst
  source/welcome/set-your-status-availability.rst
  source/welcome/what-changed-in-v60.rst
Labels: 3: Reviews Complete

#5996 Renamed experimental config settings for clarity
  source/conf.py
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#6007 MM-47632 Update steps to customize web app for products
  source/configure/customizing-mattermost.rst
Labels: 3: Reviews Complete

#5903 v5.2 desktop app changelog
  source/install/desktop-app-changelog.rst
  source/install/desktop-app-install.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#5989 Desktop app v5.2 documentation
  source/channels/share-files-in-messages.rst
  source/images/arrow-down-bold-circle-outline_F0048.svg
  source/install/desktop-app-install.rst
  source/welcome/keyboard-shortcuts.rst
  source/welcome/manage-desktop-app-server-connections.rst
Labels: 3: Reviews Complete

#6009 updated React-to-messages
  source/channels/react-to-messages.rst
  source/images/custom-emoji.png
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, preview-environment, Contributor
