Repository mattermost/docs, pull requests merged in 2022-02, with the labels that each got.

#5384 Cloud changelog - Feb
  source/install/cloud-changelog.md
Labels: 1: Dev Review

#5402 Desktop app v5.0.4 docs
  source/install/desktop-app-changelog.rst
  source/install/desktop-app-install.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 1: Dev Review

#5399 Added --disabled-pager
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#5381 Update feedback widget to redirect product feedback to the User Forum
  source/_static/myscript.js
Labels: 3: Reviews Complete

#5398 MMCTL updates
  source/manage/mmctl-command-line-tool.rst
Labels: 2: Editor Review

#5397 Documented new expand sidebar shortcut key sequence
  source/messaging/keyboard-shortcuts.rst
Labels: 3: Reviews Complete

#5403 Redirects Cleanup
  source/conf.py
Labels: 3: Reviews Complete

#5394 v6.4 Changelog + upgrade notes
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 1: PM Review

#5416 Update templates.rst
  source/boards/sharing-boards.rst
  source/boards/templates.rst
  source/boards/work-with-cards.rst
Labels: 3: Reviews Complete

#5393 v1.49 Mobile Changelog
  source/deploy/mobile-app-changelog.md
Labels: 1: PM Review

#5424 Simplify docs wording
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete, Contributor

#5425 Update self-managed-changelog.md
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#5426 Correct socked based db creation
  source/install/setting-up-socket-based-mattermost-database.rst
Labels: 3: Reviews Complete, Contributor

#5373 upgrade to sphinx 4.4
  Pipfile
  Pipfile.lock
Labels: 3: Reviews Complete

#5428 Update changelog known issues
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#5421 Create deprecated-features.rst
  source/guides/deployment.rst
  source/install/deprecated-features.rst
Labels: 3: Reviews Complete

#5431 Source License diagram updated.
  source/images/source-available-license.png
Labels: 3: Reviews Complete, Contributor

#5417 Note that Boards requires EnableReliableWebsockets in important upgrade details
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete, Contributor

#5436 Update shared-channels.rst
  source/onboard/shared-channels.rst
Labels: 3: Reviews Complete

#5433 Mobile changelog v1.49.1
  source/deploy/mobile-app-changelog.md
Labels: 1: Dev Review

#5437 Create cloud-data-residency.rst
  source/guides/administration.rst
  source/manage/cloud-data-residency.rst
Labels: 3: Reviews Complete

#5435 Update important upgrade notes
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/version-archive.rst
Labels: 1: Dev Review
