Repository mattermost/docs, pull requests merged in 2022-08, with the labels that each got.

#5792 Cloud changelog - July 27th
  source/install/cloud-changelog.md
Labels: 1: PM Review

#5803 Docs listening: clarified how to change the team icon
  source/images/edit-team-icon.png
  source/images/team-settings.png
  source/images/upload-team-icon.png
  source/welcome/about-teams.rst
  source/welcome/team-settings.rst
Labels: 3: Reviews Complete

#5801 Site URL clarifications for Desktop App server management
  source/welcome/manage-desktop-app-server-connections.rst
Labels: 2: Editor Review

#5802 Docs listening: Update location of macOS logs
  source/install/troubleshooting.rst
Labels: 3: Reviews Complete

#5683 Update mmctl-command-line-tool.rst
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete, Contributor

#5821 Create whats-new-in-v72.rst
  source/guides/welcome-to-mattermost.rst
  source/images/boards-whats-new-01.png
  source/images/boards-whats-new-02.png
  source/images/boards-whats-new-03.png
  source/images/boards-whats-new-04.png
  source/images/boards-whats-new-05.png
  source/images/boards-whats-new-06.png
  source/images/boards-whats-new-07.png
  source/images/boards-whats-new-08.png
  source/images/boards-whats-new-09.png
  source/images/boards-whats-new-10.png
  source/welcome/whats-new-in-v72.rst
Labels: 1: PM Review

#5823 Case terminology
  source/comply/data-retention-policy.rst
  source/configure/deprecated-configuration-settings.rst
  source/deploy/build-custom-mobile-apps.rst
  source/deploy/desktop-app.rst
  source/deploy/mobile-testing-notifications.rst
  source/deploy/use-prebuilt-mobile-apps.rst
  source/getting-started/admin-onboarding-tasks.rst
  source/getting-started/enterprise-roll-out-checklist.rst
  source/install/deprecated-features.rst
  source/install/desktop-app-install.rst
  source/install/desktop-app-managed-resources.rst
  source/install/desktop-custom-dictionaries.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
  source/install/install-android-app.rst
  source/install/install-ios-app.rst
  source/install/software-hardware-requirements.rst
  source/manage/bulk-export-data.rst
  source/manage/user-satisfaction-surveys.rst
Labels: 3: Reviews Complete, Contributor

#5825 Add cloud tag to compliance monitoring docs
  source/comply/compliance-monitoring.rst
Labels: 3: Reviews Complete

#5822 Update troubleshooting.rst
  source/install/troubleshooting.rst
Labels: 3: Reviews Complete, Contributor

#5827 Add copy to Workspace Limits page
  source/onboard/mattermost-limits.rst
Labels: 3: Reviews Complete

#5805 PostgreSQL & DB installation cleanup
  source/guides/deployment.rst
  source/install/common-local-deploy-docker.rst
  source/install/common-prod-deploy-docker.rst
  source/install/common-prod-deploy-kubernetes.rst
  source/install/common-prod-deploy-omnibus.rst
  source/install/common-prod-deploy-tar.rst
  source/install/config-mattermost-server.rst
  source/install/config-proxy-nginx.rst
  source/install/config-ssl-http2-nginx.rst
  source/install/config-tls-mattermost.rst
  source/install/install-common-intro.rst
  source/install/install-debian-server.rst
  source/install/install-debian.rst
  source/install/install-nginx.rst
  source/install/install-rhel-8-mattermost.rst
  source/install/install-rhel-8-mysql.rst
  source/install/install-rhel-8-postgresql.rst
  source/install/install-rhel-8-server.rst
  source/install/install-rhel-8.rst
  source/install/install-rhel-nginx.rst
  source/install/install-tar.rst
  source/install/install-ubuntu-2004-mattermost.rst
  source/install/install-ubuntu-2004-mysql.rst
  source/install/install-ubuntu-2004-postgresql.rst
  source/install/install-ubuntu-2004-server.rst
  source/install/installing-ubuntu-2004-LTS.rst
Labels: 3: Reviews Complete

#5831 Update whats-new-in-v72.rst
  source/guides/welcome-to-mattermost.rst
  source/welcome/whats-new-in-v72.rst
Labels: 3: Reviews Complete

#5811 Evaluate impact of small wins to bottom 10 docs pages
  source/channels/channels-settings.rst
  source/channels/convert-public-channels.rst
  source/channels/join-leave-channels.rst
  source/channels/manage-channel-members.rst
  source/channels/mark-messages-unread.rst
  source/channels/save-pin-messages.rst
  source/conf.py
  source/configure/file-storage-configuration-settings.rst
  source/images/browse-channels.png
  source/images/convert-public-channel-to-private.png
  source/images/join-channels.png
  source/images/leave-channels.png
  source/images/mark-message-as-unread.png
  source/images/message-more.png
  source/images/pin-message-to-channel.png
  source/images/unpin-message-from-channel.png
  source/install/desktop-custom-dictionaries.rst
  source/manage/mmctl-command-line-tool.rst
  source/welcome/keyboard-shortcuts.rst
  source/welcome/manage-custom-groups.rst
Labels: 3: Reviews Complete

#5829 New system admin role: Custom Group Manager
  source/onboard/advanced-permissions-backend-infrastructure.rst
  source/onboard/system-admin-roles.rst
Labels: 3: Reviews Complete

#5830 Documented Forward Message functionality
  source/channels/forward-messages.rst
  source/channels/share-files-in-messages.rst
  source/channels/share-links.rst
  source/guides/channels.rst
  source/images/download-outline_F0B8F.svg
Labels: 3: Reviews Complete

#5818 v7.2 changelog
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 1: PM Review, 3: Reviews Complete

#5787 Split out configuration settings by task/outcome
  source/about/certifications-and-compliance.rst
  source/comply/audit-log.rst
  source/conf.py
  source/configure/cloud-billing-account-settings.rst
  source/configure/common-config-settings-notation.rst
  source/configure/configuration-settings.rst
  source/configure/database-configuration-settings.rst
  source/configure/developer-mode-configuration-settings.rst
  source/configure/elasticsearch-configuration-settings.rst
  source/configure/environment-configuration-settings.rst
  source/configure/environment-variables.rst
  source/configure/file-storage-configuration-settings.rst
  source/configure/high-availability-configuration-settings.rst
  source/configure/image-proxy-configuration-settings.rst
  source/configure/logging-configuration-settings.rst
  source/configure/performance-monitoring-configuration-settings.rst
  source/configure/push-notification-server-configuration-settings.rst
  source/configure/rate-limiting-configuration-settings.rst
  source/configure/reporting-configuration-settings.rst
  source/configure/self-hosted-account-settings.rst
  source/configure/session-lengths-configuration-settings.rst
  source/configure/smtp-configuration-settings.rst
  source/configure/user-management-configuration-settings.rst
  source/configure/web-server-configuration-settings.rst
  source/guides/administration.rst
  source/recipes/product-vulnerability-incident.rst
  source/scale/high-availability-cluster.rst
Labels: 3: Reviews Complete

#5837 Updated the docs feedback widget to clarify CTA
  source/_static/myscript.js
Labels: 3: Reviews Complete

#5836 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5850 Update important-upgrade-notes.rst
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#5856 Added tip for local mode error
  source/configure/configuration-settings.rst
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#5857 Screenshot updates for More options
  source/channels/forward-messages.rst
  source/channels/save-pin-messages.rst
  source/channels/share-links.rst
  source/images/copy-link.png
  source/images/forward-message.png
  source/images/mark-message-as-unread.png
  source/images/pin-message-to-channel.png
  source/images/unpin-message-from-channel.png
Labels: 3: Reviews Complete

#5863 Update faq-business.rst
  source/about/faq-business.rst
Labels: 1: PM Review

#5866 Update legacy-self-hosted-changelog.md
  source/install/legacy-self-hosted-changelog.md
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 1: Dev Review

#5853 Docs listening: Max notifications per channel clarification
  source/configure/push-notification-server-configuration-settings.rst
Labels: 3: Reviews Complete
