Repository mattermost/docs, pull requests merged in 2022-09, with the labels that each got.

#5859 Cloud changelog - Sept 1st
  source/install/cloud-changelog.md
Labels: 1: Dev Review, 1: PM Review

#5872 Bump Python version to 3.9
  .github/workflows/build.yml
  .github/workflows/preview-env-fork.yml
  .github/workflows/preview-env.yml
Labels: 1: Dev Review

#5869 [MM-46464] Add self-hosted FAQ section
  source/channels/make-calls.rst
  source/configure/calls-deployment.rst
  source/images/calls-deployment-image1.png
Labels: 2: Editor Review

#5877 docs: fix some broken links
  source/about/certifications-and-compliance.rst
  source/about/cloud-subscriptions.rst
  source/about/self-hosted-subscriptions.rst
Labels: 3: Reviews Complete, Contributor

#5875 Case terminology
  source/onboard/shared-channels.rst
  source/onboard/ssl-client-certificate.rst
  source/playbooks/customize-a-playbook.rst
  source/playbooks/getting-started.rst
  source/playbooks/setting-up-playbooks.rst
  source/upgrade/release-lifecycle.rst
  source/upgrade/upgrading-to-v60.rst
  source/welcome/customize-desktop-app-experience.rst
  source/welcome/customize-your-theme.rst
  source/welcome/keyboard-shortcuts.rst
  source/welcome/log-in.rst
  source/welcome/manage-desktop-app-server-connections.rst
  source/welcome/manage-your-profile.rst
  source/welcome/set-your-status-availability.rst
Labels: 3: Reviews Complete, Contributor

#5855 Update to RestrictDirectMessage config docs
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5852 Post formatting options can be disabled
  source/channels/channels-settings.rst
  source/channels/format-messages.rst
  source/configure/developer-mode-configuration-settings.rst
Labels: 3: Reviews Complete

#5854 Added most active DMs to My Insights
  source/welcome/insights.rst
Labels: 3: Reviews Complete

#5858 Clarified OS Light/Dark Mode functionality
  source/images/dark-theme-via-os.gif
  source/welcome/customize-your-theme.rst
Labels: 3: Reviews Complete

#5824 Create faq-license.rst
  source/about/faq-business.rst
  source/about/faq-enterprise.rst
  source/about/faq-license.rst
  source/about/faq-mattermost-source-available-license.rst
  source/about/frequently-asked-questions.rst
  source/conf.py
Labels: 3: Reviews Complete

#5887 Removed embedded videos no longer available via YT
  source/install/desktop-app-install.rst
Labels: 3: Reviews Complete

#5838 Create calls-deployment.rst
  source/channels/make-calls.rst
  source/configure/calls-deployment.rst
  source/guides/administration.rst
  source/images/calls-deployment-image1.png
  source/images/calls-deployment-image2.png
  source/images/calls-deployment-image3.png
  source/images/calls-deployment-image4.png
  source/images/calls-deployment-image5.png
  source/images/calls-deployment-image7.png
  source/images/calls-deployment-kubernetes.png
Labels: 1: PM Review, 3: Reviews Complete

#5889 Update cloud data residency doc for clarity
  source/manage/cloud-data-residency.rst
Labels: 2: Editor Review

#5886 Muted channels aren't returned via Find Channels
  source/channels/find-channels.rst
Labels: 2: Editor Review

#5814 Update sso-saml.rst
  source/onboard/sso-saml.rst
Labels: 3: Reviews Complete, Contributor

#5867 Implement mid-page link redirects
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  extensions/reredirects/__init__.py
  source/conf.py
  source/templates/layout.html
  source/templates/redirect.html
  source/templates/simpleredirect.html
  tests/conftest.py
  tests/redirects_test.py
  tests/roots/test-root/conf.py
Labels: preview-environment, Contributor, 2. SME Review

#5871 v7.3 Changelog
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 1: PM Review, 3: Reviews Complete

#5890 Update cloud-subscriptions.rst
  source/about/cloud-subscriptions.rst
Labels: 1: PM Review

#5881 Boards 7.3 and doc reorg
  source/boards/accessing-boards.rst
  source/boards/calculations.rst
  source/boards/groups-filter-sort.rst
  source/boards/migrate-to-boards.rst
  source/boards/navigate-boards.rst
  source/boards/overview.rst
  source/boards/share-and-collaborate.rst
  source/boards/sharing-boards.rst
  source/boards/templates.rst
  source/boards/views-and-sorting.rst
  source/boards/work-with-boards.rst
  source/boards/work-with-cards.rst
  source/boards/work-with-views.rst
  source/boards/working-with-boards.rst
  source/guides/boards.rst
Labels: 1: PM Review

#5861 V7.3 documentation
  source/about/cloud-subscriptions.rst
  source/boards/accessing-boards.rst
  source/boards/calculations.rst
  source/boards/groups-filter-sort.rst
  source/boards/migrate-to-boards.rst
  source/boards/navigate-boards.rst
  source/boards/overview.rst
  source/boards/share-and-collaborate.rst
  source/boards/sharing-boards.rst
  source/boards/templates.rst
  source/boards/views-and-sorting.rst
  source/boards/work-with-boards.rst
  source/boards/work-with-cards.rst
  source/boards/work-with-views.rst
  source/boards/working-with-boards.rst
  source/channels/channels-settings.rst
  source/channels/find-channels.rst
  source/channels/format-messages.rst
  source/channels/forward-messages.rst
  source/channels/save-pin-messages.rst
  source/channels/share-links.rst
  source/conf.py
  source/configure/configuration-settings.rst
  source/configure/developer-mode-configuration-settings.rst
  source/configure/push-notification-server-configuration-settings.rst
  source/guides/boards.rst
  source/images/copy-link.png
  source/images/dark-theme-via-os.gif
  source/images/forward-message.png
  source/images/mark-message-as-unread.png
  source/images/pin-message-to-channel.png
  source/images/unpin-message-from-channel.png
  source/install/desktop-app-install.rst
  source/install/self-managed-changelog.md
  source/manage/mmctl-command-line-tool.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
  source/welcome/customize-your-theme.rst
  source/welcome/insights.rst
Labels: 3: Reviews Complete

#5878 Add Calls specific shortcuts
  source/channels/keyboard-shortcuts-for-channels.rst
Labels: 3: Reviews Complete

#5893 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5892 Update important-upgrade-notes.rst
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete, Contributor

#5900 Update Licences at Notice.txt to reflect dependency changes.
  NOTICE.txt
Labels: 3: Reviews Complete

#5894 Alt tag addition
  source/channels/customize-your-channel-sidebar.rst
  source/onboard/sso-saml-keycloak.rst
  source/onboard/sso-saml-okta.rst
  source/onboard/sso-saml-onelogin.rst
  source/recipes/product-vulnerability-incident.rst
Labels: 3: Reviews Complete, Contributor

#5904 Update conf.py
  source/conf.py
Labels: 3: Reviews Complete

#5896 Update for new option names
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete, Contributor

#5906 Update work-with-boards.rst
  source/boards/work-with-boards.rst
Labels: 3: Reviews Complete
