Repository mattermost/docs, pull requests merged in 2022-04, with the labels that each got.

#5516 Clarifying our editions and offerings
  source/about/deployments-and-editions.rst
  source/about/editions-and-offerings.rst
  source/conf.py
  source/guides/about-mattermost.rst
  source/overview/index.rst
Labels: 1: PM Review, 2: Editor Review

#5519 Adding link to online trial
  source/about/editions-and-offerings.rst
Labels: 3: Reviews Complete

#5518 Correcting how Cloud Enterprise can be purchased
  source/about/editions-and-offerings.rst
Labels: 3: Reviews Complete

#5317 Clarified TE scope requirements for GitLab SSO
  source/onboard/common-converting-oauth-to-openidconnect.rst
  source/onboard/common-sso-google.rst
  source/onboard/common-sso-office365.rst
  source/onboard/common-sso-openidconnect.rst
  source/onboard/convert-oauth20-service-providers-to-openidconnect.rst
  source/onboard/sso-gitlab.rst
Labels: 3: Reviews Complete

#5531 Updated mmctl channel delete requirements
  source/configure/configuration-settings.rst
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete, Contributor

#5537 Clarified mmctl user verify description
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#5451 Clarify MariaDB
  source/install/software-hardware-requirements.rst
Labels: 2. SME Review

#5536 Restart required for GPO changes
  source/install/desktop-app-install.rst
Labels: 3: Reviews Complete

#5512 Update accessing-boards.rst
  source/boards/accessing-boards.rst
  source/playbooks/get-started-with-playbooks.rst
  source/welcome/get-started-mattermost-channels.rst
Labels: 2: Editor Review

#5524 Added performance debugging options
  source/channels/channels-settings.rst
  source/configure/configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#5538 Shared Channels config setting in System Console
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5542 fix mac link shortcut
  source/channels/keyboard-shortcuts-for-channels.rst
Labels: 3: Reviews Complete

#5533 Adding links and clarifying support isn't free
  source/install/troubleshooting.rst
Labels: 3: Reviews Complete

#5521 Added Applied Schema Migrations
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5520 Automatically Follow Thread config setting surfaced in System Console
  source/configure/configuration-settings.rst
Labels: 2: Editor Review

#5523 Described how workspace score is calculated
  source/configure/optimize-your-workspace.rst
Labels: 3: Reviews Complete

#5544 Polishing Cloud changelog
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#5543 Added missing supported languages
  source/configure/configuration-settings.rst
Labels: 3: Reviews Complete

#5541 Adding non-profit licensing program
  source/about/subscription.rst
Labels: 3: Reviews Complete

#5539 Added Docker & Tar deploys to Deploy landing page
  source/conf.py
  source/guides/deployment.rst
  source/install/common-local-deploy-docker.rst
  source/install/common-prod-deploy-docker.rst
  source/install/common-prod-deploy-omnibus.rst
  source/install/common-prod-deploy-tar.rst
  source/install/troubleshooting.rst
Labels: 3: Reviews Complete

#5517 Update deploy instructions for Docker
  source/conf.py
  source/guides/deployment.rst
  source/install/common-prod-deploy-docker.rst
  source/install/common-prod-deploy-tar.rst
  source/install/install-docker.rst
  source/install/setting-up-local-machine-using-docker.rst
Labels: 3: Reviews Complete

#5522 Add Install from tar guide
  source/guides/deployment.rst
  source/install/install-debian-mattermost.rst
  source/install/install-debian.rst
  source/install/install-tar.rst
Labels: 3: Reviews Complete

#5551 Incorporated reusable content for Omnibus deployments
  source/guides/deployment.rst
  source/install/common-prod-deploy-omnibus.rst
  source/install/installing-mattermost-omnibus.rst
Labels: 3: Reviews Complete

#5547 Update channels-settings.rst
  source/channels/channels-settings.rst
Labels: 3: Reviews Complete

#5548 Corrected version support note
  source/scale/elasticsearch.rst
Labels: 3: Reviews Complete

#5505 v6.6 Changelog and Docs
  source/install/self-managed-changelog.md
  source/install/software-hardware-requirements.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
  source/upgrade/upgrading-mattermost-server.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#5527 Cloud Changelog - Apr 13
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#5545 Added channel actions documentation
  source/channels/create-channels.rst
  source/channels/join-leave-channels.rst
  source/channels/send-messages.rst
  source/welcome/about-user-roles.rst
Labels: 3: Reviews Complete

#5502 v1.51 Mobile Changelog
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#5564 Updates to wording of Mattermost Enterprise
  source/about/editions-and-offerings.rst
Labels: 3: Reviews Complete

#5563 Update Important Upgrade Notes
  source/upgrade/important-upgrade-notes.rst
Labels: 1: Dev Review

#5566 Update changelog
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#5568 v1.51.1 Mobile Changelog
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#5569 Incorporated sphinx-copybutton extension
  Pipfile
  Pipfile.lock
  source/conf.py
Labels: 3: Reviews Complete

#5562 Cloud changelog - Apr 27
  source/install/cloud-changelog.md
Labels: 1: Dev Review

#5579 [MM-42474] Updating gitlab sso docs
  source/onboard/sso-gitlab.rst
Labels: 3: Reviews Complete
