Repository mattermost/docs, pull requests merged in 2023-01, with the labels that each got.

#6135 Update self managed changelog
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#6129 Desktop App uninstall
  source/install/desktop-app-install.rst
Labels: 3: Reviews Complete

#6119 Remove Boards mention
  source/comply/audit-log.rst
Labels: 3: Reviews Complete, Contributor

#6099 Playbooks: New structure and 7.6
  source/archive/get-started-with-playbooks.rst
  source/archive/getting-started.rst
  source/archive/playbook-permissions.rst
  source/archive/running-playbooks.rst
  source/archive/setting-up-playbooks.rst
  source/conf.py
  source/guides/playbooks.rst
  source/playbooks/customize-a-run.rst
  source/playbooks/notifications-and-updates.rst
  source/playbooks/overview.rst
  source/playbooks/reusing-and-sharing-playbooks.rst
  source/playbooks/share-and-collaborate.rst
  source/playbooks/work-with-playbooks.rst
  source/playbooks/work-with-runs.rst
  source/playbooks/work-with-tasks.rst
Labels: 1: Dev Review

#6139 Update index.html
  source/templates/index.html
Labels: 3: Reviews Complete, Contributor

#6138 Updated heading for random emoji section
  source/boards/boards-settings.rst
Labels: 3: Reviews Complete

#5911 Add configuration settings to search results
  .gitignore
  Makefile
  extensions/config-setting-v2/__init__.py
  scripts/dump_doctree.py
  source/_static/mytheme.css
  source/_static/searchtools.js
  source/comply/electronic-discovery.rst
  source/conf.py
  source/configure/authentication-configuration-settings.rst
  source/configure/compliance-configuration-settings.rst
  source/configure/config-proxy-apache2.rst
  source/configure/config-ssl-http2-apache2.rst
  source/configure/database-configuration-settings.rst
  source/configure/developer-mode-configuration-settings.rst
  source/configure/elasticsearch-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/file-storage-configuration-settings.rst
  source/configure/high-availability-configuration-settings.rst
  source/configure/image-proxy-configuration-settings.rst
  source/configure/integrations-configuration-settings.rst
  source/configure/logging-configuration-settings.rst
  source/configure/performance-monitoring-configuration-settings.rst
  source/configure/plugins-configuration-settings.rst
  source/configure/push-notification-server-configuration-settings.rst
  source/configure/rate-limiting-configuration-settings.rst
  source/configure/session-lengths-configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/configure/smtp-configuration-settings.rst
  source/configure/web-server-configuration-settings.rst
  source/install/desktop-app-managed-resources.rst
  source/manage/bulk-export-data.rst
  source/manage/mmctl-command-line-tool.rst
  source/templates/search.html
Labels: 2: Editor Review, preview-environment, Contributor

#6137 Added note about moving cards to other boards
  source/boards/work-with-cards.rst
Labels: 3: Reviews Complete

#6104 v7.6 packaging changes
  source/_static/badges/entpro-cloud-free.rst
  source/about/editions-and-offerings.rst
  source/onboard/mattermost-limits.rst
  source/onboard/shared-channels.rst
  source/onboard/sso-gitlab.rst
  source/onboard/sso-google.rst
  source/onboard/sso-openidconnect.rst
  source/welcome/insights.rst
Labels: 1: PM Review

#6146 OAuth 2.0 deprecation notes removed
  source/configure/authentication-configuration-settings.rst
  source/onboard/common-converting-oauth-to-openidconnect.rst
Labels: 3: Reviews Complete

#6147 Config defaults can't be modified by Cloud admins
  source/configure/authentication-configuration-settings.rst
  source/configure/integrations-configuration-settings.rst
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete

#6142 Update navigate-boards.rst
  source/boards/navigate-boards.rst
Labels: 3: Reviews Complete

#6150 Updated team override scheme badge to professional
  source/onboard/advanced-permissions.rst
Labels: 3: Reviews Complete

#6148 Playbooks: Multiple runs
  source/playbooks/work-with-playbooks.rst
Labels: 3: Reviews Complete

#6149 Update work-with-tasks.rst
  source/playbooks/work-with-tasks.rst
Labels: 3: Reviews Complete

#6153 Remove local flag from bot create command
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#6154 Update cloud changelog
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#6136 Self-hosted: in-product purchase
  source/about/self-hosted-subscriptions.rst
Labels: 1: PM Review

#6144 Update mattermost-limits.rst
  source/onboard/mattermost-limits.rst
Labels: 1: PM Review

#6090 Calls: Added recording to config settings
  source/channels/make-calls.rst
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#6075 Mobile app v2 changelog
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#6127 Addressed docs gap around user provisioning
  source/guides/welcome-to-mattermost.rst
  source/welcome/add-people.rst
  source/welcome/manage-custom-groups.rst
Labels: 3: Reviews Complete

#6157 Add a hint to the important upgrade notes
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete, Contributor

#6118 Global drafts documentation
  source/channels/reply-to-messages.rst
  source/channels/send-messages.rst
  source/configure/experimental-configuration-settings.rst
  source/images/Global-Drafts-Animated-GIF.gif
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#6159 Update self-hosted-subscriptions.rst
  source/about/self-hosted-subscriptions.rst
Labels: 3: Reviews Complete

#6082 MM-48120/MM-48623 Add docs for ExperimentalSettings.PatchPluginsReactDOM
  source/configure/experimental-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#6059 [MM-5046] Postgres search supports email
  source/channels/search-for-messages.rst
Labels: 3: Reviews Complete

#6170 Update Uservoice links to Productboard
  source/_static/myscript.js
  source/about/editions-and-offerings.rst
  source/about/faq-use-cases.rst
  source/guides/get-help.rst
  source/manage/bulk-export-data.rst
  source/onboard/ad-ldap.rst
  source/onboard/sso-saml.rst
Labels: 3: Reviews Complete, Contributor

#6169 v7.7.1 docs
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#6168 Updated docs banner with v7.7 announcement & link
  source/templates/header.html
Labels: 2: Editor Review

#6175 Clearified keycloak steps:
  source/images/keycloak_4_create_username_attribute_finished.png
  source/onboard/sso-saml-keycloak.rst
Labels: 2: Editor Review, preview-environment

#6174 adds favicon.ico to root path (#6173)
  source/conf.py
Labels: 3: Reviews Complete, Contributor

#6151 Cloud changelog - Jan 26th
  source/install/cloud-changelog.md
Labels: 1: Dev Review, 1: PM Review

#6183 Update self-hosted-subscriptions.rst
  source/about/self-hosted-subscriptions.rst
  source/images/true-up-schedule.png
Labels: 3: Reviews Complete

#6189 Add known Playbooks issue
  source/install/cloud-changelog.md
  source/install/self-managed-changelog.md
Labels: 1: Dev Review

#6188 Support request: Make section headings sharable
  source/onboard/migrating-to-mattermost.rst
Labels: 3: Reviews Complete

#6171 Removed `list` command from docs
  source/playbooks/interact-with-playbooks.rst
Labels: 3: Reviews Complete

#6172 [GH-5951] Update Plugin Configuration Settings > Plugin Management
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete, Contributor

#6178 Docs listening: Clarified telemetry opt-out processes
  source/guides/administration.rst
  source/manage/telemetry.rst
Labels: 2: Editor Review, 2. SME Review
