Repository mattermost/docs, pull requests merged in 2023-10, with the labels that each got.

#6676 Update software-hardware-requirements.rst
  source/install/software-hardware-requirements.rst
Labels: 1: Dev Review

#6648 Desktop v5.5.1 release notes
  source/collaborate/install-desktop-app.rst
  source/install/desktop-app-changelog.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#6678 Hacktoberfest announce + footer icon title edit
  source/_static/myscript.js
  source/templates/header.html
  source/templates/index.html
Labels: 2: Editor Review

#6674 [MM-54289] Document pprof metrics in Support Packet
  source/manage/common-support-packet.rst
Labels: 3: Reviews Complete

#6673 Fix whois site URL in faq-illicit-use.rst
  source/about/faq-illicit-use.rst
  source/archive/gitlab-process.rst
Labels: Hacktoberfest, 2: Editor Review, Contributor

#6677 Added Note for User Discovery on Same Server
  source/collaborate/invite-people.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6671 Replica lag settings and guide
  source/configure/database-configuration-settings.rst
  source/images/database-configuration-settings-replica-lag-grafana-1.jpg
  source/images/database-configuration-settings-replica-lag-grafana-2.jpg
Labels: 3: Reviews Complete

#6685 [MM-54496] Document authentication options to Calls services
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#6693 Expand team admin's scope
  source/collaborate/learn-about-roles.rst
Labels: 3: Reviews Complete

#6686 Added new & changed v9.1 config settings
  source/configure/plugins-configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 1: Dev Review

#6688 Update Manage sidebar enhanced features navigation link
  source/preferences/manage-your-sidebar-options.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6662 v9.1 changelog & docs
  source/install/download-latest-tarball.rst
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 1: PM Review, 3: Reviews Complete

#6702 Replaced regular log levels for audit-specific levels
  source/comply/audit-log.rst
Labels: 3: Reviews Complete

#6700 External provider: out of desktop app during login
  source/collaborate/access-your-workspace.rst
Labels: 3: Reviews Complete

#6684 Add documentation on GM notifications
  source/collaborate/channel-types.rst
Labels: 3: Reviews Complete

#6694 Plan/deployment badge added for pprof metrics
  source/scale/performance-monitoring.rst
Labels: 3: Reviews Complete

#6691 Channel filters when browsing channels
  source/collaborate/browse-channels.rst
Labels: 1: Dev Review

#6695 Can include archived channels in export
  source/manage/cloud-data-export.rst
  source/manage/mmctl-command-line-tool.rst
Labels: 1: Dev Review, 1: PM Review

#6680 users.json example added #6180-docs
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6708 Update Mattermost Load Test repo Link
  source/install/software-hardware-requirements.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6712 Fix typo in convert-group-messages.rst
  source/collaborate/convert-group-messages.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6706 [DOC-6594]: Help Wanted: Update Mobile Troubleshooting Docs
  source/deploy/mobile-faq.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6710 Add v9.1 walkthrough video to the changelog
  source/install/self-managed-changelog.md
Labels: 2: Editor Review

#6721 Update sso-saml.rst
  source/onboard/sso-saml.rst
Labels: 1: Dev Review

#6724 In-product notices can gather user feedback
  source/manage/in-product-notices.rst
Labels: 3: Reviews Complete

#6722 Add desktop breaking change note
  source/install/cloud-changelog.md
  source/install/desktop-app-changelog.rst
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
Labels: 1: PM Review

#6726 In-product notices can gather user feedback
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete

#6725 v9.1 changelog edits
  source/install/self-managed-changelog.md
Labels: 1: PM Review

#6729 Update self-managed-changelog.md
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#6713 Clarify Changing Rate Limit Settings
  source/configure/rate-limiting-configuration-settings.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6731 [MM-55075] Incorporate new findings into Postgres migration guidelines
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#6732 Elastic Search Docs - Add information about required permissions for Mattermost service account
  source/scale/elasticsearch.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6736 Added inactive details & removed duplicated table
  source/conf.py
  source/preferences/set-your-status-availability.rst
Labels: 3: Reviews Complete

#6727 [Docs Update]: Review and Update iOS Setup documentation
  source/collaborate/install-ios-app.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6618 Added setcap FAQ for single server deploys
  source/_static/mytheme.css
  source/install/install-rhel-8.rst
  source/install/install-tar.rst
  source/install/install-ubuntu.rst
Labels: 3: Reviews Complete, 2. SME Review

#6745 Added prefetch user preference
  source/preferences/manage-advanced-options.rst
Labels: 3: Reviews Complete

#6743 Added MaxFieldSize logging config option
  source/configure/logging-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#6746 Add a note to ESR document that server version is not dependent on your license key
  source/upgrade/extended-support-release.rst
Labels: 3: Reviews Complete

#6730 Added post props reserved for integrations
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#6749 Work with Playbook Typo Fixed
  source/repeatable-processes/work-with-playbooks.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6750 Work with Runs Typo Fixed
  source/repeatable-processes/work-with-runs.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6720 add app deployment guides
  source/guides/configure-app-framework.rst
  source/guides/deploy-aws.rst
  source/guides/deploy-http.rst
  source/guides/deploy-mattermost-apps.rst
  source/guides/deploy-mm-aws.png
  source/guides/deploy-openfaas.rst
  source/guides/deploy-third-party-aws.png
  source/guides/deployment.rst
  source/guides/package-aws.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#6752 Use-Cases Typo Fixed.
  source/about/use-cases.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor
