Repository mattermost/docs, pull requests merged in 2023-06, with the labels that each got.

#6378 Cloud changelog - June 1st
  source/install/cloud-changelog.md
Labels: 1: Dev Review, 1: PM Review

#6448 Add known issue to cloud changelog
  source/install/cloud-changelog.md
Labels: 3: Reviews Complete

#6447 Added missing content from mmctl repository
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#6452 Update extended-support-release.rst
  source/upgrade/extended-support-release.rst
Labels: 3: Reviews Complete

#6454 [MM-53066] Improve documentation on STUN configuration servers usage for calls
  source/configure/calls-deployment.rst
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#6463 Updated plugin default states
  source/conf.py
  source/configure/plugins-configuration-settings.rst
  source/getting-started/light-install.rst
  source/playbooks/metrics-and-goals.rst
  source/playbooks/share-and-collaborate.rst
Labels: 3: Reviews Complete

#6465 Update certifications-and-compliance.rst
  source/about/certifications-and-compliance.rst
Labels: 3: Reviews Complete

#6461 Added new config setting: DelayChannelAutocomplete
  source/configure/experimental-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 1: Dev Review

#6471 Deprecated PatchPluginsReactDOM config setting
  source/configure/deprecated-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#6475 Fix Experimental Shared Channels Link
  source/onboard/shared-channels.rst
Labels: 3: Reviews Complete

#6456 Update PostgreSQL DB config docs
  source/guides/deployment.rst
  source/install/prepare-mattermost-database.rst
Labels: 1: PM Review

#6466 Added maxAllowedPacket size change
  source/install/trouble_mysql.rst
Labels: 3: Reviews Complete

#6430 Desktop app v5.4 changelog
  source/install/desktop-app-changelog.rst
  source/install/desktop-app-install.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
  source/upgrade/open-source-components.rst
Labels: 3: Reviews Complete

#6482 Update desktop-app-changelog.rst
  source/install/desktop-app-changelog.rst
Labels: 3: Reviews Complete

#6460 Added config setting: SqlSettings.ReplicaMonitorIntervalSeconds
  source/configure/database-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#6469 Added Desktop app MSI installer tip
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#6490 Updated German push proxy documentation
  source/configure/push-notification-server-configuration-settings.rst
  source/deploy/mobile-hpns.rst
Labels: 3: Reviews Complete

#6494 Removed PermissionUseSlashCommands
  source/onboard/advanced-permissions-backend-infrastructure.rst
Labels: 3: Reviews Complete

#6495 Auto-enable Apps Bar
  source/boards/navigate-boards.rst
  source/conf.py
  source/configure/experimental-configuration-settings.rst
  source/install/cloud-changelog.md
  source/install/desktop-app-changelog.rst
  source/install/self-managed-changelog.md
  source/manage/telemetry.rst
  source/playbooks/work-with-playbooks.rst
Labels: 3: Reviews Complete

#6493 Deprecated Insights
  source/guides/welcome-to-mattermost.rst
  source/install/deprecated-features.rst
  source/welcome/insights.rst
Labels: 3: Reviews Complete

#6492 Authentication fixes
  source/configure/authentication-configuration-settings.rst
  source/onboard/ad-ldap.rst
Labels: 3: Reviews Complete, Contributor

#6487 Fix download links
  source/install/desktop-app-changelog.rst
Labels: 3: Reviews Complete, Contributor

#6497 Updated references of "suite" to "platform"
  source/about/editions-and-offerings.rst
  source/boards/work-with-cards.rst
  source/channels/make-calls.rst
  source/configure/experimental-configuration-settings.rst
  source/install/self-managed-changelog.md
Labels: 3: Reviews Complete

#6474 Cloud changelog - June 29th release
  source/install/cloud-changelog.md
Labels: 1: Dev Review, 1: PM Review
