Repository mattermost/docs, pull requests merged in 2023-12, with the labels that each got.

#6788 Add info to slack migration docs
  source/conf.py
  source/guides/self-hosted-administration.rst
  source/onboard/migrate-from-slack.rst
  source/onboard/migrating-from-hipchat-to-mattermost.rst
  source/onboard/migrating-to-mattermost.rst
Labels: Work In Progress, 2: Editor Review

#6800 Added keyword highlighting docs
  source/images/keywords-highlighted.gif
  source/images/keywords-trigger-mentions.gif
  source/preferences/manage-your-notifications.rst
Labels: 3: Reviews Complete

#6782 Added link to article on how to set up a quick Kubernetes evaluation deployment
  source/archive/common-prod-deploy-kubernetes.rst
  source/install/faq_kubernetes.rst
  source/install/install-kubernetes.rst
Labels: 1: PM Review

#6797 Python 3.12 support
  Pipfile
  Pipfile.lock
Labels: 1: Dev Review, Contributor

#6822 [MM-55998] incorporate more findings from community
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#6823 Clarify why posts deleted by Data Retention job are visible in the webapp
  source/comply/data-retention-policy.rst
Labels: 3: Reviews Complete

#6829 Updated official MS Teams terminology, plan details, removed duplicate page
  source/about/embed-mattermost-app-within-microsoft-teams.rst
  source/about/install-mattermost-for-microsoft-teams-plugin.rst
  source/about/mattermost-for-microsoft-teams.rst
  source/about/unified-collaboration.rst
  source/archive/embed-mattermost-within-microsoft-teams.rst
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
  source/collaborate/collaborate-within-embedded-microsoft-teams.rst
  source/collaborate/extend-mattermost-with-integrations.rst
  source/conf.py
Labels: 3: Reviews Complete

#6820 [MM-55744] postgres-migration: add findings from mysql8 migration
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#6786 v9.3 Changelog
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/install/software-hardware-requirements.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#6834 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#6840 Clean up migration guide to remove some marketing verbiage
  source/onboard/migrating-to-mattermost.rst
Labels: 3: Reviews Complete, Contributor

#6781 Updated proxy guidelines & added NGINX/TLS to nav
  source/guides/deployment.rst
  source/install/common-deploy-faq.rst
  source/install/install-nginx.rst
  source/install/install-rhel-8.rst
  source/install/install-tar.rst
  source/install/install-ubuntu.rst
  source/install/installing-ubuntu-1804-LTS.rst
  source/install/setup-nginx-proxy.rst
  source/install/setup-tls.rst
Labels: 3: Reviews Complete

#6785 v5.6 Desktop changelog
  source/collaborate/install-desktop-app.rst
  source/deploy/desktop-app-changelog.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
  source/install/software-hardware-requirements.rst
Labels: 1: PM Review

#6838 Refresh post stats run time config setting
  source/configure/site-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#6835 Global Relay custom customer type & new config settings
  source/comply/compliance-export.rst
  source/configure/compliance-configuration-settings.rst
Labels: 3: Reviews Complete

#6839 docs: update mattermost version in k8s examples
  source/archive/common-prod-deploy-kubernetes.rst
Labels: 3: Reviews Complete

#6852 Audit and improve community onboarding experience
  source/guides/community-chat.rst
  source/guides/contribute-to-documentation.rst
  source/guides/get-help.rst
Labels: Area/Documentation Improvements

#6836 Unique emoji reaction limit config setting
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete

#6846 Multi-client call support & incoming call notifications for DM/GM
  source/collaborate/make-calls.rst
Labels: 3: Reviews Complete

#6813 Overhauled logging > replace audit-logging docs
  source/about/editions-and-offerings.rst
  source/archive/audit-log.rst
  source/comply/embedded-json-audit-log-schema.rst
  source/conf.py
  source/configure/experimental-configuration-settings.rst
  source/configure/logging-configuration-settings.rst
  source/guides/self-hosted-administration.rst
  source/manage/logging.rst
Labels: 1: Dev Review, 2. SME Review
