Repository mattermost/docs, pull requests merged in 2023-04, with the labels that each got.

#6312 Create "Secure Command & Control" solutions page
  source/about/secure-command-and-control.rst
  source/overview/index.rst
Labels: 3: Reviews Complete

#6309 Desktop app v5.3 changelog & docs
  source/install/desktop-app-changelog.rst
  source/install/desktop-app-install.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#6323 Update integrations-configuration-settings.rst
  source/configure/integrations-configuration-settings.rst
Labels: 3: Reviews Complete

#6322 Create message-reminders.rst
  source/channels/message-reminders.rst
  source/guides/channels.rst
Labels: 3: Reviews Complete

#6320 Update boards content for 7.10
  source/boards/get-started-with-boards.rst
  source/boards/getting-started.rst
  source/boards/share-and-collaborate.rst
Labels: 3: Reviews Complete

#6270 Removed manual SQL data check as the fix is now in-code
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
Labels: 1: Dev Review

#6325 Link to tarball archive page
  source/install/common-prod-deploy-tar.rst
Labels: 3: Reviews Complete

#6324 Update integrations-configuration-settings.rst
  source/configure/integrations-configuration-settings.rst
Labels: 3: Reviews Complete

#6326 Added enable board sharing configs and others
  source/about/cloud-subscriptions.rst
  source/about/editions-and-offerings.rst
  source/channels/create-channels.rst
  source/channels/search-for-messages.rst
  source/channels/set-channel-preferences.rst
  source/channels/share-files-in-messages.rst
  source/configure/product-configuration-settings.rst
  source/guides/administration.rst
  source/onboard/advanced-permissions.rst
  source/onboard/shared-channels.rst
  source/onboard/sso-gitlab.rst
  source/onboard/sso-office.rst
Labels: 3: Reviews Complete

#6327 Update notification banner with Productivity Webinar CTA
  source/_static/myscript.js
  source/conf.py
  source/templates/header.html
Labels: 3: Reviews Complete

#6311 v7.10 Changelog
  source/install/self-managed-changelog.md
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 1: PM Review, 3: Reviews Complete

#6330 MM-51662 Update help text for settings to enable SVGs and Latex
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete

#6336 Update conf.py
  source/conf.py
Labels: 3: Reviews Complete

#6329 Document upgrade best practices
  source/upgrade/prepare-to-upgrade-mattermost.rst
Labels: 3: Reviews Complete

#6328 Correct nesting of notes/code blocks
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete, Contributor

#6339 Update Calls benchmarks
  source/configure/calls-deployment.rst
Labels: 3: Reviews Complete

#6341 Sidebar search scroll issue and main nav updates
  source/_static/images/nav/academy.svg
  source/_static/images/nav/promo/promo-gitlab-solutions.png
  source/_static/images/nav/promo/promo-gitlab-webinar.png
  source/_static/images/nav/promo/promo-mattermost-microsoft-solutions.png
  source/_static/mytheme.css
  source/conf.py
  source/templates/header.html
Labels: 3: Reviews Complete, preview-environment

#6348 Create a troubleshooting guide for high scale deployments
  source/deploy/high-scale-troubleshoot.rst
  source/guides/deployment.rst
Labels: 3: Reviews Complete

#6343 [MM-51839] Link to ice host override setting documentation
  source/configure/calls-deployment.rst
Labels: 3: Reviews Complete

#6353 Update integrations.rst
  source/about/integrations.rst
Labels: 3: Reviews Complete

#6342 [MM-51496] Add documentation for call recording quality
  source/configure/calls-deployment.rst
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#6337 Update what-changed-in-v70.rst
  source/welcome/what-changed-in-v60.rst
  source/welcome/what-changed-in-v70.rst
  source/welcome/whats-new-in-v72.rst
Labels: 3: Reviews Complete

#6355 Create a solutions page for Mattermost Customizable ChatGPT Bot Framework
  source/about/mattermost-customizable-chatgpt-bot-framework.rst
  source/overview/index.rst
Labels: 3: Reviews Complete

#6356 Overhauled tarball install steps
  source/_static/mytheme.css
  source/conf.py
  source/guides/deployment.rst
  source/install/common-prod-deploy-omnibus.rst
  source/install/common-prod-deploy-tar.rst
  source/install/install-tar.rst
Labels: 3: Reviews Complete

#6358 Overhauled Ubuntu install steps via new page
  source/_static/myscript.js
  source/_static/mytheme.css
  source/conf.py
  source/guides/deployment.rst
  source/install/install-ubuntu.rst
Labels: 3: Reviews Complete

#6361 Trace logging doesn't apply to SAML
  source/install/troubleshooting.rst
Labels: 2: Editor Review, preview-environment, Contributor

#6338 Update guest-accounts.rst
  source/onboard/guest-accounts.rst
Labels: 3: Reviews Complete

#6317 [MM-51797] Add bullet point on calls transmission security
  source/about/security.rst
Labels: 3: Reviews Complete
