Repository mattermost/docs, pull requests merged in 2023-11, with the labels that each got.

#6753 v2.9.1 Mobile changelog
  source/deploy/mobile-app-changelog.md
Labels: 1: Dev Review

#6757 Update prepare-mattermost-database.rst
  source/install/prepare-mattermost-database.rst
Labels: 3: Reviews Complete, Contributor

#6664 Initial redo of config settings for postgres
  source/scale/high-availability-cluster.rst
Labels: 3: Reviews Complete

#6761 Added Mattermost Free note
  source/about/editions-and-offerings.rst
Labels: 3: Reviews Complete

#6762 Update notification banner
  source/_static/images/notification-bar/icon-green-rocket.svg
  source/_static/myscript.js
  source/conf.py
  source/templates/header.html
Labels: 3: Reviews Complete

#6717 v9.2 Changelog
  source/images/ESR_update.png
  source/install/download-latest-tarball.rst
  source/install/software-hardware-requirements.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/prepare-to-upgrade-mattermost.rst
  source/upgrade/release-lifecycle.rst
  source/upgrade/version-archive.rst
Labels: 1: Dev Review, 1: PM Review

#6733 Academy links added contextually
  source/_static/badges/academy-calls.rst
  source/_static/badges/academy-customize-ui.rst
  source/_static/badges/academy-file-storage.rst
  source/_static/badges/academy-mattermost-database.rst
  source/_static/badges/academy-message-formatting.rst
  source/_static/badges/academy-msteams.rst
  source/_static/badges/academy-notifications.rst
  source/_static/badges/academy-platform-overview.rst
  source/_static/badges/academy-playbooks.rst
  source/_static/badges/academy-search.rst
  source/_static/badges/academy-tarball-deployment.rst
  source/_static/badges/academy-tarball-upgrade.rst
  source/_static/badges/academy-teams.rst
  source/_static/badges/academy.rst
  source/_static/images/badges/academy-callout-image.jpg
  source/_static/images/badges/academy-qrcode.png
  source/_static/images/badges/lightbulb-outline_F0336.svg
  source/_static/mytheme.css
  source/about/mattermost-for-microsoft-teams.rst
  source/collaborate/collaborate-using-mattermost-for-microsoft-teams.rst
  source/collaborate/format-messages.rst
  source/collaborate/make-calls.rst
  source/collaborate/organize-using-teams.rst
  source/collaborate/search-for-messages.rst
  source/configure/database-configuration-settings.rst
  source/configure/file-storage-configuration-settings.rst
  source/configure/optimize-your-workspace.rst
  source/configure/plugins-configuration-settings.rst
  source/guides/get-help.rst
  source/guides/preferences.rst
  source/guides/repeatable-processes.rst
  source/guides/use-mattermost.rst
  source/install/install-tar.rst
  source/preferences/manage-your-notifications.rst
  source/templates/header.html
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#6763 Clarified SSO availability
  source/about/editions-and-offerings.rst
  source/onboard/sso-gitlab.rst
Labels: 3: Reviews Complete

#6758 Fix config name for "Enable diagnostics and error reporting"
  source/configure/logging-configuration-settings.rst
Labels: 2: Editor Review

#6770 Update legacy-self-hosted-changelog.md
  source/deploy/legacy-self-hosted-changelog.md
Labels: 3: Reviews Complete

#6769 Dot release docs
  source/deploy/legacy-self-hosted-changelog.md
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#6787 Replaced manual page TOCs with code-generated TOCs
  source/deploy/deprecated-features.rst
  source/deploy/desktop-app-changelog.rst
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#6789 Fix ESR graphic
  source/images/ESR2_update.png
  source/upgrade/extended-support-release.rst
Labels: 2: Editor Review

#6766 Split out embedded integration from connected integration
  source/about/embed-mattermost-within-microsoft-teams.rst
  source/about/install-mattermost-for-microsoft-teams-plugin.rst
  source/about/mattermost-for-microsoft-teams.rst
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
  source/collaborate/collaborate-within-embedded-microsoft-teams.rst
  source/collaborate/extend-mattermost-with-integrations.rst
  source/conf.py
Labels: 3: Reviews Complete

#6784 Added performance monitoring/alerting for MSTeams plugin
  source/about/embed-mattermost-app-within-microsoft-teams.rst
  source/about/install-mattermost-for-microsoft-teams-plugin.rst
  source/about/mattermost-for-microsoft-teams.rst
  source/images/grafana-dashboard-msteams.png
Labels: 3: Reviews Complete

#6802 Clarify changelog note
  source/deploy/mattermost-changelog.md
Labels: 3: Reviews Complete

#6805 Update collaborate-within-connected-microsoft-teams.rst
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
Labels: 3: Reviews Complete

#6777 + Vietnamese as Beta; + Hungarian where missing
  source/about/editions-and-offerings.rst
  source/configure/site-configuration-settings.rst
  source/preferences/manage-your-display-options.rst
Labels: 3: Reviews Complete

#6774 Marked mmctl integrity as deprecated from v9.3
  source/manage/mmctl-command-line-tool.rst
Labels: 1: PM Review

#6806 [MM-55337] Improvements to calls troubleshooting sections
  source/collaborate/make-calls.rst
  source/configure/calls-deployment.rst
Labels: 3: Reviews Complete

#6812 Mobile v2.10.1 changelog
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#6804 Dot release docs
  source/deploy/legacy-self-hosted-changelog.md
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete
