Repository mattermost/docs, pull requests merged in 2024-08, with the labels that each got.

#7312 add support for migrating Calls plugin
  source/deploy/manual-postgres-migration.rst
  source/deploy/postgres-migration-assist-tool.rst
Labels: 3: Reviews Complete

#7313 Add a note about Mattermost Cloud to nonprofit docs page
  source/about/subscription.rst
Labels: 3: Reviews Complete

#7311 Revert back BYOK and remove BYOC
  source/about/cloud-subscriptions.rst
  source/guides/cloud-workspace-management.rst
  source/manage/cloud-byok.rst
Labels: 3: Reviews Complete

#7316 Fix v9-changelog url
  source/about/release-policy.md
Labels: 3: Reviews Complete

#7322 Add callout for licensing in kubernetes docs
  source/install/install-kubernetes.rst
Labels: 3: Reviews Complete

#7323 Add example for LDAP trace logging
  source/manage/logging.rst
Labels: 3: Reviews Complete

#7284 v9.11 Changelog
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/release-policy.md
  source/about/version-archive.rst
  source/images/ESR_graphic12.png
  source/install/download-latest-tarball.rst
  source/install/software-hardware-requirements.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/prepare-to-upgrade-mattermost.rst
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#7295 DCT deprecation note
  source/about/deprecated-features.rst
  source/upgrade/important-upgrade-notes.rst
Labels: 1: PM Review

#7298 mysql deprecation: Add new flags to the documentation and some minor clarifications.
  source/deploy/manual-postgres-migration.rst
  source/deploy/postgres-migration-assist-tool.rst
Labels: 3: Reviews Complete

#7307 ESR upgrade guidance for legacy releases
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/release-policy.md
  source/about/unsupported-legacy-releases.md
  source/deploy/manual-postgres-migration.rst
Labels: 3: Reviews Complete

#7309 Pre-compiled binary now primary tool installation workflow
  source/deploy/manual-postgres-migration.rst
  source/deploy/postgres-migration-assist-tool.rst
Labels: 3: Reviews Complete

#7320 Manage user's settings
  source/configure/user-management-configuration-settings.rst
  source/manage/cloud-byok.rst
Labels: 3: Reviews Complete

#7321 Added metadata details for generated support packets
  source/manage/common-support-packet.rst
Labels: 3: Reviews Complete

#7324 LDAP errors included in support packet generation
  source/manage/common-support-packet.rst
Labels: 3: Reviews Complete

#7326 mmctl config set supports AdvancedLoggingJSON config
  source/manage/logging.rst
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#7327 Added support for custom status in bulk export/import
  source/manage/bulk-export-tool.rst
  source/onboard/bulk-loading-data.rst
Labels: 3: Reviews Complete

#7331 Can download mattermost.log file locally via System Console
  source/configure/logging-configuration-settings.rst
  source/configure/reporting-configuration-settings.rst
  source/manage/logging.rst
Labels: 3: Reviews Complete

#7332 Corrected feature flag & corrected Sys Console UI setting location/path
  source/configure/performance-monitoring-configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/scale/deploy-prometheus-grafana-for-performance-monitoring.rst
Labels: 3: Reviews Complete, 2. SME Review

#7336 Docs listening: Message reminders clarification
  source/collaborate/message-reminders.rst
Labels: 3: Reviews Complete

#7337 Docs listening: Added MFA flows to user login
  source/collaborate/access-your-workspace.rst
Labels: 3: Reviews Complete

#7339 Docs listening: Clarified deprecated vs. official Docker GH repos
  source/install/common-prod-deploy-docker.rst
  source/install/install-docker.rst
Labels: 3: Reviews Complete

#7319 Team selection updated
  source/configure/manage-user-surveys.rst
  source/images/survey-contents.png
  source/images/survey-schedule.png
Labels: 3: Reviews Complete

#7333 Clarified that Webhook Secret & At Rest Encryption Key are Mattermost actions
  source/integrate/github-interoperability.rst
Labels: 2. SME Review

#7334 Deprecated BulkIndexingTimeWindowSeconds in favour of BatchSize for ES
  source/configure/elasticsearch-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 1: Dev Review

#7335 Added RelayState requirement for SAML 2.0
  source/configure/authentication-configuration-settings.rst
  source/onboard/sso-saml-technical.rst
Labels: 1: Dev Review

#7338 Support for OpenSearch & Elasticsearch v8 & new backend config setting
  source/about/unsupported-legacy-releases.md
  source/configure/elasticsearch-configuration-settings.rst
  source/install/software-hardware-requirements.rst
  source/install/troubleshooting.rst
  source/manage/logging.rst
  source/scale/additional-ha-considerations.rst
  source/scale/elasticsearch.rst
Labels: 1: PM Review

#7325 GitHub subscription notification updates & Keyboard shortcuts modal update
  source/collaborate/keyboard-shortcuts.rst
  source/images/keyboard-shortcuts.png
  source/integrate/github-interoperability.rst
Labels: 3: Reviews Complete

#7282 Desktop v5.9 changelog
  source/about/desktop-app-changelog.md
  source/about/mattermost-desktop-releases.md
  source/collaborate/install-desktop-app.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
  source/install/software-hardware-requirements.rst
Labels: 1: PM Review, 3: Reviews Complete

#7157 Add command line options for new MSI installer
  source/collaborate/install-desktop-app.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#7278 V9.11 Docs
  source/about/deprecated-features.rst
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/release-policy.md
  source/about/unsupported-legacy-releases.md
  source/about/version-archive.rst
  source/collaborate/access-your-workspace.rst
  source/collaborate/keyboard-shortcuts.rst
  source/collaborate/make-calls.rst
  source/collaborate/message-reminders.rst
  source/conf.py
  source/configure/authentication-configuration-settings.rst
  source/configure/elasticsearch-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/logging-configuration-settings.rst
  source/configure/manage-user-surveys.rst
  source/configure/performance-monitoring-configuration-settings.rst
  source/configure/reporting-configuration-settings.rst
  source/configure/session-lengths-configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/configure/user-management-configuration-settings.rst
  source/images/ESR_graphic12.png
  source/images/keyboard-shortcuts.png
  source/images/survey-contents.png
  source/images/survey-schedule.png
  source/install/common-prod-deploy-docker.rst
  source/install/download-latest-tarball.rst
  source/install/install-docker.rst
  source/install/software-hardware-requirements.rst
  source/install/troubleshooting.rst
  source/integrate/github-interoperability.rst
  source/manage/bulk-export-tool.rst
  source/manage/cloud-byok.rst
  source/manage/common-support-packet.rst
  source/manage/logging.rst
  source/manage/mmctl-command-line-tool.rst
  source/manage/telemetry.rst
  source/onboard/advanced-permissions-backend-infrastructure.rst
  source/onboard/bulk-loading-data.rst
  source/onboard/sso-saml-technical.rst
  source/preferences/connect-multiple-workspaces.rst
  source/preferences/manage-your-notifications.rst
  source/scale/additional-ha-considerations.rst
  source/scale/deploy-prometheus-grafana-for-performance-monitoring.rst
  source/scale/elasticsearch.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/prepare-to-upgrade-mattermost.rst
Labels: 3: Reviews Complete

#7329 Update version-archive.rst
  source/about/version-archive.rst
Labels: 3: Reviews Complete

#7253 Add Ubuntu Noble support notes
  source/install/common-prod-deploy-omnibus.rst
  source/install/install-ubuntu.rst
  source/install/installing-mattermost-omnibus.rst
Labels: 3: Reviews Complete

#7283 Mobile v2.19 changelog
  source/about/mattermost-mobile-releases.md
  source/about/mobile-app-changelog.md
Labels: 1: PM Review, 3: Reviews Complete

#7340 Update mattermost-desktop-releases.md
  source/about/mattermost-desktop-releases.md
Labels: 3: Reviews Complete

#7346 Update download-latest-tarball.rst
  source/install/download-latest-tarball.rst
Labels: 3: Reviews Complete

#7347 Update mattermost-v9-changelog.md
  source/about/mattermost-v9-changelog.md
Labels: 3: Reviews Complete

#7305 Programmatically diagram ESR Gantt Chart POC
  Pipfile
  Pipfile.lock
  source/_static/css/mattermost-global.css
  source/about/release-policy.md
  source/conf.py
Labels: 3: Reviews Complete

#7350 Update mattermost-server-releases.md
  source/about/mattermost-mobile-releases.md
  source/about/mattermost-server-releases.md
Labels: 3: Reviews Complete

#7355 Clarified x-asis labels & adjusted frequency to every other month
  source/about/release-policy.md
Labels: 2. SME Review

#7357 Add changelog video
  source/about/mattermost-v9-changelog.md
Labels: 3: Reviews Complete

#7356 MM-53705: Update metrics docs
  source/scale/performance-monitoring-metrics.rst
Labels: 3: Reviews Complete

#7358 Updated Desktop v5.9 link, removed 32-bit links no longer supported
  source/collaborate/install-desktop-app.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#7354 Migrating MS plugins to product docs
  source/about/editions-and-offerings.rst
  source/about/mattermost-for-microsoft-teams.rst
  source/about/maximize-microsoft-investment.rst
  source/about/unified-collaboration.rst
  source/about/use-cases.rst
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
  source/conf.py
  source/guides/integrate-and-extend.rst
  source/images/ms-calendar-add-permission.png
  source/images/ms-calendar-api-permissions.png
  source/images/ms-calendar-certs-secrets.png
  source/images/ms-calendar-copy-ids.png
  source/images/ms-calendar-delegated-permissions.png
  source/images/ms-calendar-grant-admin-consent.png
  source/images/ms-calendar-new-azure-registration.png
  source/images/ms-calendar-new-client-secret.png
  source/images/ms-calendar-single-tenant.png
  source/images/ms-teams-meetings-add-permission.png
  source/images/ms-teams-meetings-api-permissions.png
  source/images/ms-teams-meetings-certs-secrets.png
  source/images/ms-teams-meetings-copy-ids.png
  source/images/ms-teams-meetings-delegated-permissions.png
  source/images/ms-teams-meetings-grant-admin-consent.png
  source/images/ms-teams-meetings-new-azure-registration.png
  source/images/ms-teams-meetings-new-client-secret.png
  source/images/ms-teams-meetings-reg-info.png
  source/integrate/microsoft-calendar-interoperability.rst
  source/integrate/microsoft-teams-interoperability.rst
  source/integrate/microsoft-teams-meetings-interoperability.rst
Labels: 3: Reviews Complete

#7364 Clarified ES version support
  source/about/mattermost-v9-changelog.md
  source/configure/elasticsearch-configuration-settings.rst
  source/deploy/manual-postgres-migration.rst
  source/scale/elasticsearch.rst
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#7353 Mobile v2.19.1 dot release docs
  source/about/mattermost-mobile-releases.md
  source/about/mobile-app-changelog.md
Labels: 3: Reviews Complete

#7352 Dot release docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v9-changelog.md
  source/about/version-archive.rst
  source/install/download-latest-tarball.rst
Labels: 3: Reviews Complete

#7370 Mattermost Playbooks for Microsoft Teams
  source/about/maximize-microsoft-investment.rst
  source/guides/integrate-and-extend.rst
  source/images/mattermost_playbooks_for_teams.png
  source/integrate/playbooks-for-microsoft-teams.rst
Labels: 2: Editor Review
