Repository mattermost/docs, pull requests merged in 2024-03, with the labels that each got.

#6941 Updated reference architectures to scale Mattermost
  source/guides/scale-mattermost.rst
  source/images/network-diagram.svg
  source/images/network_diagram-old.png
  source/install/software-hardware-requirements.rst
  source/scale/additional-ha-considerations.rst
  source/scale/estimated-storage-per-user-per-month.rst
  source/scale/lifetime-storage.rst
  source/scale/scale-to-100-users.rst
  source/scale/scale-to-1000-users.rst
  source/scale/scale-to-15000-users.rst
  source/scale/scale-to-25000-users.rst
  source/scale/scale-to-50000-users.rst
  source/scale/scale-to-70000-users.rst
  source/scale/scale-to-79000-users.rst
  source/scale/scale-to-88000-users.rst
  source/scale/scaling-for-enterprise.rst
Labels: 3: Reviews Complete

#6963 Fix title in scale-to-88000-users.rst
  source/scale/scale-to-88000-users.rst
Labels: 3: Reviews Complete

#6969 [MM-57086] Remove UseGossip setting
  source/configure/deprecated-configuration-settings.rst
  source/configure/high-availability-configuration-settings.rst
  source/scale/high-availability-cluster.rst
Labels: 3: Reviews Complete

#6968 Documented system admin user mgmt options
  source/configure/user-management-configuration-settings.rst
Labels: 3: Reviews Complete

#6971 Clarified DB config storage language from "a" to "your"
  source/conf.py
  source/configure/configuration-in-your-database.rst
  source/configure/configuration-settings.rst
  source/configure/environment-variables.rst
  source/getting-started/enterprise-roll-out-checklist.rst
  source/guides/self-hosted-administration.rst
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#6947 remove nginx proxy_cache
  source/install/config-proxy-nginx.rst
  source/install/config-ssl-http2-nginx.rst
Labels: 3: Reviews Complete, Contributor

#6928 Added decision context for end users
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
Labels: 3: Reviews Complete

#6976 Archive legacy K8s Operator page
  source/archive/mattermost-kubernetes-operator.rst
  source/conf.py
  source/configure/calls-deployment.rst
  source/guides/prepare-for-your-mattermost-deployment.rst
  source/install/install-kubernetes.rst
Labels: 3: Reviews Complete

#6950 Clarified pre-packaged vs latest vs Marketplace integrations
  source/collaborate/extend-mattermost-with-integrations.rst
Labels: 3: Reviews Complete

#6967 Added AWS HA RDS deploy guidance
  source/configure/database-configuration-settings.rst
  source/scale/high-availability-cluster.rst
Labels: 3: Reviews Complete

#6974 Update Mattermost Operator docs
  source/install/faq_kubernetes.rst
  source/install/install-kubernetes.rst
  source/install/manage_kubernetes.rst
Labels: 3: Reviews Complete

#6930 v9.6 Changelog
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/install/software-hardware-requirements.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 1: PM Review, 3: Reviews Complete

#6973 Update collaborate-within-connected-microsoft-teams.rst
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
Labels: 1: PM Review

#6927 v9.6 Docs
  source/about/faq-mattermost-source-available-license.rst
  source/about/install-mattermost-for-microsoft-teams-plugin.rst
  source/collaborate/extend-mattermost-with-integrations.rst
  source/collaborate/install-desktop-app.rst
  source/collaborate/make-calls.rst
  source/collaborate/share-files-in-messages.rst
  source/conf.py
  source/configure/database-configuration-settings.rst
  source/configure/file-storage-configuration-settings.rst
  source/configure/high-availability-configuration-settings.rst
  source/configure/logging-configuration-settings.rst
  source/configure/plugins-configuration-settings.rst
  source/configure/user-management-configuration-settings.rst
  source/deploy/deployment-overview.rst
  source/deploy/desktop-app-changelog.rst
  source/deploy/legacy-cloud-changelog.md
  source/deploy/legacy-self-hosted-changelog.md
  source/deploy/mattermost-changelog.md
  source/deploy/mobile-app-changelog.md
  source/deploy/postgres-migration.rst
  source/getting-started/implementation-plan.rst
  source/install/download-latest-tarball.rst
  source/install/install-kubernetes.rst
  source/install/install-nginx.rst
  source/install/software-hardware-requirements.rst
  source/manage/mmctl-command-line-tool.rst
  source/onboard/ad-ldap-groups-synchronization.rst
  source/onboard/bulk-loading-about.rst
  source/onboard/migrate-from-slack.rst
  source/onboard/migrating-to-mattermost.rst
  source/onboard/run-bulk-loading-command.rst
  source/preferences/customize-desktop-app-experience.rst
  source/scale/high-availability-cluster.rst
  source/scale/scale-to-15000-users.rst
  source/upgrade/installing-license-key.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 3: Reviews Complete

#6931 v2.14 Mobile app changelog
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#6978 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#6883 [MM-46676] Document new ICE host port override setting for Calls
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#6981 Add changelog video
  source/deploy/mattermost-changelog.md
Labels: 3: Reviews Complete

#6909 Desktop v5.7 changelog
  source/collaborate/install-desktop-app.rst
  source/deploy/desktop-app-changelog.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#6956 Desktop v5.7: Updated Dev Tools path
  source/collaborate/install-desktop-app.rst
  source/collaborate/make-calls.rst
Labels: 3: Reviews Complete

#6983 Changelog fixes
  source/deploy/mattermost-changelog.md
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#6979 Update the MySQL to Postgres migration guide with the recent feedback
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#6987 fix a typo in the migration doc
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#6990 Fixing theme issue
  source/_static/css/homepage-v1.css
  source/_static/css/homepage-v1.css.map
  source/_static/css/mattermost-global.css
  source/_static/scss/partials/_badge.scss
  source/_static/scss/partials/_masthead.scss
Labels: 3: Reviews Complete

#6991 Fix nav scripting, classes and styles
  source/_static/css/mattermost-global.css
  source/_static/js/myscript-v1.js
Labels: 3: Reviews Complete

#6993 Fix broken link
  source/upgrade/extended-support-release.rst
Labels: 3: Reviews Complete

#6994 fix: add missing "mmctl" keyword in a command example
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#6999 Update anchors and copy snippets
  source/_static/css/copybuttons.css
  source/_static/css/homepage-v1.css
  source/_static/css/homepage-v1.css.map
  source/_static/css/mattermost-global.css
  source/_templates/custom-nav.html
  source/install/download-latest-tarball.rst
  source/install/install-ubuntu.rst
  source/install/installing-mattermost-omnibus.rst
Labels: 3: Reviews Complete

#7002 Fixing notification bar issue
  source/_static/css/homepage-v1.css
  source/_static/css/homepage-v1.css.map
  source/_static/css/mattermost-global.css
  source/_static/scss/homepage-v1.scss
  source/_static/scss/partials/_blog.scss
Labels: 3: Reviews Complete

#7001 added new edit option icon
  source/guides/contribute-to-documentation.rst
  source/images/edit-on-github.png
Labels: 3: Reviews Complete, Contributor

#6986 Dot release docs
  source/deploy/legacy-self-hosted-changelog.md
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#6998 Added YouTube video re: CloudNative Bootstrapper
  source/install/install-kubernetes.rst
Labels: 3: Reviews Complete
