Repository mattermost/docs, pull requests merged in 2024-12, with the labels that each got.

#7619 Docs listening: Multi-line text in a table cell isn't supported
  source/collaborate/format-messages.rst
Labels: 3: Reviews Complete

#7620 Added link to interactive Copilot demo online
  source/collaborate/chat-with-copilot.rst
  source/configure/enable-copilot.rst
Labels: 3: Reviews Complete

#7622 Code blocks include Copy option
  source/collaborate/format-messages.rst
Labels: 3: Reviews Complete

#7623 Telemetry updates: custom groups, read-only channels, & passive keyword tracking
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#7624 Can import/export Bot users as separate entities
  source/manage/bulk-export-tool.rst
  source/onboard/bulk-loading-data.rst
Labels: 3: Reviews Complete

#7625 Docs Listening: Added load test tool caveats and recommendations
  source/scale/scaling-for-enterprise.rst
Labels: 3: Reviews Complete

#7626 Docs listening: Added procedure step: switch to new DB
  source/install/prepare-mattermost-database.rst
Labels: 3: Reviews Complete

#7627 Changed push notification default to Online, away, or offline
  source/preferences/manage-your-mobile-notifications.rst
Labels: 3: Reviews Complete

#7628 Copilot enabled by default from v10.3
  source/configure/enable-copilot.rst
Labels: 3: Reviews Complete

#7630 New Search UI
  source/collaborate/search-for-messages.rst
  source/images/calendar2.png
  source/images/channel-files-icon.png
  source/images/search-files.png
  source/images/search-messages-expanded.png
  source/images/search-messages.png
Labels: 3: Reviews Complete

#7631 Updated mmctl --per-page docs from default to maximum
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#7632 Docs listening: Added user management data column descriptions
  source/configure/user-management-configuration-settings.rst
Labels: 3: Reviews Complete

#7633 Docs listening: Added product limits page
  source/guides/get-started-with-administration.rst
  source/manage/product-limits.rst
Labels: 3: Reviews Complete

#7636 Docs listening: Overhauled downgrade docs
  source/upgrade/downgrading-mattermost-server.rst
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#7639 Docs listening: SAML email caveats
  source/onboard/sso-saml.rst
Labels: 3: Reviews Complete

#7641 Added justification for disabling key configs to improve performance
  source/configure/environment-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/integrations-configuration-settings.rst
  source/configure/plugins-configuration-settings.rst
  source/configure/push-notification-server-configuration-settings.rst
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete

#7638 Moved config setting results to bottom of page
  source/_static/js/mattermost-search.js
  source/_templates/search.html
Labels: 3: Reviews Complete

#7621 Added TCP target sample file & repathed downloadable files
  source/deploy/mobile-appconfig.rst
  source/manage/logging.rst
  source/samples/advanced-logging-options-sample-json.zip
  source/samples/mattermost-specfile.xml
  source/samples/sample-logger-config.json
Labels: 3: Reviews Complete

#7640 New page for push notification health targets
  source/guides/scale-mattermost.rst
  source/images/push-notification-stats.png
  source/images/push-notifications-not-sent-distribution.png
  source/images/push-proxy-delivery-rate.png
  source/images/total-acked-push-notifications.png
  source/scale/push-notification-health-targets.rst
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#7644 Notification from address is for self-hosted deployments only
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete

#7645 Go handsfree with Copilot with voice dictation
  source/collaborate/chat-with-copilot.rst
Labels: 3: Reviews Complete

#7647 Connected workspaces tweaks
  source/onboard/connected-workspaces.rst
Labels: 3: Reviews Complete

#7617 Dot release docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/version-archive.rst
  source/install/download-latest-tarball.rst
Labels: 3: Reviews Complete

#7599 v10.3 changelog
  source/about/deprecated-features.rst
  source/about/mattermost-v10-changelog.md
  source/install/download-latest-tarball.rst
  source/install/software-hardware-requirements.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#7649 Added guidance on when to reduce the config value
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#7650 Simplified the invite people docs page
  source/about/faq-product.rst
  source/collaborate/invite-people.rst
  source/images/copy-invite-link.png
  source/images/invite-email-username.png
  source/images/invite-people.png
  source/onboard/guest-accounts.rst
  source/onboard/ssl-client-certificate.rst
Labels: 3: Reviews Complete

#7656 Update site-configuration-settings.rst
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete

#7654 DOC-7652: Document how to manage channels via the System Console
  source/configure/user-management-configuration-settings.rst
  source/images/add-members-to-a-channel.png
  source/images/allow-create-posts-for-a-channel.png
  source/images/allow-manage-bookmarks-for-a-channel.png
  source/images/allow-manage-members-for-a-channel.png
  source/images/allow-mentions-for-a-channel.png
  source/images/allow-post-reactions-for-a-channel.png
  source/images/archive-a-channel.png
  source/images/channel-configuration-details.png
  source/images/channel-search-filters.png
  source/images/find-channels.png
  source/images/remove-members-from-a-channel.png
  source/images/set-a-channel-to-public-or-private.png
  source/images/sync-group-members-in-a-channel.png
Labels: 3: Reviews Complete, Contributor

#7651 DOC-7643: Document how to manage teams via the System Console
  source/configure/user-management-configuration-settings.rst
  source/images/add-members-to-a-team.png
  source/images/anyone-can-join-a-team.png
  source/images/archive-a-team.png
  source/images/find-teams.png
  source/images/remove-members-from-a-team.png
  source/images/specific-email-domains-can-join-a-team.png
  source/images/sync-group-members-in-a-team.png
  source/images/team-configuration-details.png
  source/images/team-search-filters.png
Labels: 3: Reviews Complete, Contributor

#7657 Update deprecated-features.rst
  source/about/deprecated-features.rst
Labels: 3: Reviews Complete

#7655 Update version-archive.rst
  source/about/version-archive.rst
Labels: 3: Reviews Complete

#7598 Mobile v2.23 changelog
  source/about/mattermost-mobile-releases.md
  source/about/mobile-app-changelog.md
Labels: 3: Reviews Complete

#7660 Cleanup, page archival & redirect, above the fold adjustments
  source/about/certifications-and-compliance.rst
  source/about/faq-mattermost-source-available-license.rst
  source/about/frequently-asked-questions.rst
  source/collaborate/collaborate-within-channels.rst
  source/collaborate/keyboard-accessibility.rst
  source/collaborate/mark-channels-unread.rst
  source/conf.py
  source/configure/user-management-configuration-settings.rst
  source/deploy/high-scale-troubleshoot.rst
  source/guides/deployment-troubleshooting.rst
  source/guides/deployment.rst
  source/images/announcement-banner.png
  source/install/install-kubernetes.rst
  source/manage/in-product-notices.rst
  source/manage/system-wide-notifications.rst
Labels: 3: Reviews Complete

#7665 Add v10.3 video to changelog
  source/about/mattermost-v10-changelog.md
Labels: 3: Reviews Complete

#7668 v10.1.5 docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/version-archive.rst
Labels: 2. SME Review

#7669 Added license requirement for schedule post feature in release notes
  source/about/mattermost-v10-changelog.md
Labels: 3: Reviews Complete

#7560 Add documentation for code signing custom Mattermost builds
  source/guides/other-administration-resources.rst
  source/manage/code-signing-custom-builds.rst
Labels: 3: Reviews Complete, Contributor

#7670 Mobile Dot Release 2.23.1 docs
  source/about/mattermost-mobile-releases.md
  source/about/mobile-app-changelog.md
Labels: 3: Reviews Complete
