Repository mattermost/docs, pull requests merged in 2024-01, with the labels that each got.

#6819 Update the docs for the latest Keycloak version
  source/images/keycloak_1_client_settings.png
  source/images/keycloak_2_saml_keys.png
  source/images/keycloak_3_add_builtins.png
  source/images/keycloak_4_create_username_attribute.png
  source/images/keycloak_4_create_username_attribute_finished.png
  source/images/keycloak_9_export_metadata.png
  source/onboard/sso-saml-keycloak.rst
Labels: 3: Reviews Complete, preview-environment

#6831 Dedicated filestore for bulk and compliance exports
  source/comply/compliance-export.rst
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#6860 Update install-ubuntu.rst
  source/install/install-ubuntu.rst
Labels: 3: Reviews Complete, Contributor

#6863 Update Year in footer page
  source/templates/index.html
Labels: 3: Reviews Complete, Contributor

#6864 Update documentation for operator deployments
  source/install/install-kubernetes.rst
Labels: 3: Reviews Complete

#6854 Corrected logs CLI command
  source/guides/prepare-for-your-mattermost-deployment.rst
  source/install/manage_kubernetes.rst
Labels: 3: Reviews Complete

#6818 Dot release docs
  source/deploy/legacy-self-hosted-changelog.md
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#6866 Update reporting-configuration-settings.rst
  source/configure/reporting-configuration-settings.rst
Labels: 3: Reviews Complete

#6845 Enterprise BYOK
  source/_static/badges/ent-cloud-dedicated.rst
  source/guides/cloud-workspace-management.rst
  source/manage/cloud-byok.rst
Labels: 1: PM Review, 2. SME Review

#6825 v9.4 changelog
  source/deploy/deprecated-features.rst
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/install/software-hardware-requirements.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#6868 Playbooks typo
  source/repeatable-processes/work-with-playbooks.rst
Labels: 3: Reviews Complete, Contributor

#6827 V9.4 Docs
  source/comply/compliance-export.rst
  source/conf.py
  source/configure/compliance-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/deploy/deprecated-features.rst
  source/deploy/mattermost-changelog.md
  source/guides/prepare-for-your-mattermost-deployment.rst
  source/install/download-latest-tarball.rst
  source/install/manage_kubernetes.rst
  source/install/software-hardware-requirements.rst
  source/manage/common-support-packet.rst
  source/manage/mmctl-command-line-tool.rst
  source/manage/telemetry.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 3: Reviews Complete

#6871 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#6824 Mobile v2.12 changelog
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#6792 [CLD-6659] Add documentation for Cloud IP Filtering
  source/_static/badges/ent-cloud-only.rst
  source/guides/cloud-workspace-management.rst
  source/images/add-ip-filter-range.png
  source/images/enable-disable-ip-filtering.gif
  source/images/ip-address-not-in-filters.png
  source/images/system-console-ip-filtering.png
  source/manage/cloud-ip-filtering.rst
Labels: 3: Reviews Complete

#6814 [MM-55587] Add documentation for call transcriptions settings
  source/configure/calls-deployment.rst
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#6878 Update mattermost-changelog.md
  source/deploy/mattermost-changelog.md
Labels: 3: Reviews Complete

#6856 Corrected mattermost config get command example
  source/configure/configuation-in-a-database.rst
Labels: 3: Reviews Complete

#6884 Add known issues
  source/deploy/mattermost-changelog.md
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#6882 Correct typograph `member` in the disable-apps-bar item on configure disable-data-refetching-on-browser-refocus page
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete, Contributor

#6888 Add CTA to Slack import doc
  source/onboard/migrate-from-slack.rst
Labels: 3: Reviews Complete
