Repository mattermost/docs, pull requests merged in 2024-02, with the labels that each got.

#6889 Update for Nonprofit org over 1,000 users.rst
  source/about/subscription.rst
Labels: 3: Reviews Complete, Contributor

#6885 Update performance-monitoring.rst
  source/scale/performance-monitoring.rst
Labels: 3: Reviews Complete

#6808 Add exemple and clarification about encryption with data source
  source/configure/database-configuration-settings.rst
Labels: 3: Reviews Complete, Contributor

#6901 Clarified that system roles also control access to related API endpoints
  source/onboard/system-admin-roles.rst
Labels: 3: Reviews Complete

#6908 Added new error codes docs page + safety limit code
  source/guides/cloud-workspace-management.rst
  source/guides/self-hosted-administration.rst
  source/manage/error-codes.rst
Labels: 3: Reviews Complete

#6898 Removed "Sync" to align with product naming
  source/about/embed-mattermost-app-within-microsoft-teams.rst
  source/about/install-mattermost-for-microsoft-teams-plugin.rst
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#6906 Added link to Kubernetes YAML docs via mattermost repo
  source/install/install-kubernetes.rst
Labels: 3: Reviews Complete

#6897 Clarified supported AllowCorsFrom values
  source/configure/integrations-configuration-settings.rst
Labels: 3: Reviews Complete

#6910 Added transcription end user docs
  source/collaborate/make-calls.rst
Labels: 3: Reviews Complete

#6913 Added Message and File retention config settings for less than 1 day
  source/comply/data-retention-policy.rst
  source/configure/compliance-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#6914 Added ability to process import file without uploading it to the server
  source/onboard/run-bulk-loading-command.rst
Labels: 3: Reviews Complete

#6918 Adjust styles for yaml code block
  source/_static/mytheme.css
  source/conf.py
  source/install/faq_kubernetes.rst
  source/install/install-kubernetes.rst
Labels: 3: Reviews Complete

#6904 Changed "active" to "activated users" in majority of contexts.
  source/about/self-hosted-subscriptions.rst
  source/about/subscription.rst
  source/collaborate/learn-about-roles.rst
  source/configure/authentication-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/reporting-configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/configure/user-management-configuration-settings.rst
  source/deploy/legacy-cloud-changelog.md
  source/deploy/legacy-self-hosted-changelog.md
  source/manage/cloud-billing.rst
  source/manage/self-hosted-billing.rst
  source/manage/statistics.rst
  source/manage/telemetry.rst
  source/manage/workspace-usage.rst
  source/upgrade/installing-license-key.rst
Labels: 3: Reviews Complete

#6911 Dot release docs
  source/deploy/legacy-self-hosted-changelog.md
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#6912 Added OutgoingIntegrationRequestsDefaultTimeout config setting
  source/configure/integrations-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#6881 v9.5 Changelog
  source/deploy/deprecated-features.rst
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/prepare-to-upgrade-mattermost.rst
  source/upgrade/release-lifecycle.rst
  source/upgrade/version-archive.rst
Labels: 1: Dev Review, 1: PM Review

#6922 Update mmctl-command-line-tool.rst
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#6921 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#6879 v2.13 Mobile changelog
  source/deploy/mobile-app-changelog.md
Labels: 3: Reviews Complete

#6923 Update configuation-in-a-database.rst
  source/configure/configuation-in-a-database.rst
Labels: 3: Reviews Complete

#6925 Add changelog video
  source/deploy/mattermost-changelog.md
Labels: 3: Reviews Complete

#6932 Update editions-and-offerings to match pricing page changes
  source/about/editions-and-offerings.rst
Labels: 3: Reviews Complete

#6934 Updating for MME
  source/about/subscription.rst
Labels: 3: Reviews Complete

#6937 Help Wanted: Mattermost for Microsoft Teams documentation would benefit from updated GIFs
  source/about/mattermost-for-microsoft-teams.rst
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
  source/images/ms-teams-channel-sync-feb-2024.gif
  source/images/ms-teams-dm-sync-feb-2024.gif
Labels: 3: Reviews Complete, Area/Documentation Improvements

#6939 Update encryption options for calls
  source/deploy/encryption-options.rst
Labels: 3: Reviews Complete

#6940 Update install-mattermost-for-microsoft-teams-plugin.rst
  source/about/install-mattermost-for-microsoft-teams-plugin.rst
Labels: 3: Reviews Complete

#6944 Update nav structure and notification banner
  source/_static/myscript.js
  source/_static/mytheme.css
  source/conf.py
  source/templates/header.html
Labels: 3: Reviews Complete, preview-environment

#6945 fix: synced s3 files to remove outdated pages and corrected typo error
  .github/workflows/cd.yml
  source/collaborate/install-desktop-app.rst
  source/conf.py
  source/configure/configuration-settings.rst
  source/configure/environment-variables.rst
  source/getting-started/enterprise-roll-out-checklist.rst
  source/guides/self-hosted-administration.rst
  source/manage/mmctl-command-line-tool.rst
Labels: 1: Dev Review

#6946 CLD-7192: Follow up fix with typo on filename
  source/configure/configuration-in-a-database.rst
Labels: 1: Dev Review

#6895 [CLD-7064] Mattermost Operator + Helm Documentation Updates
  source/install/install-kubernetes.rst
Labels: 3: Reviews Complete, preview-environment

#6938 Appended Beta Label to MS Teams documentation
  source/about/embed-mattermost-app-within-microsoft-teams.rst
  source/about/install-mattermost-for-microsoft-teams-plugin.rst
  source/about/mattermost-for-microsoft-teams.rst
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
  source/collaborate/collaborate-within-embedded-microsoft-teams.rst
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete
