Repository mattermost/docs, pull requests merged in 2024-04, with the labels that each got.

#7010 Added guidance for max image decoder concurrency
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#7008 Added 2 new profiling reports: allocs & mutex
  source/scale/performance-monitoring.rst
Labels: 3: Reviews Complete

#7021 Update config-proxy-nginx.rst
  source/install/config-proxy-nginx.rst
Labels: 3: Reviews Complete

#7007 Adding a fix for highlight and table overflow
  source/_static/css/homepage-v1.css
  source/_static/css/homepage-v1.css.map
  source/_static/scss/partials/_blog.scss
  source/getting-started/architecture-overview.rst
Labels: 3: Reviews Complete

#7014 Deprecated legacy config settings & telemetry
  source/configure/deprecated-configuration-settings.rst
  source/configure/high-availability-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#7022 Added mmctl config set example
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#7032 Update important-upgrade-notes.rst
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#7051 Update release-lifecycle.rst
  source/upgrade/release-lifecycle.rst
Labels: 3: Reviews Complete

#7015 Clarify consequences of EmailBatchingBufferSize & EmailBatchingInterval config settings
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#7050 Added note for Omnibus & Ubuntu admins to update GPG key
  source/install/install-ubuntu.rst
  source/install/installing-mattermost-omnibus.rst
Labels: 3: Reviews Complete

#7062 Cleanup information about old Mattermost versions
  source/onboard/sso-saml-onelogin.rst
  source/scale/high-availability-cluster.rst
Labels: 3: Reviews Complete

#7055 MySQL Deprecation: Add system requirements and configration tips
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#6985 v9.7 changelog
  source/deploy/mattermost-changelog.md
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 3: Reviews Complete

#6980 V9.7 Docs
  source/collaborate/archive-unarchive-channels.rst
  source/collaborate/channel-types.rst
  source/collaborate/collaborate-within-channels.rst
  source/collaborate/convert-public-channels.rst
  source/collaborate/install-desktop-app.rst
  source/collaborate/join-leave-channels.rst
  source/collaborate/organize-conversations.rst
  source/comply/legal-hold.rst
  source/conf.py
  source/configure/calls-deployment.rst
  source/configure/deprecated-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/high-availability-configuration-settings.rst
  source/configure/integrations-configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/deploy/mattermost-changelog.md
  source/install/common-local-deploy-docker.rst
  source/install/download-latest-tarball.rst
  source/manage/common-support-packet.rst
  source/manage/generating-support-packet.rst
  source/manage/telemetry.rst
  source/preferences/manage-your-display-options.rst
  source/preferences/manage-your-notifications.rst
  source/preferences/set-your-status-availability.rst
  source/scale/performance-monitoring.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 3: Reviews Complete

#7076 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#7078 Add changelog video
  source/deploy/mattermost-changelog.md
Labels: 3: Reviews Complete

#7012 Added new disable cloud config setting for self-hosted deployments
  source/configure/environment-configuration-settings.rst
Labels: 3: Reviews Complete

#7023 Aligned docs to latest product UI
  source/collaborate/team-settings.rst
  source/images/edit-team-icon.png
  source/images/team-settings.png
Labels: 3: Reviews Complete

#7084 Update nav
  source/_static/css/mattermost-global.css
  source/_static/images/nav/logos/nav-logo-icon-amc.png
  source/_static/images/nav/logos/nav-logo-icon-cern.png
  source/_static/images/nav/logos/nav-logo-icon-crossover.png
  source/_static/images/nav/logos/nav-logo-icon-fujitsu.png
  source/_static/images/nav/logos/nav-logo-icon-netfoundry.png
  source/_static/images/nav/logos/nav-logo-icon-nri.png
  source/_static/images/nav/logos/nav-logo-icon-pramacom.png
  source/_static/images/nav/logos/nav-logo-icon-rte.png
  source/_static/images/nav/logos/nav-logo-icon-usaf.png
  source/_templates/custom-nav.html
Labels: 3: Reviews Complete

#7089 Update MySQL to Postgres documetnation
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#7090 IS-7052: Prefixing channel names with tilde (~) in product docs not clear
  source/guides/community-chat.rst
  source/guides/contribute-to-documentation.rst
Labels: 3: Reviews Complete, Contributor

#7093 IS-7047: Incorrect `incoming webhook` link on Mattermost Performance Alerting Guide Page
  source/scale/performance-alerting.rst
Labels: 3: Reviews Complete, Contributor

#7092 [GH-7075] Use the correct config object for EnableSecurityFixAlert
  source/configure/smtp-configuration-settings.rst
Labels: 3: Reviews Complete, Contributor

#7091 IS-7067: Keyboard Accessibility Screenshot doesn't represent user's product experience
  source/images/focus.png
Labels: 3: Reviews Complete, Contributor

#7094 CLD-7471 Document new GPG key location
  source/upgrade/version-archive.rst
Labels: 2: Editor Review

#7096 Correctly state that Off-Topic can get covered to a private channel
  source/collaborate/archive-unarchive-channels.rst
  source/collaborate/collaborate-within-channels.rst
  source/collaborate/convert-public-channels.rst
  source/getting-started/enterprise-roll-out-checklist.rst
  source/onboard/ad-ldap-groups-synchronization.rst
  source/onboard/user-provisioning-workflows.rst
Labels: 3: Reviews Complete

#6916 Added Metrics plugin
  source/about/editions-and-offerings.rst
  source/about/install-mattermost-for-microsoft-teams-plugin.rst
  source/conf.py
  source/configure/calls-deployment.rst
  source/configure/database-configuration-settings.rst
  source/configure/performance-monitoring-configuration-settings.rst
  source/configure/push-notification-server-configuration-settings.rst
  source/configure/web-server-configuration-settings.rst
  source/getting-started/enterprise-roll-out-checklist.rst
  source/getting-started/implementation-plan.rst
  source/guides/scale-mattermost.rst
  source/install/software-hardware-requirements.rst
  source/manage/statistics.rst
  source/scale/additional-ha-considerations.rst
  source/scale/collect-performance-metrics-using-metrics-plugin.rst
  source/scale/deploy-prometheus-grafana-for-performance-monitoring.rst
  source/scale/elasticsearch.rst
  source/scale/performance-alerting.rst
  source/scale/performance-monitoring-metrics.rst
Labels: 1: PM Review, Do Not Merge/Awaiting Next Release

#7095 IS-5923: Document Mattermost user administration workflows
  source/configure/user-management-configuration-settings.rst
  source/images/activate-user.png
  source/images/add-user-to-team.png
  source/images/deactivate-user.png
  source/images/find-users.png
  source/images/manage-roles.png
  source/images/remove-user-from-team.png
  source/images/revoke-user-session.png
  source/images/user-email-update.png
  source/images/user-id.png
  source/images/user-password-reset.png
  source/images/user-profile-details.png
  source/images/user-search-filters.png
Labels: 3: Reviews Complete, preview-environment, Contributor

#7083 Dot release docs
  source/deploy/legacy-self-hosted-changelog.md
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#7104 IS-6830: Plugin uploads and signatures not supported in Cloud deployments
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete, Contributor

#7087 Remove information regarding self serve, the portal, etc
  source/about/cloud-subscriptions.rst
  source/about/editions-and-offerings.rst
  source/about/self-hosted-subscriptions.rst
  source/about/subscription.rst
  source/collaborate/access-your-workspace.rst
  source/deploy/legacy-self-hosted-changelog.md
  source/install/enterprise-install-upgrade.rst
  source/manage/cloud-billing.rst
  source/manage/cloud-data-export.rst
  source/manage/cloud-ip-filtering.rst
Labels: 3: Reviews Complete

#7000 Update faq-product.rst
  source/about/faq-product.rst
Labels: 3: Reviews Complete

#7011 Added golden path guidance for the websocket URL config setting
  source/configure/web-server-configuration-settings.rst
Labels: 1: PM Review, 2. SME Review

#7107 Dot release docs
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete
