Repository mattermost/docs, pull requests merged in 2024-09, with the labels that each got.

#7362 Fix windows %appdata% path
  source/collaborate/install-desktop-app.rst
Labels: 3: Reviews Complete, Contributor

#7365 Use $host instead of $http_host
  source/install/config-proxy-nginx.rst
Labels: 3: Reviews Complete, Contributor

#7351 Login screenshot updates & code-block fix
  source/collaborate/access-your-workspace.rst
  source/images/login-ad.png
  source/images/login-email-username.png
  source/images/login-gitlab.png
  source/images/login-google.png
  source/images/login-office365.png
  source/images/login-onelogin.png
  source/install/prepare-mattermost-database.rst
Labels: 3: Reviews Complete

#7366 Updated config in DB migration process & updated page heading hierarchy
  source/deploy/manual-postgres-migration.rst
Labels: 3: Reviews Complete

#7374 [GH-7349] Using Product-Icon at Site-level
  source/collaborate/archive-unarchive-channels.rst
  source/collaborate/browse-channels.rst
  source/collaborate/channel-header-purpose.rst
  source/collaborate/channel-types.rst
  source/collaborate/chat-with-copilot.rst
  source/collaborate/collaborate-within-channels.rst
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
  source/collaborate/convert-group-messages.rst
  source/collaborate/convert-public-channels.rst
  source/collaborate/create-channels.rst
  source/collaborate/favorite-channels.rst
  source/collaborate/format-messages.rst
  source/collaborate/forward-messages.rst
  source/collaborate/install-desktop-app.rst
  source/collaborate/invite-people.rst
  source/collaborate/join-leave-channels.rst
  source/collaborate/make-calls.rst
  source/collaborate/manage-channel-members.rst
  source/collaborate/mark-channels-unread.rst
  source/collaborate/mark-messages-unread.rst
  source/collaborate/message-priority.rst
  source/collaborate/message-reminders.rst
  source/collaborate/organize-conversations.rst
  source/collaborate/organize-using-custom-user-groups.rst
  source/collaborate/organize-using-teams.rst
  source/collaborate/react-with-emojis-gifs.rst
  source/collaborate/rename-channels.rst
  source/collaborate/reply-to-messages.rst
  source/collaborate/save-pin-messages.rst
  source/collaborate/search-for-messages.rst
  source/collaborate/send-messages.rst
  source/collaborate/share-files-in-messages.rst
  source/collaborate/share-links.rst
  source/collaborate/team-settings.rst
  source/conf.py
  source/configure/user-management-configuration-settings.rst
  source/guides/contribute-to-documentation.rst
  source/images/channel-files-icon.svg
  source/install/desktop-custom-dictionaries.rst
  source/install/prepare-mattermost-mysql-database.rst
  source/integrate/github-interoperability.rst
  source/integrate/gitlab-interoperability.rst
  source/integrate/jira-interoperability.rst
  source/integrate/microsoft-teams-interoperability.rst
  source/integrate/servicenow-interoperability.rst
  source/integrate/zoom-interoperability.rst
  source/preferences/connect-multiple-workspaces.rst
  source/preferences/customize-desktop-app-experience.rst
  source/preferences/customize-your-channel-sidebar.rst
  source/preferences/customize-your-theme.rst
  source/preferences/manage-advanced-options.rst
  source/preferences/manage-your-display-options.rst
  source/preferences/manage-your-notifications.rst
  source/preferences/manage-your-sidebar-options.rst
  source/preferences/set-your-status-availability.rst
  source/repeatable-processes/notifications-and-updates.rst
  source/scale/collect-performance-metrics.rst
Labels: 3: Reviews Complete, Contributor

#7381 [GH-7380] Bugfix/move maximum payload size bytes
  source/configure/file-storage-configuration-settings.rst
  source/configure/web-server-configuration-settings.rst
Labels: 3: Reviews Complete, Contributor

#7382 Add support link for playbooks-for-microsoft-teams.rst
  source/integrate/playbooks-for-microsoft-teams.rst
Labels: 1: Dev Review

#7385 Add experimental labelling to MM playbooks for teams page
  source/integrate/playbooks-for-microsoft-teams.rst
Labels: 3: Reviews Complete

#7383 Fix typo
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
Labels: 3: Reviews Complete

#7394 Playbooks v1 vs v2 clarifications
  source/guides/repeatable-processes.rst
Labels: 3: Reviews Complete

#7345 v10.0 changelog
  source/about/deprecated-features.rst
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/install/download-latest-tarball.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#7389 Added shard replica guidance for Channel, Post, and User
  source/configure/elasticsearch-configuration-settings.rst
Labels: 3: Reviews Complete

#7379 Docs listening v10 enhancements
  source/collaborate/install-desktop-app.rst
  source/configure/deprecated-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/rate-limiting-configuration-settings.rst
  source/configure/user-management-configuration-settings.rst
  source/manage/mmctl-command-line-tool.rst
  source/preferences/set-your-status-availability.rst
Labels: 3: Reviews Complete

#7388 Added DND/outside reg hours warning for DMs
  source/collaborate/channel-types.rst
  source/collaborate/send-messages.rst
Labels: 3: Reviews Complete

#7391 Added MaximumPayloadSizeBytes config setting
  source/configure/web-server-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#7392 Clarify availability of Playboks for Teams
  source/integrate/playbooks-for-microsoft-teams.rst
Labels: 3: Reviews Complete

#7398 Clarified the need to purge before indexing
  source/configure/elasticsearch-configuration-settings.rst
  source/scale/elasticsearch.rst
Labels: 3: Reviews Complete

#7387 Doc'd prepkg'd plugin install paths & cloud-available list
  source/about/cloud-dedicated.rst
  source/about/cloud-shared.rst
  source/about/cloud-supported-integrations.rst
  source/about/integrations.rst
  source/conf.py
  source/configure/manage-user-surveys.rst
  source/guides/integrate-and-extend.rst
  source/integrate/microsoft-calendar-interoperability.rst
  source/integrate/microsoft-teams-interoperability.rst
  source/integrate/microsoft-teams-meetings-interoperability.rst
Labels: 3: Reviews Complete

#7395 Calls updates for v10
  source/collaborate/make-calls.rst
  source/configure/calls-deployment.rst
  source/configure/reporting-configuration-settings.rst
  source/guides/preferences.rst
  source/preferences/customize-your-channel-sidebar.rst
  source/preferences/customize-your-theme.rst
  source/preferences/manage-advanced-options.rst
  source/preferences/manage-your-calls-preferences.rst
  source/preferences/manage-your-display-options.rst
  source/preferences/manage-your-sidebar-options.rst
Labels: 3: Reviews Complete

#7342 V10.0 Docs
  source/about/cloud-dedicated.rst
  source/about/cloud-shared.rst
  source/about/cloud-supported-integrations.rst
  source/about/deprecated-features.rst
  source/about/faq-license.rst
  source/about/integrations.rst
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/collaborate/channel-types.rst
  source/collaborate/install-desktop-app.rst
  source/collaborate/make-calls.rst
  source/collaborate/send-messages.rst
  source/conf.py
  source/configure/calls-deployment.rst
  source/configure/deprecated-configuration-settings.rst
  source/configure/elasticsearch-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/manage-user-surveys.rst
  source/configure/rate-limiting-configuration-settings.rst
  source/configure/reporting-configuration-settings.rst
  source/configure/user-management-configuration-settings.rst
  source/configure/web-server-configuration-settings.rst
  source/deploy/mobile-faq.rst
  source/guides/integrate-and-extend.rst
  source/guides/preferences.rst
  source/guides/repeatable-processes.rst
  source/install/download-latest-tarball.rst
  source/integrate/microsoft-calendar-interoperability.rst
  source/integrate/microsoft-teams-interoperability.rst
  source/integrate/microsoft-teams-meetings-interoperability.rst
  source/integrate/playbooks-for-microsoft-teams.rst
  source/manage/common-support-packet.rst
  source/manage/mmctl-command-line-tool.rst
  source/manage/telemetry.rst
  source/preferences/customize-your-channel-sidebar.rst
  source/preferences/customize-your-theme.rst
  source/preferences/manage-advanced-options.rst
  source/preferences/manage-your-calls-preferences.rst
  source/preferences/manage-your-display-options.rst
  source/preferences/manage-your-sidebar-options.rst
  source/preferences/set-your-status-availability.rst
  source/scale/deploy-prometheus-grafana-for-performance-monitoring.rst
  source/scale/elasticsearch.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
Labels: 3: Reviews Complete

#7396 Update version-archive.rst
  source/about/version-archive.rst
Labels: 3: Reviews Complete

#7343 Mobile v2.20 changelog
  source/about/mattermost-mobile-releases.md
  source/about/mobile-app-changelog.md
Labels: 3: Reviews Complete

#7167 Update docs for multi-bot LLM and name change.
  source/collaborate/chat-with-copilot.rst
  source/configure/enable-copilot.rst
  source/images/multi-llm-copilot.png
Labels: 3: Reviews Complete

#7299 Add FAQ to the mysql deprecation
  source/deploy/manual-postgres-migration.rst
  source/deploy/postgres-migration-assist-tool.rst
  source/deploy/postgres-migration.rst
Labels: 2: Editor Review

#7402 Fix broken link
  source/about/mattermost-mobile-releases.md
  source/about/mattermost-server-releases.md
Labels: 3: Reviews Complete

#7404 MD syntax corrections for broken links
  source/about/mattermost-mobile-releases.md
  source/about/mattermost-server-releases.md
Labels: 3: Reviews Complete

#7406 Updated true/false descriptions
  source/configure/authentication-configuration-settings.rst
Labels: 3: Reviews Complete

#7405 Added experiental AV1 config setting
  source/configure/plugins-configuration-settings.rst
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#7410 Update notification banner for Sept v10 launch
  source/_static/js/myscript-v1.js
  source/_templates/custom-nav.html
Labels: 3: Reviews Complete, preview-environment

#7412 Add changelog video
  source/about/mattermost-v10-changelog.md
Labels: 3: Reviews Complete

#7409 Add 'ensuring releases perform at scale' doc
  source/guides/scale-mattermost.rst
  source/scale/ensuring-releases-perform-at-scale.rst
Labels: 1: PM Review

#7417 [MM-57194_github]: Added note to copy secrets as they will not be visible again
  source/integrate/github-interoperability.rst
Labels: 3: Reviews Complete

#7386 Dot release docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v9-changelog.md
  source/about/version-archive.rst
  source/install/download-latest-tarball.rst
Labels: 3: Reviews Complete

#7432 Update dot release changelog notes
  source/about/mattermost-v9-changelog.md
Labels: 3: Reviews Complete

#7431 Packaging Clarifications for Calls & Playbooks
  source/about/mattermost-v10-changelog.md
  source/guides/repeatable-processes.rst
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#7434 Moved appcustomurlschemes from experimental to site config
  source/configure/experimental-configuration-settings.rst
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete
