Repository mattermost/docs, pull requests merged in 2024-11, with the labels that each got.

#7527 DOC-7526: Communicate a channel’s focus and scope page needs animated…
  source/collaborate/channel-header-purpose.rst
  source/images/mobile-update-channel-header.jpg
  source/images/mobile-update-channel-purpose.jpg
Labels: Hacktoberfest, 2: Editor Review, preview-environment, Contributor

#7532 DOC-7531: Join and leave channels page needs animated GIFs for mobile app workflows
  source/collaborate/join-leave-channels.rst
  source/images/mobile-browse-public-channels.jpg
  source/images/mobile-confirm-leave-a-channel.jpg
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7530 DOC-7528: Convert public channels to private channels page needs animated GIFs for mobile app workflows
  source/collaborate/convert-public-channels.rst
  source/images/mobile-confirm-convert-to-private-channel.jpg
  source/images/mobile-convert-to-private-channel.jpg
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7534 Highlight configuration in DB for migration-assist
  source/deploy/postgres-migration-assist-tool.rst
Labels: 3: Reviews Complete

#7535 DOC-7533: Manage channel members page needs animated GIFs for mobile app workflows
  source/collaborate/manage-channel-members.rst
  source/conf.py
  source/images/account-plus-outline_F0801.svg
  source/images/add-member-pop.jpg
  source/images/add-member-pop.png
  source/images/mobile-add-selected-member-to-a-channel.jpg
  source/images/mobile-add-user-from-profile.jpg
  source/images/mobile-add-user-to-a-channel-by-mentioning.jpg
  source/images/mobile-channel-name-click.jpg
  source/images/mobile-confirm-remove-user-from-channel.jpg
  source/images/mobile-exit-after-removing-user-from-a-channel.jpg
  source/images/mobile-manage-channel-members-list.jpg
  source/images/mobile-remove-user-from-a-channel.jpg
  source/images/mobile-select-members-to-add-to-a-channel.jpg
  source/images/mobile-view-members-of-a-channel.jpg
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7537 DOC-7536: Browse channels page needs animated GIFs for mobile app workflows
  source/collaborate/browse-channels.rst
  source/images/mobile-browse-public-channels-using-filters.jpg
  source/images/mobile-browse-public-channels-using-search.jpg
Labels: 3: Reviews Complete, Contributor, QA-done

#7546 DOC-7538: Mark channels as favorites page needs animated GIFs for mobile app workflows
  source/collaborate/favorite-channels.rst
  source/images/mobile-favorite-a-channel-within-channel.jpg
  source/images/mobile-unfavorite-a-channel-from-within-the-channel.jpg
  source/images/mobile-unfavorite-a-channel.jpg
Labels: 3: Reviews Complete, Contributor, QA-done

#7547 DOC-7539: Manage channel bookmarks page needs animated GIFs for mobile app workflows
  source/collaborate/manage-channel-bookmarks.rst
  source/images/mobile-add-first-channel-bookmark.jpg
  source/images/mobile-add-subsequent-channel-bookmarks.jpg
  source/images/mobile-attach-a-channel-bookmark-file.jpg
  source/images/mobile-attach-a-channel-bookmark-link.jpg
  source/images/mobile-bookmark-add-choice.png
  source/images/mobile-bookmark-add-details.png
  source/images/mobile-bookmark-add.png
  source/images/mobile-copy-a-channel-bookmark-link.gif
  source/images/mobile-delete-a-channel-bookmark.gif
  source/images/mobile-edit-a-channel-bookmark.gif
Labels: 3: Reviews Complete, Contributor

#7555 DOC-7551: Archive and unarchive channels page needs animated GIFs for mobile app workflows
  source/collaborate/archive-unarchive-channels.rst
  source/images/mobile-confirm-archive-a-channel.jpg
  source/images/mobile-confirm-unarchive-a-channel.jpg
  source/images/mobile-unarchive-a-channel.jpg
Labels: 3: Reviews Complete, Contributor

#7558 DOC-7552: Convert group messages to private channels page needs animated GIFs for mobile app workflows
  source/collaborate/convert-group-messages.rst
  source/images/mobile-convert-group-to-private-channel.jpg
  source/images/mobile-provide-private-channel-name-for-the-group.jpg
  source/images/mobile-select-a-group-message.jpg
  source/images/mobile-select-more-options-for-a-group.jpg
  source/images/mobile-select-view-info-for-a-group.jpg
Labels: 3: Reviews Complete, Contributor

#7550 DOC-4173: Clarify how to use mmctl with non-email authentication systems
  source/images/edit-on-github.png
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete, Contributor

#7513 Removed Cloud deploy badge
  source/configure/calls-deployment.rst
Labels: 3: Reviews Complete

#7514 Desktop v5.10: Removed full screen mode on Linux
  source/deploy/postgres-migration.rst
  source/preferences/customize-desktop-app-experience.rst
Labels: 3: Reviews Complete

#7516 Replaced Calls plugin prefs with general page
  source/collaborate/make-calls.rst
  source/conf.py
  source/guides/preferences.rst
  source/preferences/manage-your-calls-preferences.rst
  source/preferences/manage-your-plugin-preferences.rst
Labels: 3: Reviews Complete

#7517 Updated End Call for All to server v10.2
  source/collaborate/make-calls.rst
Labels: 3: Reviews Complete

#7518 Updated list of exported data
  source/manage/bulk-export-tool.rst
Labels: 3: Reviews Complete

#7519 Pinned icon hidden when no messages pinned in channel
  source/collaborate/save-pin-messages.rst
  source/conf.py
  source/images/pin-outline_F0931.svg
Labels: 3: Reviews Complete

#7520 Added release details for MobileExternalBrowser
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete

#7561 Clarified that LDAP users can't be deactivated via MM
  source/configure/user-management-configuration-settings.rst
Labels: 3: Reviews Complete

#7521 Docs listening: Added menu option to access logs
  source/install/troubleshooting.rst
Labels: 3: Reviews Complete

#7563 Added EnableAPIPostDeletion config setting & mmctl command
  source/configure/environment-configuration-settings.rst
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#7573 DOC-7570: Share links to channels and messages page needs animated GIFs for mobile app workflows
  source/collaborate/share-links.rst
  source/images/mobile-copy-a-link-to-the-message.gif
Labels: 3: Reviews Complete, Contributor

#7572 DOC-7569: Mark messages as unread page needs animated GIFs for mobile app workflows
  source/collaborate/mark-messages-unread.rst
  source/images/mobile-mark-a-message-as-unread.gif
Labels: 3: Reviews Complete, Contributor

#7574 DOC-7571: Share files in messages page needs animated GIFs for mobile app workflows
  source/collaborate/share-files-in-messages.rst
  source/images/mobile-attach-a-file-to-send-in-a-channel.gif
  source/images/mobile-edit-channel.jpg
  source/images/mobile-more-options-to-download-or-view-a-file.jpg
  source/images/mobile-tap-a-file-name-to-download.jpg
Labels: 3: Reviews Complete, Contributor

#7420 [MM-57194_servicenow]: Added note to copy secrets as they will not be visible again
  source/integrate/servicenow-interoperability.rst
Labels: 3: Reviews Complete

#7419 [MM-57194_zoom]: Added note to copy secrets as they will not be visible again
  source/integrate/zoom-interoperability.rst
Labels: 3: Reviews Complete

#7418 [MM-57194_gitlab]: Added note to copy secrets as they will not be visible again
  source/integrate/gitlab-interoperability.rst
Labels: 3: Reviews Complete

#7586 Added PG FAQs based on customer input
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#7515 Added env var developer mode setting
  source/configure/environment-configuration-settings.rst
Labels: 3: Reviews Complete

#7554 Added upgrade & maintenance guidance for plugins
  source/guides/integrate-and-extend.rst
  source/integrate/microsoft-calendar-interoperability.rst
  source/integrate/microsoft-teams-interoperability.rst
  source/integrate/microsoft-teams-meetings-interoperability.rst
  source/integrate/servicenow-interoperability.rst
Labels: 3: Reviews Complete

#7559 Config in database corrections
  source/configure/configuration-in-your-database.rst
Labels: 3: Reviews Complete

#7580 DOC-7577: Save and pin messages page needs animated GIFs for mobile app workflows
  source/collaborate/save-pin-messages.rst
  source/conf.py
  source/images/bookmark_F00C0.svg
  source/images/mobile-edit-channel.jpg
  source/images/mobile-pin-a-message-to-the-channel.gif
  source/images/mobile-save-a-message.gif
  source/images/mobile-unpin-a-message-from-pinned-messages.gif
  source/images/mobile-unpin-a-message-from-the-channel.gif
  source/images/mobile-unsave-a-message-from-saved-messages.gif
  source/images/mobile-unsave-a-message-from-the-channel.gif
  source/images/mobile-view-saved-messages.gif
  source/images/mobile-view-the-pinned-message-in-the-pinned-messages-list.jpg
Labels: 2: Editor Review, preview-environment, Contributor

#7582 Docs listening: Updated language & added docs link
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#7583 Docs listening: Clarified the path config for the ES certificate
  source/configure/environment-configuration-settings.rst
Labels: 3: Reviews Complete

#7584 Added mobile workflow
  source/collaborate/chat-with-copilot.rst
Labels: 3: Reviews Complete

#7585 Added Playbooks FAQs based on customer feedback
  source/repeatable-processes/learn-about-playbooks.rst
  source/repeatable-processes/work-with-playbooks.rst
  source/repeatable-processes/work-with-runs.rst
  source/repeatable-processes/work-with-tasks.rst
Labels: 3: Reviews Complete

#7587 Docs listening: Added custom emoji screenshot
  source/collaborate/react-with-emojis-gifs.rst
  source/images/add-custom-emoji1.png
Labels: 3: Reviews Complete

#7566 DOC-7565: Reply to messages page needs animated GIFs for mobile app workflows
  source/collaborate/reply-to-messages.rst
  source/images/mobile-reply-to-a-message-by-tapping-on-it.gif
  source/images/mobile-reply-to-a-message-using-reply.gif
Labels: 3: Reviews Complete, Contributor

#7549 Refactor config.json settings tables in configuration-settings.rst files to remove horizontal bars
  source/configure/authentication-configuration-settings.rst
  source/configure/environment-configuration-settings.rst
  source/configure/plugins-configuration-settings.rst
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete, Contributor

#7497 v10.2 Changelog
  source/about/deprecated-features.rst
  source/about/mattermost-desktop-releases.md
  source/about/mattermost-mobile-releases.md
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/release-policy.md
  source/about/version-archive.rst
  source/install/download-latest-tarball.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/prepare-to-upgrade-mattermost.rst
Labels: 1: Dev Review, 1: PM Review

#7595 Update send-messages.rst
  source/collaborate/send-messages.rst
Labels: 3: Reviews Complete

#7588 Docs listening: Added guidance on using team-URL over display name
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#7589 Replaced YES with standard green checkmarks
  source/about/cloud-subscriptions.rst
Labels: 3: Reviews Complete

#7592 Docs listening: Elevate comply and secure topics to align with scale
  source/about/faq-integrations.rst
  source/about/faq-video-audio-screensharing.rst
  source/guides/compliance-with-mattermost.rst
  source/guides/deployment.rst
  source/guides/get-started-with-administration.rst
  source/guides/secure-mattermost.rst
  source/guides/self-hosted-administration.rst
  source/guides/server-deployment.rst
  source/onboard/certificate-based-authentication.rst
Labels: 3: Reviews Complete

#7593 DOC-7579: Send messages page needs animated GIFs and tabbed sections for mobile app workflows
  source/collaborate/send-messages.rst
  source/conf.py
  source/images/mobile-confirm-delete-a-message.jpg
  source/images/mobile-delete-a-message.gif
  source/images/mobile-draft-a-message.gif
  source/images/mobile-edit-a-message.gif
  source/images/mobile-editing-a-message.jpg
  source/images/mobile-sending-a-message.gif
  source/images/mobile-type-a-message-in-a-channel.jpg
  source/images/pencil-outline_F0CB6.svg
Labels: 3: Reviews Complete, Contributor

#7596 Clarified that admins can perform any actions on a system
  source/collaborate/learn-about-roles.rst
Labels: 3: Reviews Complete

#7542 Dot release docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/version-archive.rst
  source/install/download-latest-tarball.rst
Labels: 3: Reviews Complete

#7529 Notification Troubleshooting via nested tabbed content
  source/_static/css/mattermost-global.css
  source/images/desktop-notification-check.gif
  source/images/desktop-server-notification-check.gif
  source/preferences/manage-your-notifications.rst
  source/preferences/troubleshoot-notifications.rst
Labels: 3: Reviews Complete, QA-done

#7575 Connected workspaces rewrites & updates for Beta release
  source/about/editions-and-offerings.rst
  source/about/subscription.rst
  source/conf.py
  source/configure/deprecated-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/reporting-configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/guides/get-started-with-administration.rst
  source/images/circle-multiple-outline_F0695.svg
  source/manage/telemetry.rst
  source/onboard/connected-workspaces.rst
  source/onboard/shared-channels.rst
Labels: 1: Dev Review

#7562 Added best practice recommendations re: attributes & identifiers
  source/onboard/ad-ldap.rst
Labels: 3: Reviews Complete

#7594 Update version-archive.rst
  source/about/version-archive.rst
Labels: 3: Reviews Complete

#7503 MM-50347 Add documentation for EnableDesktopLandingPage setting
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete

#7543 add new telemetry events for features behind a SKU
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#7591 Fix navigation not closing on large screens
  source/_static/js/myscript-v1.js
Labels: 3: Reviews Complete, Contributor

#7495 Desktop v5.10 changelog
  source/about/desktop-app-changelog.md
  source/about/mattermost-desktop-releases.md
  source/collaborate/install-desktop-app.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
  source/install/software-hardware-requirements.rst
Labels: 3: Reviews Complete

#7601 Update deprecated-features.rst
  source/about/deprecated-features.rst
Labels: 1: Dev Review

#7602 Update deprecated-features.rst
  source/about/deprecated-features.rst
Labels: 1: Dev Review

#7606 Adding Academy & Marketing asset links contextually
  source/_static/badges/academy-calls.rst
  source/_static/badges/academy-playbooks.rst
  source/_static/badges/academy-teams.rst
  source/about/devops-collaboration.rst
  source/about/incident-response-collaboration.rst
  source/about/maximize-microsoft-investment.rst
  source/about/secure-command-and-control.rst
  source/about/use-cases.rst
  source/collaborate/chat-with-copilot.rst
  source/collaborate/collaborate-with-audio-video.rst
  source/configure/enable-copilot.rst
  source/configure/plugins-configuration-settings.rst
  source/deploy/mobile-overview.rst
  source/guides/preferences.rst
  source/guides/repeatable-processes.rst
  source/integrate/gitlab-interoperability.rst
  source/integrate/jira-interoperability.rst
  source/integrate/servicenow-interoperability.rst
  source/preferences/manage-your-plugin-preferences.rst
  source/repeatable-processes/learn-about-playbooks.rst
  source/repeatable-processes/work-with-playbooks.rst
Labels: Work In Progress

#7614 DOC-7578: Search for messages page needs animated GIFs for mobile app workflows
  source/collaborate/search-for-messages.rst
  source/images/mobile-search-for-messages.jpg
  source/images/mobile-search-message-criteria-with-hashtags.jpg
  source/images/mobile-search-message-results.jpg
  source/images/mobile-search-message-team-selection.jpg
  source/images/mobile-search-message-with-modifiers.jpg
Labels: 3: Reviews Complete, Contributor

#7611 DOC-7576: Organize conversations using threaded discussions page needs animated GIFs for mobile app workflows
  source/collaborate/organize-conversations.rst
  source/images/desktop-unfollow-message-thread.jpg
  source/images/mobile-follow-a-message-thread-by-tapping-follow.gif
  source/images/mobile-follow-a-message-thread-with-follow-option.gif
  source/images/mobile-follow-a-message-with-no-replies.gif
  source/images/mobile-unfollow-a-message-thread-by-tapping-following.gif
  source/images/mobile-unfollow-a-message-thread-with-unfollow-option.gif
Labels: 3: Reviews Complete, Contributor
