Repository mattermost/docs, pull requests merged in 2024-10, with the labels that each got.

#7433 Rolled back deprecation of API deletion config settings
  source/configure/deprecated-configuration-settings.rst
  source/configure/environment-configuration-settings.rst
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#7435 Updated as per Issue #7428
  source/collaborate/install-desktop-app.rst
Labels: 3: Reviews Complete, Hacktoberfest, Hacktoberfest-accepted, Contributor

#7438 Update banner for Hacktoberfest announce
  source/_static/js/myscript-v1.js
  source/_templates/custom-nav.html
Labels: 3: Reviews Complete

#7441 fix version number
  source/scale/elasticsearch.rst
Labels: 3: Reviews Complete

#7411 Update legal hold plugin installation, setup, & usage
  source/comply/legal-hold.rst
  source/images/legal-hold-secret.png
  source/images/legal-holds.png
Labels: 3: Reviews Complete

#7448 Fix Issue 7447 config-tls-mattermost.rst
  source/install/config-tls-mattermost.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#7397 Added v2 reference architecture details
  source/conf.py
  source/deploy/postgres-migration.rst
  source/guides/scale-mattermost.rst
  source/scale/scale-to-100-users.rst
  source/scale/scale-to-1000-users.rst
  source/scale/scale-to-100000-users.rst
  source/scale/scale-to-15000-users.rst
  source/scale/scale-to-200-users.rst
  source/scale/scale-to-2000-users.rst
  source/scale/scale-to-25000-users.rst
  source/scale/scale-to-30000-users.rst
  source/scale/scale-to-70000-users.rst
  source/scale/scale-to-79000-users.rst
  source/scale/scale-to-80000-users.rst
  source/scale/scale-to-88000-users.rst
  source/scale/scale-to-90000-users.rst
  source/scale/scaling-for-enterprise.rst
Labels: 3: Reviews Complete

#7462 Clarification on Playbooks in Mattermost v10
  source/about/mattermost-v10-changelog.md
  source/guides/repeatable-processes.rst
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#7442 Mobile dot release docs
  source/about/mattermost-mobile-releases.md
  source/about/mobile-app-changelog.md
Labels: 3: Reviews Complete

#7439 Dot release docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/version-archive.rst
  source/install/download-latest-tarball.rst
Labels: 3: Reviews Complete

#7413 Improve Copilot + local AI setup instructions
  source/_static/badges/academy-copilot-setup.rst
  source/configure/enable-copilot.rst
Labels: 3: Reviews Complete

#7473 Copilot prepackaged with server
  source/about/editions-and-offerings.rst
  source/collaborate/extend-mattermost-with-integrations.rst
  source/configure/enable-copilot.rst
  source/guides/repeatable-processes.rst
Labels: 3: Reviews Complete

#7474 Updated minimum PostgreSQL version from 11 to 12
  source/install/common-prod-deploy-omnibus.rst
  source/install/common-prod-deploy-tar.rst
  source/install/install-rhel-7-postgresql.rst
  source/install/install-rhel-8-postgresql.rst
  source/install/install-rhel-8.rst
  source/install/install-tar.rst
  source/install/install-ubuntu-2004-postgresql.rst
  source/install/install-ubuntu.rst
  source/install/installing-mattermost-omnibus.rst
  source/install/trouble-postgres.rst
  source/install/troubleshooting.rst
Labels: 3: Reviews Complete

#7477 Improved consistency using: workspace, instance, & deployment
  source/about/cloud-dedicated.rst
  source/about/cloud-shared.rst
  source/about/cloud-subscriptions.rst
  source/about/cloud-vpc-private-connectivity.rst
  source/about/faq-enterprise.rst
  source/collaborate/access-your-workspace.rst
  source/collaborate/built-in-slash-commands.rst
  source/collaborate/collaborate-within-channels.rst
  source/collaborate/invite-people.rst
  source/collaborate/organize-using-custom-user-groups.rst
  source/collaborate/organize-using-teams.rst
  source/collaborate/react-with-emojis-gifs.rst
  source/collaborate/search-for-messages.rst
  source/collaborate/share-files-in-messages.rst
  source/comply/export-mattermost-channel-data.rst
  source/comply/legal-hold.rst
  source/configure/authentication-configuration-settings.rst
  source/configure/cloud-billing-account-settings.rst
  source/configure/configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/manage-user-surveys.rst
  source/configure/optimize-your-workspace.rst
  source/configure/reporting-configuration-settings.rst
  source/configure/self-hosted-account-settings.rst
  source/configure/user-management-configuration-settings.rst
  source/guides/administration.rst
  source/guides/cloud-workspace-management.rst
  source/guides/self-hosted-administration.rst
  source/guides/use-mattermost.rst
  source/integrate/microsoft-calendar-interoperability.rst
  source/integrate/microsoft-teams-interoperability.rst
  source/integrate/microsoft-teams-meetings-interoperability.rst
  source/manage/bulk-export-data.rst
  source/manage/logging.rst
  source/manage/telemetry.rst
  source/onboard/guest-accounts.rst
  source/onboard/shared-channels.rst
  source/preferences/manage-your-display-options.rst
  source/recipes/product-vulnerability-incident.rst
  source/scale/collect-performance-metrics.rst
Labels: 3: Reviews Complete

#7478 Added note for account creation config setting
  source/configure/authentication-configuration-settings.rst
Labels: 3: Reviews Complete

#7479 Added per-channel notification sound preference
  source/preferences/manage-your-channel-specific-notifications.rst
Labels: 3: Reviews Complete

#7449 [MM-45894] Add documentation for Calls EnableDCSignaling setting
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#7451 feature/7053-fix-search-special-chars
  source/_static/js/mattermost-search.js
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7445 Feature: User satisfaction survey plugin config
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7466 Fix Acknowledgement icons in Dark Mode
  source/conf.py
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7444 Fix blank page when initiating a search with no search criteria
  source/_templates/search.html
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7452 Added bookmarks docs & permissions
  source/collaborate/collaborate-within-channels.rst
  source/collaborate/learn-about-roles.rst
  source/collaborate/manage-channel-bookmarks.rst
  source/images/desktop-bookmark-add-choice.png
  source/images/desktop-bookmark-add-details.png
  source/images/desktop-bookmark-add.png
  source/images/mobile-bookmark-add-choice.png
  source/images/mobile-bookmark-add-details.png
  source/images/mobile-bookmark-add.png
  source/manage/team-channel-members.rst
  source/onboard/advanced-permissions-backend-infrastructure.rst
Labels: 1: Dev Review

#7488 Addressed team management docs gaps
  source/collaborate/organize-using-teams.rst
  source/configure/user-management-configuration-settings.rst
Labels: 3: Reviews Complete

#7407 Mobile v2.21 Changelog
  source/about/mattermost-mobile-releases.md
  source/about/mobile-app-changelog.md
Labels: 3: Reviews Complete

#7461 Update deprecated configuration settings documentation
  source/configure/deprecated-configuration-settings.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7490 docs: add information about inviting present members
  source/collaborate/invite-people.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7489 DOC-7453: Document New Server Configuration Setting- Mobile External Browser
  source/configure/site-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7475 Feature: Access conversations with deactivated users
  source/collaborate/channel-types.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7492 DOC-6760: Add a Note for the DataSource sslmode property in the Insta…
  source/install/install-ubuntu.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7481 Update share-links.rst
  source/collaborate/share-links.rst
Labels: Hacktoberfest, preview-environment, Contributor, QA-done

#7421 [MM-57194_msteams]: Added note to copy secrets as they will not be visible again
  source/integrate/microsoft-teams-interoperability.rst
Labels: 3: Reviews Complete

#7501 DOC-7500: Invite People page needs animated GIFs for mobile app workflows
  source/collaborate/invite-people.rst
  source/images/direct-mobile-invite-by-email.jpg
  source/images/direct-mobile-invite-by-name.jpg
  source/images/direct-mobile-invite-by-share-link.jpg
  source/images/direct-mobile-invite-options.jpg
  source/images/direct-mobile-invite.jpg
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7505 Updated plugins-configuration-settings.rst to address issue #7423
  source/collaborate/search-for-messages.rst
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7507 Updated Opensearch guidance for clarity
  source/about/mattermost-v9-changelog.md
  source/configure/elasticsearch-configuration-settings.rst
  source/scale/elasticsearch.rst
  source/upgrade/important-upgrade-notes.rst
Labels: 1: Dev Review, 3: Reviews Complete

#7509 DOC-7455: Remove 4 experimental configuration settings that are no lo…
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor, QA-done

#7508 Feature: Client/Server url schemas limitations for custom mobile apps
  source/deploy/build-custom-mobile-apps.rst
Labels: 3: Reviews Complete, Hacktoberfest, preview-environment, Contributor, QA-done

#7510 mysql deprecation: add more troubleshooting steps
  source/deploy/postgres-migration.rst
Labels: 1: Dev Review

#7499 Dot release docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/version-archive.rst
  source/install/download-latest-tarball.rst
Labels: 3: Reviews Complete

#7512 Feature: Product feature breakdown table reformat
  source/about/faq-product.rst
Labels: 3: Reviews Complete, Hacktoberfest, Contributor

#7525 DOC-7524: Rename channels page needs animated GIFs for mobile app workflows
  source/collaborate/rename-channels.rst
  source/images/mobile-edit-channel.jpg
  source/images/mobile-rename-channel-name-and-save.jpg
  source/images/mobile-select-a-channel.jpg
  source/images/mobile-select-more-options-for-a-channel.jpg
  source/images/mobile-select-view-info-for-a-channel.jpg
Labels: Hacktoberfest, preview-environment, Contributor, QA-done
