Repository mattermost/docs, pull requests merged in 2024-06, with the labels that each got.

#7153 Dot release docs
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/upgrade/extended-support-release.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#7163 postgres-migration: add remove-null-characters to prevent errors
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#7168 Make curl output silent
  source/collaborate/install-desktop-app.rst
Labels: 1: Dev Review

#7169 Update collaborate.rst
  source/guides/collaborate.rst
Labels: 3: Reviews Complete

#7177 Removed v7.9 & later true-up workflow
  source/about/self-hosted-subscriptions.rst
Labels: 3: Reviews Complete

#7179 Added DisableWakeUpReconnectHandler config setting
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#7194 Added note to close desktop app before installing via MSI
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#7188 Added FAQ for MM sub-path deploy
  source/install/config-ssl-http2-nginx.rst
  source/install/setup-nginx-proxy.rst
Labels: 3: Reviews Complete

#7150 Updates in the gitlab, servicenow and jira plugin documentation after migration
  source/integrate/gitlab-interoperability.rst
  source/integrate/jira-interoperability.rst
  source/integrate/servicenow-interoperability.rst
Labels: 3: Reviews Complete

#7190 Prioritized Enterprise offerings first over others
  source/about/editions-and-offerings.rst
  source/about/self-hosted-subscriptions.rst
  source/about/subscription.rst
  source/collaborate/message-priority.rst
  source/collaborate/send-messages.rst
  source/configure/site-configuration-settings.rst
  source/deploy/build-custom-mobile-apps.rst
  source/deploy/legacy-cloud-changelog.md
  source/deploy/legacy-self-hosted-changelog.md
  source/deploy/mattermost-changelog.md
  source/deploy/mobile-faq.rst
  source/getting-started/admin-onboarding-tasks.rst
  source/getting-started/implementation-plan.rst
  source/guides/get-help.rst
  source/guides/get-started-with-administration.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
  source/install/enterprise-install-upgrade.rst
  source/integrate/jira-interoperability.rst
  source/manage/self-hosted-billing.rst
  source/onboard/advanced-permissions.rst
  source/onboard/sso-gitlab.rst
  source/recipes/product-vulnerability-incident.rst
  source/repeatable-processes/share-and-collaborate.rst
  source/upgrade/installing-license-key.rst
Labels: 3: Reviews Complete

#7176 Added live captioning end user docs & updated calls search metadata
  source/collaborate/make-calls.rst
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#7183 Noted that require plugin signature disables file upload
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#7184 Clarified wording re: migration window
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#7202 Added FAQ re: enabling calls on a per-channel basis for slower rollouts
  source/configure/calls-deployment.rst
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#7201 Added browser notification prompt & cleaned up indentation syntax
  source/preferences/manage-your-notifications.rst
Labels: 3: Reviews Complete

#7195 Added mmctl ldap job, job list, and job show
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#7192 Added note detailing what happens with deactivated user integrations
  source/configure/user-management-configuration-settings.rst
Labels: 3: Reviews Complete

#7185 Documented S3Bucket name
  source/comply/legal-hold.rst
Labels: 3: Reviews Complete

#7197 Improve the required tools section and add pgloader image
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete

#7142 v9.9 changelog
  source/deploy/deprecated-features.rst
  source/deploy/mattermost-changelog.md
  source/install/download-latest-tarball.rst
  source/install/software-hardware-requirements.rst
  source/upgrade/open-source-components.rst
  source/upgrade/release-lifecycle.rst
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#7204 Added calls host control functionality to docs
  source/collaborate/make-calls.rst
Labels: 3: Reviews Complete

#7198 Added Cloud & SH advanced & audit logging config settings
  source/_static/badges/ent-cloud-only.rst
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#7210 Replaced support email links with Support portal links
  source/about/self-hosted-subscriptions.rst
  source/deploy/mobile-troubleshoot-notifications.rst
Labels: 3: Reviews Complete

#7208 Doc'd bash script that checks for new integrations via Marketplace
  source/about/faq-integrations.rst
  source/about/frequently-asked-questions.rst
  source/collaborate/extend-mattermost-with-integrations.rst
Labels: 3: Reviews Complete

#7166 Desktop v5.8.1 dot release changelog
  source/collaborate/install-desktop-app.rst
  source/deploy/desktop-app-changelog.rst
  source/install/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#7173 New user survey plugin admin docs
  source/configure/enable-copilot.rst
  source/configure/manage-user-surveys.rst
  source/guides/get-started-with-administration.rst
  source/images/active-past-surveys.png
  source/images/survey-setup.png
  source/images/user-feedback.png
  source/manage/user-satisfaction-surveys.rst
Labels: 1: Dev Review, 2. SME Review

#7209 Updated configuration in the DB to incorporate reviewer feedback.
  source/configure/configuration-in-your-database.rst
Labels: 3: Reviews Complete

#7203 Added links for WebApp & Notification Health metrics
  source/configure/performance-monitoring-configuration-settings.rst
  source/manage/telemetry.rst
  source/scale/deploy-prometheus-grafana-for-performance-monitoring.rst
Labels: 3: Reviews Complete

#7141 Mobile v2.17 changelog
  source/deploy/mobile-app-changelog.md
  source/install/software-hardware-requirements.rst
Labels: 3: Reviews Complete

#7111 [MM-58091] Update documentation for `mattermost_http_websockets_total` metric
  source/scale/performance-monitoring-metrics.rst
Labels: 3: Reviews Complete

#7206 Update version-archive.rst
  source/upgrade/version-archive.rst
Labels: 3: Reviews Complete

#7211 Add changelog video
  source/deploy/mattermost-changelog.md
Labels: 3: Reviews Complete

#7214 Added v8.1 ESR as supported server release for the user survey plugin
  source/configure/manage-user-surveys.rst
Labels: 3: Reviews Complete

#7216 Fix gencert.sh and update related files
  .gitignore
  source/onboard/sso-saml-before-you-begin.rst
  source/onboard/sso-saml.rst
  source/scale/performance-monitoring-metrics.rst
  source/scripts/generate-certificates/gencert.md
  source/scripts/generate-certificates/gencert.sh
Labels: 3: Reviews Complete

#7164 Upcoming breaking changes
  source/deploy/mattermost-changelog.md
  source/upgrade/important-upgrade-notes.rst
Labels: 1: Dev Review, 1: PM Review

#7223 Link fix
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#7224 fix broken docprom github link
  source/scale/collect-performance-metrics.rst
Labels: 3: Reviews Complete, Area/Documentation Improvements

#7228 Update deprecated-features.rst
  source/deploy/deprecated-features.rst
Labels: 1: PM Review

#7219 [MM-58584] Update Calls metrics
  source/configure/calls-deployment.rst
Labels: 3: Reviews Complete

#7232 Update notification bar with Copilot webinar CTA
  source/_static/css/mattermost-global.css
  source/_static/js/myscript-v1.js
  source/_templates/custom-nav.html
Labels: 3: Reviews Complete

#7233 Update notification bar
  source/_templates/custom-nav.html
Labels: 3: Reviews Complete

#7227 [MM-51523] Clarify documentation for `WebsocketPort` and `WebsocketSecurePort` settings
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#7231 Desktop: add note about rotated key, chrome-sandbox instructions
  source/collaborate/install-desktop-app.rst
Labels: 1: Dev Review, 2. SME Review

#7235 MM-58742: Add a note for postgres upgrade
  source/install/prepare-mattermost-database.rst
Labels: 3: Reviews Complete

#7238 [MM-524] Fix spelling mistake in event param of Jira webhook
  source/integrate/jira-interoperability.rst
Labels: 3: Reviews Complete

#7110 Release lifecycle docs overhaul & simplification
  README.md
  source/_static/badges/allplans-cloud-selfhosted.md
  source/_static/badges/allplans-selfhosted.md
  source/_static/badges/ent-only.md
  source/_static/badges/selfhosted-only.md
  source/about/deprecated-features.rst
  source/about/desktop-app-changelog.md
  source/about/desktop.rst
  source/about/editions-and-offerings.rst
  source/about/faq-general.rst
  source/about/mattermost-desktop-releases.md
  source/about/mattermost-mobile-releases.md
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/mobile-app-changelog.md
  source/about/mobile.rst
  source/about/release-policy.md
  source/about/releases-lifecycle.rst
  source/about/server.rst
  source/about/unsupported-legacy-releases.md
  source/about/version-archive.rst
  source/archive/OLD-extended-support-release.rst
  source/archive/OLD-release-lifecycle.rst
  source/archive/changelogs.rst
  source/archive/legacy-cloud-changelog.md
  source/archive/legacy-self-hosted-changelog.md
  source/archive/mattermost-changelog.md
  source/archive/release-definitions.rst
  source/archive/version-archive.rst
  source/collaborate/install-desktop-app.rst
  source/conf.py
  source/configure/enable-copilot.rst
  source/configure/manage-user-surveys.rst
  source/deploy/build-custom-mobile-apps.rst
  source/deploy/deploy-mobile-apps-using-emm-provider.rst
  source/deploy/desktop-app-changelog.rst
  source/deploy/mobile-faq.rst
  source/deploy/mobile-overview.rst
  source/deploy/postgres-migration.rst
  source/getting-started/admin-onboarding-tasks.rst
  source/getting-started/enterprise-roll-out-checklist.rst
  source/guides/about-mattermost.rst
  source/guides/deployment.rst
  source/guides/repeatable-processes.rst
  source/guides/self-hosted-administration.rst
  source/guides/upgrade-mattermost.rst
  source/install/common-prod-deploy-tar.rst
  source/install/download-latest-tarball.rst
  source/install/install-kubernetes.rst
  source/onboard/certificate-based-authentication.rst
  source/onboard/migrate-from-slack.rst
  source/overview/index.rst
  source/upgrade/downgrading-mattermost-server.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/prepare-to-upgrade-mattermost.rst
Labels: 3: Reviews Complete
