Repository mattermost/docs, pull requests merged in 2025-08, with the labels that each got.

#8265 Update postgres-migration.rst
  source/deployment-guide/postgres-migration.rst
Labels: 3: Reviews Complete, Guidance

#8274 Update upgrading-mattermost-server.rst
  source/administration-guide/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#8276 Fix v10.5.8 changelog
  source/product-overview/mattermost-v10-changelog.md
Labels: 3: Reviews Complete, Guidance

#8278 Add SBOM EE download links
  source/product-overview/version-archive.rst
Labels: Guidance

#8279 Update optimize-your-workspace.rst
  source/administration-guide/configure/optimize-your-workspace.rst
Labels: 3: Reviews Complete

#8282 Fix enterprise SBOM links
  source/product-overview/version-archive.rst
Labels: 3: Reviews Complete

#8241 Require signatures for prepackaged plugins from v10.11 onward
  source/administration-guide/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete, Guidance

#8271 v10.11 changelog
  source/administration-guide/upgrade/open-source-components.rst
  source/deployment-guide/server/linux/deploy-rhel.rst
  source/deployment-guide/server/linux/deploy-tar.rst
  source/deployment-guide/software-hardware-requirements.rst
  source/product-overview/common-esr-support-rst.rst
  source/product-overview/common-esr-support-upgrade.md
  source/product-overview/common-esr-support.md
  source/product-overview/mattermost-server-releases.md
  source/product-overview/mattermost-v10-changelog.md
  source/product-overview/release-policy.md
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#8288 Remove duplicate ToC entries from pages with inline tabs
  extensions/sphinx_inline_tabs/directive.py
  extensions/sphinx_inline_tabs/events.py
Labels: 3: Reviews Complete, Contributor

#8227 Add mobile security settings documentation for v10.11
  source/administration-guide/configure/site-configuration-settings.rst
  source/deployment-guide/mobile/mobile-security-features.rst
  source/security-guide/security/mobile-security.rst
Labels: 3: Reviews Complete, Guidance

#8291 Deep Links to Users
  source/end-user-guide/collaborate/share-links.rst
Labels: 3: Reviews Complete, Guidance

#8283 Clarify data retention policy behavior for custom policies
  source/administration-guide/configure/compliance-configuration-settings.rst
Labels: 3: Reviews Complete, Guidance

#8294 Update documentation for v10.11 ABAC user-editable attributes security restriction
  source/administration-guide/configure/system-attributes.rst
  source/administration-guide/manage/admin/attribute-based-access-control.rst
  source/administration-guide/manage/admin/user-attributes.rst
Labels: 3: Reviews Complete, Guidance

#8188 V10.11 Docs
  extensions/sphinx_inline_tabs/events.py
  source/_static/badges/ent-cloud-dedicated.rst
  source/_static/badges/ent-cloud-only.rst
  source/_static/badges/ent-cloud-selfhosted.rst
  source/_static/badges/ent-only.md
  source/_static/badges/ent-only.rst
  source/_static/badges/ent-pro-cloud-selfhosted.rst
  source/_static/badges/ent-pro-only.rst
  source/_static/badges/ent-pro-selfhosted.rst
  source/_static/badges/entpro-cloud-free.rst
  source/administration-guide/comply/compliance-export.rst
  source/administration-guide/configure/deprecated-configuration-settings.rst
  source/administration-guide/configure/environment-configuration-settings.rst
  source/administration-guide/configure/manage-user-surveys.rst
  source/administration-guide/configure/plugins-configuration-settings.rst
  source/administration-guide/configure/site-configuration-settings.rst
  source/administration-guide/configure/system-attributes.rst
  source/administration-guide/configure/user-management-configuration-settings.rst
  source/administration-guide/manage/admin/attribute-based-access-control.rst
  source/administration-guide/manage/admin/generating-support-packet.rst
  source/administration-guide/manage/admin/user-attributes.rst
  source/administration-guide/manage/mmctl-command-line-tool.rst
  source/administration-guide/manage/user-satisfaction-surveys.rst
  source/administration-guide/scale/deploy-prometheus-grafana-for-performance-monitoring.rst
  source/administration-guide/upgrade/open-source-components.rst
  source/conf.py
  source/deployment-guide/encryption-options.rst
  source/deployment-guide/mobile/mobile-security-features.rst
  source/deployment-guide/server/linux/deploy-rhel.rst
  source/deployment-guide/server/linux/deploy-tar.rst
  source/deployment-guide/server/linux/deploy-ubuntu.rst
  source/deployment-guide/software-hardware-requirements.rst
  source/end-user-guide/collaborate/manage-channel-bookmarks.rst
  source/end-user-guide/collaborate/send-messages.rst
  source/end-user-guide/collaborate/share-links.rst
  source/end-user-guide/messaging-collaboration.rst
  source/end-user-guide/preferences/manage-advanced-options.rst
  source/end-user-guide/workflow-automation.rst
  source/end-user-guide/workflow-automation/interact-with-playbooks.rst
  source/end-user-guide/workflow-automation/work-with-playbooks.rst
  source/end-user-guide/workflow-automation/work-with-runs.rst
  source/product-overview/common-esr-support-rst.rst
  source/product-overview/common-esr-support-upgrade.md
  source/product-overview/common-esr-support.md
  source/product-overview/mattermost-server-releases.md
  source/product-overview/mattermost-v10-changelog.md
  source/product-overview/release-policy.md
  source/security-guide/security/mobile-security.rst
Labels: 3: Reviews Complete, Guidance

#8290 Update version archive
  source/product-overview/version-archive.rst
Labels: 3: Reviews Complete, Guidance

#8269 Desktop v5.13 changelog
  source/deployment-guide/desktop/desktop-msi-installer-and-group-policy-install.rst
  source/deployment-guide/desktop/linux-desktop-install.rst
  source/deployment-guide/software-hardware-requirements.rst
  source/product-overview/desktop-app-changelog.md
  source/product-overview/mattermost-desktop-releases.md
Labels: 3: Reviews Complete, Guidance

#8302 v10.9.5 and v10.5.10 dot release docs
  source/product-overview/mattermost-server-releases.md
  source/product-overview/mattermost-v10-changelog.md
  source/product-overview/version-archive.rst
Labels: 3: Reviews Complete

#8304 Fixed egregious word choice error
  source/administration-guide/configure/agents-admin-guide.rst
  source/administration-guide/configure/plugins-configuration-settings.rst
  source/administration-guide/configure/site-configuration-settings.rst
  source/administration-guide/onboard/ad-ldap.rst
  source/end-user-guide/agents.rst
  source/integrations-guide/jira.rst
  source/product-overview/unsupported-legacy-releases.md
Labels: 3: Reviews Complete

#8311 Simplified AppConfig table to eliminate horizontal scroll
  source/deployment-guide/mobile/deploy-mobile-apps-using-emm-provider.rst
Labels: 3: Reviews Complete

#8313 Adding a lic disabled when set via environment variable
  source/administration-guide/manage/admin/installing-license-key.rst
Labels: 3: Reviews Complete, Guidance

#8316 Add GitLab child pipeline notification configuration setting
  source/integrations-guide/gitlab.rst
Labels: 3: Reviews Complete, Guidance

#8317 Add GitLab Enable Code Previews configuration setting
  source/integrations-guide/gitlab.rst
Labels: 3: Reviews Complete, Guidance

#8321 Clarified that Android mobile app not supported on Chromebooks
  source/deployment-guide/software-hardware-requirements.rst
  source/end-user-guide/collaborate/install-android-app.rst
Labels: 3: Reviews Complete, Guidance

#8322 Clarify operator compatibility
  source/deployment-guide/server/kubernetes/deploy-k8s.rst
Labels: 3: Reviews Complete, Guidance

#8331 Add PowerShell specific commands to the docs
  source/deployment-guide/desktop/desktop-msi-installer-and-group-policy-install.rst
Labels: 3: Reviews Complete

#8334 Update Team Edition to Enterprise Edition documentation
  source/administration-guide/upgrade-mattermost.rst
  source/administration-guide/upgrade/enterprise-install-upgrade.rst
Labels: 3: Reviews Complete, Guidance

#8281 Add sections for integrations guide around webhooks, attachemnts, pri…
  source/administration-guide/onboard/connected-workspaces.rst
  source/end-user-guide/collaborate/collaborate-within-connected-microsoft-teams.rst
  source/end-user-guide/collaborate/keyboard-shortcuts.rst
  source/end-user-guide/collaborate/schedule-messages.rst
  source/end-user-guide/preferences/manage-your-display-options.rst
  source/end-user-guide/workflow-automation/work-with-playbooks.rst
  source/images/add-outgoing-webhook.png
  source/images/attachments-author.png
  source/images/attachments-color.png
  source/images/attachments-example.png
  source/images/attachments-fields.png
  source/images/attachments-footer.png
  source/images/attachments-image.png
  source/images/attachments-pretext.png
  source/images/attachments-text.png
  source/images/attachments-thumb.png
  source/images/attachments-titles.png
  source/images/card-prop-example.png
  source/images/create-incoming-webhook-details.png
  source/images/create-outgoing-webhook-details-more.png
  source/images/create-outgoing-webhook-details.png
  source/images/fastlane-incoming-webhook.png
  source/images/github-incoming-webhook.png
  source/images/incoming-webhook-created.png
  source/images/incoming_webhooks_full_example.png
  source/images/jira-incoming-webhook.png
  source/images/manage-webhooks.png
  source/images/mattermost-incoming-webhook.png
  source/images/outgoing-webhook-created.png
  source/images/outgoing_webhooks_full_example.png
  source/images/product-menu-integrations.png
  source/images/select-add-incoming-webhook.png
  source/images/select-add-outgoing-webhook.png
  source/images/webhooksTable.png
  source/images/weblate-incoming-webhook.png
  source/integrations-guide/built-in-slash-commands.rst
  source/integrations-guide/incoming-webhooks.rst
  source/integrations-guide/integrations-guide-index.rst
  source/integrations-guide/outgoing-webhooks.rst
  source/integrations-guide/run-slash-commands.rst
  source/integrations-guide/webhook-integrations.rst
  source/product-overview/deprecated-features.rst
  source/product-overview/product-overview-index.rst
  source/redirects.py
Labels: 3: Reviews Complete, Guidance

#8336 Add Legal Hold processor tool documentation with full invocation example
  source/administration-guide/comply/legal-hold.rst
Labels: 1: Dev Review, 2: Editor Review

#8339 CMMC CTA
  source/security-guide/cmmc-compliance.rst
Labels: 3: Reviews Complete, Guidance
