Repository mattermost/docs, pull requests merged in 2025-10, with the labels that each got.

#8444 Update important-upgrade-notes.rst
  source/administration-guide/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#8442 Update plans.md
  source/product-overview/plans.md
Labels: 3: Reviews Complete, Guidance

#8420 v11: Added FIPS/STIG as container deployment option
  source/deployment-guide/server/containers/fips-stig.rst
  source/deployment-guide/server/deploy-containers.rst
Labels: 1: PM Review, Guidance

#8432 v11: new private channel settings permission
  source/administration-guide/onboard/advanced-permissions-backend-infrastructure.rst
  source/administration-guide/onboard/advanced-permissions.rst
Labels: 3: Reviews Complete, Guidance

#8433 v11: Update logging documentation for consolidated mattermost.log
  source/administration-guide/configure/environment-configuration-settings.rst
  source/administration-guide/manage/logging.rst
Labels: 3: Reviews Complete, Guidance

#8455 Add version-specific Bleve documentation guidance
  source/administration-guide/configure/bleve-search.rst
  source/administration-guide/configure/experimental-configuration-settings.rst
  source/administration-guide/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete
