Repository mattermost/docs, pull requests merged in 2025-02, with the labels that each got.

#7605 [MM-1137]: Updated the Jira docs with help text for Admin API Token and Admin Email
  source/integrate/jira-interoperability.rst
Labels: 1: Dev Review

#7722 Update faq-business.rst
  source/about/faq-business.rst
Labels: 3: Reviews Complete

#7723 Update access-your-workspace.rst
  source/collaborate/access-your-workspace.rst
Labels: 3: Reviews Complete

#7727 Added S3 storage guidance for Legal Holds
  source/comply/legal-hold.rst
Labels: 3: Reviews Complete

#7732 Added note re: Azure costs incurred & credits
  source/install/install-kubernetes-aks.rst
Labels: 3: Reviews Complete

#7719 Compliance Export updates
  source/comply/compliance-export.rst
Labels: 3: Reviews Complete

#7728 [MM-62887] Update docs for removed command line export cmds
  source/manage/command-line-tools.rst
Labels: 3: Reviews Complete

#7725 MS Teams v2.1.0 docs updates: notifications enabled by default
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
Labels: 3: Reviews Complete

#7726 Updated bookmark flow
  source/collaborate/manage-channel-bookmarks.rst
Labels: 3: Reviews Complete

#7718 add mmctl config export docs
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#7729 Clarify system roles
  source/onboard/advanced-permissions-backend-infrastructure.rst
  source/onboard/delegated-granular-administration.rst
Labels: 3: Reviews Complete

#7720 Added tip for ability to edit/remove message attachments
  source/collaborate/send-messages.rst
Labels: 3: Reviews Complete

#7737 Added support packet v2 details to docs
  source/manage/generating-support-packet.rst
Labels: 3: Reviews Complete

#7703 v2.25 Mobile changelog
  source/about/mattermost-mobile-releases.md
  source/about/mobile-app-changelog.md
Labels: 3: Reviews Complete

#7743 Update supported iOS version
  source/about/deprecated-features.rst
  source/about/mobile-app-changelog.md
  source/install/software-hardware-requirements.rst
Labels: 2: Editor Review

#7704 v10.5 Changelog
  source/about/deprecated-features.rst
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/install/download-latest-tarball.rst
  source/install/software-hardware-requirements.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#7701 V10.5 Docs
  source/about/deprecated-features.rst
  source/about/mattermost-mobile-releases.md
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/release-policy.md
  source/about/version-archive.rst
  source/collaborate/collaborate-within-connected-microsoft-teams.rst
  source/collaborate/install-desktop-app.rst
  source/collaborate/manage-channel-bookmarks.rst
  source/collaborate/send-messages.rst
  source/comply/compliance-export.rst
  source/comply/export-mattermost-channel-data.rst
  source/comply/legal-hold.rst
  source/conf.py
  source/install/download-latest-tarball.rst
  source/install/install-kubernetes-aks.rst
  source/install/prepare-mattermost-database.rst
  source/install/software-hardware-requirements.rst
  source/manage/generating-support-packet.rst
  source/manage/mmctl-command-line-tool.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
  source/upgrade/prepare-to-upgrade-mattermost.rst
Labels: 3: Reviews Complete

#7744 Update version-archive.rst
  source/about/version-archive.rst
Labels: 3: Reviews Complete

#7751 Call out lack of support for v9.3 and before.
  source/about/desktop-app-changelog.md
Labels: 3: Reviews Complete

#7721 Reduced ESR maintenance overhead with file includes
  source/about/common-esr-support-rst.rst
  source/about/common-esr-support-upgrade.md
  source/about/common-esr-support.md
  source/about/desktop-app-changelog.md
  source/about/mattermost-desktop-releases.md
  source/about/mattermost-mobile-releases.md
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/mobile-app-changelog.md
  source/about/releases-lifecycle.rst
  source/about/unsupported-legacy-releases.md
  source/about/version-archive.rst
  source/conf.py
  source/install/prepare-mattermost-mysql-database.rst
  source/install/software-hardware-requirements.rst
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#7759 fix: remove duplicated upgrade notes
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete, preview-environment, Contributor

#7761 fix: update checksums for 10.5.1
  source/about/version-archive.rst
Labels: 3: Reviews Complete

#7731 Deployment documentation updates
  source/conf.py
  source/configure/calls-deployment.rst
  source/guides/additional-server-installation-guides.rst
  source/guides/deployment.rst
  source/install/common-configure-support-email.rst
  source/install/common-default-config-changes.rst
  source/install/common-deploy-faq.rst
  source/install/common-gpg-public-key-changed.rst
  source/install/common-omnibus-tip.rst
  source/install/common-postgres-database-important.rst
  source/install/install-docker.rst
  source/install/install-kubernetes.rst
  source/install/install-rhel.rst
  source/install/install-tar.rst
  source/install/install-ubuntu.rst
  source/install/installing-mattermost-omnibus.rst
  source/install/installing-team-edition-helm-chart.rst
  source/install/prepare-mattermost-database.rst
  source/install/setup-mattermost-server.rst
  source/install/troubleshooting.rst
  source/preferences/manage-your-plugin-preferences.rst
Labels: 1: Dev Review, 2: Editor Review

#7766 Update cloud-subscriptions.rst
  source/about/cloud-subscriptions.rst
Labels: 3: Reviews Complete

#7764 Update deprecated-features.rst
  source/about/deprecated-features.rst
Labels: 2: Editor Review

#7771 Add new documentation for Mattermost Community for Microsoft 365
  source/guides/integrate-and-extend.rst
  source/images/mattermost_community_for_microsoft_365.png
  source/integrate/community-for-mattermost-for-microsoft-teams.rst
Labels: 3: Reviews Complete

#7772 Update sso-saml-technical.rst
  source/onboard/sso-saml-technical.rst
Labels: 3: Reviews Complete

#7770 Support packet plugin specific
  source/manage/generating-support-packet.rst
Labels: 3: Reviews Complete

#7773 Added new Zero Trust page & nav pane topic
  source/about/zero-trust.rst
  source/overview/index.rst
Labels: 3: Reviews Complete
