Repository mattermost/docs, pull requests merged in 2025-04, with the labels that each got.

#7842 Remove 1000 Day Elasticsearch Limitation
  source/scale/elasticsearch.rst
Labels: 3: Reviews Complete

#7841 Add Jira plugin notes to 10.5 release notes
  source/about/mattermost-v10-changelog.md
  source/upgrade/important-upgrade-notes.rst
Labels: 1: Dev Review

#7840 docs: add new mattermost discord dark theme
  source/images/DiscordNewDarkTheme.png
  source/preferences/customize-your-theme.rst
Labels: 3: Reviews Complete, Contributor

#7835 Update high-availability-cluster-based-deployment.rst
  source/scale/high-availability-cluster-based-deployment.rst
Labels: 3: Reviews Complete

#7843 Update deprecated features list
  source/about/deprecated-features.rst
Labels: 3: Reviews Complete

#7851 Added audit & notification logs to support packet
  source/manage/generating-support-packet.rst
Labels: 3: Reviews Complete

#7850 Added new config setting for Max AD/LDAP login attempts
  source/configure/authentication-configuration-settings.rst
Labels: 3: Reviews Complete

#7849 Added mobile audio play/download support for files
  source/collaborate/share-files-in-messages.rst
Labels: 3: Reviews Complete

#7846 Add link to Environment configuration settings documentation
  source/deploy/postgres-migration-assist-tool.rst
Labels: 3: Reviews Complete, Contributor

#7870 Fix format on release docs
  source/about/common-esr-support-rst.rst
  source/about/common-esr-support-upgrade.md
  source/about/common-esr-support.md
  source/about/releases-lifecycle.rst
  source/about/version-archive.rst
Labels: 3: Reviews Complete

#7859 Removed specific Postgres version string
  source/scale/high-availability-cluster-based-deployment.rst
Labels: 3: Reviews Complete

#7858 Gossip protocol source & description
  source/configure/environment-configuration-settings.rst
  source/deploy/encryption-options.rst
Labels: 3: Reviews Complete

#7857 Added client-side user ids & client perf config settings
  source/configure/enable-copilot.rst
  source/configure/environment-configuration-settings.rst
Labels: 3: Reviews Complete

#7856 Added Redis cache prefix config setting
  source/configure/environment-configuration-settings.rst
Labels: 3: Reviews Complete

#7855 Added Embedding config setting
  source/configure/integrations-configuration-settings.rst
Labels: 3: Reviews Complete

#7867 Moved Copilot setup to Admin Guide
  source/conf.py
  source/configure/enable-copilot.rst
  source/deploy/server/preparations.rst
  source/manage/admin/server-configuration.rst
Labels: 3: Reviews Complete

#7780 Add mobile security settings
  source/configure/environment-configuration-settings.rst
Labels: 3: Reviews Complete

#7873 Formatting fixes & examples
  source/configure/environment-configuration-settings.rst
  source/deploy/server/setup-nginx-proxy.rst
  source/manage/mmctl-command-line-tool.rst
  source/onboard/migrate-from-slack.rst
Labels: 3: Reviews Complete

#7866 New landing page & top-level navigation
  source/about/accessibility-compliance-policy.rst
  source/about/certifications-and-compliance.rst
  source/about/cloud-subscriptions.rst
  source/about/corporate-directory-integration.rst
  source/about/deprecated-features.rst
  source/about/desktop-app-changelog.md
  source/about/devops-collaboration.rst
  source/about/editions-and-offerings.rst
  source/about/faq-business.rst
  source/about/faq-community.rst
  source/about/faq-design-decisions.rst
  source/about/faq-enterprise.rst
  source/about/faq-general.rst
  source/about/faq-high-trust.rst
  source/about/faq-illicit-use.rst
  source/about/faq-integrations.rst
  source/about/faq-license.rst
  source/about/faq-mattermost-source-available-license.rst
  source/about/faq-notifications.rst
  source/about/faq-product.rst
  source/about/faq-use-cases.rst
  source/about/faq-video-audio-screensharing.rst
  source/about/frequently-asked-questions.rst
  source/about/incident-response-collaboration.rst
  source/about/integrations.rst
  source/about/mattermost-desktop-releases.md
  source/about/mattermost-mobile-releases.md
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/maximize-microsoft-investment.rst
  source/about/mobile-app-changelog.md
  source/about/non-profit-subscriptions.rst
  source/about/out-of-band-collaboration.rst
  source/about/product.rst
  source/about/release-policy.md
  source/about/releases-lifecycle.rst
  source/about/secure-command-and-control.rst
  source/about/security.rst
  source/about/self-hosted-subscriptions.rst
  source/about/subscription.rst
  source/about/unsupported-legacy-releases.md
  source/about/use-cases.rst
  source/about/version-archive.rst
  source/conf.py
  source/deploy/mobile/mobile-faq.rst
  source/deploy/server/server-architecture.rst
  source/guides/get-help.rst
  source/guides/use-mattermost.rst
  source/index.rst
  source/manage/admin/user-provisioning.rst
  source/overview/index.rst
Labels: 3: Reviews Complete

#7797 v10.7 Changelog
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/release-policy.md
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
Labels: 1: Dev Review, 1: PM Review, 3: Reviews Complete

#7876 Improve docs on reader endpoints and vacuuming
  source/scale/high-availability-cluster-based-deployment.rst
Labels: 1: Dev Review, Guidance

#7847 Dot release docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/version-archive.rst
Labels: 3: Reviews Complete

#7861 Dot release docs part 2
  source/deploy/server/linux/deploy-rhel.rst
  source/deploy/server/linux/deploy-tar.rst
Labels: 3: Reviews Complete

#7872 Added air-gapped PG migration guidance
  source/deploy/postgres-migration-assist-tool.rst
Labels: 3: Reviews Complete, Guidance

#7883 Update error-codes.rst
  source/manage/admin/error-codes.rst
Labels: 3: Reviews Complete

#7795 V10.7 Docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/release-policy.md
  source/collaborate/share-files-in-messages.rst
  source/conf.py
  source/configure/authentication-configuration-settings.rst
  source/configure/enable-copilot.rst
  source/configure/environment-configuration-settings.rst
  source/configure/integrations-configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/deploy/encryption-options.rst
  source/deploy/mobile/deploy-mobile-apps-using-emm-provider.rst
  source/deploy/postgres-migration-assist-tool.rst
  source/deploy/server/linux/deploy-rhel.rst
  source/deploy/server/linux/deploy-tar.rst
  source/deploy/server/setup-nginx-proxy.rst
  source/manage/admin/generating-support-packet.rst
  source/manage/mmctl-command-line-tool.rst
  source/onboard/migrate-from-slack.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
Labels: 3: Reviews Complete

#7880 (POC) Add mobile compatibility for future releases
  source/about/mattermost-mobile-releases.md
Labels: 3: Reviews Complete

#7889 Added back GPG Public Key download link
  source/deploy/desktop/linux-desktop-install.rst
Labels: 3: Reviews Complete

#7890 [CLD-9060] Add documentation for Azure AIO VM offer
  source/deploy/quick-start-evaluation.rst
Labels: 3: Reviews Complete

#7848 MM-63660: Added client-side filtering capability for upgrade notes and changelog
  source/_static/css/changelog-filter.css
  source/_static/css/version-filter.css
  source/_static/js/changelog-filter.js
  source/_static/js/myscript-v1.js
  source/_static/js/version-filter.js
  source/conf.py
  watch_and_sync.sh
Labels: 3: Reviews Complete

#7896 Replace dead SELinux Project Wiki link with GitHub repo (#7892)
  source/deploy/server/linux/deploy-rhel.rst
Labels: 3: Reviews Complete, Contributor

#7882 Added mobile security section, including features & secure file storage details
  source/about/security.rst
  source/about/security/mobile-security.rst
  source/about/security/zero-trust.rst
  source/configure/integrations-configuration-settings.rst
  source/deploy/encryption-options.rst
  source/deploy/mobile/mobile-app-deployment.rst
  source/deploy/mobile/mobile-security-features.rst
  source/deploy/mobile/secure-mobile-file-storage.rst
  source/deploy/quick-start-evaluation.rst
  source/overview/index.rst
Labels: 3: Reviews Complete, Guidance

#7894 v10.7.1 dot release docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/version-archive.rst
  source/deploy/server/linux/deploy-rhel.rst
  source/deploy/server/linux/deploy-tar.rst
Labels: 3: Reviews Complete

#7895 Dot release docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/mattermost-v9-changelog.md
  source/about/version-archive.rst
  source/deploy/server/linux/deploy-rhel.rst
  source/deploy/server/linux/deploy-tar.rst
Labels: 3: Reviews Complete

#7903 Update cloud-dedicated.rst
  source/about/cloud-dedicated.rst
Labels: 3: Reviews Complete

#7907 Update scaling-for-enterprise.rst
  source/scale/scaling-for-enterprise.rst
Labels: 3: Reviews Complete

#7901 Mobile v2.27.1 dot release docs
  source/about/mattermost-mobile-releases.md
  source/about/mobile-app-changelog.md
Labels: 3: Reviews Complete

#7908 fixed "Migrate configuration from.." example
  source/configure/configuration-in-your-database.rst
Labels: 3: Reviews Complete
