Repository mattermost/docs, pull requests merged in 2025-06, with the labels that each got.

#7986 Removed Go mmctl install option docs
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#7998 Added K8s FAQ
  source/deploy/server/deploy-kubernetes.rst
Labels: 3: Reviews Complete

#7999 Removed "beta" from titles/subsection titles & URLs
  source/about/devops-collaboration.rst
  source/about/editions-and-offerings.rst
  source/about/integrated-security-operations.rst
  source/about/on-prem-skype-for-business-replacement.rst
  source/about/out-of-band-incident-response.rst
  source/about/plans.md
  source/about/self-sovereign-collaboration.rst
  source/collaborate/make-calls.rst
  source/conf.py
  source/configure/calls-deployment.md
  source/configure/deprecated-configuration-settings.rst
  source/configure/enable-copilot.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/plugins-configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/integrate/mattermost-mission-collaboration-for-m365.rst
  source/manage/logging.rst
  source/onboard/connected-workspaces.rst
Labels: 3: Reviews Complete

#8000 Mobile v2.28.1 docs
  source/about/mattermost-mobile-releases.md
  source/about/mobile-app-changelog.md
Labels: 3: Reviews Complete

#7995 Update schema permission in postgres setup docs
  source/deploy/postgres-migration.rst
  source/deploy/server/preparations.rst
Labels: 3: Reviews Complete

#8003 Update maximize-microsoft-investments.rst
  source/about/maximize-microsoft-investments.rst
Labels: 3: Reviews Complete

#8007 Add Oracle reference architecture
  source/deploy/server/server-architecture.rst
  source/images/MattermostDeployment5kOracle.png
Labels: 3: Reviews Complete

#8010 try different checkout job
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 3: Reviews Complete

#8009 Update unsupported-legacy-releases.md
  source/about/unsupported-legacy-releases.md
Labels: 3: Reviews Complete

#7863 Updated the Github plugin docs for the release v2.4.0
  source/integrate/github.rst
Labels: 3: Reviews Complete

#8002 Overview updates for IME
  source/about/on-prem-skype-for-business-replacement.rst
  source/about/out-of-band-incident-response.rst
  source/about/product.rst
  source/deploy/mobile/deploy-mobile-apps-using-emm-provider.rst
  source/deploy/server/deploy-kubernetes.rst
  source/guides/agents.rst
  source/images/Messaging.png
  source/images/agents-meeting-summary.png
  source/images/boards-kanban.png
  source/images/call-window.png
  source/images/github-integration.png
  source/images/ime.jpg
  source/images/playbooks.png
Labels: 3: Reviews Complete

#8013 Add note on login rate for 200k users architecture
  source/scale/scale-to-200000-users.rst
Labels: 3: Reviews Complete

#8005 [MM-64436] Calls: documentation on sharing audio while screen sharing
  source/collaborate/make-calls.rst
Labels: 3: Reviews Complete

#8021 Added new re-add members option for LDAP sync
  source/configure/authentication-configuration-settings.rst
  source/deploy/server/air-gapped-deployment.rst
  source/onboard/ad-ldap.rst
Labels: 3: Reviews Complete

#8016 Incorporated https://github.com/mattermost/docs/pull/7244/
  source/integrate/github.rst
Labels: 3: Reviews Complete

#8015 Moved Connected Workspaces from Beta to GA
  source/configure/site-configuration-settings.rst
  source/onboard/connected-workspaces.rst
Labels: 3: Reviews Complete

#8029 Added note re: angle-bracketed emails will be rejected
  source/configure/authentication-configuration-settings.rst
  source/configure/user-management-configuration-settings.rst
  source/manage/mmctl-command-line-tool.rst
Labels: 3: Reviews Complete

#8042 Add sitemap excludes
  extensions/sitemap/__init__.py
  source/conf.py
Labels: 3: Reviews Complete, preview-environment

#8040 Update compliance-export.rst
  source/comply/compliance-export.rst
Labels: 3: Reviews Complete

#8019 Renamed System Properties to User Attributes
  source/conf.py
  source/configure/configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/configure/system-attributes.rst
  source/manage/admin/server-configuration.rst
  source/manage/admin/user-attributes.rst
  source/preferences/manage-your-profile.rst
Labels: 3: Reviews Complete

#8027 Converted Markdown tables to HTML
  source/configure/calls-deployment.md
Labels: 3: Reviews Complete

#8030 Added display tip for console server logs
  source/configure/reporting-configuration-settings.rst
Labels: 3: Reviews Complete

#8031 Doc'd new Channel Settings modal for creating/renaming channels
  source/collaborate/archive-unarchive-channels.rst
  source/collaborate/channel-header-purpose.rst
  source/collaborate/rename-channels.rst
Labels: 3: Reviews Complete

#8033 Added SAML encryption support details/links
  source/configure/authentication-configuration-settings.rst
  source/deploy/encryption-options.rst
  source/onboard/sso-saml-faq.rst
  source/onboard/sso-saml-keycloak.rst
  source/onboard/sso-saml-okta.rst
  source/onboard/sso-saml-onelogin.rst
  source/onboard/sso-saml-technical.rst
  source/onboard/sso-saml.rst
Labels: 3: Reviews Complete

#8035 Moved experimental feature to GA
  source/about/cloud-dedicated.rst
  source/about/cloud-shared.rst
  source/comply/compliance-export.rst
  source/configure/environment-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#8037 Added Pro/Ent badges for related config settings
  source/configure/site-configuration-settings.rst
Labels: 3: Reviews Complete

#8038 Added new config setting/FF
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#8044 added abac
  source/manage/admin/server-configuration.rst
  source/manage/admin/zero-trust-security.rst
Labels: 3: Reviews Complete

#8041 Dependency Vulnerability Analysis
  source/about/security.rst
  source/about/security/dependency-vulnerability-analysis.rst
Labels: 3: Reviews Complete

#7952 V10.9 docs
  source/_static/badges/ent-adv-cloud-selfhosted.rst
  source/_static/badges/ent-adv-only.md
  source/_static/badges/ent-adv-only.rst
  source/about/cloud-dedicated.rst
  source/about/cloud-shared.rst
  source/about/deprecated-features.rst
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/release-policy.md
  source/boards/boards-settings.rst
  source/boards/navigate-boards.rst
  source/collaborate/access-your-workspace.rst
  source/collaborate/archive-unarchive-channels.rst
  source/collaborate/channel-header-purpose.rst
  source/collaborate/collaborate-within-channels.rst
  source/collaborate/display-channel-banners.rst
  source/collaborate/rename-channels.rst
  source/comply/compliance-export.rst
  source/conf.py
  source/configure/authentication-configuration-settings.rst
  source/configure/calls-deployment.md
  source/configure/configuration-settings.rst
  source/configure/environment-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
  source/configure/install-boards.rst
  source/configure/push-notification-server-configuration-settings.rst
  source/configure/reporting-configuration-settings.rst
  source/configure/site-configuration-settings.rst
  source/configure/system-attributes.rst
  source/configure/user-management-configuration-settings.rst
  source/deploy/desktop/desktop-app-deployment.rst
  source/deploy/encryption-options.rst
  source/deploy/mobile/mobile-app-deployment.rst
  source/deploy/mobile/mobile-faq.rst
  source/deploy/server/air-gapped-deployment.rst
  source/deploy/server/linux/deploy-rhel.rst
  source/deploy/server/linux/deploy-tar.rst
  source/guides/project-task-management.rst
  source/integrate/github.rst
  source/integrate/mattermost-mission-collaboration-for-m365.rst
  source/manage/admin/server-configuration.rst
  source/manage/admin/user-attributes.rst
  source/manage/admin/zero-trust-security.rst
  source/manage/mmctl-command-line-tool.rst
  source/onboard/ad-ldap.rst
  source/onboard/advanced-permissions-backend-infrastructure.rst
  source/onboard/connected-workspaces.rst
  source/onboard/sso-saml-faq.rst
  source/onboard/sso-saml-keycloak.rst
  source/onboard/sso-saml-okta.rst
  source/onboard/sso-saml-onelogin.rst
  source/onboard/sso-saml-technical.rst
  source/onboard/sso-saml.rst
  source/preferences/manage-your-profile.rst
  source/scale/collect-performance-metrics.rst
  source/scale/performance-monitoring-metrics.rst
  source/upgrade/important-upgrade-notes.rst
  source/upgrade/open-source-components.rst
Labels: 3: Reviews Complete

#7949 Calls: Add full support for config environment overrides
  source/configure/plugins-configuration-settings.rst
Labels: 3: Reviews Complete

#7809 Add initial documentation for new report a problem settings
  source/configure/site-configuration-settings.rst
  source/manage/telemetry.rst
Labels: 3: Reviews Complete

#8065 Remove the automatic Claude review workflow
  .github/workflows/claude-code-review.yml
Labels: 2: Editor Review

#8061 v10.9.1 dot release docs
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/about/version-archive.rst
  source/deploy/server/linux/deploy-rhel.rst
  source/deploy/server/linux/deploy-tar.rst
  source/deploy/software-hardware-requirements.rst
Labels: 3: Reviews Complete

#8025 reordering linux install options
  source/deploy/server/deploy-linux.rst
Labels: 3: Reviews Complete

#8066 AI-Aided: Remove built-in grace period references from documentation
  source/manage/admin/error-codes.rst
Labels: 3: Reviews Complete

#8097 Update subscription.rst
  source/about/subscription.rst
Labels: 3: Reviews Complete

#8099 Update product.rst
  source/about/product.rst
Labels: 3: Reviews Complete

#8100 AI-Aided: Fix image borders adding noise to inline icons
  source/_static/css/mattermost-global.css
Labels: 3: Reviews Complete

#8103 AI-Aided: Add documentation for Load Metric field in About dialog
  source/collaborate/view-system-information.rst
  source/guides/messaging-collaboration.rst
  source/manage/admin/generating-support-packet.rst
Labels: 3: Reviews Complete

#8106 AI-Aided: Replaced CUI with Sensitive Information
  source/about/secure-command-and-control.rst
  source/about/self-sovereign-collaboration.rst
  source/collaborate/display-channel-banners.rst
  source/conf.py
  source/deploy/mobile/secure-mobile-file-storage.rst
Labels: 3: Reviews Complete

#8108 Update how to contact us.rst
  source/deploy/server/orchestration.rst
Labels: 3: Reviews Complete

#8111 Fix typo in env var for max notifications per channel
  source/configure/push-notification-server-configuration-settings.rst
Labels: 3: Reviews Complete
