Repository mattermost/docs, pull requests merged in 2025-07, with the labels that each got.

#8092 AI-Aided: Enable from: filter support in cross-team search
  source/collaborate/search-for-messages.rst
Labels: 3: Reviews Complete

#8088 AI-Aided: Add emoticon auto-rendering documentation for v10.10
  source/collaborate/react-with-emojis-gifs.rst
  source/preferences/manage-your-display-options.rst
Labels: 3: Reviews Complete

#8079 AI-Aided: Add connected workspaces channel membership synchronization for v10.10
  source/onboard/connected-workspaces.rst
Labels: 3: Reviews Complete

#8093 AI-Aided: Add v10.10 documentation with GitLab plugin v1.10.0 update
  source/about/mattermost-server-releases.md
  source/about/mattermost-v10-changelog.md
  source/integrate/gitlab.rst
Labels: 3: Reviews Complete

#8134 Update prepackaged plugins list with complete inventory
  source/guides/pre-built-integrations.rst
Labels: 3: Reviews Complete

#8136 Add simplified upgrade checklist for experienced system admins
  source/upgrade/upgrading-mattermost-server.rst
Labels: 3: Reviews Complete

#8144 Clarify SQL queries in schema changes are automatically executed
  source/upgrade/important-upgrade-notes.rst
Labels: 3: Reviews Complete

#8076 AI-Aided: Add comprehensive NotificationLogSettings documentation
  source/configure/environment-configuration-settings.rst
  source/manage/logging.rst
  source/scale/deploy-prometheus-grafana-for-performance-monitoring.rst
Labels: 3: Reviews Complete, Guidance

#8089 AI-Aided: Add documentation for automatic channel category sorting feature (v10.10)
  source/collaborate/create-channels.rst
  source/collaborate/rename-channels.rst
  source/configure/experimental-configuration-settings.rst
  source/preferences/customize-your-channel-sidebar.rst
Labels: 3: Reviews Complete

#8146 Add documentation for default team in remote cluster entities
  source/about/mattermost-v10-changelog.md
  source/onboard/connected-workspaces.rst
Labels: 3: Reviews Complete

#8047 Update the MsCalendar plugin docs for clarity
  source/images/ms-teams-meeting-permissions-final-state.png
  source/integrate/microsoft-calendar.rst
Labels: 3: Reviews Complete

#8095 [MM-64629] Add documentation for the new LDAP setup wizard
  source/configure/authentication-configuration-settings.rst
  source/onboard/ad-ldap-groups-synchronization.rst
  source/onboard/ad-ldap.rst
  source/onboard/guest-accounts.rst
  source/onboard/sso-saml-ldapsync.rst
Labels: 3: Reviews Complete

#7972 Sphinx tech stack update + Tab sections in table of contents
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  extensions/compass-icons/__init__.py
  extensions/config-setting-v2/__init__.py
  extensions/reredirects/__init__.py
  extensions/sphinx_inline_tabs/LICENSE
  extensions/sphinx_inline_tabs/__init__.py
  extensions/sphinx_inline_tabs/directive.py
  extensions/sphinx_inline_tabs/events.py
  extensions/sphinx_inline_tabs/nodes.py
  extensions/sphinx_inline_tabs/sectiondata.py
  extensions/sphinx_inline_tabs/static/tabs.css
  extensions/sphinx_inline_tabs/static/tabs.js
  extensions/sphinx_inline_tabs/tab_id.py
  extensions/sphinx_inline_tabs/transform.py
  make.bat
  scripts/convert-links.py
  scripts/detect-duplicate-redirects.py
  source/_static/css/compass-icons.css
  source/_static/font/compass-icons.eot
  source/_static/font/compass-icons.svg
  source/_static/font/compass-icons.ttf
  source/_static/font/compass-icons.woff
  source/_static/font/compass-icons.woff2
  source/collaborate/access-your-workspace.rst
  source/collaborate/create-channels.rst
  source/collaborate/make-calls.rst
  source/collaborate/search-for-messages.rst
  source/collaborate/share-files-in-messages.rst
  source/comply/compliance-export.rst
  source/conf.py
  source/configure/environment-configuration-settings.rst
  source/deploy/desktop/linux-desktop-install.rst
  source/deploy/quick-start-evaluation.rst
  source/deploy/server/containers/install-aws-beanstalk.rst
  source/deploy/server/containers/install-docker.rst
  source/deploy/server/deploy-containers.rst
  source/deploy/server/deploy-kubernetes.rst
  source/deploy/server/deploy-linux.rst
  source/deploy/server/kubernetes/deploy-k8s-aks.rst
  source/deploy/server/kubernetes/deploy-k8s-oke.rst
  source/deploy/server/kubernetes/deploy-k8s.rst
  source/deploy/server/linux/deploy-omnibus.rst
  source/deploy/server/linux/deploy-rhel.rst
  source/deploy/server/linux/deploy-tar.rst
  source/deploy/server/linux/deploy-ubuntu.rst
  source/deploy/server/prepare-mattermost-mysql-database.rst
  source/manage/code-signing-custom-builds.rst
  source/preferences/connect-multiple-workspaces.rst
  source/preferences/customize-desktop-app-experience.rst
  source/redirects.py
  source/scale/opensearch-setup.rst
Labels: preview-environment, Contributor, Guidance

#8135 Restructure Linux deployment documentation based on feedback
  source/deploy/server/deploy-linux.rst
  source/deploy/server/linux/deploy-omnibus.rst
  source/deploy/server/linux/deploy-rhel.rst
  source/deploy/server/linux/deploy-tar.rst
  source/deploy/server/linux/deploy-ubuntu.rst
  source/deploy/server/preparations.rst
  source/scale/scale-to-200-users.rst
Labels: 3: Reviews Complete

#8171 MM-64747: Clarify that guests can leave town-square
  source/onboard/guest-accounts.rst
Labels: 3: Reviews Complete

#8170 Converted RST tables to HTML to remove horizontal scroll
  source/scale/scale-to-100000-users.rst
  source/scale/scale-to-15000-users.rst
  source/scale/scale-to-200-users.rst
  source/scale/scale-to-2000-users.rst
  source/scale/scale-to-200000-users.rst
  source/scale/scale-to-30000-users.rst
  source/scale/scale-to-50000-users.rst
  source/scale/scale-to-80000-users.rst
  source/scale/scale-to-90000-users.rst
Labels: 3: Reviews Complete

#8174 Fixes to tab processing code to stop hiding child pages
  extensions/sphinx_inline_tabs/events.py
  source/deploy/server/preparations.rst
  source/deploy/server/server-deployment-planning.rst
  source/guides/deployment-guide.rst
Labels: 3: Reviews Complete

#8175 Revamp Security Use Case Pages
  source/about/integrated-security-operations.rst
  source/about/out-of-band-incident-response.rst
  source/images/secure-out-of-band.png
Labels: 3: Reviews Complete

#8162 Document comprehensive audit log event types
  source/comply/embedded-json-audit-log-schema.rst
Labels: 3: Reviews Complete, Guidance

#8173 Clarify PostgreSQL migration documentation
  source/deploy/manual-postgres-migration.rst
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete, Guidance

#8180 Add more detail for service deployment in airgapped environments
  source/deploy/server/air-gapped-deployment.rst
Labels: 3: Reviews Complete

#8185 Update self-hosted-subscriptions.rst
  source/about/self-hosted-subscriptions.rst
Labels: 3: Reviews Complete

#8178 Update version-archive.rst
  source/about/version-archive.rst
Labels: 3: Reviews Complete

#8194 Clarify DB connection steps when fixing search_path after migration
  source/deploy/postgres-migration.rst
Labels: 3: Reviews Complete, Guidance

#8193 Fix audit and notification links
  source/configure/environment-configuration-settings.rst
  source/configure/experimental-configuration-settings.rst
Labels: 3: Reviews Complete

#8251 Create faq-federal-procurement.rst
  source/about/faq-federal-procurement.rst
  source/about/frequently-asked-questions.rst
Labels: 3: Reviews Complete

#8260 Added link to ime.png (web-searchable)
  source/about/product.rst
Labels: 3: Reviews Complete

#8261 Fix: Use port 443 instead of 9200 for AWS OpenSearch
  source/scale/opensearch-setup.rst
Labels: 3: Reviews Complete
